/**
 * A1 (입문) 한국어 학습 콘텐츠 — 영어권 학습자 대상.
 * 각 카드: 한국어 표현(ko) + 로마자(roman) + 영어 뜻(en) + 예문(한/영).
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * note 는 영어(학습자 모국어)로 사용 맥락을 설명한다.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_A1_DECKS: Deck[] = [
  {
    id: "greetings",
    level: "A1",
    title: { ko: "인사", en: "Greetings" },
    description: { ko: "기본 인사와 작별", en: "Hellos and goodbyes" },
    order: 1,
    icon: "Hand",
  },
  {
    id: "self-intro",
    level: "A1",
    title: { ko: "자기소개", en: "Introducing Yourself" },
    description: { ko: "이름·출신·직업·나이", en: "Name, origin, job, and age" },
    order: 2,
    icon: "UserRound",
  },
  {
    id: "numbers",
    level: "A1",
    title: { ko: "숫자", en: "Numbers" },
    description: { ko: "하나~열, 십~백, 수량 세기", en: "Counting and quantities" },
    order: 3,
    icon: "Hash",
  },
  {
    id: "food",
    level: "A1",
    title: { ko: "음식·식당", en: "Food & Dining" },
    description: { ko: "주문·맛·계산", en: "Ordering, taste, and paying" },
    order: 4,
    icon: "Utensils",
  },
  {
    id: "family",
    level: "A1",
    title: { ko: "가족", en: "Family" },
    description: { ko: "가족 호칭·소개", en: "Family members and introductions" },
    order: 5,
    icon: "Users",
  },
];

export const KO_A1_CARDS: VocabCard[] = [
  {
    id: "ko-a1-greetings-001",
    level: "A1",
    deck: "greetings",
    en: "Hello",
    ko: "안녕하세요",
    roman: "annyeonghaseyo",
    exampleKo: "안녕하세요, 만나서 반가워요.",
    exampleEn: "Hello, nice to meet you.",
    note: "The standard polite greeting — works any time of day.",
  },
  {
    id: "ko-a1-greetings-002",
    level: "A1",
    deck: "greetings",
    en: "Goodbye (to someone leaving)",
    ko: "안녕히 가세요",
    roman: "annyeonghi gaseyo",
    exampleKo: "안녕히 가세요, 또 만나요.",
    exampleEn: "Goodbye, see you again.",
    note: "Say this to the person who is leaving while you stay.",
  },
  {
    id: "ko-a1-greetings-003",
    level: "A1",
    deck: "greetings",
    en: "Goodbye (to someone staying)",
    ko: "안녕히 계세요",
    roman: "annyeonghi gyeseyo",
    exampleKo: "안녕히 계세요, 내일 봬요.",
    exampleEn: "Goodbye, see you tomorrow.",
    note: "Say this when you are the one leaving and they stay.",
  },
  {
    id: "ko-a1-greetings-004",
    level: "A1",
    deck: "greetings",
    en: "Thank you",
    ko: "감사합니다",
    roman: "gamsahamnida",
    exampleKo: "도와주셔서 감사합니다.",
    exampleEn: "Thank you for your help.",
    note: "Polite, formal thanks — safe in almost any situation.",
  },
  {
    id: "ko-a1-greetings-005",
    level: "A1",
    deck: "greetings",
    en: "Thanks",
    ko: "고맙습니다",
    roman: "gomapseumnida",
    exampleKo: "정말 고맙습니다.",
    exampleEn: "Thank you so much.",
    note: "Also polite; a touch warmer and more native than 감사합니다.",
  },
  {
    id: "ko-a1-greetings-006",
    level: "A1",
    deck: "greetings",
    en: "I'm sorry",
    ko: "죄송합니다",
    roman: "joesonghamnida",
    exampleKo: "늦어서 죄송합니다.",
    exampleEn: "I'm sorry for being late.",
    note: "Formal apology. Use 미안해요 with close friends.",
  },
  {
    id: "ko-a1-greetings-007",
    level: "A1",
    deck: "greetings",
    en: "It's okay / It's fine",
    ko: "괜찮아요",
    roman: "gwaenchanayo",
    exampleKo: "괜찮아요, 신경 쓰지 마세요.",
    exampleEn: "It's okay, don't worry about it.",
    note: "Versatile: accepts apologies, declines offers, says you're fine.",
  },
  {
    id: "ko-a1-greetings-008",
    level: "A1",
    deck: "greetings",
    en: "Yes",
    ko: "네",
    roman: "ne",
    exampleKo: "네, 맞아요.",
    exampleEn: "Yes, that's right.",
    note: "Standard polite 'yes'. 예 (ye) is a bit more formal.",
  },
  {
    id: "ko-a1-greetings-009",
    level: "A1",
    deck: "greetings",
    en: "No",
    ko: "아니요",
    roman: "aniyo",
    exampleKo: "아니요, 괜찮아요.",
    exampleEn: "No, I'm fine.",
    note: "Polite 'no'. Often softened with 괜찮아요 to stay friendly.",
  },
  {
    id: "ko-a1-greetings-010",
    level: "A1",
    deck: "greetings",
    en: "Excuse me",
    ko: "실례합니다",
    roman: "sillyehamnida",
    exampleKo: "실례합니다, 길 좀 묻겠습니다.",
    exampleEn: "Excuse me, may I ask for directions?",
    note: "Use to get attention politely or before interrupting.",
  },
  {
    id: "ko-a1-greetings-011",
    level: "A1",
    deck: "greetings",
    en: "Nice to meet you",
    ko: "만나서 반갑습니다",
    roman: "mannaseo bangapseumnida",
    exampleKo: "만나서 반갑습니다. 저는 민수예요.",
    exampleEn: "Nice to meet you. I'm Minsu.",
    note: "Standard first-meeting line. 반가워요 is the softer casual form.",
  },
  {
    id: "ko-a1-greetings-012",
    level: "A1",
    deck: "greetings",
    en: "How have you been?",
    ko: "잘 지내셨어요?",
    roman: "jal jinaesyeosseoyo?",
    exampleKo: "오랜만이에요. 잘 지내셨어요?",
    exampleEn: "Long time no see. How have you been?",
    note: "Polite catch-up greeting for someone you haven't seen in a while.",
  },

  // ── self-intro (자기소개) ───────────────────────────────────────────────
  {
    id: "ko-a1-self-intro-001",
    level: "A1",
    deck: "self-intro",
    en: "I am ~ (My name is ~)",
    ko: "저는 ~예요",
    roman: "jeoneun ~yeyo",
    exampleKo: "저는 사라예요.",
    exampleEn: "I'm Sarah.",
    note: "Use 예요 after a vowel, 이에요 after a consonant. 저는 = 'as for me'.",
  },
  {
    id: "ko-a1-self-intro-002",
    level: "A1",
    deck: "self-intro",
    en: "My name is ~",
    ko: "제 이름은 ~이에요",
    roman: "je ireumeun ~ieyo",
    exampleKo: "제 이름은 민준이에요.",
    exampleEn: "My name is Minjun.",
    note: "제 이름은 = 'my name'. A more explicit way to give your name.",
  },
  {
    id: "ko-a1-self-intro-003",
    level: "A1",
    deck: "self-intro",
    en: "What is your name?",
    ko: "이름이 뭐예요?",
    roman: "ireumi mwoyeyo?",
    exampleKo: "안녕하세요, 이름이 뭐예요?",
    exampleEn: "Hello, what's your name?",
    note: "Casual-polite. Use 성함이 어떻게 되세요? to be extra formal.",
  },
  {
    id: "ko-a1-self-intro-004",
    level: "A1",
    deck: "self-intro",
    en: "Where are you from?",
    ko: "어디에서 왔어요?",
    roman: "eodieseo wasseoyo?",
    exampleKo: "어디에서 왔어요? 저는 캐나다에서 왔어요.",
    exampleEn: "Where are you from? I'm from Canada.",
    note: "Literally 'where did you come from?'. A standard get-to-know-you line.",
  },
  {
    id: "ko-a1-self-intro-005",
    level: "A1",
    deck: "self-intro",
    en: "I'm from ~",
    ko: "저는 ~에서 왔어요",
    roman: "jeoneun ~eseo wasseoyo",
    exampleKo: "저는 미국에서 왔어요.",
    exampleEn: "I'm from the US.",
    note: "Put the country before 에서. 에서 marks the place of origin.",
  },
  {
    id: "ko-a1-self-intro-006",
    level: "A1",
    deck: "self-intro",
    en: "I am a student",
    ko: "저는 학생이에요",
    roman: "jeoneun haksaengieyo",
    exampleKo: "저는 대학교 학생이에요.",
    exampleEn: "I'm a university student.",
    note: "학생 = student. 이에요 follows because 학생 ends in a consonant.",
  },
  {
    id: "ko-a1-self-intro-007",
    level: "A1",
    deck: "self-intro",
    en: "What do you do (for work)?",
    ko: "무슨 일 하세요?",
    roman: "museun il haseyo?",
    exampleKo: "실례지만, 무슨 일 하세요?",
    exampleEn: "Excuse me, what do you do for work?",
    note: "Literally 'what work do you do?'. Polite way to ask someone's job.",
  },
  {
    id: "ko-a1-self-intro-008",
    level: "A1",
    deck: "self-intro",
    en: "I am an office worker",
    ko: "저는 회사원이에요",
    roman: "jeoneun hoesawonieyo",
    exampleKo: "저는 회사원이에요. 서울에서 일해요.",
    exampleEn: "I'm an office worker. I work in Seoul.",
    note: "회사원 = company employee, a very common answer about one's job.",
  },
  {
    id: "ko-a1-self-intro-009",
    level: "A1",
    deck: "self-intro",
    en: "Nice to meet you (set phrase)",
    ko: "잘 부탁드려요",
    roman: "jal butakdeuryeoyo",
    exampleKo: "앞으로 잘 부탁드려요.",
    exampleEn: "I look forward to working with you.",
    note: "Set phrase to close an introduction. No direct English equivalent.",
  },
  {
    id: "ko-a1-self-intro-010",
    level: "A1",
    deck: "self-intro",
    en: "How old are you?",
    ko: "나이가 어떻게 되세요?",
    roman: "naiga eotteoke doeseyo?",
    exampleKo: "나이가 어떻게 되세요? 저는 스물다섯 살이에요.",
    exampleEn: "How old are you? I'm twenty-five.",
    note: "Polite way to ask age. Age matters for choosing the right speech level.",
  },
  {
    id: "ko-a1-self-intro-011",
    level: "A1",
    deck: "self-intro",
    en: "I live in ~",
    ko: "저는 ~에 살아요",
    roman: "jeoneun ~e sarayo",
    exampleKo: "저는 서울에 살아요.",
    exampleEn: "I live in Seoul.",
    note: "에 marks the place where you live (location, not direction).",
  },
  {
    id: "ko-a1-self-intro-012",
    level: "A1",
    deck: "self-intro",
    en: "Please speak comfortably (casually) to me",
    ko: "말씀 편하게 하세요",
    roman: "malsseum pyeonhage haseyo",
    exampleKo: "제가 더 어려요. 말씀 편하게 하세요.",
    exampleEn: "I'm younger. Please feel free to speak casually to me.",
    note: "Polite offer to let an older person drop formal speech with you.",
  },

  // ── numbers (숫자) ──────────────────────────────────────────────────────
  {
    id: "ko-a1-numbers-001",
    level: "A1",
    deck: "numbers",
    en: "one (native)",
    ko: "하나",
    roman: "hana",
    exampleKo: "커피 하나 주세요.",
    exampleEn: "One coffee, please.",
    note: "Native Korean number. Used for counting things, age, and hours.",
  },
  {
    id: "ko-a1-numbers-002",
    level: "A1",
    deck: "numbers",
    en: "two (native)",
    ko: "둘",
    roman: "dul",
    exampleKo: "사과 둘이요.",
    exampleEn: "Two apples.",
    note: "Becomes 두 before a counter: 두 개 (two items), 두 명 (two people).",
  },
  {
    id: "ko-a1-numbers-003",
    level: "A1",
    deck: "numbers",
    en: "three (native)",
    ko: "셋",
    roman: "set",
    exampleKo: "셋이 함께 가요.",
    exampleEn: "The three of us go together.",
    note: "Becomes 세 before a counter: 세 잔 (three cups/glasses).",
  },
  {
    id: "ko-a1-numbers-004",
    level: "A1",
    deck: "numbers",
    en: "four (native)",
    ko: "넷",
    roman: "net",
    exampleKo: "의자가 넷 있어요.",
    exampleEn: "There are four chairs.",
    note: "Becomes 네 before a counter: 네 개 (four items).",
  },
  {
    id: "ko-a1-numbers-005",
    level: "A1",
    deck: "numbers",
    en: "five (native)",
    ko: "다섯",
    roman: "daseot",
    exampleKo: "다섯 명이에요.",
    exampleEn: "It's five people.",
    note: "Native number used for small counts up to about twenty.",
  },
  {
    id: "ko-a1-numbers-006",
    level: "A1",
    deck: "numbers",
    en: "ten (native)",
    ko: "열",
    roman: "yeol",
    exampleKo: "열 개 주세요.",
    exampleEn: "Give me ten, please.",
    note: "Native ten. 여섯·일곱·여덟·아홉 are six to nine.",
  },
  {
    id: "ko-a1-numbers-007",
    level: "A1",
    deck: "numbers",
    en: "one (Sino)",
    ko: "일",
    roman: "il",
    exampleKo: "일 번 출구로 나가세요.",
    exampleEn: "Go out through exit number one.",
    note: "Sino-Korean number. Used for dates, money, phone numbers, and minutes.",
  },
  {
    id: "ko-a1-numbers-008",
    level: "A1",
    deck: "numbers",
    en: "ten (Sino)",
    ko: "십",
    roman: "sip",
    exampleKo: "십 분 후에 만나요.",
    exampleEn: "Let's meet in ten minutes.",
    note: "Sino ten. 이십 = 20, 삼십 = 30, and so on.",
  },
  {
    id: "ko-a1-numbers-009",
    level: "A1",
    deck: "numbers",
    en: "hundred (Sino)",
    ko: "백",
    roman: "baek",
    exampleKo: "이거 백 원이에요.",
    exampleEn: "This is one hundred won.",
    note: "Sino hundred. 천 = 1,000 and 만 = 10,000.",
  },
  {
    id: "ko-a1-numbers-010",
    level: "A1",
    deck: "numbers",
    en: "How much is it?",
    ko: "얼마예요?",
    roman: "eolmayeyo?",
    exampleKo: "이거 얼마예요?",
    exampleEn: "How much is this?",
    note: "The go-to question for prices. Prices use Sino-Korean numbers.",
  },
  {
    id: "ko-a1-numbers-011",
    level: "A1",
    deck: "numbers",
    en: "~ item(s) (counter)",
    ko: "~ 개",
    roman: "~ gae",
    exampleKo: "빵 세 개 주세요.",
    exampleEn: "Three pieces of bread, please.",
    note: "General counter for objects, used with native numbers (한 개, 두 개...).",
  },
  {
    id: "ko-a1-numbers-012",
    level: "A1",
    deck: "numbers",
    en: "~ person/people (counter)",
    ko: "~ 명",
    roman: "~ myeong",
    exampleKo: "네 명이에요.",
    exampleEn: "It's four people.",
    note: "Counter for people, used with native numbers (한 명, 두 명...).",
  },

  // ── food (음식·식당) ─────────────────────────────────────────────────────
  {
    id: "ko-a1-food-001",
    level: "A1",
    deck: "food",
    en: "Please give me ~ (I'd like ~)",
    ko: "~ 주세요",
    roman: "~ juseyo",
    exampleKo: "물 주세요.",
    exampleEn: "Water, please.",
    note: "The essential ordering phrase. Put the item before 주세요.",
  },
  {
    id: "ko-a1-food-002",
    level: "A1",
    deck: "food",
    en: "menu",
    ko: "메뉴",
    roman: "menyu",
    exampleKo: "메뉴 좀 주세요.",
    exampleEn: "May I have the menu, please?",
    note: "A loanword from English. 좀 softens the request to 'please'.",
  },
  {
    id: "ko-a1-food-003",
    level: "A1",
    deck: "food",
    en: "water",
    ko: "물",
    roman: "mul",
    exampleKo: "물 한 잔 주세요.",
    exampleEn: "A glass of water, please.",
    note: "Water is usually free and self-serve in Korean restaurants.",
  },
  {
    id: "ko-a1-food-004",
    level: "A1",
    deck: "food",
    en: "rice / meal",
    ko: "밥",
    roman: "bap",
    exampleKo: "밥 먹었어요?",
    exampleEn: "Have you eaten?",
    note: "Literally 'rice', but 밥 먹었어요? is also a friendly greeting.",
  },
  {
    id: "ko-a1-food-005",
    level: "A1",
    deck: "food",
    en: "kimchi",
    ko: "김치",
    roman: "gimchi",
    exampleKo: "김치 좀 더 주세요.",
    exampleEn: "A little more kimchi, please.",
    note: "Side dishes like kimchi are typically refilled for free.",
  },
  {
    id: "ko-a1-food-006",
    level: "A1",
    deck: "food",
    en: "It's delicious",
    ko: "맛있어요",
    roman: "masisseoyo",
    exampleKo: "와, 정말 맛있어요!",
    exampleEn: "Wow, it's really delicious!",
    note: "Compliment for food. The opposite is 맛없어요 (it's not tasty).",
  },
  {
    id: "ko-a1-food-007",
    level: "A1",
    deck: "food",
    en: "It's spicy",
    ko: "매워요",
    roman: "maewoyo",
    exampleKo: "이거 너무 매워요.",
    exampleEn: "This is too spicy.",
    note: "From 맵다. Add 안 for 'not spicy': 안 매워요.",
  },
  {
    id: "ko-a1-food-008",
    level: "A1",
    deck: "food",
    en: "I want to eat ~",
    ko: "~ 먹고 싶어요",
    roman: "~ meokgo sipeoyo",
    exampleKo: "비빔밥 먹고 싶어요.",
    exampleEn: "I want to eat bibimbap.",
    note: "~고 싶어요 = 'want to'. Attach to a verb stem like 먹- (to eat).",
  },
  {
    id: "ko-a1-food-009",
    level: "A1",
    deck: "food",
    en: "I'll have this one",
    ko: "이거 주세요",
    roman: "igeo juseyo",
    exampleKo: "이거 하나 주세요.",
    exampleEn: "I'll have one of these.",
    note: "Point at the menu and say 이거 (this one) when you don't know the name.",
  },
  {
    id: "ko-a1-food-010",
    level: "A1",
    deck: "food",
    en: "Check, please",
    ko: "계산서 주세요",
    roman: "gyesanseo juseyo",
    exampleKo: "저기요, 계산서 주세요.",
    exampleEn: "Excuse me, the check, please.",
    note: "계산서 = bill. You can also just say 계산할게요 (I'll pay now).",
  },
  {
    id: "ko-a1-food-011",
    level: "A1",
    deck: "food",
    en: "Excuse me! (calling a server)",
    ko: "저기요",
    roman: "jeogiyo",
    exampleKo: "저기요, 여기 주문할게요.",
    exampleEn: "Excuse me, we'd like to order here.",
    note: "Standard way to get a server's attention in a restaurant.",
  },
  {
    id: "ko-a1-food-012",
    level: "A1",
    deck: "food",
    en: "to go / takeout",
    ko: "포장",
    roman: "pojang",
    exampleKo: "포장해 주세요.",
    exampleEn: "To go, please.",
    note: "포장 = packaging. 포장해 주세요 means 'please pack it to go'.",
  },

  // ── family (가족) ───────────────────────────────────────────────────────
  {
    id: "ko-a1-family-001",
    level: "A1",
    deck: "family",
    en: "family",
    ko: "가족",
    roman: "gajok",
    exampleKo: "우리 가족은 네 명이에요.",
    exampleEn: "There are four people in my family.",
    note: "우리 ('our') is often used instead of 'my' for family in Korean.",
  },
  {
    id: "ko-a1-family-002",
    level: "A1",
    deck: "family",
    en: "mother / mom",
    ko: "어머니",
    roman: "eomeoni",
    exampleKo: "어머니는 선생님이에요.",
    exampleEn: "My mother is a teacher.",
    note: "어머니 is polite; 엄마 (eomma) is the casual 'mom'.",
  },
  {
    id: "ko-a1-family-003",
    level: "A1",
    deck: "family",
    en: "father / dad",
    ko: "아버지",
    roman: "abeoji",
    exampleKo: "아버지는 회사원이에요.",
    exampleEn: "My father is an office worker.",
    note: "아버지 is polite; 아빠 (appa) is the casual 'dad'.",
  },
  {
    id: "ko-a1-family-004",
    level: "A1",
    deck: "family",
    en: "older brother (of a male)",
    ko: "형",
    roman: "hyeong",
    exampleKo: "형이 한 명 있어요.",
    exampleEn: "I have one older brother.",
    note: "A male calls his older brother 형. A female uses 오빠 instead.",
  },
  {
    id: "ko-a1-family-005",
    level: "A1",
    deck: "family",
    en: "older brother (of a female)",
    ko: "오빠",
    roman: "oppa",
    exampleKo: "오빠는 대학생이에요.",
    exampleEn: "My older brother is a college student.",
    note: "Only a female uses 오빠 for an older brother (or older male friend).",
  },
  {
    id: "ko-a1-family-006",
    level: "A1",
    deck: "family",
    en: "older sister (of a male)",
    ko: "누나",
    roman: "nuna",
    exampleKo: "누나가 두 명 있어요.",
    exampleEn: "I have two older sisters.",
    note: "A male calls his older sister 누나. A female uses 언니 instead.",
  },
  {
    id: "ko-a1-family-007",
    level: "A1",
    deck: "family",
    en: "older sister (of a female)",
    ko: "언니",
    roman: "eonni",
    exampleKo: "언니는 의사예요.",
    exampleEn: "My older sister is a doctor.",
    note: "Only a female uses 언니 for an older sister (or older female friend).",
  },
  {
    id: "ko-a1-family-008",
    level: "A1",
    deck: "family",
    en: "younger sibling",
    ko: "동생",
    roman: "dongsaeng",
    exampleKo: "동생이 있어요.",
    exampleEn: "I have a younger sibling.",
    note: "동생 covers both sexes. Specify with 남동생 (younger brother) / 여동생 (younger sister).",
  },
  {
    id: "ko-a1-family-009",
    level: "A1",
    deck: "family",
    en: "I have ~ (it exists)",
    ko: "있어요",
    roman: "isseoyo",
    exampleKo: "동생이 한 명 있어요.",
    exampleEn: "I have one younger sibling.",
    note: "있어요 means 'there is / I have'. The negative is 없어요.",
  },
  {
    id: "ko-a1-family-010",
    level: "A1",
    deck: "family",
    en: "I don't have ~ (none)",
    ko: "없어요",
    roman: "eopseoyo",
    exampleKo: "형제가 없어요.",
    exampleEn: "I don't have any siblings.",
    note: "없어요 means 'there isn't / I don't have'. The opposite of 있어요.",
  },
  {
    id: "ko-a1-family-011",
    level: "A1",
    deck: "family",
    en: "grandfather",
    ko: "할아버지",
    roman: "harabeoji",
    exampleKo: "할아버지는 부산에 사세요.",
    exampleEn: "My grandfather lives in Busan.",
    note: "Use the honorific 사세요 (not 살아요) when speaking about elders.",
  },
  {
    id: "ko-a1-family-012",
    level: "A1",
    deck: "family",
    en: "grandmother",
    ko: "할머니",
    roman: "halmeoni",
    exampleKo: "할머니가 요리를 잘하세요.",
    exampleEn: "My grandmother cooks well.",
    note: "Pairs with 할아버지. 잘하세요 = '(she) does well', honorific form.",
  },
];
