/**
 * A1 (입문) 한국어 학습 콘텐츠 — 영어권 학습자 대상.
 * 각 카드: 한국어 표현(ko) + 로마자(roman) + 영어 뜻(en) + 예문(한/영).
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * note 는 영어(학습자 모국어)로 사용 맥락을 설명한다.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_A1_DECKS: Deck[] = [
  {
    id: "greetings",
    level: "A1",
    title: { ko: "인사", en: "Greetings", zh: "问候" },
    description: { ko: "기본 인사와 작별", en: "Hellos and goodbyes", zh: "基本问候与道别" },
    order: 1,
    icon: "Hand",
  },
  {
    id: "self-intro",
    level: "A1",
    title: { ko: "자기소개", en: "Introducing Yourself", zh: "自我介绍" },
    description: { ko: "이름·출신·직업·나이", en: "Name, origin, job, and age", zh: "姓名、出身、职业、年龄" },
    order: 2,
    icon: "UserRound",
  },
  {
    id: "numbers",
    level: "A1",
    title: { ko: "숫자", en: "Numbers", zh: "数字" },
    description: { ko: "하나~열, 십~백, 수량 세기", en: "Counting and quantities", zh: "一到十、十到百、数数量" },
    order: 3,
    icon: "Hash",
  },
  {
    id: "food",
    level: "A1",
    title: { ko: "음식·식당", en: "Food & Dining", zh: "饮食·餐厅" },
    description: { ko: "주문·맛·계산", en: "Ordering, taste, and paying", zh: "点餐、味道、结账" },
    order: 4,
    icon: "Utensils",
  },
  {
    id: "family",
    level: "A1",
    title: { ko: "가족", en: "Family", zh: "家人" },
    description: { ko: "가족 호칭·소개", en: "Family members and introductions", zh: "家人的称呼与介绍" },
    order: 5,
    icon: "Users",
  },
];

export const KO_A1_CARDS: VocabCard[] = [
  {
    id: "ko-a1-greetings-001",
    level: "A1",
    deck: "greetings",
    en: "Hello",
    zh: "你好",
    ko: "안녕하세요",
    roman: "annyeonghaseyo",
    exampleKo: "안녕하세요, 만나서 반가워요.",
    exampleEn: "Hello, nice to meet you.",
    exampleZh: "你好，很高兴见到你。",
    note: "The standard polite greeting — works any time of day.",
    noteZh: "最标准的礼貌问候语，一天中任何时候都能用。",
  },
  {
    id: "ko-a1-greetings-002",
    level: "A1",
    deck: "greetings",
    en: "Goodbye (to someone leaving)",
    zh: "再见（对离开的人说）",
    ko: "안녕히 가세요",
    roman: "annyeonghi gaseyo",
    exampleKo: "안녕히 가세요, 또 만나요.",
    exampleEn: "Goodbye, see you again.",
    exampleZh: "再见，下次见。",
    note: "Say this to the person who is leaving while you stay.",
    noteZh: "你留下、对方离开时，对要离开的人说这句话。",
  },
  {
    id: "ko-a1-greetings-003",
    level: "A1",
    deck: "greetings",
    en: "Goodbye (to someone staying)",
    zh: "再见（对留下的人说）",
    ko: "안녕히 계세요",
    roman: "annyeonghi gyeseyo",
    exampleKo: "안녕히 계세요, 내일 봬요.",
    exampleEn: "Goodbye, see you tomorrow.",
    exampleZh: "再见，明天见。",
    note: "Say this when you are the one leaving and they stay.",
    noteZh: "你离开、对方留下时说这句话。",
  },
  {
    id: "ko-a1-greetings-004",
    level: "A1",
    deck: "greetings",
    en: "Thank you",
    zh: "谢谢",
    ko: "감사합니다",
    roman: "gamsahamnida",
    exampleKo: "도와주셔서 감사합니다.",
    exampleEn: "Thank you for your help.",
    exampleZh: "谢谢您的帮助。",
    note: "Polite, formal thanks — safe in almost any situation.",
    noteZh: "礼貌正式的感谢，几乎任何场合都适用。",
  },
  {
    id: "ko-a1-greetings-005",
    level: "A1",
    deck: "greetings",
    en: "Thanks",
    zh: "谢谢（更亲切）",
    ko: "고맙습니다",
    roman: "gomapseumnida",
    exampleKo: "정말 고맙습니다.",
    exampleEn: "Thank you so much.",
    exampleZh: "真的非常感谢。",
    note: "Also polite; a touch warmer and more native than 감사합니다.",
    noteZh: "同样礼貌，比감사합니다更亲切、更地道。",
  },
  {
    id: "ko-a1-greetings-006",
    level: "A1",
    deck: "greetings",
    en: "I'm sorry",
    zh: "对不起",
    ko: "죄송합니다",
    roman: "joesonghamnida",
    exampleKo: "늦어서 죄송합니다.",
    exampleEn: "I'm sorry for being late.",
    exampleZh: "对不起，我来晚了。",
    note: "Formal apology. Use 미안해요 with close friends.",
    noteZh: "正式的道歉。对亲近的朋友用미안해요。",
  },
  {
    id: "ko-a1-greetings-007",
    level: "A1",
    deck: "greetings",
    en: "It's okay / It's fine",
    zh: "没关系 / 没事",
    ko: "괜찮아요",
    roman: "gwaenchanayo",
    exampleKo: "괜찮아요, 신경 쓰지 마세요.",
    exampleEn: "It's okay, don't worry about it.",
    exampleZh: "没关系，别放在心上。",
    note: "Versatile: accepts apologies, declines offers, says you're fine.",
    noteZh: "用途广泛：可接受道歉、婉拒好意、表示自己没事。",
  },
  {
    id: "ko-a1-greetings-008",
    level: "A1",
    deck: "greetings",
    en: "Yes",
    zh: "是 / 好的",
    ko: "네",
    roman: "ne",
    exampleKo: "네, 맞아요.",
    exampleEn: "Yes, that's right.",
    exampleZh: "是的，没错。",
    note: "Standard polite 'yes'. 예 (ye) is a bit more formal.",
    noteZh: "标准的礼貌“是”。예更正式一些。",
  },
  {
    id: "ko-a1-greetings-009",
    level: "A1",
    deck: "greetings",
    en: "No",
    zh: "不 / 不是",
    ko: "아니요",
    roman: "aniyo",
    exampleKo: "아니요, 괜찮아요.",
    exampleEn: "No, I'm fine.",
    exampleZh: "不用了，没关系。",
    note: "Polite 'no'. Often softened with 괜찮아요 to stay friendly.",
    noteZh: "礼貌的“不”。常加괜찮아요让语气更友好。",
  },
  {
    id: "ko-a1-greetings-010",
    level: "A1",
    deck: "greetings",
    en: "Excuse me",
    zh: "打扰一下",
    ko: "실례합니다",
    roman: "sillyehamnida",
    exampleKo: "실례합니다, 길 좀 묻겠습니다.",
    exampleEn: "Excuse me, may I ask for directions?",
    exampleZh: "打扰一下，我想问一下路。",
    note: "Use to get attention politely or before interrupting.",
    noteZh: "礼貌地引起注意或打断别人之前用。",
  },
  {
    id: "ko-a1-greetings-011",
    level: "A1",
    deck: "greetings",
    en: "Nice to meet you",
    zh: "很高兴见到你",
    ko: "만나서 반갑습니다",
    roman: "mannaseo bangapseumnida",
    exampleKo: "만나서 반갑습니다. 저는 민수예요.",
    exampleEn: "Nice to meet you. I'm Minsu.",
    exampleZh: "很高兴见到你。我是民秀。",
    note: "Standard first-meeting line. 반가워요 is the softer casual form.",
    noteZh: "初次见面的标准用语。반가워요是更柔和随意的说法。",
  },
  {
    id: "ko-a1-greetings-012",
    level: "A1",
    deck: "greetings",
    en: "How have you been?",
    zh: "最近过得好吗？",
    ko: "잘 지내셨어요?",
    roman: "jal jinaesyeosseoyo?",
    exampleKo: "오랜만이에요. 잘 지내셨어요?",
    exampleEn: "Long time no see. How have you been?",
    exampleZh: "好久不见。最近过得好吗？",
    note: "Polite catch-up greeting for someone you haven't seen in a while.",
    noteZh: "对久未见面的人礼貌寒暄时用。",
  },

  // ── self-intro (자기소개) ───────────────────────────────────────────────
  {
    id: "ko-a1-self-intro-001",
    level: "A1",
    deck: "self-intro",
    en: "I am ~ (My name is ~)",
    zh: "我是～",
    ko: "저는 ~예요",
    roman: "jeoneun ~yeyo",
    exampleKo: "저는 사라예요.",
    exampleEn: "I'm Sarah.",
    exampleZh: "我是莎拉。",
    note: "Use 예요 after a vowel, 이에요 after a consonant. 저는 = 'as for me'.",
    noteZh: "元音结尾用예요，辅音结尾用이에요。저는意为“我（的话）”。",
  },
  {
    id: "ko-a1-self-intro-002",
    level: "A1",
    deck: "self-intro",
    en: "My name is ~",
    zh: "我的名字是～",
    ko: "제 이름은 ~이에요",
    roman: "je ireumeun ~ieyo",
    exampleKo: "제 이름은 민준이에요.",
    exampleEn: "My name is Minjun.",
    exampleZh: "我的名字是民俊。",
    note: "제 이름은 = 'my name'. A more explicit way to give your name.",
    noteZh: "제 이름은意为“我的名字”，是更明确的自报姓名方式。",
  },
  {
    id: "ko-a1-self-intro-003",
    level: "A1",
    deck: "self-intro",
    en: "What is your name?",
    zh: "你叫什么名字？",
    ko: "이름이 뭐예요?",
    roman: "ireumi mwoyeyo?",
    exampleKo: "안녕하세요, 이름이 뭐예요?",
    exampleEn: "Hello, what's your name?",
    exampleZh: "你好，你叫什么名字？",
    note: "Casual-polite. Use 성함이 어떻게 되세요? to be extra formal.",
    noteZh: "随和又礼貌。更正式时用성함이 어떻게 되세요?。",
  },
  {
    id: "ko-a1-self-intro-004",
    level: "A1",
    deck: "self-intro",
    en: "Where are you from?",
    zh: "你从哪里来？",
    ko: "어디에서 왔어요?",
    roman: "eodieseo wasseoyo?",
    exampleKo: "어디에서 왔어요? 저는 캐나다에서 왔어요.",
    exampleEn: "Where are you from? I'm from Canada.",
    exampleZh: "你从哪里来？我来自加拿大。",
    note: "Literally 'where did you come from?'. A standard get-to-know-you line.",
    noteZh: "直译是“你从哪里来”，是认识新朋友的常用问句。",
  },
  {
    id: "ko-a1-self-intro-005",
    level: "A1",
    deck: "self-intro",
    en: "I'm from ~",
    zh: "我来自～",
    ko: "저는 ~에서 왔어요",
    roman: "jeoneun ~eseo wasseoyo",
    exampleKo: "저는 미국에서 왔어요.",
    exampleEn: "I'm from the US.",
    exampleZh: "我来自美国。",
    note: "Put the country before 에서. 에서 marks the place of origin.",
    noteZh: "国家名放在에서前面。에서表示出身地。",
  },
  {
    id: "ko-a1-self-intro-006",
    level: "A1",
    deck: "self-intro",
    en: "I am a student",
    zh: "我是学生",
    ko: "저는 학생이에요",
    roman: "jeoneun haksaengieyo",
    exampleKo: "저는 대학교 학생이에요.",
    exampleEn: "I'm a university student.",
    exampleZh: "我是大学生。",
    note: "학생 = student. 이에요 follows because 학생 ends in a consonant.",
    noteZh: "학생即学生。因학생以辅音结尾，所以接이에요。",
  },
  {
    id: "ko-a1-self-intro-007",
    level: "A1",
    deck: "self-intro",
    en: "What do you do (for work)?",
    zh: "您做什么工作？",
    ko: "무슨 일 하세요?",
    roman: "museun il haseyo?",
    exampleKo: "실례지만, 무슨 일 하세요?",
    exampleEn: "Excuse me, what do you do for work?",
    exampleZh: "不好意思，请问您做什么工作？",
    note: "Literally 'what work do you do?'. Polite way to ask someone's job.",
    noteZh: "直译是“您做什么工作”，是礼貌询问职业的说法。",
  },
  {
    id: "ko-a1-self-intro-008",
    level: "A1",
    deck: "self-intro",
    en: "I am an office worker",
    zh: "我是公司职员",
    ko: "저는 회사원이에요",
    roman: "jeoneun hoesawonieyo",
    exampleKo: "저는 회사원이에요. 서울에서 일해요.",
    exampleEn: "I'm an office worker. I work in Seoul.",
    exampleZh: "我是公司职员。我在首尔工作。",
    note: "회사원 = company employee, a very common answer about one's job.",
    noteZh: "회사원即公司职员，是回答职业时非常常见的说法。",
  },
  {
    id: "ko-a1-self-intro-009",
    level: "A1",
    deck: "self-intro",
    en: "Nice to meet you (set phrase)",
    zh: "请多关照",
    ko: "잘 부탁드려요",
    roman: "jal butakdeuryeoyo",
    exampleKo: "앞으로 잘 부탁드려요.",
    exampleEn: "I look forward to working with you.",
    exampleZh: "今后请多多关照。",
    note: "Set phrase to close an introduction. No direct English equivalent.",
    noteZh: "结束自我介绍的固定用语，相当于“请多关照”。",
  },
  {
    id: "ko-a1-self-intro-010",
    level: "A1",
    deck: "self-intro",
    en: "How old are you?",
    zh: "您多大年纪？",
    ko: "나이가 어떻게 되세요?",
    roman: "naiga eotteoke doeseyo?",
    exampleKo: "나이가 어떻게 되세요? 저는 스물다섯 살이에요.",
    exampleEn: "How old are you? I'm twenty-five.",
    exampleZh: "您多大年纪？我二十五岁。",
    note: "Polite way to ask age. Age matters for choosing the right speech level.",
    noteZh: "礼貌询问年龄的说法。年龄决定该用哪种敬语等级。",
  },
  {
    id: "ko-a1-self-intro-011",
    level: "A1",
    deck: "self-intro",
    en: "I live in ~",
    zh: "我住在～",
    ko: "저는 ~에 살아요",
    roman: "jeoneun ~e sarayo",
    exampleKo: "저는 서울에 살아요.",
    exampleEn: "I live in Seoul.",
    exampleZh: "我住在首尔。",
    note: "에 marks the place where you live (location, not direction).",
    noteZh: "에表示居住的地点（位置，不是方向）。",
  },
  {
    id: "ko-a1-self-intro-012",
    level: "A1",
    deck: "self-intro",
    en: "Please speak comfortably (casually) to me",
    zh: "您说话随意就好",
    ko: "말씀 편하게 하세요",
    roman: "malsseum pyeonhage haseyo",
    exampleKo: "제가 더 어려요. 말씀 편하게 하세요.",
    exampleEn: "I'm younger. Please feel free to speak casually to me.",
    exampleZh: "我年纪更小，您说话随意就好。",
    note: "Polite offer to let an older person drop formal speech with you.",
    noteZh: "礼貌地请年长者对自己不必用敬语。",
  },

  // ── numbers (숫자) ──────────────────────────────────────────────────────
  {
    id: "ko-a1-numbers-001",
    level: "A1",
    deck: "numbers",
    en: "one (native)",
    zh: "一（固有数词）",
    ko: "하나",
    roman: "hana",
    exampleKo: "커피 하나 주세요.",
    exampleEn: "One coffee, please.",
    exampleZh: "请给我一杯咖啡。",
    note: "Native Korean number. Used for counting things, age, and hours.",
    noteZh: "韩语固有数词，用于数物品、年龄和小时。",
  },
  {
    id: "ko-a1-numbers-002",
    level: "A1",
    deck: "numbers",
    en: "two (native)",
    zh: "二（固有数词）",
    ko: "둘",
    roman: "dul",
    exampleKo: "사과 둘이요.",
    exampleEn: "Two apples.",
    exampleZh: "两个苹果。",
    note: "Becomes 두 before a counter: 두 개 (two items), 두 명 (two people).",
    noteZh: "在量词前变成두：두 개（两个）、두 명（两个人）。",
  },
  {
    id: "ko-a1-numbers-003",
    level: "A1",
    deck: "numbers",
    en: "three (native)",
    zh: "三（固有数词）",
    ko: "셋",
    roman: "set",
    exampleKo: "셋이 함께 가요.",
    exampleEn: "The three of us go together.",
    exampleZh: "我们三个人一起去。",
    note: "Becomes 세 before a counter: 세 잔 (three cups/glasses).",
    noteZh: "在量词前变成세：세 잔（三杯）。",
  },
  {
    id: "ko-a1-numbers-004",
    level: "A1",
    deck: "numbers",
    en: "four (native)",
    zh: "四（固有数词）",
    ko: "넷",
    roman: "net",
    exampleKo: "의자가 넷 있어요.",
    exampleEn: "There are four chairs.",
    exampleZh: "有四把椅子。",
    note: "Becomes 네 before a counter: 네 개 (four items).",
    noteZh: "在量词前变成네：네 개（四个）。",
  },
  {
    id: "ko-a1-numbers-005",
    level: "A1",
    deck: "numbers",
    en: "five (native)",
    zh: "五（固有数词）",
    ko: "다섯",
    roman: "daseot",
    exampleKo: "다섯 명이에요.",
    exampleEn: "It's five people.",
    exampleZh: "是五个人。",
    note: "Native number used for small counts up to about twenty.",
    noteZh: "固有数词，多用于二十以内的小数目。",
  },
  {
    id: "ko-a1-numbers-006",
    level: "A1",
    deck: "numbers",
    en: "ten (native)",
    zh: "十（固有数词）",
    ko: "열",
    roman: "yeol",
    exampleKo: "열 개 주세요.",
    exampleEn: "Give me ten, please.",
    exampleZh: "请给我十个。",
    note: "Native ten. 여섯·일곱·여덟·아홉 are six to nine.",
    noteZh: "固有数词的十。여섯·일곱·여덟·아홉是六到九。",
  },
  {
    id: "ko-a1-numbers-007",
    level: "A1",
    deck: "numbers",
    en: "one (Sino)",
    zh: "一（汉字数词）",
    ko: "일",
    roman: "il",
    exampleKo: "일 번 출구로 나가세요.",
    exampleEn: "Go out through exit number one.",
    exampleZh: "请从一号出口出去。",
    note: "Sino-Korean number. Used for dates, money, phone numbers, and minutes.",
    noteZh: "汉字数词，用于日期、金额、电话号码和分钟。",
  },
  {
    id: "ko-a1-numbers-008",
    level: "A1",
    deck: "numbers",
    en: "ten (Sino)",
    zh: "十（汉字数词）",
    ko: "십",
    roman: "sip",
    exampleKo: "십 분 후에 만나요.",
    exampleEn: "Let's meet in ten minutes.",
    exampleZh: "十分钟后见。",
    note: "Sino ten. 이십 = 20, 삼십 = 30, and so on.",
    noteZh: "汉字数词的十。이십=20、삼십=30，以此类推。",
  },
  {
    id: "ko-a1-numbers-009",
    level: "A1",
    deck: "numbers",
    en: "hundred (Sino)",
    zh: "百（汉字数词）",
    ko: "백",
    roman: "baek",
    exampleKo: "이거 백 원이에요.",
    exampleEn: "This is one hundred won.",
    exampleZh: "这个是一百韩元。",
    note: "Sino hundred. 천 = 1,000 and 만 = 10,000.",
    noteZh: "汉字数词的百。천=1,000，만=10,000。",
  },
  {
    id: "ko-a1-numbers-010",
    level: "A1",
    deck: "numbers",
    en: "How much is it?",
    zh: "多少钱？",
    ko: "얼마예요?",
    roman: "eolmayeyo?",
    exampleKo: "이거 얼마예요?",
    exampleEn: "How much is this?",
    exampleZh: "这个多少钱？",
    note: "The go-to question for prices. Prices use Sino-Korean numbers.",
    noteZh: "问价格的常用句。价格用汉字数词表达。",
  },
  {
    id: "ko-a1-numbers-011",
    level: "A1",
    deck: "numbers",
    en: "~ item(s) (counter)",
    zh: "～个（量词）",
    ko: "~ 개",
    roman: "~ gae",
    exampleKo: "빵 세 개 주세요.",
    exampleEn: "Three pieces of bread, please.",
    exampleZh: "请给我三个面包。",
    note: "General counter for objects, used with native numbers (한 개, 두 개...).",
    noteZh: "物品的通用量词，与固有数词连用（한 개、두 개……）。",
  },
  {
    id: "ko-a1-numbers-012",
    level: "A1",
    deck: "numbers",
    en: "~ person/people (counter)",
    zh: "～名 / 人（量词）",
    ko: "~ 명",
    roman: "~ myeong",
    exampleKo: "네 명이에요.",
    exampleEn: "It's four people.",
    exampleZh: "是四个人。",
    note: "Counter for people, used with native numbers (한 명, 두 명...).",
    noteZh: "数人的量词，与固有数词连用（한 명、두 명……）。",
  },

  // ── food (음식·식당) ─────────────────────────────────────────────────────
  {
    id: "ko-a1-food-001",
    level: "A1",
    deck: "food",
    en: "Please give me ~ (I'd like ~)",
    zh: "请给我～",
    ko: "~ 주세요",
    roman: "~ juseyo",
    exampleKo: "물 주세요.",
    exampleEn: "Water, please.",
    exampleZh: "请给我水。",
    note: "The essential ordering phrase. Put the item before 주세요.",
    noteZh: "点餐必备句型。把物品放在주세요前面。",
  },
  {
    id: "ko-a1-food-002",
    level: "A1",
    deck: "food",
    en: "menu",
    zh: "菜单",
    ko: "메뉴",
    roman: "menyu",
    exampleKo: "메뉴 좀 주세요.",
    exampleEn: "May I have the menu, please?",
    exampleZh: "请给我菜单。",
    note: "A loanword from English. 좀 softens the request to 'please'.",
    noteZh: "来自英语的外来词。좀让请求语气更委婉。",
  },
  {
    id: "ko-a1-food-003",
    level: "A1",
    deck: "food",
    en: "water",
    zh: "水",
    ko: "물",
    roman: "mul",
    exampleKo: "물 한 잔 주세요.",
    exampleEn: "A glass of water, please.",
    exampleZh: "请给我一杯水。",
    note: "Water is usually free and self-serve in Korean restaurants.",
    noteZh: "韩国餐厅的水通常免费，自助取用。",
  },
  {
    id: "ko-a1-food-004",
    level: "A1",
    deck: "food",
    en: "rice / meal",
    zh: "米饭 / 饭",
    ko: "밥",
    roman: "bap",
    exampleKo: "밥 먹었어요?",
    exampleEn: "Have you eaten?",
    exampleZh: "吃饭了吗？",
    note: "Literally 'rice', but 밥 먹었어요? is also a friendly greeting.",
    noteZh: "本义是“米饭”，但밥 먹었어요?也是亲切的问候语。",
  },
  {
    id: "ko-a1-food-005",
    level: "A1",
    deck: "food",
    en: "kimchi",
    zh: "泡菜（辛奇）",
    ko: "김치",
    roman: "gimchi",
    exampleKo: "김치 좀 더 주세요.",
    exampleEn: "A little more kimchi, please.",
    exampleZh: "请再给我一点泡菜。",
    note: "Side dishes like kimchi are typically refilled for free.",
    noteZh: "泡菜等小菜通常可以免费续加。",
  },
  {
    id: "ko-a1-food-006",
    level: "A1",
    deck: "food",
    en: "It's delicious",
    zh: "好吃 / 很美味",
    ko: "맛있어요",
    roman: "masisseoyo",
    exampleKo: "와, 정말 맛있어요!",
    exampleEn: "Wow, it's really delicious!",
    exampleZh: "哇，真好吃！",
    note: "Compliment for food. The opposite is 맛없어요 (it's not tasty).",
    noteZh: "夸食物好吃的话。反义是맛없어요（不好吃）。",
  },
  {
    id: "ko-a1-food-007",
    level: "A1",
    deck: "food",
    en: "It's spicy",
    zh: "辣",
    ko: "매워요",
    roman: "maewoyo",
    exampleKo: "이거 너무 매워요.",
    exampleEn: "This is too spicy.",
    exampleZh: "这个太辣了。",
    note: "From 맵다. Add 안 for 'not spicy': 안 매워요.",
    noteZh: "来自맵다。前加안表示“不辣”：안 매워요。",
  },
  {
    id: "ko-a1-food-008",
    level: "A1",
    deck: "food",
    en: "I want to eat ~",
    zh: "我想吃～",
    ko: "~ 먹고 싶어요",
    roman: "~ meokgo sipeoyo",
    exampleKo: "비빔밥 먹고 싶어요.",
    exampleEn: "I want to eat bibimbap.",
    exampleZh: "我想吃拌饭。",
    note: "~고 싶어요 = 'want to'. Attach to a verb stem like 먹- (to eat).",
    noteZh: "~고 싶어요表示“想做”，接在먹-（吃）等动词词干后。",
  },
  {
    id: "ko-a1-food-009",
    level: "A1",
    deck: "food",
    en: "I'll have this one",
    zh: "请给我这个",
    ko: "이거 주세요",
    roman: "igeo juseyo",
    exampleKo: "이거 하나 주세요.",
    exampleEn: "I'll have one of these.",
    exampleZh: "请给我一个这个。",
    note: "Point at the menu and say 이거 (this one) when you don't know the name.",
    noteZh: "不知道菜名时，指着菜单说이거（这个）就行。",
  },
  {
    id: "ko-a1-food-010",
    level: "A1",
    deck: "food",
    en: "Check, please",
    zh: "请给我账单",
    ko: "계산서 주세요",
    roman: "gyesanseo juseyo",
    exampleKo: "저기요, 계산서 주세요.",
    exampleEn: "Excuse me, the check, please.",
    exampleZh: "服务员，请给我账单。",
    note: "계산서 = bill. You can also just say 계산할게요 (I'll pay now).",
    noteZh: "계산서即账单。也可以直接说계산할게요（我要买单）。",
  },
  {
    id: "ko-a1-food-011",
    level: "A1",
    deck: "food",
    en: "Excuse me! (calling a server)",
    zh: "服务员！（招呼店员）",
    ko: "저기요",
    roman: "jeogiyo",
    exampleKo: "저기요, 여기 주문할게요.",
    exampleEn: "Excuse me, we'd like to order here.",
    exampleZh: "服务员，我们这边要点餐。",
    note: "Standard way to get a server's attention in a restaurant.",
    noteZh: "在餐厅招呼服务员的标准说法。",
  },
  {
    id: "ko-a1-food-012",
    level: "A1",
    deck: "food",
    en: "to go / takeout",
    zh: "打包 / 外带",
    ko: "포장",
    roman: "pojang",
    exampleKo: "포장해 주세요.",
    exampleEn: "To go, please.",
    exampleZh: "请帮我打包。",
    note: "포장 = packaging. 포장해 주세요 means 'please pack it to go'.",
    noteZh: "포장本义是包装。포장해 주세요意为“请打包带走”。",
  },

  // ── family (가족) ───────────────────────────────────────────────────────
  {
    id: "ko-a1-family-001",
    level: "A1",
    deck: "family",
    en: "family",
    zh: "家人 / 家庭",
    ko: "가족",
    roman: "gajok",
    exampleKo: "우리 가족은 네 명이에요.",
    exampleEn: "There are four people in my family.",
    exampleZh: "我们家有四口人。",
    note: "우리 ('our') is often used instead of 'my' for family in Korean.",
    noteZh: "韩语说家人时常用우리（我们的）代替“我的”。",
  },
  {
    id: "ko-a1-family-002",
    level: "A1",
    deck: "family",
    en: "mother / mom",
    zh: "母亲 / 妈妈",
    ko: "어머니",
    roman: "eomeoni",
    exampleKo: "어머니는 선생님이에요.",
    exampleEn: "My mother is a teacher.",
    exampleZh: "我妈妈是老师。",
    note: "어머니 is polite; 엄마 (eomma) is the casual 'mom'.",
    noteZh: "어머니是礼貌说法；엄마是随意的“妈妈”。",
  },
  {
    id: "ko-a1-family-003",
    level: "A1",
    deck: "family",
    en: "father / dad",
    zh: "父亲 / 爸爸",
    ko: "아버지",
    roman: "abeoji",
    exampleKo: "아버지는 회사원이에요.",
    exampleEn: "My father is an office worker.",
    exampleZh: "我爸爸是公司职员。",
    note: "아버지 is polite; 아빠 (appa) is the casual 'dad'.",
    noteZh: "아버지是礼貌说法；아빠是随意的“爸爸”。",
  },
  {
    id: "ko-a1-family-004",
    level: "A1",
    deck: "family",
    en: "older brother (of a male)",
    zh: "哥哥（男性称呼）",
    ko: "형",
    roman: "hyeong",
    exampleKo: "형이 한 명 있어요.",
    exampleEn: "I have one older brother.",
    exampleZh: "我有一个哥哥。",
    note: "A male calls his older brother 형. A female uses 오빠 instead.",
    noteZh: "男性叫哥哥用형，女性则用오빠。",
  },
  {
    id: "ko-a1-family-005",
    level: "A1",
    deck: "family",
    en: "older brother (of a female)",
    zh: "哥哥（女性称呼）",
    ko: "오빠",
    roman: "oppa",
    exampleKo: "오빠는 대학생이에요.",
    exampleEn: "My older brother is a college student.",
    exampleZh: "我哥哥是大学生。",
    note: "Only a female uses 오빠 for an older brother (or older male friend).",
    noteZh: "只有女性用오빠称呼哥哥（或年长的男性朋友）。",
  },
  {
    id: "ko-a1-family-006",
    level: "A1",
    deck: "family",
    en: "older sister (of a male)",
    zh: "姐姐（男性称呼）",
    ko: "누나",
    roman: "nuna",
    exampleKo: "누나가 두 명 있어요.",
    exampleEn: "I have two older sisters.",
    exampleZh: "我有两个姐姐。",
    note: "A male calls his older sister 누나. A female uses 언니 instead.",
    noteZh: "男性叫姐姐用누나，女性则用언니。",
  },
  {
    id: "ko-a1-family-007",
    level: "A1",
    deck: "family",
    en: "older sister (of a female)",
    zh: "姐姐（女性称呼）",
    ko: "언니",
    roman: "eonni",
    exampleKo: "언니는 의사예요.",
    exampleEn: "My older sister is a doctor.",
    exampleZh: "我姐姐是医生。",
    note: "Only a female uses 언니 for an older sister (or older female friend).",
    noteZh: "只有女性用언니称呼姐姐（或年长的女性朋友）。",
  },
  {
    id: "ko-a1-family-008",
    level: "A1",
    deck: "family",
    en: "younger sibling",
    zh: "弟弟 / 妹妹",
    ko: "동생",
    roman: "dongsaeng",
    exampleKo: "동생이 있어요.",
    exampleEn: "I have a younger sibling.",
    exampleZh: "我有弟弟（或妹妹）。",
    note: "동생 covers both sexes. Specify with 남동생 (younger brother) / 여동생 (younger sister).",
    noteZh: "동생不分性别。可用남동생（弟弟）/여동생（妹妹）具体区分。",
  },
  {
    id: "ko-a1-family-009",
    level: "A1",
    deck: "family",
    en: "I have ~ (it exists)",
    zh: "有 / 在",
    ko: "있어요",
    roman: "isseoyo",
    exampleKo: "동생이 한 명 있어요.",
    exampleEn: "I have one younger sibling.",
    exampleZh: "我有一个弟弟（或妹妹）。",
    note: "있어요 means 'there is / I have'. The negative is 없어요.",
    noteZh: "있어요表示“有/存在”，否定形是없어요。",
  },
  {
    id: "ko-a1-family-010",
    level: "A1",
    deck: "family",
    en: "I don't have ~ (none)",
    zh: "没有",
    ko: "없어요",
    roman: "eopseoyo",
    exampleKo: "형제가 없어요.",
    exampleEn: "I don't have any siblings.",
    exampleZh: "我没有兄弟姐妹。",
    note: "없어요 means 'there isn't / I don't have'. The opposite of 있어요.",
    noteZh: "없어요表示“没有”，是있어요的反义。",
  },
  {
    id: "ko-a1-family-011",
    level: "A1",
    deck: "family",
    en: "grandfather",
    zh: "爷爷 / 外公",
    ko: "할아버지",
    roman: "harabeoji",
    exampleKo: "할아버지는 부산에 사세요.",
    exampleEn: "My grandfather lives in Busan.",
    exampleZh: "我爷爷住在釜山。",
    note: "Use the honorific 사세요 (not 살아요) when speaking about elders.",
    noteZh: "谈到长辈时要用敬语사세요（而不是살아요）。",
  },
  {
    id: "ko-a1-family-012",
    level: "A1",
    deck: "family",
    en: "grandmother",
    zh: "奶奶 / 外婆",
    ko: "할머니",
    roman: "halmeoni",
    exampleKo: "할머니가 요리를 잘하세요.",
    exampleEn: "My grandmother cooks well.",
    exampleZh: "我奶奶很会做菜。",
    note: "Pairs with 할아버지. 잘하세요 = '(she) does well', honorific form.",
    noteZh: "与할아버지相对。잘하세요是“做得好”的敬语形式。",
  },
];
