/**
 * A2 (초급) 한국어 학습 콘텐츠 — 영어권 학습자 대상.
 * 각 카드: 한국어 표현(ko) + 로마자(roman) + 영어 뜻(en) + 예문(한/영).
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * note 는 영어(학습자 모국어)로 사용 맥락을 설명한다.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_A2_DECKS: Deck[] = [
  {
    id: "time-date",
    level: "A2",
    title: { ko: "시간·날짜", en: "Time & Date", zh: "时间·日期", vi: "Thời gian · Ngày tháng" },
    description: { ko: "시간, 요일, 날짜 말하기", en: "Telling time, days, and dates", zh: "说时间、星期、日期", vi: "Nói về thời gian, thứ trong tuần và ngày tháng" },
    order: 1,
    icon: "Clock",
  },
  {
    id: "shopping",
    level: "A2",
    title: { ko: "쇼핑", en: "Shopping", zh: "购物", vi: "Mua sắm" },
    description: { ko: "가게에서 사고 묻기", en: "Buying and asking in stores", zh: "在店里购买和询问", vi: "Mua hàng và hỏi han ở cửa hàng" },
    order: 2,
    icon: "ShoppingBag",
  },
  {
    id: "transport",
    level: "A2",
    title: { ko: "교통", en: "Transportation", zh: "交通", vi: "Giao thông" },
    description: { ko: "버스, 지하철, 길 찾기", en: "Buses, subways, and getting around", zh: "公交、地铁、问路", vi: "Xe buýt, tàu điện ngầm và tìm đường" },
    order: 3,
    icon: "Bus",
  },
  {
    id: "weather",
    level: "A2",
    title: { ko: "날씨", en: "Weather", zh: "天气", vi: "Thời tiết" },
    description: { ko: "날씨와 계절 말하기", en: "Talking about weather and seasons", zh: "谈论天气和季节", vi: "Nói về thời tiết và các mùa" },
    order: 4,
    icon: "CloudSun",
  },
  {
    id: "hobby",
    level: "A2",
    title: { ko: "취미·여가", en: "Hobbies", zh: "爱好·休闲", vi: "Sở thích · Giải trí" },
    description: { ko: "취미와 여가 활동", en: "Hobbies and free-time activities", zh: "爱好与休闲活动", vi: "Sở thích và các hoạt động giải trí" },
    order: 5,
    icon: "Gamepad2",
  },
];

export const KO_A2_CARDS: VocabCard[] = [
  // ───────── time-date (시간·날짜) ─────────
  {
    id: "ko-a2-time-date-001",
    level: "A2",
    deck: "time-date",
    en: "What time is it now?",
    zh: "现在几点？",
    vi: "Bây giờ là mấy giờ?",
    ko: "지금 몇 시예요?",
    roman: "jigeum myeot siyeyo?",
    exampleKo: "실례합니다, 지금 몇 시예요?",
    exampleEn: "Excuse me, what time is it now?",
    exampleZh: "不好意思，现在几点？",
    exampleVi: "Xin lỗi, bây giờ là mấy giờ ạ?",
    note: "몇 (myeot) means 'how many/what'; 시 (si) is the counter for the hour.",
    noteZh: "몇意为“多少/几”；시是“点（钟）”的量词。",
    noteVi: "몇 (myeot) nghĩa là 'bao nhiêu/mấy'; 시 (si) là lượng từ chỉ giờ.",
  },
  {
    id: "ko-a2-time-date-002",
    level: "A2",
    deck: "time-date",
    en: "It's three o'clock.",
    zh: "三点。",
    vi: "Là ba giờ.",
    ko: "세 시예요",
    roman: "se siyeyo",
    exampleKo: "지금 세 시예요.",
    exampleEn: "It's three o'clock now.",
    exampleZh: "现在三点。",
    exampleVi: "Bây giờ là ba giờ.",
    note: "Hours use native Korean numbers (한, 두, 세…), not Sino-Korean.",
    noteZh: "“点”用韩国固有数词（한、두、세…），不用汉字数词。",
    noteVi: "Giờ dùng số đếm thuần Hàn (한, 두, 세…), không dùng số Hán-Hàn.",
  },
  {
    id: "ko-a2-time-date-003",
    level: "A2",
    deck: "time-date",
    en: "thirty minutes / half past",
    zh: "三十分",
    vi: "ba mươi phút / rưỡi",
    ko: "삼십 분",
    roman: "samsip bun",
    exampleKo: "두 시 삼십 분이에요.",
    exampleEn: "It's two thirty.",
    exampleZh: "两点三十分。",
    exampleVi: "Là hai giờ ba mươi phút.",
    note: "Minutes use Sino-Korean numbers (일, 이, 삼…) + 분 (bun).",
    noteZh: "“分”用汉字数词（일、이、삼…）加분。",
    noteVi: "Phút dùng số Hán-Hàn (일, 이, 삼…) + 분 (bun).",
  },
  {
    id: "ko-a2-time-date-004",
    level: "A2",
    deck: "time-date",
    en: "today",
    zh: "今天",
    vi: "hôm nay",
    ko: "오늘",
    roman: "oneul",
    exampleKo: "오늘 날씨가 좋아요.",
    exampleEn: "The weather is nice today.",
    exampleZh: "今天天气很好。",
    exampleVi: "Hôm nay thời tiết đẹp.",
    note: "Pairs with 어제 (yesterday) and 내일 (tomorrow).",
    noteZh: "与어제（昨天）和내일（明天）搭配使用。",
    noteVi: "Đi cùng với 어제 (hôm qua) và 내일 (ngày mai).",
  },
  {
    id: "ko-a2-time-date-005",
    level: "A2",
    deck: "time-date",
    en: "tomorrow",
    zh: "明天",
    vi: "ngày mai",
    ko: "내일",
    roman: "naeil",
    exampleKo: "내일 만나요.",
    exampleEn: "Let's meet tomorrow.",
    exampleZh: "明天见。",
    exampleVi: "Ngày mai gặp nhau nhé.",
    note: "Often used with future plans: 내일 + verb in plain form.",
    noteZh: "常用于将来的计划：내일＋动词原形。",
    noteVi: "Thường dùng với kế hoạch tương lai: 내일 + động từ nguyên thể.",
  },
  {
    id: "ko-a2-time-date-006",
    level: "A2",
    deck: "time-date",
    en: "yesterday",
    zh: "昨天",
    vi: "hôm qua",
    ko: "어제",
    roman: "eoje",
    exampleKo: "어제 친구를 만났어요.",
    exampleEn: "I met a friend yesterday.",
    exampleZh: "昨天我见了朋友。",
    exampleVi: "Hôm qua tôi đã gặp bạn.",
    note: "Triggers past tense: 만났어요 (met), 갔어요 (went).",
    noteZh: "引导过去时：만났어요（见了）、갔어요（去了）。",
    noteVi: "Kéo theo thì quá khứ: 만났어요 (đã gặp), 갔어요 (đã đi).",
  },
  {
    id: "ko-a2-time-date-007",
    level: "A2",
    deck: "time-date",
    en: "What day is it?",
    zh: "今天星期几？",
    vi: "Hôm nay là thứ mấy?",
    ko: "무슨 요일이에요?",
    roman: "museun yoirieyo?",
    exampleKo: "오늘이 무슨 요일이에요?",
    exampleEn: "What day is it today?",
    exampleZh: "今天星期几？",
    exampleVi: "Hôm nay là thứ mấy?",
    note: "요일 (yoil) = day of the week; 무슨 (museun) = which/what.",
    noteZh: "요일即星期；무슨意为“哪个/什么”。",
    noteVi: "요일 (yoil) = thứ trong tuần; 무슨 (museun) = nào/gì.",
  },
  {
    id: "ko-a2-time-date-008",
    level: "A2",
    deck: "time-date",
    en: "Monday",
    zh: "星期一",
    vi: "thứ Hai",
    ko: "월요일",
    roman: "woryoil",
    exampleKo: "월요일에 회의가 있어요.",
    exampleEn: "There's a meeting on Monday.",
    exampleZh: "星期一有会议。",
    exampleVi: "Thứ Hai có cuộc họp.",
    note: "Days end in 요일: 화(Tue), 수(Wed), 목(Thu), 금(Fri).",
    noteZh: "星期都以요일结尾：화（二）、수（三）、목（四）、금（五）。",
    noteVi: "Các thứ đều kết thúc bằng 요일: 화 (thứ Ba), 수 (thứ Tư), 목 (thứ Năm), 금 (thứ Sáu).",
  },
  {
    id: "ko-a2-time-date-009",
    level: "A2",
    deck: "time-date",
    en: "the weekend",
    zh: "周末",
    vi: "cuối tuần",
    ko: "주말",
    roman: "jumal",
    exampleKo: "주말에 뭐 해요?",
    exampleEn: "What do you do on the weekend?",
    exampleZh: "周末做什么？",
    exampleVi: "Cuối tuần bạn làm gì?",
    note: "주말 = weekend; 평일 (pyeongil) = weekday.",
    noteZh: "주말即周末；평일即工作日。",
    noteVi: "주말 = cuối tuần; 평일 (pyeongil) = ngày thường.",
  },
  {
    id: "ko-a2-time-date-010",
    level: "A2",
    deck: "time-date",
    en: "What's the date today?",
    zh: "今天几号？",
    vi: "Hôm nay là ngày mấy?",
    ko: "오늘 며칠이에요?",
    roman: "oneul myeochirieyo?",
    exampleKo: "오늘 며칠이에요? 6월 6일이에요.",
    exampleEn: "What's the date today? It's June 6th.",
    exampleZh: "今天几号？六月六号。",
    exampleVi: "Hôm nay là ngày mấy? Là ngày 6 tháng 6.",
    note: "며칠 (myeochil) asks the day-of-month; answer with Sino-Korean number + 일.",
    noteZh: "며칠用来问几号；用汉字数词加일来回答。",
    noteVi: "며칠 (myeochil) dùng để hỏi ngày trong tháng; trả lời bằng số Hán-Hàn + 일.",
  },
  {
    id: "ko-a2-time-date-011",
    level: "A2",
    deck: "time-date",
    en: "in the morning",
    zh: "在早上",
    vi: "vào buổi sáng",
    ko: "아침에",
    roman: "achime",
    exampleKo: "아침에 운동해요.",
    exampleEn: "I exercise in the morning.",
    exampleZh: "我早上运动。",
    exampleVi: "Tôi tập thể dục vào buổi sáng.",
    note: "Time words take the particle 에 (e) to mean 'at/in'.",
    noteZh: "时间词加助词에表示“在（某时）”。",
    noteVi: "Từ chỉ thời gian đi với trợ từ 에 (e) mang nghĩa 'vào lúc'.",
  },
  {
    id: "ko-a2-time-date-012",
    level: "A2",
    deck: "time-date",
    en: "in the evening",
    zh: "在晚上",
    vi: "vào buổi tối",
    ko: "저녁에",
    roman: "jeonyeoge",
    exampleKo: "저녁에 가족과 밥을 먹어요.",
    exampleEn: "In the evening I eat with my family.",
    exampleZh: "晚上我和家人一起吃饭。",
    exampleVi: "Buổi tối tôi ăn cơm cùng gia đình.",
    note: "저녁 also means 'dinner'; 점심 (jeomsim) = lunch / midday.",
    noteZh: "저녁也指“晚饭”；점심即午饭/中午。",
    noteVi: "저녁 cũng có nghĩa là 'bữa tối'; 점심 (jeomsim) = bữa trưa / buổi trưa.",
  },

  // ───────── shopping (쇼핑) ─────────
  {
    id: "ko-a2-shopping-001",
    level: "A2",
    deck: "shopping",
    en: "How much is it?",
    zh: "多少钱？",
    vi: "Bao nhiêu tiền?",
    ko: "얼마예요?",
    roman: "eolmayeyo?",
    exampleKo: "이거 얼마예요?",
    exampleEn: "How much is this?",
    exampleZh: "这个多少钱？",
    exampleVi: "Cái này bao nhiêu tiền?",
    note: "The essential shopping phrase. 이거 (igeo) = this one.",
    noteZh: "最基本的购物用语。이거即“这个”。",
    noteVi: "Câu nói thiết yếu khi mua sắm. 이거 (igeo) = cái này.",
  },
  {
    id: "ko-a2-shopping-002",
    level: "A2",
    deck: "shopping",
    en: "It's too expensive.",
    zh: "太贵了。",
    vi: "Đắt quá.",
    ko: "너무 비싸요",
    roman: "neomu bissayo",
    exampleKo: "이건 너무 비싸요.",
    exampleEn: "This is too expensive.",
    exampleZh: "这个太贵了。",
    exampleVi: "Cái này đắt quá.",
    note: "너무 (neomu) = too/very; opposite of 싸요 (cheap).",
    noteZh: "너무意为“太/很”；与싸요（便宜）相反。",
    noteVi: "너무 (neomu) = quá/rất; trái nghĩa với 싸요 (rẻ).",
  },
  {
    id: "ko-a2-shopping-003",
    level: "A2",
    deck: "shopping",
    en: "cheap / inexpensive",
    zh: "便宜",
    vi: "rẻ",
    ko: "싸요",
    roman: "ssayo",
    exampleKo: "이 가게는 과일이 싸요.",
    exampleEn: "Fruit is cheap at this store.",
    exampleZh: "这家店的水果很便宜。",
    exampleVi: "Trái cây ở cửa hàng này rẻ.",
    note: "Dictionary form is 싸다 (ssada).",
    noteZh: "原形是싸다。",
    noteVi: "Dạng nguyên thể là 싸다 (ssada).",
  },
  {
    id: "ko-a2-shopping-004",
    level: "A2",
    deck: "shopping",
    en: "Please give me this one.",
    zh: "请给我这个。",
    vi: "Cho tôi cái này.",
    ko: "이거 주세요",
    roman: "igeo juseyo",
    exampleKo: "이거 하나 주세요.",
    exampleEn: "Please give me one of these.",
    exampleZh: "请给我一个这个。",
    exampleVi: "Cho tôi một cái này.",
    note: "주세요 (juseyo) = please give; add 하나 (one) to specify quantity.",
    noteZh: "주세요意为“请给我”；加하나（一个）来说明数量。",
    noteVi: "주세요 (juseyo) = xin hãy cho; thêm 하나 (một) để chỉ số lượng.",
  },
  {
    id: "ko-a2-shopping-005",
    level: "A2",
    deck: "shopping",
    en: "Can I try it on?",
    zh: "可以试穿吗？",
    vi: "Tôi mặc thử được không?",
    ko: "입어 봐도 돼요?",
    roman: "ibeo bwado dwaeyo?",
    exampleKo: "이 옷 입어 봐도 돼요?",
    exampleEn: "Can I try on these clothes?",
    exampleZh: "这件衣服可以试穿吗？",
    exampleVi: "Tôi mặc thử bộ quần áo này được không?",
    note: "-아/어 봐도 돼요? asks permission to try doing something.",
    noteZh: "-아/어 봐도 돼요?用来请求“试着做某事”的许可。",
    noteVi: "-아/어 봐도 돼요? dùng để xin phép thử làm việc gì đó.",
  },
  {
    id: "ko-a2-shopping-006",
    level: "A2",
    deck: "shopping",
    en: "Do you have a bigger size?",
    zh: "有大一点的吗？",
    vi: "Có cái to hơn không?",
    ko: "더 큰 거 있어요?",
    roman: "deo keun geo isseoyo?",
    exampleKo: "이거 말고 더 큰 거 있어요?",
    exampleEn: "Do you have a bigger one than this?",
    exampleZh: "有没有比这个大一点的？",
    exampleVi: "Ngoài cái này ra có cái to hơn không?",
    note: "더 (deo) = more; 큰 거 = a big one; 작은 거 = a small one.",
    noteZh: "더意为“更”；큰 거即“大的”；작은 거即“小的”。",
    noteVi: "더 (deo) = hơn; 큰 거 = cái to; 작은 거 = cái nhỏ.",
  },
  {
    id: "ko-a2-shopping-007",
    level: "A2",
    deck: "shopping",
    en: "I'm just looking.",
    zh: "我只是看看。",
    vi: "Tôi chỉ xem thôi.",
    ko: "그냥 구경하는 거예요",
    roman: "geunyang gugyeonghaneun geoyeyo",
    exampleKo: "괜찮아요, 그냥 구경하는 거예요.",
    exampleEn: "It's okay, I'm just looking.",
    exampleZh: "没关系，我只是看看。",
    exampleVi: "Không sao, tôi chỉ xem thôi.",
    note: "Polite way to decline help from a shop clerk.",
    noteZh: "婉拒店员帮忙的礼貌说法。",
    noteVi: "Cách lịch sự để từ chối sự giúp đỡ của nhân viên cửa hàng.",
  },
  {
    id: "ko-a2-shopping-008",
    level: "A2",
    deck: "shopping",
    en: "Can I pay by card?",
    zh: "可以刷卡吗？",
    vi: "Tôi có thể trả bằng thẻ không?",
    ko: "카드로 계산할 수 있어요?",
    roman: "kadeuro gyesanhal su isseoyo?",
    exampleKo: "여기 카드로 계산할 수 있어요?",
    exampleEn: "Can I pay by card here?",
    exampleZh: "这里可以刷卡吗？",
    exampleVi: "Ở đây có thể trả bằng thẻ không?",
    note: "-(으)ㄹ 수 있어요? asks if something is possible. 현금 (cash) = hyeongeum.",
    noteZh: "-(으)ㄹ 수 있어요?用来问某事是否可行。현금即现金。",
    noteVi: "-(으)ㄹ 수 있어요? dùng để hỏi việc gì đó có khả thi không. 현금 (tiền mặt) = hyeongeum.",
  },
  {
    id: "ko-a2-shopping-009",
    level: "A2",
    deck: "shopping",
    en: "Please give me a discount.",
    zh: "请便宜一点。",
    vi: "Bớt cho tôi chút đi.",
    ko: "좀 깎아 주세요",
    roman: "jom kkakka juseyo",
    exampleKo: "조금 비싸요. 좀 깎아 주세요.",
    exampleEn: "It's a bit pricey. Please give me a discount.",
    exampleZh: "有点贵，请便宜一点。",
    exampleVi: "Hơi đắt. Bớt cho tôi chút đi.",
    note: "Common at markets. 깎다 (kkakkda) = to cut down (a price).",
    noteZh: "在市场常用。깎다意为“砍（价）”。",
    noteVi: "Thường dùng ở chợ. 깎다 (kkakkda) = bớt (giá).",
  },
  {
    id: "ko-a2-shopping-010",
    level: "A2",
    deck: "shopping",
    en: "I'll take this one.",
    zh: "我要这个。",
    vi: "Tôi lấy cái này.",
    ko: "이걸로 할게요",
    roman: "igeollo halgeyo",
    exampleKo: "다 봤어요. 이걸로 할게요.",
    exampleEn: "I've seen everything. I'll take this one.",
    exampleZh: "都看过了，我要这个。",
    exampleVi: "Tôi xem hết rồi. Tôi lấy cái này.",
    note: "이걸로 = with this one; -ㄹ게요 states your decision.",
    noteZh: "이걸로意为“就要这个”；-ㄹ게요表示你的决定。",
    noteVi: "이걸로 = bằng cái này; -ㄹ게요 dùng để nói quyết định của bạn.",
  },
  {
    id: "ko-a2-shopping-011",
    level: "A2",
    deck: "shopping",
    en: "Where is the fitting room?",
    zh: "试衣间在哪里？",
    vi: "Phòng thử đồ ở đâu?",
    ko: "탈의실이 어디예요?",
    roman: "taruisiri eodiyeyo?",
    exampleKo: "탈의실이 어디예요?",
    exampleEn: "Where is the fitting room?",
    exampleZh: "试衣间在哪里？",
    exampleVi: "Phòng thử đồ ở đâu?",
    note: "탈의실 = fitting room; 계산대 (gyesandae) = the checkout counter.",
    noteZh: "탈의실即试衣间；계산대即收银台。",
    noteVi: "탈의실 = phòng thử đồ; 계산대 (gyesandae) = quầy thu ngân.",
  },
  {
    id: "ko-a2-shopping-012",
    level: "A2",
    deck: "shopping",
    en: "Please give me a receipt.",
    zh: "请给我收据。",
    vi: "Cho tôi hóa đơn.",
    ko: "영수증 주세요",
    roman: "yeongsujeung juseyo",
    exampleKo: "영수증 주세요.",
    exampleEn: "Please give me a receipt.",
    exampleZh: "请给我收据。",
    exampleVi: "Cho tôi hóa đơn.",
    note: "영수증 = receipt; 봉투 (bongtu) = a bag.",
    noteZh: "영수증即收据；봉투即袋子。",
    noteVi: "영수증 = hóa đơn; 봉투 (bongtu) = túi đựng.",
  },

  // ───────── transport (교통) ─────────
  {
    id: "ko-a2-transport-001",
    level: "A2",
    deck: "transport",
    en: "Where is the subway station?",
    zh: "地铁站在哪里？",
    vi: "Ga tàu điện ngầm ở đâu?",
    ko: "지하철역이 어디예요?",
    roman: "jihacheoryeogi eodiyeyo?",
    exampleKo: "지하철역이 어디예요?",
    exampleEn: "Where is the subway station?",
    exampleZh: "地铁站在哪里？",
    exampleVi: "Ga tàu điện ngầm ở đâu?",
    note: "지하철 = subway; 역 (yeok) = station.",
    noteZh: "지하철即地铁；역即站。",
    noteVi: "지하철 = tàu điện ngầm; 역 (yeok) = ga.",
  },
  {
    id: "ko-a2-transport-002",
    level: "A2",
    deck: "transport",
    en: "Does this bus go to Seoul Station?",
    zh: "这趟公交去首尔站吗？",
    vi: "Xe buýt này có đi đến ga Seoul không?",
    ko: "이 버스 서울역에 가요?",
    roman: "i beoseu seoullyeoge gayo?",
    exampleKo: "이 버스 서울역에 가요?",
    exampleEn: "Does this bus go to Seoul Station?",
    exampleZh: "这趟公交去首尔站吗？",
    exampleVi: "Xe buýt này có đi đến ga Seoul không?",
    note: "Destination + 에 가요? asks whether it goes there.",
    noteZh: "目的地＋에 가요?用来问是否到那里。",
    noteVi: "Điểm đến + 에 가요? dùng để hỏi có đi đến đó không.",
  },
  {
    id: "ko-a2-transport-003",
    level: "A2",
    deck: "transport",
    en: "How long does it take?",
    zh: "要多长时间？",
    vi: "Mất bao lâu?",
    ko: "얼마나 걸려요?",
    roman: "eolmana geollyeoyo?",
    exampleKo: "여기서 공항까지 얼마나 걸려요?",
    exampleEn: "How long does it take from here to the airport?",
    exampleZh: "从这里到机场要多长时间？",
    exampleVi: "Từ đây đến sân bay mất bao lâu?",
    note: "걸리다 (geollida) = to take (time). 까지 (kkaji) = up to/until.",
    noteZh: "걸리다意为“花费（时间）”。까지意为“到……为止”。",
    noteVi: "걸리다 (geollida) = mất (thời gian). 까지 (kkaji) = cho đến.",
  },
  {
    id: "ko-a2-transport-004",
    level: "A2",
    deck: "transport",
    en: "Please take me to this address.",
    zh: "请带我去这个地址。",
    vi: "Cho tôi đến địa chỉ này.",
    ko: "이 주소로 가 주세요",
    roman: "i jusoro ga juseyo",
    exampleKo: "기사님, 이 주소로 가 주세요.",
    exampleEn: "Driver, please take me to this address.",
    exampleZh: "师傅，请带我去这个地址。",
    exampleVi: "Bác tài ơi, cho tôi đến địa chỉ này.",
    note: "Used in taxis. 기사님 (gisanim) = driver (polite).",
    noteZh: "打车时用。기사님是对司机的礼貌称呼。",
    noteVi: "Dùng khi đi taxi. 기사님 (gisanim) = bác tài (cách gọi lịch sự).",
  },
  {
    id: "ko-a2-transport-005",
    level: "A2",
    deck: "transport",
    en: "Please stop here.",
    zh: "请在这里停。",
    vi: "Dừng lại ở đây giúp tôi.",
    ko: "여기서 세워 주세요",
    roman: "yeogiseo sewo juseyo",
    exampleKo: "저기 신호등에서 세워 주세요.",
    exampleEn: "Please stop at the traffic light over there.",
    exampleZh: "请在那边红绿灯那儿停。",
    exampleVi: "Dừng ở chỗ đèn giao thông đằng kia giúp tôi.",
    note: "세우다 (seuda) = to stop/pull over (a vehicle).",
    noteZh: "세우다意为“把（车）停下、靠边停”。",
    noteVi: "세우다 (seuda) = dừng/tấp xe vào lề.",
  },
  {
    id: "ko-a2-transport-006",
    level: "A2",
    deck: "transport",
    en: "Where do I transfer?",
    zh: "在哪里换乘？",
    vi: "Tôi chuyển tuyến ở đâu?",
    ko: "어디에서 갈아타요?",
    roman: "eodieseo garatayo?",
    exampleKo: "2호선은 어디에서 갈아타요?",
    exampleEn: "Where do I transfer to line 2?",
    exampleZh: "2号线在哪里换乘？",
    exampleVi: "Tôi chuyển sang tuyến số 2 ở đâu?",
    note: "갈아타다 (garatada) = to transfer (trains/buses).",
    noteZh: "갈아타다意为“换乘（地铁/公交）”。",
    noteVi: "갈아타다 (garatada) = chuyển tuyến (tàu/xe buýt).",
  },
  {
    id: "ko-a2-transport-007",
    level: "A2",
    deck: "transport",
    en: "by subway",
    zh: "坐地铁",
    vi: "bằng tàu điện ngầm",
    ko: "지하철로",
    roman: "jihacheollo",
    exampleKo: "회사에 지하철로 가요.",
    exampleEn: "I go to work by subway.",
    exampleZh: "我坐地铁去公司。",
    exampleVi: "Tôi đi làm bằng tàu điện ngầm.",
    note: "(으)로 marks the means of transport: 버스로, 택시로.",
    noteZh: "(으)로表示交通方式：버스로（坐公交）、택시로（打车）。",
    noteVi: "(으)로 đánh dấu phương tiện di chuyển: 버스로 (bằng xe buýt), 택시로 (bằng taxi).",
  },
  {
    id: "ko-a2-transport-008",
    level: "A2",
    deck: "transport",
    en: "Which exit should I take?",
    zh: "从几号出口出去？",
    vi: "Ra bằng cửa số mấy?",
    ko: "몇 번 출구로 나가요?",
    roman: "myeot beon chulguro nagayo?",
    exampleKo: "백화점은 몇 번 출구로 나가요?",
    exampleEn: "Which exit do I take for the department store?",
    exampleZh: "去百货商店从几号出口出去？",
    exampleVi: "Đi đến trung tâm thương mại thì ra cửa số mấy?",
    note: "출구 = exit; numbered with Sino-Korean + 번 (beon).",
    noteZh: "출구即出口；用汉字数词加번来标号。",
    noteVi: "출구 = cửa ra; đánh số bằng số Hán-Hàn + 번 (beon).",
  },
  {
    id: "ko-a2-transport-009",
    level: "A2",
    deck: "transport",
    en: "Please go straight.",
    zh: "请一直往前走。",
    vi: "Đi thẳng.",
    ko: "쭉 가세요",
    roman: "jjuk gaseyo",
    exampleKo: "여기서 쭉 가세요.",
    exampleEn: "Go straight from here.",
    exampleZh: "从这里一直往前走。",
    exampleVi: "Từ đây đi thẳng.",
    note: "쭉 (jjuk) = straight/all the way. Often heard giving directions.",
    noteZh: "쭉意为“一直/笔直”。指路时常听到。",
    noteVi: "쭉 (jjuk) = thẳng/suốt. Thường nghe khi chỉ đường.",
  },
  {
    id: "ko-a2-transport-010",
    level: "A2",
    deck: "transport",
    en: "Please turn left.",
    zh: "请向左走。",
    vi: "Rẽ trái.",
    ko: "왼쪽으로 가세요",
    roman: "oenjjogeuro gaseyo",
    exampleKo: "저 모퉁이에서 왼쪽으로 가세요.",
    exampleEn: "Turn left at that corner.",
    exampleZh: "在那个拐角向左走。",
    exampleVi: "Rẽ trái ở góc đường đó.",
    note: "왼쪽 = left, 오른쪽 (oreunjjok) = right.",
    noteZh: "왼쪽即左；오른쪽即右。",
    noteVi: "왼쪽 = trái, 오른쪽 (oreunjjok) = phải.",
  },
  {
    id: "ko-a2-transport-011",
    level: "A2",
    deck: "transport",
    en: "Is it far from here?",
    zh: "离这里远吗？",
    vi: "Có xa đây không?",
    ko: "여기서 멀어요?",
    roman: "yeogiseo meoreoyo?",
    exampleKo: "지하철역이 여기서 멀어요?",
    exampleEn: "Is the subway station far from here?",
    exampleZh: "地铁站离这里远吗？",
    exampleVi: "Ga tàu điện ngầm có xa đây không?",
    note: "멀다 (meolda) = far; 가깝다 (gakkapda) = close/near.",
    noteZh: "멀다即远；가깝다即近。",
    noteVi: "멀다 (meolda) = xa; 가깝다 (gakkapda) = gần.",
  },
  {
    id: "ko-a2-transport-012",
    level: "A2",
    deck: "transport",
    en: "I missed the bus.",
    zh: "我没赶上公交。",
    vi: "Tôi lỡ chuyến xe buýt rồi.",
    ko: "버스를 놓쳤어요",
    roman: "beoseureul nochyeosseoyo",
    exampleKo: "늦어서 버스를 놓쳤어요.",
    exampleEn: "I was late, so I missed the bus.",
    exampleZh: "我迟到了，没赶上公交。",
    exampleVi: "Vì đến muộn nên tôi lỡ chuyến xe buýt.",
    note: "놓치다 (nochida) = to miss (a bus/train); past form 놓쳤어요.",
    noteZh: "놓치다意为“错过（公交/火车）”；过去式是놓쳤어요。",
    noteVi: "놓치다 (nochida) = lỡ (xe buýt/tàu); dạng quá khứ là 놓쳤어요.",
  },

  // ───────── weather (날씨) ─────────
  {
    id: "ko-a2-weather-001",
    level: "A2",
    deck: "weather",
    en: "How's the weather today?",
    zh: "今天天气怎么样？",
    vi: "Hôm nay thời tiết thế nào?",
    ko: "오늘 날씨 어때요?",
    roman: "oneul nalssi eottaeyo?",
    exampleKo: "오늘 날씨 어때요?",
    exampleEn: "How's the weather today?",
    exampleZh: "今天天气怎么样？",
    exampleVi: "Hôm nay thời tiết thế nào?",
    note: "어때요? (eottaeyo?) = how is it? A very common opener.",
    noteZh: "어때요?意为“怎么样？”，是很常用的开场白。",
    noteVi: "어때요? (eottaeyo?) = thế nào? Câu mở đầu rất thường dùng.",
  },
  {
    id: "ko-a2-weather-002",
    level: "A2",
    deck: "weather",
    en: "The weather is nice.",
    zh: "天气很好。",
    vi: "Thời tiết đẹp.",
    ko: "날씨가 좋아요",
    roman: "nalssiga joayo",
    exampleKo: "오늘은 날씨가 정말 좋아요.",
    exampleEn: "The weather is really nice today.",
    exampleZh: "今天天气真好。",
    exampleVi: "Hôm nay thời tiết thật sự rất đẹp.",
    note: "좋다 (jota) = good; 나쁘다 (nappeuda) = bad.",
    noteZh: "좋다即好；나쁘다即坏。",
    noteVi: "좋다 (jota) = tốt/đẹp; 나쁘다 (nappeuda) = xấu.",
  },
  {
    id: "ko-a2-weather-003",
    level: "A2",
    deck: "weather",
    en: "It's hot.",
    zh: "很热。",
    vi: "Nóng quá.",
    ko: "더워요",
    roman: "deowoyo",
    exampleKo: "여름이라서 너무 더워요.",
    exampleEn: "It's summer, so it's really hot.",
    exampleZh: "因为是夏天，太热了。",
    exampleVi: "Vì là mùa hè nên rất nóng.",
    note: "Dictionary form 덥다 (deopda); opposite 춥다 (cold).",
    noteZh: "原形是덥다；反义词춥다（冷）。",
    noteVi: "Dạng nguyên thể là 덥다 (deopda); trái nghĩa là 춥다 (lạnh).",
  },
  {
    id: "ko-a2-weather-004",
    level: "A2",
    deck: "weather",
    en: "It's cold.",
    zh: "很冷。",
    vi: "Lạnh quá.",
    ko: "추워요",
    roman: "chuwoyo",
    exampleKo: "밖이 추워요. 따뜻하게 입으세요.",
    exampleEn: "It's cold outside. Dress warmly.",
    exampleZh: "外面很冷，请穿暖和点。",
    exampleVi: "Bên ngoài lạnh lắm. Hãy mặc ấm vào.",
    note: "Dictionary form 춥다 (chupda). For things/food use 차가워요.",
    noteZh: "原形是춥다。形容物品/食物冷时用차가워요。",
    noteVi: "Dạng nguyên thể là 춥다 (chupda). Với đồ vật/thức ăn dùng 차가워요.",
  },
  {
    id: "ko-a2-weather-005",
    level: "A2",
    deck: "weather",
    en: "It's raining.",
    zh: "在下雨。",
    vi: "Trời đang mưa.",
    ko: "비가 와요",
    roman: "biga wayo",
    exampleKo: "지금 밖에 비가 와요.",
    exampleEn: "It's raining outside now.",
    exampleZh: "现在外面在下雨。",
    exampleVi: "Bây giờ bên ngoài đang mưa.",
    note: "Literally 'rain comes'. 눈이 와요 = it's snowing.",
    noteZh: "直译是“雨来了”。눈이 와요即“在下雪”。",
    noteVi: "Nghĩa đen là 'mưa đến'. 눈이 와요 = trời đang có tuyết.",
  },
  {
    id: "ko-a2-weather-006",
    level: "A2",
    deck: "weather",
    en: "It's snowing.",
    zh: "在下雪。",
    vi: "Trời đang có tuyết.",
    ko: "눈이 와요",
    roman: "nuni wayo",
    exampleKo: "겨울이라서 눈이 와요.",
    exampleEn: "It's snowing because it's winter.",
    exampleZh: "因为是冬天，在下雪。",
    exampleVi: "Vì là mùa đông nên trời có tuyết.",
    note: "눈 means both 'snow' and 'eye' — context decides.",
    noteZh: "눈既指“雪”也指“眼睛”——由上下文决定。",
    noteVi: "눈 vừa có nghĩa là 'tuyết' vừa có nghĩa là 'mắt' — tùy ngữ cảnh mà hiểu.",
  },
  {
    id: "ko-a2-weather-007",
    level: "A2",
    deck: "weather",
    en: "It's windy.",
    zh: "在刮风。",
    vi: "Trời có gió.",
    ko: "바람이 불어요",
    roman: "barami bureoyo",
    exampleKo: "오늘은 바람이 많이 불어요.",
    exampleEn: "It's very windy today.",
    exampleZh: "今天风很大。",
    exampleVi: "Hôm nay gió thổi rất mạnh.",
    note: "불다 (bulda) = to blow; 많이 (mani) = a lot.",
    noteZh: "불다意为“刮、吹”；많이意为“很多”。",
    noteVi: "불다 (bulda) = thổi; 많이 (mani) = nhiều.",
  },
  {
    id: "ko-a2-weather-008",
    level: "A2",
    deck: "weather",
    en: "It's warm.",
    zh: "很暖和。",
    vi: "Ấm áp.",
    ko: "따뜻해요",
    roman: "ttatteutaeyo",
    exampleKo: "봄이라서 날씨가 따뜻해요.",
    exampleEn: "It's warm because it's spring.",
    exampleZh: "因为是春天，天气很暖和。",
    exampleVi: "Vì là mùa xuân nên thời tiết ấm áp.",
    note: "따뜻하다 = pleasantly warm; 시원하다 = pleasantly cool.",
    noteZh: "따뜻하다指“暖和舒适”；시원하다指“凉爽舒适”。",
    noteVi: "따뜻하다 = ấm áp dễ chịu; 시원하다 = mát mẻ dễ chịu.",
  },
  {
    id: "ko-a2-weather-009",
    level: "A2",
    deck: "weather",
    en: "spring",
    zh: "春天",
    vi: "mùa xuân",
    ko: "봄",
    roman: "bom",
    exampleKo: "봄에 꽃이 많이 피어요.",
    exampleEn: "Many flowers bloom in spring.",
    exampleZh: "春天开很多花。",
    exampleVi: "Mùa xuân hoa nở rất nhiều.",
    note: "Four seasons: 봄, 여름(summer), 가을(autumn), 겨울(winter).",
    noteZh: "四季：봄、여름（夏）、가을（秋）、겨울（冬）。",
    noteVi: "Bốn mùa: 봄 (xuân), 여름 (hè), 가을 (thu), 겨울 (đông).",
  },
  {
    id: "ko-a2-weather-010",
    level: "A2",
    deck: "weather",
    en: "summer",
    zh: "夏天",
    vi: "mùa hè",
    ko: "여름",
    roman: "yeoreum",
    exampleKo: "한국의 여름은 덥고 습해요.",
    exampleEn: "Summer in Korea is hot and humid.",
    exampleZh: "韩国的夏天又热又潮湿。",
    exampleVi: "Mùa hè ở Hàn Quốc vừa nóng vừa ẩm.",
    note: "-고 (go) links two adjectives: 덥고 습해요 (hot and humid).",
    noteZh: "-고连接两个形容词：덥고 습해요（又热又潮湿）。",
    noteVi: "-고 (go) nối hai tính từ: 덥고 습해요 (nóng và ẩm).",
  },
  {
    id: "ko-a2-weather-011",
    level: "A2",
    deck: "weather",
    en: "Please bring an umbrella.",
    zh: "请带上雨伞。",
    vi: "Hãy mang theo ô.",
    ko: "우산을 가져가세요",
    roman: "usaneul gajyeogaseyo",
    exampleKo: "비가 오니까 우산을 가져가세요.",
    exampleEn: "It's raining, so please bring an umbrella.",
    exampleZh: "因为下雨，请带上雨伞。",
    exampleVi: "Vì trời mưa nên hãy mang theo ô.",
    note: "-(으)니까 gives a reason. 우산 = umbrella.",
    noteZh: "-(으)니까表示原因。우산即雨伞。",
    noteVi: "-(으)니까 dùng để nêu lý do. 우산 = cái ô.",
  },
  {
    id: "ko-a2-weather-012",
    level: "A2",
    deck: "weather",
    en: "It might rain tomorrow.",
    zh: "明天可能会下雨。",
    vi: "Có lẽ ngày mai sẽ mưa.",
    ko: "내일 비가 올 것 같아요",
    roman: "naeil biga ol geot gatayo",
    exampleKo: "구름이 많아서 내일 비가 올 것 같아요.",
    exampleEn: "It's cloudy, so it might rain tomorrow.",
    exampleZh: "云很多，明天可能会下雨。",
    exampleVi: "Vì nhiều mây nên có lẽ ngày mai sẽ mưa.",
    note: "-(으)ㄹ 것 같아요 = I think / it seems (a soft guess).",
    noteZh: "-(으)ㄹ 것 같아요意为“我觉得/好像”（委婉的推测）。",
    noteVi: "-(으)ㄹ 것 같아요 = tôi nghĩ / có vẻ như (cách đoán nhẹ nhàng).",
  },

  // ───────── hobby (취미·여가) ─────────
  {
    id: "ko-a2-hobby-001",
    level: "A2",
    deck: "hobby",
    en: "What's your hobby?",
    zh: "你的爱好是什么？",
    vi: "Sở thích của bạn là gì?",
    ko: "취미가 뭐예요?",
    roman: "chwimiga mwoyeyo?",
    exampleKo: "시간 있을 때 취미가 뭐예요?",
    exampleEn: "What's your hobby in your free time?",
    exampleZh: "有空的时候你的爱好是什么？",
    exampleVi: "Khi có thời gian rảnh, sở thích của bạn là gì?",
    note: "취미 = hobby; 뭐예요? = what is it?",
    noteZh: "취미即爱好；뭐예요?意为“是什么？”。",
    noteVi: "취미 = sở thích; 뭐예요? = là gì?",
  },
  {
    id: "ko-a2-hobby-002",
    level: "A2",
    deck: "hobby",
    en: "I like watching movies.",
    zh: "我喜欢看电影。",
    vi: "Tôi thích xem phim.",
    ko: "영화 보는 걸 좋아해요",
    roman: "yeonghwa boneun geol joahaeyo",
    exampleKo: "저는 영화 보는 걸 좋아해요.",
    exampleEn: "I like watching movies.",
    exampleZh: "我喜欢看电影。",
    exampleVi: "Tôi thích xem phim.",
    note: "Verb + -는 걸 좋아해요 = I like doing (the verb).",
    noteZh: "动词＋-는 걸 좋아해요意为“喜欢做（某事）”。",
    noteVi: "Động từ + -는 걸 좋아해요 = tôi thích làm (hành động đó).",
  },
  {
    id: "ko-a2-hobby-003",
    level: "A2",
    deck: "hobby",
    en: "I listen to music.",
    zh: "我听音乐。",
    vi: "Tôi nghe nhạc.",
    ko: "음악을 들어요",
    roman: "eumageul deureoyo",
    exampleKo: "쉴 때 음악을 들어요.",
    exampleEn: "I listen to music when I rest.",
    exampleZh: "休息的时候我听音乐。",
    exampleVi: "Khi nghỉ ngơi tôi nghe nhạc.",
    note: "듣다 (deutda) becomes 들어요 (irregular ㄷ → ㄹ).",
    noteZh: "듣다变为들어요（ㄷ不规则变ㄹ）。",
    noteVi: "듣다 (deutda) biến thành 들어요 (biến âm bất quy tắc ㄷ → ㄹ).",
  },
  {
    id: "ko-a2-hobby-004",
    level: "A2",
    deck: "hobby",
    en: "I exercise.",
    zh: "我运动。",
    vi: "Tôi tập thể dục.",
    ko: "운동해요",
    roman: "undonghaeyo",
    exampleKo: "건강을 위해서 매일 운동해요.",
    exampleEn: "I exercise every day for my health.",
    exampleZh: "为了健康，我每天运动。",
    exampleVi: "Vì sức khỏe nên tôi tập thể dục mỗi ngày.",
    note: "운동하다 = to exercise; 매일 (maeil) = every day.",
    noteZh: "운동하다即运动；매일即每天。",
    noteVi: "운동하다 = tập thể dục; 매일 (maeil) = mỗi ngày.",
  },
  {
    id: "ko-a2-hobby-005",
    level: "A2",
    deck: "hobby",
    en: "I read books.",
    zh: "我看书。",
    vi: "Tôi đọc sách.",
    ko: "책을 읽어요",
    roman: "chaegeul ilgeoyo",
    exampleKo: "주말에 카페에서 책을 읽어요.",
    exampleEn: "I read books at a cafe on weekends.",
    exampleZh: "周末我在咖啡馆看书。",
    exampleVi: "Cuối tuần tôi đọc sách ở quán cà phê.",
    note: "읽다 (ikda) = to read; 책 (chaek) = book.",
    noteZh: "읽다即读；책即书。",
    noteVi: "읽다 (ikda) = đọc; 책 (chaek) = sách.",
  },
  {
    id: "ko-a2-hobby-006",
    level: "A2",
    deck: "hobby",
    en: "I like to travel.",
    zh: "我喜欢旅行。",
    vi: "Tôi thích du lịch.",
    ko: "여행을 좋아해요",
    roman: "yeohaengeul joahaeyo",
    exampleKo: "저는 새로운 곳으로 여행하는 걸 좋아해요.",
    exampleEn: "I like traveling to new places.",
    exampleZh: "我喜欢去新的地方旅行。",
    exampleVi: "Tôi thích đi du lịch đến những nơi mới.",
    note: "여행 = travel/trip; 여행하다 = to travel.",
    noteZh: "여행即旅行；여행하다即去旅行。",
    noteVi: "여행 = chuyến du lịch; 여행하다 = đi du lịch.",
  },
  {
    id: "ko-a2-hobby-007",
    level: "A2",
    deck: "hobby",
    en: "I'm learning to cook.",
    zh: "我在学做菜。",
    vi: "Tôi đang học nấu ăn.",
    ko: "요리를 배워요",
    roman: "yorireul baewoyo",
    exampleKo: "요즘 한국 요리를 배워요.",
    exampleEn: "These days I'm learning Korean cooking.",
    exampleZh: "最近我在学韩国料理。",
    exampleVi: "Dạo này tôi đang học nấu món Hàn Quốc.",
    note: "배우다 (baeuda) = to learn; 요리 = cooking/dish.",
    noteZh: "배우다即学；요리即做菜/菜肴。",
    noteVi: "배우다 (baeuda) = học; 요리 = nấu ăn/món ăn.",
  },
  {
    id: "ko-a2-hobby-008",
    level: "A2",
    deck: "hobby",
    en: "I play games.",
    zh: "我玩游戏。",
    vi: "Tôi chơi game.",
    ko: "게임을 해요",
    roman: "geimeul haeyo",
    exampleKo: "친구들과 같이 게임을 해요.",
    exampleEn: "I play games with my friends.",
    exampleZh: "我和朋友们一起玩游戏。",
    exampleVi: "Tôi chơi game cùng với bạn bè.",
    note: "-와/과 같이 = together with. 게임하다 = to game.",
    noteZh: "-와/과 같이意为“和……一起”。게임하다即玩游戏。",
    noteVi: "-와/과 같이 = cùng với. 게임하다 = chơi game.",
  },
  {
    id: "ko-a2-hobby-009",
    level: "A2",
    deck: "hobby",
    en: "I take photos.",
    zh: "我拍照。",
    vi: "Tôi chụp ảnh.",
    ko: "사진을 찍어요",
    roman: "sajineul jjigeoyo",
    exampleKo: "여행할 때 사진을 많이 찍어요.",
    exampleEn: "I take a lot of photos when I travel.",
    exampleZh: "旅行的时候我拍很多照片。",
    exampleVi: "Khi đi du lịch tôi chụp rất nhiều ảnh.",
    note: "찍다 (jjikda) = to take (a photo); 사진 = photo.",
    noteZh: "찍다意为“拍（照）”；사진即照片。",
    noteVi: "찍다 (jjikda) = chụp (ảnh); 사진 = ảnh.",
  },
  {
    id: "ko-a2-hobby-010",
    level: "A2",
    deck: "hobby",
    en: "How often do you do it?",
    zh: "你多久做一次？",
    vi: "Bạn làm bao lâu một lần?",
    ko: "얼마나 자주 해요?",
    roman: "eolmana jaju haeyo?",
    exampleKo: "운동을 얼마나 자주 해요?",
    exampleEn: "How often do you exercise?",
    exampleZh: "你多久运动一次？",
    exampleVi: "Bạn tập thể dục bao lâu một lần?",
    note: "자주 (jaju) = often; 가끔 (gakkeum) = sometimes.",
    noteZh: "자주意为“经常”；가끔意为“偶尔”。",
    noteVi: "자주 (jaju) = thường xuyên; 가끔 (gakkeum) = thỉnh thoảng.",
  },
  {
    id: "ko-a2-hobby-011",
    level: "A2",
    deck: "hobby",
    en: "Let's do it together sometime.",
    zh: "下次一起做吧。",
    vi: "Lần sau cùng làm nhé.",
    ko: "다음에 같이 해요",
    roman: "daeume gachi haeyo",
    exampleKo: "재미있겠어요! 다음에 같이 해요.",
    exampleEn: "That sounds fun! Let's do it together sometime.",
    exampleZh: "应该很有趣！下次一起做吧。",
    exampleVi: "Nghe có vẻ thú vị! Lần sau cùng làm nhé.",
    note: "다음에 = next time/sometime; 같이 (gachi) = together.",
    noteZh: "다음에意为“下次/改天”；같이意为“一起”。",
    noteVi: "다음에 = lần sau/khi nào đó; 같이 (gachi) = cùng nhau.",
  },
  {
    id: "ko-a2-hobby-012",
    level: "A2",
    deck: "hobby",
    en: "It's fun.",
    zh: "很有趣。",
    vi: "Thú vị lắm.",
    ko: "재미있어요",
    roman: "jaemiisseoyo",
    exampleKo: "이 취미는 정말 재미있어요.",
    exampleEn: "This hobby is really fun.",
    exampleZh: "这个爱好真的很有趣。",
    exampleVi: "Sở thích này thực sự rất thú vị.",
    note: "재미있다 = fun/interesting; 재미없다 = boring.",
    noteZh: "재미있다即有趣；재미없다即无聊。",
    noteVi: "재미있다 = thú vị/hay; 재미없다 = chán.",
  },
];
