/**
 * A2 (초급) 한국어 학습 콘텐츠 — 영어권 학습자 대상.
 * 각 카드: 한국어 표현(ko) + 로마자(roman) + 영어 뜻(en) + 예문(한/영).
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * note 는 영어(학습자 모국어)로 사용 맥락을 설명한다.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_A2_DECKS: Deck[] = [
  {
    id: "time-date",
    level: "A2",
    title: { ko: "시간·날짜", en: "Time & Date" },
    description: { ko: "시간, 요일, 날짜 말하기", en: "Telling time, days, and dates" },
    order: 1,
    icon: "Clock",
  },
  {
    id: "shopping",
    level: "A2",
    title: { ko: "쇼핑", en: "Shopping" },
    description: { ko: "가게에서 사고 묻기", en: "Buying and asking in stores" },
    order: 2,
    icon: "ShoppingBag",
  },
  {
    id: "transport",
    level: "A2",
    title: { ko: "교통", en: "Transportation" },
    description: { ko: "버스, 지하철, 길 찾기", en: "Buses, subways, and getting around" },
    order: 3,
    icon: "Bus",
  },
  {
    id: "weather",
    level: "A2",
    title: { ko: "날씨", en: "Weather" },
    description: { ko: "날씨와 계절 말하기", en: "Talking about weather and seasons" },
    order: 4,
    icon: "CloudSun",
  },
  {
    id: "hobby",
    level: "A2",
    title: { ko: "취미·여가", en: "Hobbies" },
    description: { ko: "취미와 여가 활동", en: "Hobbies and free-time activities" },
    order: 5,
    icon: "Gamepad2",
  },
];

export const KO_A2_CARDS: VocabCard[] = [
  // ───────── time-date (시간·날짜) ─────────
  {
    id: "ko-a2-time-date-001",
    level: "A2",
    deck: "time-date",
    en: "What time is it now?",
    ko: "지금 몇 시예요?",
    roman: "jigeum myeot siyeyo?",
    exampleKo: "실례합니다, 지금 몇 시예요?",
    exampleEn: "Excuse me, what time is it now?",
    note: "몇 (myeot) means 'how many/what'; 시 (si) is the counter for the hour.",
  },
  {
    id: "ko-a2-time-date-002",
    level: "A2",
    deck: "time-date",
    en: "It's three o'clock.",
    ko: "세 시예요",
    roman: "se siyeyo",
    exampleKo: "지금 세 시예요.",
    exampleEn: "It's three o'clock now.",
    note: "Hours use native Korean numbers (한, 두, 세…), not Sino-Korean.",
  },
  {
    id: "ko-a2-time-date-003",
    level: "A2",
    deck: "time-date",
    en: "thirty minutes / half past",
    ko: "삼십 분",
    roman: "samsip bun",
    exampleKo: "두 시 삼십 분이에요.",
    exampleEn: "It's two thirty.",
    note: "Minutes use Sino-Korean numbers (일, 이, 삼…) + 분 (bun).",
  },
  {
    id: "ko-a2-time-date-004",
    level: "A2",
    deck: "time-date",
    en: "today",
    ko: "오늘",
    roman: "oneul",
    exampleKo: "오늘 날씨가 좋아요.",
    exampleEn: "The weather is nice today.",
    note: "Pairs with 어제 (yesterday) and 내일 (tomorrow).",
  },
  {
    id: "ko-a2-time-date-005",
    level: "A2",
    deck: "time-date",
    en: "tomorrow",
    ko: "내일",
    roman: "naeil",
    exampleKo: "내일 만나요.",
    exampleEn: "Let's meet tomorrow.",
    note: "Often used with future plans: 내일 + verb in plain form.",
  },
  {
    id: "ko-a2-time-date-006",
    level: "A2",
    deck: "time-date",
    en: "yesterday",
    ko: "어제",
    roman: "eoje",
    exampleKo: "어제 친구를 만났어요.",
    exampleEn: "I met a friend yesterday.",
    note: "Triggers past tense: 만났어요 (met), 갔어요 (went).",
  },
  {
    id: "ko-a2-time-date-007",
    level: "A2",
    deck: "time-date",
    en: "What day is it?",
    ko: "무슨 요일이에요?",
    roman: "museun yoirieyo?",
    exampleKo: "오늘이 무슨 요일이에요?",
    exampleEn: "What day is it today?",
    note: "요일 (yoil) = day of the week; 무슨 (museun) = which/what.",
  },
  {
    id: "ko-a2-time-date-008",
    level: "A2",
    deck: "time-date",
    en: "Monday",
    ko: "월요일",
    roman: "woryoil",
    exampleKo: "월요일에 회의가 있어요.",
    exampleEn: "There's a meeting on Monday.",
    note: "Days end in 요일: 화(Tue), 수(Wed), 목(Thu), 금(Fri).",
  },
  {
    id: "ko-a2-time-date-009",
    level: "A2",
    deck: "time-date",
    en: "the weekend",
    ko: "주말",
    roman: "jumal",
    exampleKo: "주말에 뭐 해요?",
    exampleEn: "What do you do on the weekend?",
    note: "주말 = weekend; 평일 (pyeongil) = weekday.",
  },
  {
    id: "ko-a2-time-date-010",
    level: "A2",
    deck: "time-date",
    en: "What's the date today?",
    ko: "오늘 며칠이에요?",
    roman: "oneul myeochirieyo?",
    exampleKo: "오늘 며칠이에요? 6월 6일이에요.",
    exampleEn: "What's the date today? It's June 6th.",
    note: "며칠 (myeochil) asks the day-of-month; answer with Sino-Korean number + 일.",
  },
  {
    id: "ko-a2-time-date-011",
    level: "A2",
    deck: "time-date",
    en: "in the morning",
    ko: "아침에",
    roman: "achime",
    exampleKo: "아침에 운동해요.",
    exampleEn: "I exercise in the morning.",
    note: "Time words take the particle 에 (e) to mean 'at/in'.",
  },
  {
    id: "ko-a2-time-date-012",
    level: "A2",
    deck: "time-date",
    en: "in the evening",
    ko: "저녁에",
    roman: "jeonyeoge",
    exampleKo: "저녁에 가족과 밥을 먹어요.",
    exampleEn: "In the evening I eat with my family.",
    note: "저녁 also means 'dinner'; 점심 (jeomsim) = lunch / midday.",
  },

  // ───────── shopping (쇼핑) ─────────
  {
    id: "ko-a2-shopping-001",
    level: "A2",
    deck: "shopping",
    en: "How much is it?",
    ko: "얼마예요?",
    roman: "eolmayeyo?",
    exampleKo: "이거 얼마예요?",
    exampleEn: "How much is this?",
    note: "The essential shopping phrase. 이거 (igeo) = this one.",
  },
  {
    id: "ko-a2-shopping-002",
    level: "A2",
    deck: "shopping",
    en: "It's too expensive.",
    ko: "너무 비싸요",
    roman: "neomu bissayo",
    exampleKo: "이건 너무 비싸요.",
    exampleEn: "This is too expensive.",
    note: "너무 (neomu) = too/very; opposite of 싸요 (cheap).",
  },
  {
    id: "ko-a2-shopping-003",
    level: "A2",
    deck: "shopping",
    en: "cheap / inexpensive",
    ko: "싸요",
    roman: "ssayo",
    exampleKo: "이 가게는 과일이 싸요.",
    exampleEn: "Fruit is cheap at this store.",
    note: "Dictionary form is 싸다 (ssada).",
  },
  {
    id: "ko-a2-shopping-004",
    level: "A2",
    deck: "shopping",
    en: "Please give me this one.",
    ko: "이거 주세요",
    roman: "igeo juseyo",
    exampleKo: "이거 하나 주세요.",
    exampleEn: "Please give me one of these.",
    note: "주세요 (juseyo) = please give; add 하나 (one) to specify quantity.",
  },
  {
    id: "ko-a2-shopping-005",
    level: "A2",
    deck: "shopping",
    en: "Can I try it on?",
    ko: "입어 봐도 돼요?",
    roman: "ibeo bwado dwaeyo?",
    exampleKo: "이 옷 입어 봐도 돼요?",
    exampleEn: "Can I try on these clothes?",
    note: "-아/어 봐도 돼요? asks permission to try doing something.",
  },
  {
    id: "ko-a2-shopping-006",
    level: "A2",
    deck: "shopping",
    en: "Do you have a bigger size?",
    ko: "더 큰 거 있어요?",
    roman: "deo keun geo isseoyo?",
    exampleKo: "이거 말고 더 큰 거 있어요?",
    exampleEn: "Do you have a bigger one than this?",
    note: "더 (deo) = more; 큰 거 = a big one; 작은 거 = a small one.",
  },
  {
    id: "ko-a2-shopping-007",
    level: "A2",
    deck: "shopping",
    en: "I'm just looking.",
    ko: "그냥 구경하는 거예요",
    roman: "geunyang gugyeonghaneun geoyeyo",
    exampleKo: "괜찮아요, 그냥 구경하는 거예요.",
    exampleEn: "It's okay, I'm just looking.",
    note: "Polite way to decline help from a shop clerk.",
  },
  {
    id: "ko-a2-shopping-008",
    level: "A2",
    deck: "shopping",
    en: "Can I pay by card?",
    ko: "카드로 계산할 수 있어요?",
    roman: "kadeuro gyesanhal su isseoyo?",
    exampleKo: "여기 카드로 계산할 수 있어요?",
    exampleEn: "Can I pay by card here?",
    note: "-(으)ㄹ 수 있어요? asks if something is possible. 현금 (cash) = hyeongeum.",
  },
  {
    id: "ko-a2-shopping-009",
    level: "A2",
    deck: "shopping",
    en: "Please give me a discount.",
    ko: "좀 깎아 주세요",
    roman: "jom kkakka juseyo",
    exampleKo: "조금 비싸요. 좀 깎아 주세요.",
    exampleEn: "It's a bit pricey. Please give me a discount.",
    note: "Common at markets. 깎다 (kkakkda) = to cut down (a price).",
  },
  {
    id: "ko-a2-shopping-010",
    level: "A2",
    deck: "shopping",
    en: "I'll take this one.",
    ko: "이걸로 할게요",
    roman: "igeollo halgeyo",
    exampleKo: "다 봤어요. 이걸로 할게요.",
    exampleEn: "I've seen everything. I'll take this one.",
    note: "이걸로 = with this one; -ㄹ게요 states your decision.",
  },
  {
    id: "ko-a2-shopping-011",
    level: "A2",
    deck: "shopping",
    en: "Where is the fitting room?",
    ko: "탈의실이 어디예요?",
    roman: "taruisiri eodiyeyo?",
    exampleKo: "탈의실이 어디예요?",
    exampleEn: "Where is the fitting room?",
    note: "탈의실 = fitting room; 계산대 (gyesandae) = the checkout counter.",
  },
  {
    id: "ko-a2-shopping-012",
    level: "A2",
    deck: "shopping",
    en: "Please give me a receipt.",
    ko: "영수증 주세요",
    roman: "yeongsujeung juseyo",
    exampleKo: "영수증 주세요.",
    exampleEn: "Please give me a receipt.",
    note: "영수증 = receipt; 봉투 (bongtu) = a bag.",
  },

  // ───────── transport (교통) ─────────
  {
    id: "ko-a2-transport-001",
    level: "A2",
    deck: "transport",
    en: "Where is the subway station?",
    ko: "지하철역이 어디예요?",
    roman: "jihacheoryeogi eodiyeyo?",
    exampleKo: "지하철역이 어디예요?",
    exampleEn: "Where is the subway station?",
    note: "지하철 = subway; 역 (yeok) = station.",
  },
  {
    id: "ko-a2-transport-002",
    level: "A2",
    deck: "transport",
    en: "Does this bus go to Seoul Station?",
    ko: "이 버스 서울역에 가요?",
    roman: "i beoseu seoullyeoge gayo?",
    exampleKo: "이 버스 서울역에 가요?",
    exampleEn: "Does this bus go to Seoul Station?",
    note: "Destination + 에 가요? asks whether it goes there.",
  },
  {
    id: "ko-a2-transport-003",
    level: "A2",
    deck: "transport",
    en: "How long does it take?",
    ko: "얼마나 걸려요?",
    roman: "eolmana geollyeoyo?",
    exampleKo: "여기서 공항까지 얼마나 걸려요?",
    exampleEn: "How long does it take from here to the airport?",
    note: "걸리다 (geollida) = to take (time). 까지 (kkaji) = up to/until.",
  },
  {
    id: "ko-a2-transport-004",
    level: "A2",
    deck: "transport",
    en: "Please take me to this address.",
    ko: "이 주소로 가 주세요",
    roman: "i jusoro ga juseyo",
    exampleKo: "기사님, 이 주소로 가 주세요.",
    exampleEn: "Driver, please take me to this address.",
    note: "Used in taxis. 기사님 (gisanim) = driver (polite).",
  },
  {
    id: "ko-a2-transport-005",
    level: "A2",
    deck: "transport",
    en: "Please stop here.",
    ko: "여기서 세워 주세요",
    roman: "yeogiseo sewo juseyo",
    exampleKo: "저기 신호등에서 세워 주세요.",
    exampleEn: "Please stop at the traffic light over there.",
    note: "세우다 (seuda) = to stop/pull over (a vehicle).",
  },
  {
    id: "ko-a2-transport-006",
    level: "A2",
    deck: "transport",
    en: "Where do I transfer?",
    ko: "어디에서 갈아타요?",
    roman: "eodieseo garatayo?",
    exampleKo: "2호선은 어디에서 갈아타요?",
    exampleEn: "Where do I transfer to line 2?",
    note: "갈아타다 (garatada) = to transfer (trains/buses).",
  },
  {
    id: "ko-a2-transport-007",
    level: "A2",
    deck: "transport",
    en: "by subway",
    ko: "지하철로",
    roman: "jihacheollo",
    exampleKo: "회사에 지하철로 가요.",
    exampleEn: "I go to work by subway.",
    note: "(으)로 marks the means of transport: 버스로, 택시로.",
  },
  {
    id: "ko-a2-transport-008",
    level: "A2",
    deck: "transport",
    en: "Which exit should I take?",
    ko: "몇 번 출구로 나가요?",
    roman: "myeot beon chulguro nagayo?",
    exampleKo: "백화점은 몇 번 출구로 나가요?",
    exampleEn: "Which exit do I take for the department store?",
    note: "출구 = exit; numbered with Sino-Korean + 번 (beon).",
  },
  {
    id: "ko-a2-transport-009",
    level: "A2",
    deck: "transport",
    en: "Please go straight.",
    ko: "쭉 가세요",
    roman: "jjuk gaseyo",
    exampleKo: "여기서 쭉 가세요.",
    exampleEn: "Go straight from here.",
    note: "쭉 (jjuk) = straight/all the way. Often heard giving directions.",
  },
  {
    id: "ko-a2-transport-010",
    level: "A2",
    deck: "transport",
    en: "Please turn left.",
    ko: "왼쪽으로 가세요",
    roman: "oenjjogeuro gaseyo",
    exampleKo: "저 모퉁이에서 왼쪽으로 가세요.",
    exampleEn: "Turn left at that corner.",
    note: "왼쪽 = left, 오른쪽 (oreunjjok) = right.",
  },
  {
    id: "ko-a2-transport-011",
    level: "A2",
    deck: "transport",
    en: "Is it far from here?",
    ko: "여기서 멀어요?",
    roman: "yeogiseo meoreoyo?",
    exampleKo: "지하철역이 여기서 멀어요?",
    exampleEn: "Is the subway station far from here?",
    note: "멀다 (meolda) = far; 가깝다 (gakkapda) = close/near.",
  },
  {
    id: "ko-a2-transport-012",
    level: "A2",
    deck: "transport",
    en: "I missed the bus.",
    ko: "버스를 놓쳤어요",
    roman: "beoseureul nochyeosseoyo",
    exampleKo: "늦어서 버스를 놓쳤어요.",
    exampleEn: "I was late, so I missed the bus.",
    note: "놓치다 (nochida) = to miss (a bus/train); past form 놓쳤어요.",
  },

  // ───────── weather (날씨) ─────────
  {
    id: "ko-a2-weather-001",
    level: "A2",
    deck: "weather",
    en: "How's the weather today?",
    ko: "오늘 날씨 어때요?",
    roman: "oneul nalssi eottaeyo?",
    exampleKo: "오늘 날씨 어때요?",
    exampleEn: "How's the weather today?",
    note: "어때요? (eottaeyo?) = how is it? A very common opener.",
  },
  {
    id: "ko-a2-weather-002",
    level: "A2",
    deck: "weather",
    en: "The weather is nice.",
    ko: "날씨가 좋아요",
    roman: "nalssiga joayo",
    exampleKo: "오늘은 날씨가 정말 좋아요.",
    exampleEn: "The weather is really nice today.",
    note: "좋다 (jota) = good; 나쁘다 (nappeuda) = bad.",
  },
  {
    id: "ko-a2-weather-003",
    level: "A2",
    deck: "weather",
    en: "It's hot.",
    ko: "더워요",
    roman: "deowoyo",
    exampleKo: "여름이라서 너무 더워요.",
    exampleEn: "It's summer, so it's really hot.",
    note: "Dictionary form 덥다 (deopda); opposite 춥다 (cold).",
  },
  {
    id: "ko-a2-weather-004",
    level: "A2",
    deck: "weather",
    en: "It's cold.",
    ko: "추워요",
    roman: "chuwoyo",
    exampleKo: "밖이 추워요. 따뜻하게 입으세요.",
    exampleEn: "It's cold outside. Dress warmly.",
    note: "Dictionary form 춥다 (chupda). For things/food use 차가워요.",
  },
  {
    id: "ko-a2-weather-005",
    level: "A2",
    deck: "weather",
    en: "It's raining.",
    ko: "비가 와요",
    roman: "biga wayo",
    exampleKo: "지금 밖에 비가 와요.",
    exampleEn: "It's raining outside now.",
    note: "Literally 'rain comes'. 눈이 와요 = it's snowing.",
  },
  {
    id: "ko-a2-weather-006",
    level: "A2",
    deck: "weather",
    en: "It's snowing.",
    ko: "눈이 와요",
    roman: "nuni wayo",
    exampleKo: "겨울이라서 눈이 와요.",
    exampleEn: "It's snowing because it's winter.",
    note: "눈 means both 'snow' and 'eye' — context decides.",
  },
  {
    id: "ko-a2-weather-007",
    level: "A2",
    deck: "weather",
    en: "It's windy.",
    ko: "바람이 불어요",
    roman: "barami bureoyo",
    exampleKo: "오늘은 바람이 많이 불어요.",
    exampleEn: "It's very windy today.",
    note: "불다 (bulda) = to blow; 많이 (mani) = a lot.",
  },
  {
    id: "ko-a2-weather-008",
    level: "A2",
    deck: "weather",
    en: "It's warm.",
    ko: "따뜻해요",
    roman: "ttatteutaeyo",
    exampleKo: "봄이라서 날씨가 따뜻해요.",
    exampleEn: "It's warm because it's spring.",
    note: "따뜻하다 = pleasantly warm; 시원하다 = pleasantly cool.",
  },
  {
    id: "ko-a2-weather-009",
    level: "A2",
    deck: "weather",
    en: "spring",
    ko: "봄",
    roman: "bom",
    exampleKo: "봄에 꽃이 많이 피어요.",
    exampleEn: "Many flowers bloom in spring.",
    note: "Four seasons: 봄, 여름(summer), 가을(autumn), 겨울(winter).",
  },
  {
    id: "ko-a2-weather-010",
    level: "A2",
    deck: "weather",
    en: "summer",
    ko: "여름",
    roman: "yeoreum",
    exampleKo: "한국의 여름은 덥고 습해요.",
    exampleEn: "Summer in Korea is hot and humid.",
    note: "-고 (go) links two adjectives: 덥고 습해요 (hot and humid).",
  },
  {
    id: "ko-a2-weather-011",
    level: "A2",
    deck: "weather",
    en: "Please bring an umbrella.",
    ko: "우산을 가져가세요",
    roman: "usaneul gajyeogaseyo",
    exampleKo: "비가 오니까 우산을 가져가세요.",
    exampleEn: "It's raining, so please bring an umbrella.",
    note: "-(으)니까 gives a reason. 우산 = umbrella.",
  },
  {
    id: "ko-a2-weather-012",
    level: "A2",
    deck: "weather",
    en: "It might rain tomorrow.",
    ko: "내일 비가 올 것 같아요",
    roman: "naeil biga ol geot gatayo",
    exampleKo: "구름이 많아서 내일 비가 올 것 같아요.",
    exampleEn: "It's cloudy, so it might rain tomorrow.",
    note: "-(으)ㄹ 것 같아요 = I think / it seems (a soft guess).",
  },

  // ───────── hobby (취미·여가) ─────────
  {
    id: "ko-a2-hobby-001",
    level: "A2",
    deck: "hobby",
    en: "What's your hobby?",
    ko: "취미가 뭐예요?",
    roman: "chwimiga mwoyeyo?",
    exampleKo: "시간 있을 때 취미가 뭐예요?",
    exampleEn: "What's your hobby in your free time?",
    note: "취미 = hobby; 뭐예요? = what is it?",
  },
  {
    id: "ko-a2-hobby-002",
    level: "A2",
    deck: "hobby",
    en: "I like watching movies.",
    ko: "영화 보는 걸 좋아해요",
    roman: "yeonghwa boneun geol joahaeyo",
    exampleKo: "저는 영화 보는 걸 좋아해요.",
    exampleEn: "I like watching movies.",
    note: "Verb + -는 걸 좋아해요 = I like doing (the verb).",
  },
  {
    id: "ko-a2-hobby-003",
    level: "A2",
    deck: "hobby",
    en: "I listen to music.",
    ko: "음악을 들어요",
    roman: "eumageul deureoyo",
    exampleKo: "쉴 때 음악을 들어요.",
    exampleEn: "I listen to music when I rest.",
    note: "듣다 (deutda) becomes 들어요 (irregular ㄷ → ㄹ).",
  },
  {
    id: "ko-a2-hobby-004",
    level: "A2",
    deck: "hobby",
    en: "I exercise.",
    ko: "운동해요",
    roman: "undonghaeyo",
    exampleKo: "건강을 위해서 매일 운동해요.",
    exampleEn: "I exercise every day for my health.",
    note: "운동하다 = to exercise; 매일 (maeil) = every day.",
  },
  {
    id: "ko-a2-hobby-005",
    level: "A2",
    deck: "hobby",
    en: "I read books.",
    ko: "책을 읽어요",
    roman: "chaegeul ilgeoyo",
    exampleKo: "주말에 카페에서 책을 읽어요.",
    exampleEn: "I read books at a cafe on weekends.",
    note: "읽다 (ikda) = to read; 책 (chaek) = book.",
  },
  {
    id: "ko-a2-hobby-006",
    level: "A2",
    deck: "hobby",
    en: "I like to travel.",
    ko: "여행을 좋아해요",
    roman: "yeohaengeul joahaeyo",
    exampleKo: "저는 새로운 곳으로 여행하는 걸 좋아해요.",
    exampleEn: "I like traveling to new places.",
    note: "여행 = travel/trip; 여행하다 = to travel.",
  },
  {
    id: "ko-a2-hobby-007",
    level: "A2",
    deck: "hobby",
    en: "I'm learning to cook.",
    ko: "요리를 배워요",
    roman: "yorireul baewoyo",
    exampleKo: "요즘 한국 요리를 배워요.",
    exampleEn: "These days I'm learning Korean cooking.",
    note: "배우다 (baeuda) = to learn; 요리 = cooking/dish.",
  },
  {
    id: "ko-a2-hobby-008",
    level: "A2",
    deck: "hobby",
    en: "I play games.",
    ko: "게임을 해요",
    roman: "geimeul haeyo",
    exampleKo: "친구들과 같이 게임을 해요.",
    exampleEn: "I play games with my friends.",
    note: "-와/과 같이 = together with. 게임하다 = to game.",
  },
  {
    id: "ko-a2-hobby-009",
    level: "A2",
    deck: "hobby",
    en: "I take photos.",
    ko: "사진을 찍어요",
    roman: "sajineul jjigeoyo",
    exampleKo: "여행할 때 사진을 많이 찍어요.",
    exampleEn: "I take a lot of photos when I travel.",
    note: "찍다 (jjikda) = to take (a photo); 사진 = photo.",
  },
  {
    id: "ko-a2-hobby-010",
    level: "A2",
    deck: "hobby",
    en: "How often do you do it?",
    ko: "얼마나 자주 해요?",
    roman: "eolmana jaju haeyo?",
    exampleKo: "운동을 얼마나 자주 해요?",
    exampleEn: "How often do you exercise?",
    note: "자주 (jaju) = often; 가끔 (gakkeum) = sometimes.",
  },
  {
    id: "ko-a2-hobby-011",
    level: "A2",
    deck: "hobby",
    en: "Let's do it together sometime.",
    ko: "다음에 같이 해요",
    roman: "daeume gachi haeyo",
    exampleKo: "재미있겠어요! 다음에 같이 해요.",
    exampleEn: "That sounds fun! Let's do it together sometime.",
    note: "다음에 = next time/sometime; 같이 (gachi) = together.",
  },
  {
    id: "ko-a2-hobby-012",
    level: "A2",
    deck: "hobby",
    en: "It's fun.",
    ko: "재미있어요",
    roman: "jaemiisseoyo",
    exampleKo: "이 취미는 정말 재미있어요.",
    exampleEn: "This hobby is really fun.",
    note: "재미있다 = fun/interesting; 재미없다 = boring.",
  },
];
