/**
 * B1 (중급) 한국어 학습 콘텐츠 — 영어권 학습자 대상.
 * 각 카드: 한국어 표현(ko) + 로마자(roman) + 영어 뜻(en) + 예문(한/영).
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * note 는 영어(학습자 모국어)로 사용 맥락을 설명한다.
 *
 * B1: 기본 대화를 더 자연스럽게 — 이유·의견·연결 표현, 다양한 동사 활용.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_B1_DECKS: Deck[] = [
  {
    id: "work",
    level: "B1",
    title: { ko: "직장·업무", en: "Work" },
    description: {
      ko: "회의·보고·협업 표현",
      en: "Meetings, reports, and teamwork",
    },
    order: 1,
    icon: "Briefcase",
  },
  {
    id: "health",
    level: "B1",
    title: { ko: "건강·병원", en: "Health" },
    description: {
      ko: "증상 설명·진료·약국",
      en: "Symptoms, doctors, and pharmacies",
    },
    order: 2,
    icon: "Stethoscope",
  },
  {
    id: "travel",
    level: "B1",
    title: { ko: "여행", en: "Travel" },
    description: {
      ko: "예약·길찾기·문제 해결",
      en: "Booking, directions, and problem-solving",
    },
    order: 3,
    icon: "Plane",
  },
  {
    id: "feelings",
    level: "B1",
    title: { ko: "감정·기분", en: "Feelings" },
    description: {
      ko: "기분·감정·공감 표현",
      en: "Moods, emotions, and empathy",
    },
    order: 4,
    icon: "Smile",
  },
  {
    id: "appointment",
    level: "B1",
    title: { ko: "약속·일정", en: "Plans & Appointments" },
    description: {
      ko: "약속 잡기·변경·확인",
      en: "Making, changing, and confirming plans",
    },
    order: 5,
    icon: "CalendarClock",
  },
];

export const KO_B1_CARDS: VocabCard[] = [
  // ─────────────────────────────── work ───────────────────────────────
  {
    id: "ko-b1-work-001",
    level: "B1",
    deck: "work",
    en: "to be in a meeting",
    ko: "회의 중이다",
    roman: "hoeui jungida",
    exampleKo: "지금 회의 중이라서 나중에 전화드릴게요.",
    exampleEn: "I'm in a meeting right now, so I'll call you later.",
    note: "Use the '-중이다' pattern to say you're in the middle of something.",
  },
  {
    id: "ko-b1-work-002",
    level: "B1",
    deck: "work",
    en: "to submit a report",
    ko: "보고서를 제출하다",
    roman: "bogoseoreul jechulhada",
    exampleKo: "내일까지 보고서를 제출해야 해요.",
    exampleEn: "I have to submit the report by tomorrow.",
    note: "제출하다 (to submit) is more formal than 내다 in the workplace.",
  },
  {
    id: "ko-b1-work-003",
    level: "B1",
    deck: "work",
    en: "to work overtime",
    ko: "야근하다",
    roman: "yageunhada",
    exampleKo: "이번 주에는 매일 야근했어요.",
    exampleEn: "I worked overtime every day this week.",
    note: "야근 literally means 'night work' — common in Korean office life.",
  },
  {
    id: "ko-b1-work-004",
    level: "B1",
    deck: "work",
    en: "to meet a deadline",
    ko: "마감을 맞추다",
    roman: "magameul matchuda",
    exampleKo: "마감을 맞추려고 주말에도 일했어요.",
    exampleEn: "I worked on the weekend too in order to meet the deadline.",
    note: "맞추다 here means 'to make something fit/align' with the deadline.",
  },
  {
    id: "ko-b1-work-005",
    level: "B1",
    deck: "work",
    en: "to take a day off",
    ko: "휴가를 내다",
    roman: "hyugareul naeda",
    exampleKo: "다음 주에 하루 휴가를 내려고 해요.",
    exampleEn: "I'm planning to take a day off next week.",
    note: "휴가를 내다 = to put in for leave. 연차 specifically means annual leave.",
  },
  {
    id: "ko-b1-work-006",
    level: "B1",
    deck: "work",
    en: "to be in charge of",
    ko: "담당하다",
    roman: "damdanghada",
    exampleKo: "제가 이 프로젝트를 담당하고 있어요.",
    exampleEn: "I'm in charge of this project.",
    note: "담당자 means 'the person in charge / point of contact'.",
  },
  {
    id: "ko-b1-work-007",
    level: "B1",
    deck: "work",
    en: "to discuss / talk over",
    ko: "의논하다",
    roman: "uinonhada",
    exampleKo: "그 문제는 팀장님과 의논해 볼게요.",
    exampleEn: "I'll discuss that issue with the team leader.",
    note: "의논하다 implies seeking advice; 상의하다 is a close synonym.",
  },
  {
    id: "ko-b1-work-008",
    level: "B1",
    deck: "work",
    en: "in my opinion",
    ko: "제 생각에는",
    roman: "je saenggageneun",
    exampleKo: "제 생각에는 이 방법이 더 좋을 것 같아요.",
    exampleEn: "In my opinion, this method seems better.",
    note: "A polite way to open an opinion. 제 = humble 'my'.",
  },
  {
    id: "ko-b1-work-009",
    level: "B1",
    deck: "work",
    en: "to be busy with work",
    ko: "일이 바쁘다",
    roman: "iri bappeuda",
    exampleKo: "요즘 일이 너무 바빠서 정신이 없어요.",
    exampleEn: "I'm so busy with work these days that I'm overwhelmed.",
    note: "정신이 없다 ('to have no mind') idiomatically means 'to be hectic'.",
  },
  {
    id: "ko-b1-work-010",
    level: "B1",
    deck: "work",
    en: "to send an email",
    ko: "이메일을 보내다",
    roman: "imeireul bonaeda",
    exampleKo: "자세한 내용은 이메일로 보내 드릴게요.",
    exampleEn: "I'll send you the details by email.",
    note: "메일 보내다 is the common short form in spoken Korean.",
  },
  {
    id: "ko-b1-work-011",
    level: "B1",
    deck: "work",
    en: "to ask a favor",
    ko: "부탁을 드리다",
    roman: "butageul deurida",
    exampleKo: "바쁘시겠지만 부탁 좀 드려도 될까요?",
    exampleEn: "I know you're busy, but may I ask you a favor?",
    note: "드리다 is the humble form of 주다, used when asking up the hierarchy.",
  },
  {
    id: "ko-b1-work-012",
    level: "B1",
    deck: "work",
    en: "good work / well done (to coworkers)",
    ko: "수고하셨습니다",
    roman: "sugohasyeotseumnida",
    exampleKo: "오늘 다들 수고하셨습니다.",
    exampleEn: "Everyone did a great job today.",
    note: "Said at the end of work to acknowledge others' effort. Very common.",
  },

  // ────────────────────────────── health ──────────────────────────────
  {
    id: "ko-b1-health-001",
    level: "B1",
    deck: "health",
    en: "I have a cold",
    ko: "감기에 걸리다",
    roman: "gamgie geollida",
    exampleKo: "어제부터 감기에 걸려서 목이 아파요.",
    exampleEn: "I caught a cold yesterday, so my throat hurts.",
    note: "Use the particle 에 + 걸리다 ('to be caught by') for illnesses.",
  },
  {
    id: "ko-b1-health-002",
    level: "B1",
    deck: "health",
    en: "to have a fever",
    ko: "열이 나다",
    roman: "yeori nada",
    exampleKo: "아이가 열이 나서 병원에 갔어요.",
    exampleEn: "My child had a fever, so we went to the hospital.",
    note: "나다 ('to come out') pairs with many symptoms: 열, 기침, 콧물.",
  },
  {
    id: "ko-b1-health-003",
    level: "B1",
    deck: "health",
    en: "my whole body aches",
    ko: "온몸이 아프다",
    roman: "onmomi apeuda",
    exampleKo: "몸살이 났는지 온몸이 아파요.",
    exampleEn: "My whole body aches — I think I'm coming down with something.",
    note: "몸살 is the body aches/fatigue of a cold; 몸살이 나다 = to get run down.",
  },
  {
    id: "ko-b1-health-004",
    level: "B1",
    deck: "health",
    en: "to see a doctor",
    ko: "진료를 받다",
    roman: "jillyoreul batda",
    exampleKo: "증상이 심해서 진료를 받으러 왔어요.",
    exampleEn: "My symptoms got worse, so I came to see a doctor.",
    note: "진료 = medical examination. 진찰을 받다 is a close synonym.",
  },
  {
    id: "ko-b1-health-005",
    level: "B1",
    deck: "health",
    en: "to prescribe medicine",
    ko: "약을 처방하다",
    roman: "yageul cheobanghada",
    exampleKo: "의사 선생님이 약을 처방해 주셨어요.",
    exampleEn: "The doctor prescribed me some medicine.",
    note: "From the patient's side, you 약을 처방받다 (get a prescription).",
  },
  {
    id: "ko-b1-health-006",
    level: "B1",
    deck: "health",
    en: "to take medicine",
    ko: "약을 먹다",
    roman: "yageul meokda",
    exampleKo: "하루에 세 번 식후에 약을 드세요.",
    exampleEn: "Take the medicine three times a day after meals.",
    note: "Korean uses 먹다 ('to eat') for taking medicine, not 마시다.",
  },
  {
    id: "ko-b1-health-007",
    level: "B1",
    deck: "health",
    en: "to get some rest",
    ko: "푹 쉬다",
    roman: "puk swida",
    exampleKo: "무리하지 말고 푹 쉬세요.",
    exampleEn: "Don't overdo it and get plenty of rest.",
    note: "푹 is an adverb meaning 'thoroughly/deeply' — 푹 쉬다, 푹 자다.",
  },
  {
    id: "ko-b1-health-008",
    level: "B1",
    deck: "health",
    en: "to get better / recover",
    ko: "낫다",
    roman: "natda",
    exampleKo: "약을 먹으니까 좀 나았어요.",
    exampleEn: "I feel a bit better after taking the medicine.",
    note: "Irregular ㅅ verb: 낫다 → 나아요, 나았어요. Also means 'to be better'.",
  },
  {
    id: "ko-b1-health-009",
    level: "B1",
    deck: "health",
    en: "to be careful / take care",
    ko: "조심하다",
    roman: "josimhada",
    exampleKo: "감기 걸리지 않게 조심하세요.",
    exampleEn: "Be careful not to catch a cold.",
    note: "감기 조심하세요 is a common caring farewell in cold weather.",
  },
  {
    id: "ko-b1-health-010",
    level: "B1",
    deck: "health",
    en: "Where does it hurt?",
    ko: "어디가 아프세요?",
    roman: "eodiga apeuseyo?",
    exampleKo: "어디가 아프세요? 증상을 말씀해 주세요.",
    exampleEn: "Where does it hurt? Please describe your symptoms.",
    note: "What a doctor or pharmacist asks first. 아프세요 is the polite form.",
  },
  {
    id: "ko-b1-health-011",
    level: "B1",
    deck: "health",
    en: "to make a reservation (appointment)",
    ko: "예약하다",
    roman: "yeyakhada",
    exampleKo: "병원에 미리 예약하고 가는 게 좋아요.",
    exampleEn: "It's better to make an appointment before going to the hospital.",
    note: "Used for clinics, restaurants, hotels — anything booked in advance.",
  },

  // ────────────────────────────── travel ──────────────────────────────
  {
    id: "ko-b1-travel-001",
    level: "B1",
    deck: "travel",
    en: "to book a flight ticket",
    ko: "비행기 표를 예매하다",
    roman: "bihaenggi pyoreul yemaehada",
    exampleKo: "다음 달 비행기 표를 벌써 예매했어요.",
    exampleEn: "I already booked the flight ticket for next month.",
    note: "예매하다 = to book tickets in advance (transport, movies, shows).",
  },
  {
    id: "ko-b1-travel-002",
    level: "B1",
    deck: "travel",
    en: "to check in (hotel)",
    ko: "체크인하다",
    roman: "chekeuinhada",
    exampleKo: "보통 체크인은 오후 세 시부터예요.",
    exampleEn: "Check-in usually starts at 3 p.m.",
    note: "Loanword from English. Checkout is 체크아웃하다.",
  },
  {
    id: "ko-b1-travel-003",
    level: "B1",
    deck: "travel",
    en: "How do I get to...?",
    ko: "어떻게 가요?",
    roman: "eotteoke gayo?",
    exampleKo: "여기에서 시청까지 어떻게 가요?",
    exampleEn: "How do I get from here to City Hall?",
    note: "Put the destination before 까지 (to/until): 시청까지 어떻게 가요?",
  },
  {
    id: "ko-b1-travel-004",
    level: "B1",
    deck: "travel",
    en: "to transfer (trains/buses)",
    ko: "갈아타다",
    roman: "garatada",
    exampleKo: "여기에서 2호선으로 갈아타세요.",
    exampleEn: "Transfer to Line 2 here.",
    note: "환승하다 is the more formal/written equivalent.",
  },
  {
    id: "ko-b1-travel-005",
    level: "B1",
    deck: "travel",
    en: "to get lost / lose one's way",
    ko: "길을 잃다",
    roman: "gireul ilta",
    exampleKo: "지도를 봤는데도 길을 잃었어요.",
    exampleEn: "Even though I looked at the map, I got lost.",
    note: "-는데도 means 'even though' — useful for contrasting results.",
  },
  {
    id: "ko-b1-travel-006",
    level: "B1",
    deck: "travel",
    en: "Could you recommend...?",
    ko: "추천해 주시겠어요?",
    roman: "chucheonhae jusigesseoyo?",
    exampleKo: "이 근처에 맛있는 식당 좀 추천해 주시겠어요?",
    exampleEn: "Could you recommend a good restaurant nearby?",
    note: "-아/어 주시겠어요? is a very polite request pattern.",
  },
  {
    id: "ko-b1-travel-007",
    level: "B1",
    deck: "travel",
    en: "to take a picture",
    ko: "사진을 찍다",
    roman: "sajineul jjikda",
    exampleKo: "실례지만 사진 좀 찍어 주실 수 있어요?",
    exampleEn: "Excuse me, could you take a picture for us?",
    note: "찍어 주다 = take a photo for someone else's benefit.",
  },
  {
    id: "ko-b1-travel-008",
    level: "B1",
    deck: "travel",
    en: "It's worth seeing / a must-see",
    ko: "볼 만하다",
    roman: "bol manhada",
    exampleKo: "경복궁은 한번 볼 만해요.",
    exampleEn: "Gyeongbokgung Palace is worth seeing.",
    note: "-(으)ㄹ 만하다 means 'worth doing'. 갈 만하다, 먹을 만하다 too.",
  },
  {
    id: "ko-b1-travel-009",
    level: "B1",
    deck: "travel",
    en: "to exchange money",
    ko: "환전하다",
    roman: "hwanjeonhada",
    exampleKo: "공항에서 환전하면 수수료가 비싸요.",
    exampleEn: "If you exchange money at the airport, the fee is high.",
    note: "수수료 = service/handling fee, useful for banking and travel.",
  },
  {
    id: "ko-b1-travel-010",
    level: "B1",
    deck: "travel",
    en: "How much is the fare?",
    ko: "요금이 얼마예요?",
    roman: "yogeumi eolmayeyo?",
    exampleKo: "택시 요금이 얼마예요?",
    exampleEn: "How much is the taxi fare?",
    note: "요금 = fare/charge (transport, utilities); 값/가격 = price of goods.",
  },
  {
    id: "ko-b1-travel-011",
    level: "B1",
    deck: "travel",
    en: "to cancel a reservation",
    ko: "예약을 취소하다",
    roman: "yeyageul chwisohada",
    exampleKo: "일정이 바뀌어서 예약을 취소해야 해요.",
    exampleEn: "My schedule changed, so I have to cancel the reservation.",
    note: "취소하다 = to cancel; 변경하다 = to change/modify.",
  },
  {
    id: "ko-b1-travel-012",
    level: "B1",
    deck: "travel",
    en: "Have a safe trip",
    ko: "잘 다녀오세요",
    roman: "jal danyeooseyo",
    exampleKo: "여행 잘 다녀오세요!",
    exampleEn: "Have a safe trip!",
    note: "Said to someone leaving and coming back. They reply 다녀오겠습니다.",
  },

  // ───────────────────────────── feelings ─────────────────────────────
  {
    id: "ko-b1-feelings-001",
    level: "B1",
    deck: "feelings",
    en: "to be in a good mood",
    ko: "기분이 좋다",
    roman: "gibuni jota",
    exampleKo: "오늘은 날씨가 좋아서 기분이 좋아요.",
    exampleEn: "The weather is nice today, so I'm in a good mood.",
    note: "기분 = mood/feeling at the moment; 감정 = emotion in general.",
  },
  {
    id: "ko-b1-feelings-002",
    level: "B1",
    deck: "feelings",
    en: "to be upset / in a bad mood",
    ko: "기분이 나쁘다",
    roman: "gibuni nappeuda",
    exampleKo: "그 말을 듣고 기분이 나빴어요.",
    exampleEn: "I felt bad after hearing that.",
    note: "기분이 상하다 ('mood gets hurt') is a softer way to say offended.",
  },
  {
    id: "ko-b1-feelings-003",
    level: "B1",
    deck: "feelings",
    en: "to be worried",
    ko: "걱정되다",
    roman: "geokjeongdoeda",
    exampleKo: "시험 결과가 걱정돼요.",
    exampleEn: "I'm worried about the test results.",
    note: "걱정되다 = to feel worried; 걱정하다 = to worry (active). 걱정하지 마세요 = don't worry.",
  },
  {
    id: "ko-b1-feelings-004",
    level: "B1",
    deck: "feelings",
    en: "to be excited / look forward to",
    ko: "기대되다",
    roman: "gidaedoeda",
    exampleKo: "내일 여행이 정말 기대돼요.",
    exampleEn: "I'm really looking forward to the trip tomorrow.",
    note: "기대 = expectation/anticipation. 기대돼요 = I can't wait.",
  },
  {
    id: "ko-b1-feelings-005",
    level: "B1",
    deck: "feelings",
    en: "to be disappointed",
    ko: "실망하다",
    roman: "silmanghada",
    exampleKo: "기대를 많이 해서 그런지 좀 실망했어요.",
    exampleEn: "Maybe because I expected a lot, I was a bit disappointed.",
    note: "-아/어서 그런지 = 'maybe because...' — softens a guess about a reason.",
  },
  {
    id: "ko-b1-feelings-006",
    level: "B1",
    deck: "feelings",
    en: "to be nervous",
    ko: "긴장되다",
    roman: "ginjangdoeda",
    exampleKo: "면접 때문에 너무 긴장돼요.",
    exampleEn: "I'm so nervous because of the interview.",
    note: "긴장 = tension/nerves. 긴장을 풀다 = to relax/release the tension.",
  },
  {
    id: "ko-b1-feelings-007",
    level: "B1",
    deck: "feelings",
    en: "to feel relieved",
    ko: "마음이 놓이다",
    roman: "maeumi noida",
    exampleKo: "네가 무사하다니 마음이 놓이네.",
    exampleEn: "I'm relieved to hear that you're safe.",
    note: "Literally 'the heart is set down'. 다행이다 also means 'what a relief'.",
  },
  {
    id: "ko-b1-feelings-008",
    level: "B1",
    deck: "feelings",
    en: "I understand how you feel",
    ko: "그 마음 이해해요",
    roman: "geu maeum ihaehaeyo",
    exampleKo: "힘들겠지만 그 마음 이해해요.",
    exampleEn: "It must be hard, but I understand how you feel.",
    note: "A warm empathy phrase. 공감하다 = to empathize/relate.",
  },
  {
    id: "ko-b1-feelings-009",
    level: "B1",
    deck: "feelings",
    en: "Cheer up / Stay strong",
    ko: "힘내세요",
    roman: "himnaeseyo",
    exampleKo: "너무 속상해하지 말고 힘내세요.",
    exampleEn: "Don't be too upset — stay strong.",
    note: "Literally 'put out strength'. The go-to phrase to encourage someone.",
  },
  {
    id: "ko-b1-feelings-010",
    level: "B1",
    deck: "feelings",
    en: "to be touched / moved",
    ko: "감동받다",
    roman: "gamdongbatda",
    exampleKo: "편지를 읽고 정말 감동받았어요.",
    exampleEn: "I was really moved after reading the letter.",
    note: "감동 = deep emotional impact. 감동적이다 = to be touching/moving.",
  },
  {
    id: "ko-b1-feelings-011",
    level: "B1",
    deck: "feelings",
    en: "to be annoyed / fed up",
    ko: "짜증이 나다",
    roman: "jjajeungi nada",
    exampleKo: "일이 자꾸 안 풀려서 짜증이 나요.",
    exampleEn: "Things keep not working out, so I'm getting annoyed.",
    note: "짜증 is everyday irritation. Casual: 짜증 나 ('ugh, so annoying').",
  },

  // ──────────────────────────── appointment ───────────────────────────
  {
    id: "ko-b1-appointment-001",
    level: "B1",
    deck: "appointment",
    en: "to make plans / set a date",
    ko: "약속을 잡다",
    roman: "yaksogeul japda",
    exampleKo: "이번 주말에 친구랑 약속을 잡았어요.",
    exampleEn: "I made plans with a friend for this weekend.",
    note: "약속 = a promise or an appointment. 약속을 잡다 = to set up a meeting.",
  },
  {
    id: "ko-b1-appointment-002",
    level: "B1",
    deck: "appointment",
    en: "Are you free / available?",
    ko: "시간 괜찮으세요?",
    roman: "sigan gwaenchaneuseyo?",
    exampleKo: "내일 오후에 시간 괜찮으세요?",
    exampleEn: "Are you free tomorrow afternoon?",
    note: "Polite way to ask availability. 시간 있으세요? is a bit more direct.",
  },
  {
    id: "ko-b1-appointment-003",
    level: "B1",
    deck: "appointment",
    en: "to be late / run late",
    ko: "늦다",
    roman: "neutda",
    exampleKo: "길이 막혀서 조금 늦을 것 같아요.",
    exampleEn: "The traffic is bad, so I think I'll be a little late.",
    note: "-(으)ㄹ 것 같아요 = 'I think it'll...' — softens predictions politely.",
  },
  {
    id: "ko-b1-appointment-004",
    level: "B1",
    deck: "appointment",
    en: "to reschedule / change plans",
    ko: "약속을 미루다",
    roman: "yaksogeul miruda",
    exampleKo: "갑자기 일이 생겨서 약속을 미뤄도 될까요?",
    exampleEn: "Something came up — could we push the appointment back?",
    note: "미루다 = to postpone/put off. 앞당기다 = to move up (earlier).",
  },
  {
    id: "ko-b1-appointment-005",
    level: "B1",
    deck: "appointment",
    en: "Something came up",
    ko: "일이 생기다",
    roman: "iri saenggida",
    exampleKo: "급한 일이 생겨서 못 갈 것 같아요.",
    exampleEn: "Something urgent came up, so I don't think I can go.",
    note: "생기다 = to come about/arise. 급한 일 = an urgent matter.",
  },
  {
    id: "ko-b1-appointment-006",
    level: "B1",
    deck: "appointment",
    en: "to confirm / check (a plan)",
    ko: "확인하다",
    roman: "hwaginhada",
    exampleKo: "약속 시간을 다시 한번 확인하고 싶어요.",
    exampleEn: "I'd like to confirm the appointment time once more.",
    note: "확인하다 = to confirm/verify. 다시 한번 = once more, one more time.",
  },
  {
    id: "ko-b1-appointment-007",
    level: "B1",
    deck: "appointment",
    en: "Let's meet at...",
    ko: "에서 만나요",
    roman: "eseo mannayo",
    exampleKo: "그럼 강남역에서 만나요.",
    exampleEn: "Then let's meet at Gangnam Station.",
    note: "Place + 에서 marks where an action happens. 만나다 takes 에서, not 에.",
  },
  {
    id: "ko-b1-appointment-008",
    level: "B1",
    deck: "appointment",
    en: "to be on time / make it in time",
    ko: "시간을 지키다",
    roman: "siganeul jikida",
    exampleKo: "약속 시간을 잘 지키는 사람이 좋아요.",
    exampleEn: "I like people who are punctual.",
    note: "지키다 = to keep/protect; 약속을 지키다 = to keep a promise.",
  },
  {
    id: "ko-b1-appointment-009",
    level: "B1",
    deck: "appointment",
    en: "When works for you?",
    ko: "언제가 좋으세요?",
    roman: "eonjega joeuseyo?",
    exampleKo: "다음 주 중에 언제가 좋으세요?",
    exampleEn: "Sometime next week, when works for you?",
    note: "Polite way to let the other person pick a time. 중에 = among/during.",
  },
  {
    id: "ko-b1-appointment-010",
    level: "B1",
    deck: "appointment",
    en: "to look forward to (seeing you)",
    ko: "기다리고 있을게요",
    roman: "gidarigo isseulgeyo",
    exampleKo: "그날 뵙기를 기다리고 있을게요.",
    exampleEn: "I'll be looking forward to seeing you that day.",
    note: "-고 있을게요 = 'I'll be (doing)' — a warm, forward-looking close.",
  },
  {
    id: "ko-b1-appointment-011",
    level: "B1",
    deck: "appointment",
    en: "to cancel (plans)",
    ko: "약속을 취소하다",
    roman: "yaksogeul chwisohada",
    exampleKo: "미안하지만 오늘 약속을 취소해야 할 것 같아요.",
    exampleEn: "I'm sorry, but I think I have to cancel today's plans.",
    note: "Softening with 미안하지만 ('I'm sorry, but') makes the cancel polite.",
  },
];
