/**
 * B1 (중급) 한국어 학습 콘텐츠 — 영어권 학습자 대상.
 * 각 카드: 한국어 표현(ko) + 로마자(roman) + 영어 뜻(en) + 예문(한/영).
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * note 는 영어(학습자 모국어)로 사용 맥락을 설명한다.
 *
 * B1: 기본 대화를 더 자연스럽게 — 이유·의견·연결 표현, 다양한 동사 활용.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_B1_DECKS: Deck[] = [
  {
    id: "work",
    level: "B1",
    title: { ko: "직장·업무", en: "Work", zh: "职场·工作", vi: "Công việc" },
    description: {
      ko: "회의·보고·협업 표현",
      en: "Meetings, reports, and teamwork",
      zh: "会议、汇报、协作表达",
      vi: "Họp, báo cáo và làm việc nhóm",
    },
    order: 1,
    icon: "Briefcase",
  },
  {
    id: "health",
    level: "B1",
    title: { ko: "건강·병원", en: "Health", zh: "健康·医院", vi: "Sức khỏe" },
    description: {
      ko: "증상 설명·진료·약국",
      en: "Symptoms, doctors, and pharmacies",
      zh: "症状描述、看诊、药店",
      vi: "Mô tả triệu chứng, khám bệnh và hiệu thuốc",
    },
    order: 2,
    icon: "Stethoscope",
  },
  {
    id: "travel",
    level: "B1",
    title: { ko: "여행", en: "Travel", zh: "旅行", vi: "Du lịch" },
    description: {
      ko: "예약·길찾기·문제 해결",
      en: "Booking, directions, and problem-solving",
      zh: "预订、问路、解决问题",
      vi: "Đặt chỗ, hỏi đường và giải quyết vấn đề",
    },
    order: 3,
    icon: "Plane",
  },
  {
    id: "feelings",
    level: "B1",
    title: { ko: "감정·기분", en: "Feelings", zh: "情感·心情", vi: "Cảm xúc" },
    description: {
      ko: "기분·감정·공감 표현",
      en: "Moods, emotions, and empathy",
      zh: "心情、情绪、共情表达",
      vi: "Cách diễn đạt tâm trạng, cảm xúc và sự đồng cảm",
    },
    order: 4,
    icon: "Smile",
  },
  {
    id: "appointment",
    level: "B1",
    title: { ko: "약속·일정", en: "Plans & Appointments", zh: "约定·日程", vi: "Lịch hẹn" },
    description: {
      ko: "약속 잡기·변경·확인",
      en: "Making, changing, and confirming plans",
      zh: "约定、变更、确认",
      vi: "Đặt hẹn, thay đổi và xác nhận",
    },
    order: 5,
    icon: "CalendarClock",
  },
];

export const KO_B1_CARDS: VocabCard[] = [
  // ─────────────────────────────── work ───────────────────────────────
  {
    id: "ko-b1-work-001",
    level: "B1",
    deck: "work",
    en: "to be in a meeting",
    zh: "在开会",
    vi: "Đang họp",
    ko: "회의 중이다",
    roman: "hoeui jungida",
    exampleKo: "지금 회의 중이라서 나중에 전화드릴게요.",
    exampleEn: "I'm in a meeting right now, so I'll call you later.",
    exampleZh: "我现在在开会，稍后再给您打电话。",
    exampleVi: "Tôi đang họp nên lát nữa tôi sẽ gọi lại cho bạn.",
    note: "Use the '-중이다' pattern to say you're in the middle of something.",
    noteZh: "用 '-중이다' 句型表示正在做某事的过程中。",
    noteVi: "Dùng mẫu câu '-중이다' để diễn đạt việc đang trong quá trình làm gì đó.",
  },
  {
    id: "ko-b1-work-002",
    level: "B1",
    deck: "work",
    en: "to submit a report",
    zh: "提交报告",
    vi: "Nộp báo cáo",
    ko: "보고서를 제출하다",
    roman: "bogoseoreul jechulhada",
    exampleKo: "내일까지 보고서를 제출해야 해요.",
    exampleEn: "I have to submit the report by tomorrow.",
    exampleZh: "我明天之前必须提交报告。",
    exampleVi: "Tôi phải nộp báo cáo trước ngày mai.",
    note: "제출하다 (to submit) is more formal than 내다 in the workplace.",
    noteZh: "在职场中，제출하다（提交）比 내다 更正式。",
    noteVi: "제출하다 (nộp) mang tính trang trọng hơn 내다 khi dùng ở nơi làm việc.",
  },
  {
    id: "ko-b1-work-003",
    level: "B1",
    deck: "work",
    en: "to work overtime",
    zh: "加班",
    vi: "Tăng ca",
    ko: "야근하다",
    roman: "yageunhada",
    exampleKo: "이번 주에는 매일 야근했어요.",
    exampleEn: "I worked overtime every day this week.",
    exampleZh: "这周我每天都加班。",
    exampleVi: "Tuần này ngày nào tôi cũng tăng ca.",
    note: "야근 literally means 'night work' — common in Korean office life.",
    noteZh: "야근 字面意思是'夜间工作'，在韩国职场很常见。",
    noteVi: "야근 theo nghĩa đen là 'làm việc ban đêm' — rất phổ biến trong đời sống công sở Hàn Quốc.",
  },
  {
    id: "ko-b1-work-004",
    level: "B1",
    deck: "work",
    en: "to meet a deadline",
    zh: "赶上截止期限",
    vi: "Kịp hạn chót",
    ko: "마감을 맞추다",
    roman: "magameul matchuda",
    exampleKo: "마감을 맞추려고 주말에도 일했어요.",
    exampleEn: "I worked on the weekend too in order to meet the deadline.",
    exampleZh: "为了赶上截止期限，我周末也在工作。",
    exampleVi: "Tôi đã làm việc cả cuối tuần để kịp hạn chót.",
    note: "맞추다 here means 'to make something fit/align' with the deadline.",
    noteZh: "这里的 맞추다 意为让进度'对上／赶上'截止期限。",
    noteVi: "맞추다 ở đây nghĩa là làm cho tiến độ 'khớp/kịp' với hạn chót.",
  },
  {
    id: "ko-b1-work-005",
    level: "B1",
    deck: "work",
    en: "to take a day off",
    zh: "请假",
    vi: "Xin nghỉ phép",
    ko: "휴가를 내다",
    roman: "hyugareul naeda",
    exampleKo: "다음 주에 하루 휴가를 내려고 해요.",
    exampleEn: "I'm planning to take a day off next week.",
    exampleZh: "我打算下周请一天假。",
    exampleVi: "Tuần sau tôi định xin nghỉ phép một ngày.",
    note: "휴가를 내다 = to put in for leave. 연차 specifically means annual leave.",
    noteZh: "휴가를 내다 = 提出休假申请。연차 特指年假。",
    noteVi: "휴가를 내다 = nộp đơn xin nghỉ phép. 연차 chỉ riêng phép năm.",
  },
  {
    id: "ko-b1-work-006",
    level: "B1",
    deck: "work",
    en: "to be in charge of",
    zh: "负责",
    vi: "Phụ trách",
    ko: "담당하다",
    roman: "damdanghada",
    exampleKo: "제가 이 프로젝트를 담당하고 있어요.",
    exampleEn: "I'm in charge of this project.",
    exampleZh: "这个项目由我负责。",
    exampleVi: "Tôi đang phụ trách dự án này.",
    note: "담당자 means 'the person in charge / point of contact'.",
    noteZh: "담당자 意为'负责人／对接人'。",
    noteVi: "담당자 nghĩa là 'người phụ trách / người đầu mối liên hệ'.",
  },
  {
    id: "ko-b1-work-007",
    level: "B1",
    deck: "work",
    en: "to discuss / talk over",
    zh: "商量／商议",
    vi: "Bàn bạc / trao đổi",
    ko: "의논하다",
    roman: "uinonhada",
    exampleKo: "그 문제는 팀장님과 의논해 볼게요.",
    exampleEn: "I'll discuss that issue with the team leader.",
    exampleZh: "那个问题我会跟组长商量一下。",
    exampleVi: "Vấn đề đó tôi sẽ bàn bạc với trưởng nhóm.",
    note: "의논하다 implies seeking advice; 상의하다 is a close synonym.",
    noteZh: "의논하다 含有征求意见的意味；상의하다 是近义词。",
    noteVi: "의논하다 hàm ý xin ý kiến; 상의하다 là từ đồng nghĩa gần giống.",
  },
  {
    id: "ko-b1-work-008",
    level: "B1",
    deck: "work",
    en: "in my opinion",
    zh: "在我看来／我认为",
    vi: "Theo tôi nghĩ",
    ko: "제 생각에는",
    roman: "je saenggageneun",
    exampleKo: "제 생각에는 이 방법이 더 좋을 것 같아요.",
    exampleEn: "In my opinion, this method seems better.",
    exampleZh: "我觉得这个方法可能更好。",
    exampleVi: "Theo tôi nghĩ, cách này có vẻ tốt hơn.",
    note: "A polite way to open an opinion. 제 = humble 'my'.",
    noteZh: "礼貌地引出自己意见的说法。제 = 谦逊的'我的'。",
    noteVi: "Cách nói lịch sự để mở đầu khi nêu ý kiến. 제 = 'của tôi' ở dạng khiêm nhường.",
  },
  {
    id: "ko-b1-work-009",
    level: "B1",
    deck: "work",
    en: "to be busy with work",
    zh: "工作忙",
    vi: "Bận công việc",
    ko: "일이 바쁘다",
    roman: "iri bappeuda",
    exampleKo: "요즘 일이 너무 바빠서 정신이 없어요.",
    exampleEn: "I'm so busy with work these days that I'm overwhelmed.",
    exampleZh: "最近工作太忙，忙得晕头转向。",
    exampleVi: "Dạo này công việc bận quá nên tôi rối tung cả lên.",
    note: "정신이 없다 ('to have no mind') idiomatically means 'to be hectic'.",
    noteZh: "정신이 없다（字面'没有神志'）是习惯用语，意为'忙得不可开交'。",
    noteVi: "정신이 없다 (nghĩa đen là 'không còn tâm trí') là thành ngữ mang nghĩa 'bận rộn tối mắt tối mũi'.",
  },
  {
    id: "ko-b1-work-010",
    level: "B1",
    deck: "work",
    en: "to send an email",
    zh: "发邮件",
    vi: "Gửi email",
    ko: "이메일을 보내다",
    roman: "imeireul bonaeda",
    exampleKo: "자세한 내용은 이메일로 보내 드릴게요.",
    exampleEn: "I'll send you the details by email.",
    exampleZh: "详细内容我会用邮件发给您。",
    exampleVi: "Tôi sẽ gửi nội dung chi tiết qua email cho bạn.",
    note: "메일 보내다 is the common short form in spoken Korean.",
    noteZh: "口语中常用简略说法 메일 보내다。",
    noteVi: "메일 보내다 là cách nói tắt thường dùng trong khẩu ngữ.",
  },
  {
    id: "ko-b1-work-011",
    level: "B1",
    deck: "work",
    en: "to ask a favor",
    zh: "拜托／请求帮忙",
    vi: "Nhờ vả",
    ko: "부탁을 드리다",
    roman: "butageul deurida",
    exampleKo: "바쁘시겠지만 부탁 좀 드려도 될까요?",
    exampleEn: "I know you're busy, but may I ask you a favor?",
    exampleZh: "您可能很忙，不过能拜托您一件事吗？",
    exampleVi: "Chắc bạn đang bận, nhưng tôi có thể nhờ một việc được không?",
    note: "드리다 is the humble form of 주다, used when asking up the hierarchy.",
    noteZh: "드리다 是 주다 的谦语形式，向上级请求时使用。",
    noteVi: "드리다 là dạng khiêm nhường của 주다, dùng khi nhờ vả người có vị trí cao hơn.",
  },
  {
    id: "ko-b1-work-012",
    level: "B1",
    deck: "work",
    en: "good work / well done (to coworkers)",
    zh: "辛苦了",
    vi: "Vất vả rồi",
    ko: "수고하셨습니다",
    roman: "sugohasyeotseumnida",
    exampleKo: "오늘 다들 수고하셨습니다.",
    exampleEn: "Everyone did a great job today.",
    exampleZh: "今天大家都辛苦了。",
    exampleVi: "Hôm nay mọi người đã vất vả rồi.",
    note: "Said at the end of work to acknowledge others' effort. Very common.",
    noteZh: "下班时用来慰劳他人辛劳的话，非常常用。",
    noteVi: "Câu nói dùng lúc kết thúc công việc để ghi nhận sự vất vả của người khác. Rất thông dụng.",
  },

  // ────────────────────────────── health ──────────────────────────────
  {
    id: "ko-b1-health-001",
    level: "B1",
    deck: "health",
    en: "I have a cold",
    zh: "感冒",
    vi: "Bị cảm",
    ko: "감기에 걸리다",
    roman: "gamgie geollida",
    exampleKo: "어제부터 감기에 걸려서 목이 아파요.",
    exampleEn: "I caught a cold yesterday, so my throat hurts.",
    exampleZh: "我从昨天开始感冒，嗓子疼。",
    exampleVi: "Tôi bị cảm từ hôm qua nên đau họng.",
    note: "Use the particle 에 + 걸리다 ('to be caught by') for illnesses.",
    noteZh: "生病时用助词 에 + 걸리다（'被……缠上'）。",
    noteVi: "Dùng trợ từ 에 + 걸리다 ('bị vướng vào') khi nói về bệnh tật.",
  },
  {
    id: "ko-b1-health-002",
    level: "B1",
    deck: "health",
    en: "to have a fever",
    zh: "发烧",
    vi: "Bị sốt",
    ko: "열이 나다",
    roman: "yeori nada",
    exampleKo: "아이가 열이 나서 병원에 갔어요.",
    exampleEn: "My child had a fever, so we went to the hospital.",
    exampleZh: "孩子发烧了，所以去了医院。",
    exampleVi: "Con tôi bị sốt nên tôi đã đưa đi bệnh viện.",
    note: "나다 ('to come out') pairs with many symptoms: 열, 기침, 콧물.",
    noteZh: "나다（'出现'）可与多种症状搭配：열（发烧）、기침（咳嗽）、콧물（流鼻涕）。",
    noteVi: "나다 ('xuất hiện, nổi lên') kết hợp được với nhiều triệu chứng: 열 (sốt), 기침 (ho), 콧물 (sổ mũi).",
  },
  {
    id: "ko-b1-health-003",
    level: "B1",
    deck: "health",
    en: "my whole body aches",
    zh: "浑身酸痛",
    vi: "Đau nhức khắp người",
    ko: "온몸이 아프다",
    roman: "onmomi apeuda",
    exampleKo: "몸살이 났는지 온몸이 아파요.",
    exampleEn: "My whole body aches — I think I'm coming down with something.",
    exampleZh: "大概是累病了，浑身酸痛。",
    exampleVi: "Chắc tôi bị cảm mệt nên đau nhức khắp người.",
    note: "몸살 is the body aches/fatigue of a cold; 몸살이 나다 = to get run down.",
    noteZh: "몸살 指感冒引起的浑身酸痛乏力；몸살이 나다 = 累垮、病倒。",
    noteVi: "몸살 là tình trạng đau nhức, mệt mỏi do cảm; 몸살이 나다 = kiệt sức, đổ bệnh.",
  },
  {
    id: "ko-b1-health-004",
    level: "B1",
    deck: "health",
    en: "to see a doctor",
    zh: "看病／就诊",
    vi: "Khám bệnh",
    ko: "진료를 받다",
    roman: "jillyoreul batda",
    exampleKo: "증상이 심해서 진료를 받으러 왔어요.",
    exampleEn: "My symptoms got worse, so I came to see a doctor.",
    exampleZh: "症状加重了，所以来看病。",
    exampleVi: "Triệu chứng nặng hơn nên tôi đến khám bệnh.",
    note: "진료 = medical examination. 진찰을 받다 is a close synonym.",
    noteZh: "진료 = 诊疗。진찰을 받다 是近义说法。",
    noteVi: "진료 = việc khám chữa bệnh. 진찰을 받다 là cách nói gần nghĩa.",
  },
  {
    id: "ko-b1-health-005",
    level: "B1",
    deck: "health",
    en: "to prescribe medicine",
    zh: "开药",
    vi: "Kê đơn thuốc",
    ko: "약을 처방하다",
    roman: "yageul cheobanghada",
    exampleKo: "의사 선생님이 약을 처방해 주셨어요.",
    exampleEn: "The doctor prescribed me some medicine.",
    exampleZh: "医生给我开了药。",
    exampleVi: "Bác sĩ đã kê đơn thuốc cho tôi.",
    note: "From the patient's side, you 약을 처방받다 (get a prescription).",
    noteZh: "从患者角度说 약을 처방받다（拿到处方／被开药）。",
    noteVi: "Đứng từ phía bệnh nhân thì nói 약을 처방받다 (được kê đơn thuốc).",
  },
  {
    id: "ko-b1-health-006",
    level: "B1",
    deck: "health",
    en: "to take medicine",
    zh: "吃药",
    vi: "Uống thuốc",
    ko: "약을 먹다",
    roman: "yageul meokda",
    exampleKo: "하루에 세 번 식후에 약을 드세요.",
    exampleEn: "Take the medicine three times a day after meals.",
    exampleZh: "请一天三次，饭后服药。",
    exampleVi: "Ngày uống ba lần sau bữa ăn.",
    note: "Korean uses 먹다 ('to eat') for taking medicine, not 마시다.",
    noteZh: "韩语'吃药'用 먹다（吃），而不用 마시다（喝）。",
    noteVi: "Tiếng Hàn dùng 먹다 ('ăn') để nói uống thuốc, chứ không dùng 마시다 ('uống').",
  },
  {
    id: "ko-b1-health-007",
    level: "B1",
    deck: "health",
    en: "to get some rest",
    zh: "好好休息",
    vi: "Nghỉ ngơi thật đầy đủ",
    ko: "푹 쉬다",
    roman: "puk swida",
    exampleKo: "무리하지 말고 푹 쉬세요.",
    exampleEn: "Don't overdo it and get plenty of rest.",
    exampleZh: "别勉强，好好休息。",
    exampleVi: "Đừng cố quá sức, hãy nghỉ ngơi thật đầy đủ.",
    note: "푹 is an adverb meaning 'thoroughly/deeply' — 푹 쉬다, 푹 자다.",
    noteZh: "푹 是副词，意为'充分地／酣畅地'——푹 쉬다（好好休息）、푹 자다（睡个好觉）。",
    noteVi: "푹 là phó từ nghĩa là 'một cách trọn vẹn/sâu' — 푹 쉬다 (nghỉ ngơi thật kỹ), 푹 자다 (ngủ thật ngon).",
  },
  {
    id: "ko-b1-health-008",
    level: "B1",
    deck: "health",
    en: "to get better / recover",
    zh: "痊愈／好转",
    vi: "Khỏi bệnh / thuyên giảm",
    ko: "낫다",
    roman: "natda",
    exampleKo: "약을 먹으니까 좀 나았어요.",
    exampleEn: "I feel a bit better after taking the medicine.",
    exampleZh: "吃了药之后好一些了。",
    exampleVi: "Sau khi uống thuốc, tôi thấy đỡ hơn một chút.",
    note: "Irregular ㅅ verb: 낫다 → 나아요, 나았어요. Also means 'to be better'.",
    noteZh: "ㅅ 不规则动词：낫다 → 나아요、나았어요。也有'更好'之意。",
    noteVi: "Động từ bất quy tắc ㅅ: 낫다 → 나아요, 나았어요. Cũng mang nghĩa 'tốt hơn'.",
  },
  {
    id: "ko-b1-health-009",
    level: "B1",
    deck: "health",
    en: "to be careful / take care",
    zh: "小心／注意",
    vi: "Cẩn thận",
    ko: "조심하다",
    roman: "josimhada",
    exampleKo: "감기 걸리지 않게 조심하세요.",
    exampleEn: "Be careful not to catch a cold.",
    exampleZh: "请注意别感冒。",
    exampleVi: "Hãy cẩn thận kẻo bị cảm.",
    note: "감기 조심하세요 is a common caring farewell in cold weather.",
    noteZh: "감기 조심하세요（小心别感冒）是天冷时常用的关切告别语。",
    noteVi: "감기 조심하세요 (cẩn thận kẻo bị cảm) là lời chào tạm biệt thể hiện sự quan tâm, thường dùng khi trời lạnh.",
  },
  {
    id: "ko-b1-health-010",
    level: "B1",
    deck: "health",
    en: "Where does it hurt?",
    zh: "哪里不舒服？",
    vi: "Anh/chị đau ở đâu?",
    ko: "어디가 아프세요?",
    roman: "eodiga apeuseyo?",
    exampleKo: "어디가 아프세요? 증상을 말씀해 주세요.",
    exampleEn: "Where does it hurt? Please describe your symptoms.",
    exampleZh: "您哪里不舒服？请说一下症状。",
    exampleVi: "Anh/chị đau ở đâu ạ? Xin hãy nói rõ triệu chứng.",
    note: "What a doctor or pharmacist asks first. 아프세요 is the polite form.",
    noteZh: "医生或药剂师最先问的话。아프세요 是敬语形式。",
    noteVi: "Câu bác sĩ hoặc dược sĩ thường hỏi đầu tiên. 아프세요 là dạng kính ngữ.",
  },
  {
    id: "ko-b1-health-011",
    level: "B1",
    deck: "health",
    en: "to make a reservation (appointment)",
    zh: "预约",
    vi: "Đặt hẹn",
    ko: "예약하다",
    roman: "yeyakhada",
    exampleKo: "병원에 미리 예약하고 가는 게 좋아요.",
    exampleEn: "It's better to make an appointment before going to the hospital.",
    exampleZh: "最好先跟医院预约再去。",
    exampleVi: "Tốt nhất nên đặt hẹn trước với bệnh viện rồi mới đến.",
    note: "Used for clinics, restaurants, hotels — anything booked in advance.",
    noteZh: "用于医院、餐厅、酒店等一切需提前预订的场合。",
    noteVi: "Dùng cho phòng khám, nhà hàng, khách sạn — bất cứ việc gì cần đặt trước.",
  },

  // ────────────────────────────── travel ──────────────────────────────
  {
    id: "ko-b1-travel-001",
    level: "B1",
    deck: "travel",
    en: "to book a flight ticket",
    zh: "订机票",
    vi: "Đặt vé máy bay",
    ko: "비행기 표를 예매하다",
    roman: "bihaenggi pyoreul yemaehada",
    exampleKo: "다음 달 비행기 표를 벌써 예매했어요.",
    exampleEn: "I already booked the flight ticket for next month.",
    exampleZh: "我已经订好了下个月的机票。",
    exampleVi: "Tôi đã đặt vé máy bay cho tháng sau rồi.",
    note: "예매하다 = to book tickets in advance (transport, movies, shows).",
    noteZh: "예매하다 = 提前购票（交通、电影、演出等）。",
    noteVi: "예매하다 = mua vé trước (giao thông, phim, biểu diễn, v.v.).",
  },
  {
    id: "ko-b1-travel-002",
    level: "B1",
    deck: "travel",
    en: "to check in (hotel)",
    zh: "办理入住",
    vi: "Nhận phòng",
    ko: "체크인하다",
    roman: "chekeuinhada",
    exampleKo: "보통 체크인은 오후 세 시부터예요.",
    exampleEn: "Check-in usually starts at 3 p.m.",
    exampleZh: "入住一般从下午三点开始。",
    exampleVi: "Thông thường nhận phòng bắt đầu từ 3 giờ chiều.",
    note: "Loanword from English. Checkout is 체크아웃하다.",
    noteZh: "来自英语的外来词。退房是 체크아웃하다。",
    noteVi: "Từ mượn từ tiếng Anh. Trả phòng là 체크아웃하다.",
  },
  {
    id: "ko-b1-travel-003",
    level: "B1",
    deck: "travel",
    en: "How do I get to...?",
    zh: "怎么去……？",
    vi: "Đi đến … như thế nào?",
    ko: "어떻게 가요?",
    roman: "eotteoke gayo?",
    exampleKo: "여기에서 시청까지 어떻게 가요?",
    exampleEn: "How do I get from here to City Hall?",
    exampleZh: "从这里到市政厅怎么走？",
    exampleVi: "Từ đây đến tòa thị chính đi như thế nào?",
    note: "Put the destination before 까지 (to/until): 시청까지 어떻게 가요?",
    noteZh: "把目的地放在 까지（到）之前：시청까지 어떻게 가요？（到市政厅怎么走？）",
    noteVi: "Đặt điểm đến trước 까지 (đến/cho tới): 시청까지 어떻게 가요? (Đến tòa thị chính đi thế nào?)",
  },
  {
    id: "ko-b1-travel-004",
    level: "B1",
    deck: "travel",
    en: "to transfer (trains/buses)",
    zh: "换乘",
    vi: "Chuyển tuyến",
    ko: "갈아타다",
    roman: "garatada",
    exampleKo: "여기에서 2호선으로 갈아타세요.",
    exampleEn: "Transfer to Line 2 here.",
    exampleZh: "请在这里换乘二号线。",
    exampleVi: "Hãy đổi sang tuyến số 2 ở đây.",
    note: "환승하다 is the more formal/written equivalent.",
    noteZh: "환승하다 是更正式／书面的说法。",
    noteVi: "환승하다 là cách nói trang trọng/văn viết hơn.",
  },
  {
    id: "ko-b1-travel-005",
    level: "B1",
    deck: "travel",
    en: "to get lost / lose one's way",
    zh: "迷路",
    vi: "Bị lạc đường",
    ko: "길을 잃다",
    roman: "gireul ilta",
    exampleKo: "지도를 봤는데도 길을 잃었어요.",
    exampleEn: "Even though I looked at the map, I got lost.",
    exampleZh: "我明明看了地图，还是迷路了。",
    exampleVi: "Dù đã xem bản đồ nhưng tôi vẫn bị lạc đường.",
    note: "-는데도 means 'even though' — useful for contrasting results.",
    noteZh: "-는데도 意为'尽管……还是'，用于表达出乎意料的结果。",
    noteVi: "-는데도 nghĩa là 'mặc dù... vẫn', dùng để diễn đạt kết quả trái với mong đợi.",
  },
  {
    id: "ko-b1-travel-006",
    level: "B1",
    deck: "travel",
    en: "Could you recommend...?",
    zh: "能推荐一下……吗？",
    vi: "Có thể giới thiệu … được không?",
    ko: "추천해 주시겠어요?",
    roman: "chucheonhae jusigesseoyo?",
    exampleKo: "이 근처에 맛있는 식당 좀 추천해 주시겠어요?",
    exampleEn: "Could you recommend a good restaurant nearby?",
    exampleZh: "能给我推荐一下这附近好吃的餐厅吗？",
    exampleVi: "Anh/chị có thể giới thiệu giúp tôi một nhà hàng ngon gần đây được không?",
    note: "-아/어 주시겠어요? is a very polite request pattern.",
    noteZh: "-아/어 주시겠어요？是非常礼貌的请求句型。",
    noteVi: "-아/어 주시겠어요? là mẫu câu yêu cầu rất lịch sự.",
  },
  {
    id: "ko-b1-travel-007",
    level: "B1",
    deck: "travel",
    en: "to take a picture",
    zh: "拍照",
    vi: "Chụp ảnh",
    ko: "사진을 찍다",
    roman: "sajineul jjikda",
    exampleKo: "실례지만 사진 좀 찍어 주실 수 있어요?",
    exampleEn: "Excuse me, could you take a picture for us?",
    exampleZh: "不好意思，能帮我们拍张照吗？",
    exampleVi: "Xin lỗi, anh/chị có thể chụp giúp chúng tôi một tấm ảnh không?",
    note: "찍어 주다 = take a photo for someone else's benefit.",
    noteZh: "찍어 주다 = 替别人拍照。",
    noteVi: "찍어 주다 = chụp ảnh giúp cho người khác.",
  },
  {
    id: "ko-b1-travel-008",
    level: "B1",
    deck: "travel",
    en: "It's worth seeing / a must-see",
    zh: "值得一看",
    vi: "Đáng để xem",
    ko: "볼 만하다",
    roman: "bol manhada",
    exampleKo: "경복궁은 한번 볼 만해요.",
    exampleEn: "Gyeongbokgung Palace is worth seeing.",
    exampleZh: "景福宫值得一去看看。",
    exampleVi: "Cung Gyeongbok rất đáng để xem một lần.",
    note: "-(으)ㄹ 만하다 means 'worth doing'. 갈 만하다, 먹을 만하다 too.",
    noteZh: "-(으)ㄹ 만하다 意为'值得做'。也有 갈 만하다（值得去）、먹을 만하다（值得吃）。",
    noteVi: "-(으)ㄹ 만하다 nghĩa là 'đáng để làm'. Còn có 갈 만하다 (đáng để đi), 먹을 만하다 (đáng để ăn).",
  },
  {
    id: "ko-b1-travel-009",
    level: "B1",
    deck: "travel",
    en: "to exchange money",
    zh: "换钱／兑换货币",
    vi: "Đổi tiền",
    ko: "환전하다",
    roman: "hwanjeonhada",
    exampleKo: "공항에서 환전하면 수수료가 비싸요.",
    exampleEn: "If you exchange money at the airport, the fee is high.",
    exampleZh: "在机场换钱手续费很高。",
    exampleVi: "Nếu đổi tiền ở sân bay thì phí rất cao.",
    note: "수수료 = service/handling fee, useful for banking and travel.",
    noteZh: "수수료 = 手续费，在银行和旅行中都常用。",
    noteVi: "수수료 = phí dịch vụ/phí xử lý, hữu ích khi dùng trong ngân hàng và du lịch.",
  },
  {
    id: "ko-b1-travel-010",
    level: "B1",
    deck: "travel",
    en: "How much is the fare?",
    zh: "费用是多少？",
    vi: "Giá vé là bao nhiêu?",
    ko: "요금이 얼마예요?",
    roman: "yogeumi eolmayeyo?",
    exampleKo: "택시 요금이 얼마예요?",
    exampleEn: "How much is the taxi fare?",
    exampleZh: "打车费是多少？",
    exampleVi: "Cước taxi là bao nhiêu?",
    note: "요금 = fare/charge (transport, utilities); 값/가격 = price of goods.",
    noteZh: "요금 = 费用（交通、水电等）；값/가격 = 商品价格。",
    noteVi: "요금 = cước phí (giao thông, điện nước...); 값/가격 = giá của hàng hóa.",
  },
  {
    id: "ko-b1-travel-011",
    level: "B1",
    deck: "travel",
    en: "to cancel a reservation",
    zh: "取消预订",
    vi: "Hủy đặt chỗ",
    ko: "예약을 취소하다",
    roman: "yeyageul chwisohada",
    exampleKo: "일정이 바뀌어서 예약을 취소해야 해요.",
    exampleEn: "My schedule changed, so I have to cancel the reservation.",
    exampleZh: "行程变了，我得取消预订。",
    exampleVi: "Lịch trình thay đổi nên tôi phải hủy đặt chỗ.",
    note: "취소하다 = to cancel; 변경하다 = to change/modify.",
    noteZh: "취소하다 = 取消；변경하다 = 变更／修改。",
    noteVi: "취소하다 = hủy; 변경하다 = thay đổi/chỉnh sửa.",
  },
  {
    id: "ko-b1-travel-012",
    level: "B1",
    deck: "travel",
    en: "Have a safe trip",
    zh: "一路平安",
    vi: "Đi đường bình an",
    ko: "잘 다녀오세요",
    roman: "jal danyeooseyo",
    exampleKo: "여행 잘 다녀오세요!",
    exampleEn: "Have a safe trip!",
    exampleZh: "祝您旅途平安！",
    exampleVi: "Chúc bạn đi du lịch bình an!",
    note: "Said to someone leaving and coming back. They reply 다녀오겠습니다.",
    noteZh: "对出门后会回来的人说。对方回答 다녀오겠습니다（我出门了）。",
    noteVi: "Nói với người sắp đi và sẽ quay về. Người đó đáp lại bằng 다녀오겠습니다 (con/tôi xin phép đi đây).",
  },

  // ───────────────────────────── feelings ─────────────────────────────
  {
    id: "ko-b1-feelings-001",
    level: "B1",
    deck: "feelings",
    en: "to be in a good mood",
    zh: "心情好",
    vi: "Tâm trạng tốt",
    ko: "기분이 좋다",
    roman: "gibuni jota",
    exampleKo: "오늘은 날씨가 좋아서 기분이 좋아요.",
    exampleEn: "The weather is nice today, so I'm in a good mood.",
    exampleZh: "今天天气好，所以心情很好。",
    exampleVi: "Hôm nay thời tiết đẹp nên tôi cảm thấy vui vẻ.",
    note: "기분 = mood/feeling at the moment; 감정 = emotion in general.",
    noteZh: "기분 = 当下的心情／感觉；감정 = 泛指情感。",
    noteVi: "기분 = tâm trạng/cảm giác tại thời điểm hiện tại; 감정 = cảm xúc nói chung.",
  },
  {
    id: "ko-b1-feelings-002",
    level: "B1",
    deck: "feelings",
    en: "to be upset / in a bad mood",
    zh: "心情不好",
    vi: "Tâm trạng không tốt",
    ko: "기분이 나쁘다",
    roman: "gibuni nappeuda",
    exampleKo: "그 말을 듣고 기분이 나빴어요.",
    exampleEn: "I felt bad after hearing that.",
    exampleZh: "听到那句话后我心情很差。",
    exampleVi: "Nghe câu đó xong tôi thấy khó chịu.",
    note: "기분이 상하다 ('mood gets hurt') is a softer way to say offended.",
    noteZh: "기분이 상하다（'心情受伤'）是表达'被冒犯'的委婉说法。",
    noteVi: "기분이 상하다 ('tâm trạng bị tổn thương') là cách nói nhẹ nhàng hơn để diễn đạt việc cảm thấy bị xúc phạm.",
  },
  {
    id: "ko-b1-feelings-003",
    level: "B1",
    deck: "feelings",
    en: "to be worried",
    zh: "担心",
    vi: "Lo lắng",
    ko: "걱정되다",
    roman: "geokjeongdoeda",
    exampleKo: "시험 결과가 걱정돼요.",
    exampleEn: "I'm worried about the test results.",
    exampleZh: "我很担心考试结果。",
    exampleVi: "Tôi lo lắng về kết quả thi.",
    note: "걱정되다 = to feel worried; 걱정하다 = to worry (active). 걱정하지 마세요 = don't worry.",
    noteZh: "걱정되다 = 感到担心（自发）；걱정하다 = 担心（主动）。걱정하지 마세요 = 别担心。",
    noteVi: "걱정되다 = cảm thấy lo lắng (tự nhiên phát sinh); 걱정하다 = lo lắng (chủ động). 걱정하지 마세요 = đừng lo lắng.",
  },
  {
    id: "ko-b1-feelings-004",
    level: "B1",
    deck: "feelings",
    en: "to be excited / look forward to",
    zh: "期待",
    vi: "Mong chờ",
    ko: "기대되다",
    roman: "gidaedoeda",
    exampleKo: "내일 여행이 정말 기대돼요.",
    exampleEn: "I'm really looking forward to the trip tomorrow.",
    exampleZh: "我非常期待明天的旅行。",
    exampleVi: "Tôi rất mong chờ chuyến đi ngày mai.",
    note: "기대 = expectation/anticipation. 기대돼요 = I can't wait.",
    noteZh: "기대 = 期待／期盼。기대돼요 = 迫不及待。",
    noteVi: "기대 = sự mong đợi/kỳ vọng. 기대돼요 = nóng lòng không thể chờ được.",
  },
  {
    id: "ko-b1-feelings-005",
    level: "B1",
    deck: "feelings",
    en: "to be disappointed",
    zh: "失望",
    vi: "Thất vọng",
    ko: "실망하다",
    roman: "silmanghada",
    exampleKo: "기대를 많이 해서 그런지 좀 실망했어요.",
    exampleEn: "Maybe because I expected a lot, I was a bit disappointed.",
    exampleZh: "可能是因为期望太高，我有点失望。",
    exampleVi: "Có lẽ vì tôi kỳ vọng nhiều nên hơi thất vọng.",
    note: "-아/어서 그런지 = 'maybe because...' — softens a guess about a reason.",
    noteZh: "-아/어서 그런지 = '也许是因为……'，委婉地推测原因。",
    noteVi: "-아/어서 그런지 = 'có lẽ vì...' — cách nói giảm nhẹ khi phỏng đoán nguyên nhân.",
  },
  {
    id: "ko-b1-feelings-006",
    level: "B1",
    deck: "feelings",
    en: "to be nervous",
    zh: "紧张",
    vi: "Hồi hộp",
    ko: "긴장되다",
    roman: "ginjangdoeda",
    exampleKo: "면접 때문에 너무 긴장돼요.",
    exampleEn: "I'm so nervous because of the interview.",
    exampleZh: "因为面试，我特别紧张。",
    exampleVi: "Vì buổi phỏng vấn nên tôi rất hồi hộp.",
    note: "긴장 = tension/nerves. 긴장을 풀다 = to relax/release the tension.",
    noteZh: "긴장 = 紧张情绪。긴장을 풀다 = 放松、缓解紧张。",
    noteVi: "긴장 = sự căng thẳng/hồi hộp. 긴장을 풀다 = thư giãn, giải tỏa căng thẳng.",
  },
  {
    id: "ko-b1-feelings-007",
    level: "B1",
    deck: "feelings",
    en: "to feel relieved",
    zh: "放心",
    vi: "Yên tâm",
    ko: "마음이 놓이다",
    roman: "maeumi noida",
    exampleKo: "네가 무사하다니 마음이 놓이네.",
    exampleEn: "I'm relieved to hear that you're safe.",
    exampleZh: "听说你平安无事，我就放心了。",
    exampleVi: "Nghe nói bạn bình an vô sự, tôi thấy yên tâm.",
    note: "Literally 'the heart is set down'. 다행이다 also means 'what a relief'.",
    noteZh: "字面意为'心放下了'。다행이다 也表示'太好了／幸好'。",
    noteVi: "Nghĩa đen là 'trái tim được đặt xuống'. 다행이다 cũng có nghĩa 'may quá/thật nhẹ nhõm'.",
  },
  {
    id: "ko-b1-feelings-008",
    level: "B1",
    deck: "feelings",
    en: "I understand how you feel",
    zh: "我理解你的心情",
    vi: "Tôi hiểu cảm giác của bạn",
    ko: "그 마음 이해해요",
    roman: "geu maeum ihaehaeyo",
    exampleKo: "힘들겠지만 그 마음 이해해요.",
    exampleEn: "It must be hard, but I understand how you feel.",
    exampleZh: "虽然很难受，但我理解你的心情。",
    exampleVi: "Chắc là khó khăn lắm, nhưng tôi hiểu cảm giác của bạn.",
    note: "A warm empathy phrase. 공감하다 = to empathize/relate.",
    noteZh: "温暖的共情用语。공감하다 = 产生共鸣／感同身受。",
    noteVi: "Cách nói đồng cảm ấm áp. 공감하다 = đồng cảm/cảm nhận chung.",
  },
  {
    id: "ko-b1-feelings-009",
    level: "B1",
    deck: "feelings",
    en: "Cheer up / Stay strong",
    zh: "加油／打起精神",
    vi: "Cố lên",
    ko: "힘내세요",
    roman: "himnaeseyo",
    exampleKo: "너무 속상해하지 말고 힘내세요.",
    exampleEn: "Don't be too upset — stay strong.",
    exampleZh: "别太难过，加油。",
    exampleVi: "Đừng buồn quá, cố lên nhé.",
    note: "Literally 'put out strength'. The go-to phrase to encourage someone.",
    noteZh: "字面意为'拿出力气'。鼓励他人时最常用的一句话。",
    noteVi: "Nghĩa đen là 'hãy đưa sức mạnh ra'. Là câu nói động viên người khác thông dụng nhất.",
  },
  {
    id: "ko-b1-feelings-010",
    level: "B1",
    deck: "feelings",
    en: "to be touched / moved",
    zh: "感动",
    vi: "Cảm động",
    ko: "감동받다",
    roman: "gamdongbatda",
    exampleKo: "편지를 읽고 정말 감동받았어요.",
    exampleEn: "I was really moved after reading the letter.",
    exampleZh: "读了信之后我真的很感动。",
    exampleVi: "Đọc xong lá thư tôi thực sự rất cảm động.",
    note: "감동 = deep emotional impact. 감동적이다 = to be touching/moving.",
    noteZh: "감동 = 深深的感动。감동적이다 = 令人感动的。",
    noteVi: "감동 = sự xúc động sâu sắc. 감동적이다 = gây xúc động, cảm động.",
  },
  {
    id: "ko-b1-feelings-011",
    level: "B1",
    deck: "feelings",
    en: "to be annoyed / fed up",
    zh: "心烦／烦躁",
    vi: "Bực mình",
    ko: "짜증이 나다",
    roman: "jjajeungi nada",
    exampleKo: "일이 자꾸 안 풀려서 짜증이 나요.",
    exampleEn: "Things keep not working out, so I'm getting annoyed.",
    exampleZh: "事情老是不顺，让我很烦躁。",
    exampleVi: "Việc cứ không suôn sẻ nên tôi thấy bực mình.",
    note: "짜증 is everyday irritation. Casual: 짜증 나 ('ugh, so annoying').",
    noteZh: "짜증 是日常的烦躁。口语：짜증 나（'啊，真烦'）。",
    noteVi: "짜증 là sự bực bội thường ngày. Khẩu ngữ: 짜증 나 ('chán ghê, bực thật').",
  },

  // ──────────────────────────── appointment ───────────────────────────
  {
    id: "ko-b1-appointment-001",
    level: "B1",
    deck: "appointment",
    en: "to make plans / set a date",
    zh: "约定时间／定约会",
    vi: "Hẹn gặp",
    ko: "약속을 잡다",
    roman: "yaksogeul japda",
    exampleKo: "이번 주말에 친구랑 약속을 잡았어요.",
    exampleEn: "I made plans with a friend for this weekend.",
    exampleZh: "我和朋友约好了这个周末见面。",
    exampleVi: "Cuối tuần này tôi đã hẹn gặp bạn bè.",
    note: "약속 = a promise or an appointment. 약속을 잡다 = to set up a meeting.",
    noteZh: "약속 = 约定或约会。약속을 잡다 = 定下见面安排。",
    noteVi: "약속 = lời hứa hoặc cuộc hẹn. 약속을 잡다 = sắp xếp một cuộc gặp.",
  },
  {
    id: "ko-b1-appointment-002",
    level: "B1",
    deck: "appointment",
    en: "Are you free / available?",
    zh: "您有时间吗？",
    vi: "Anh/chị có thời gian không?",
    ko: "시간 괜찮으세요?",
    roman: "sigan gwaenchaneuseyo?",
    exampleKo: "내일 오후에 시간 괜찮으세요?",
    exampleEn: "Are you free tomorrow afternoon?",
    exampleZh: "您明天下午有时间吗？",
    exampleVi: "Chiều mai anh/chị có thời gian không?",
    note: "Polite way to ask availability. 시간 있으세요? is a bit more direct.",
    noteZh: "礼貌地询问对方是否有空。시간 있으세요？稍微直接一些。",
    noteVi: "Cách hỏi lịch sự xem đối phương có rảnh không. 시간 있으세요? trực tiếp hơn một chút.",
  },
  {
    id: "ko-b1-appointment-003",
    level: "B1",
    deck: "appointment",
    en: "to be late / run late",
    zh: "迟到／晚",
    vi: "Trễ",
    ko: "늦다",
    roman: "neutda",
    exampleKo: "길이 막혀서 조금 늦을 것 같아요.",
    exampleEn: "The traffic is bad, so I think I'll be a little late.",
    exampleZh: "路上堵车，我可能会晚一点。",
    exampleVi: "Đường bị kẹt nên chắc tôi sẽ đến trễ một chút.",
    note: "-(으)ㄹ 것 같아요 = 'I think it'll...' — softens predictions politely.",
    noteZh: "-(으)ㄹ 것 같아요 = '我觉得会……'，礼貌地委婉预测。",
    noteVi: "-(으)ㄹ 것 같아요 = 'tôi nghĩ sẽ...' — cách nói giảm nhẹ, lịch sự khi dự đoán.",
  },
  {
    id: "ko-b1-appointment-004",
    level: "B1",
    deck: "appointment",
    en: "to reschedule / change plans",
    zh: "推迟约定",
    vi: "Dời lịch hẹn",
    ko: "약속을 미루다",
    roman: "yaksogeul miruda",
    exampleKo: "갑자기 일이 생겨서 약속을 미뤄도 될까요?",
    exampleEn: "Something came up — could we push the appointment back?",
    exampleZh: "我突然有事，约会可以往后推吗？",
    exampleVi: "Tôi đột nhiên có việc, có thể dời lịch hẹn được không?",
    note: "미루다 = to postpone/put off. 앞당기다 = to move up (earlier).",
    noteZh: "미루다 = 推迟／延后。앞당기다 = 提前。",
    noteVi: "미루다 = hoãn lại/dời sau. 앞당기다 = dời sớm lên.",
  },
  {
    id: "ko-b1-appointment-005",
    level: "B1",
    deck: "appointment",
    en: "Something came up",
    zh: "有事情／出了点事",
    vi: "Có việc phát sinh",
    ko: "일이 생기다",
    roman: "iri saenggida",
    exampleKo: "급한 일이 생겨서 못 갈 것 같아요.",
    exampleEn: "Something urgent came up, so I don't think I can go.",
    exampleZh: "我突然有急事，可能去不了了。",
    exampleVi: "Tôi có việc gấp phát sinh nên chắc không đi được.",
    note: "생기다 = to come about/arise. 급한 일 = an urgent matter.",
    noteZh: "생기다 = 发生／出现。급한 일 = 急事。",
    noteVi: "생기다 = phát sinh/xuất hiện. 급한 일 = việc gấp.",
  },
  {
    id: "ko-b1-appointment-006",
    level: "B1",
    deck: "appointment",
    en: "to confirm / check (a plan)",
    zh: "确认",
    vi: "Xác nhận",
    ko: "확인하다",
    roman: "hwaginhada",
    exampleKo: "약속 시간을 다시 한번 확인하고 싶어요.",
    exampleEn: "I'd like to confirm the appointment time once more.",
    exampleZh: "我想再确认一次约定的时间。",
    exampleVi: "Tôi muốn xác nhận lại giờ hẹn một lần nữa.",
    note: "확인하다 = to confirm/verify. 다시 한번 = once more, one more time.",
    noteZh: "확인하다 = 确认／核实。다시 한번 = 再一次。",
    noteVi: "확인하다 = xác nhận/kiểm tra. 다시 한번 = một lần nữa.",
  },
  {
    id: "ko-b1-appointment-007",
    level: "B1",
    deck: "appointment",
    en: "Let's meet at...",
    zh: "在……见面吧",
    vi: "Gặp nhau ở …",
    ko: "에서 만나요",
    roman: "eseo mannayo",
    exampleKo: "그럼 강남역에서 만나요.",
    exampleEn: "Then let's meet at Gangnam Station.",
    exampleZh: "那我们在江南站见吧。",
    exampleVi: "Vậy thì gặp nhau ở ga Gangnam nhé.",
    note: "Place + 에서 marks where an action happens. 만나다 takes 에서, not 에.",
    noteZh: "地点 + 에서 表示动作发生的场所。만나다 用 에서，而非 에。",
    noteVi: "Địa điểm + 에서 đánh dấu nơi hành động diễn ra. 만나다 đi với 에서, không phải 에.",
  },
  {
    id: "ko-b1-appointment-008",
    level: "B1",
    deck: "appointment",
    en: "to be on time / make it in time",
    zh: "守时／遵守时间",
    vi: "Đúng giờ",
    ko: "시간을 지키다",
    roman: "siganeul jikida",
    exampleKo: "약속 시간을 잘 지키는 사람이 좋아요.",
    exampleEn: "I like people who are punctual.",
    exampleZh: "我喜欢守时的人。",
    exampleVi: "Tôi thích những người đúng giờ hẹn.",
    note: "지키다 = to keep/protect; 약속을 지키다 = to keep a promise.",
    noteZh: "지키다 = 遵守／守护；약속을 지키다 = 遵守约定。",
    noteVi: "지키다 = giữ/bảo vệ; 약속을 지키다 = giữ lời hứa.",
  },
  {
    id: "ko-b1-appointment-009",
    level: "B1",
    deck: "appointment",
    en: "When works for you?",
    zh: "您什么时候方便？",
    vi: "Khi nào thì tiện?",
    ko: "언제가 좋으세요?",
    roman: "eonjega joeuseyo?",
    exampleKo: "다음 주 중에 언제가 좋으세요?",
    exampleEn: "Sometime next week, when works for you?",
    exampleZh: "下周之内您什么时候方便？",
    exampleVi: "Trong tuần sau thì khi nào tiện cho anh/chị?",
    note: "Polite way to let the other person pick a time. 중에 = among/during.",
    noteZh: "礼貌地让对方选时间的说法。중에 = 在……之中／期间。",
    noteVi: "Cách nói lịch sự để đối phương tự chọn thời gian. 중에 = trong số/trong khoảng.",
  },
  {
    id: "ko-b1-appointment-010",
    level: "B1",
    deck: "appointment",
    en: "to look forward to (seeing you)",
    zh: "我会一直期待着",
    vi: "Tôi sẽ mong chờ",
    ko: "기다리고 있을게요",
    roman: "gidarigo isseulgeyo",
    exampleKo: "그날 뵙기를 기다리고 있을게요.",
    exampleEn: "I'll be looking forward to seeing you that day.",
    exampleZh: "我会一直期待那天见到您。",
    exampleVi: "Tôi sẽ mong chờ được gặp anh/chị vào hôm đó.",
    note: "-고 있을게요 = 'I'll be (doing)' — a warm, forward-looking close.",
    noteZh: "-고 있을게요 = '我会一直……'，温暖而充满期待的结尾。",
    noteVi: "-고 있을게요 = 'tôi sẽ tiếp tục...' — lời kết ấm áp, hướng về phía trước đầy mong đợi.",
  },
  {
    id: "ko-b1-appointment-011",
    level: "B1",
    deck: "appointment",
    en: "to cancel (plans)",
    zh: "取消约会",
    vi: "Hủy hẹn",
    ko: "약속을 취소하다",
    roman: "yaksogeul chwisohada",
    exampleKo: "미안하지만 오늘 약속을 취소해야 할 것 같아요.",
    exampleEn: "I'm sorry, but I think I have to cancel today's plans.",
    exampleZh: "不好意思，今天的约会我可能得取消了。",
    exampleVi: "Xin lỗi nhưng chắc tôi phải hủy hẹn hôm nay.",
    note: "Softening with 미안하지만 ('I'm sorry, but') makes the cancel polite.",
    noteZh: "用 미안하지만（'不好意思，但是'）来缓和，使取消显得礼貌。",
    noteVi: "Dùng 미안하지만 ('xin lỗi nhưng') để giảm nhẹ, khiến việc hủy trở nên lịch sự.",
  },
];
