/**
 * B2 (중상급) 한국어 학습 콘텐츠 — 영어권 학습자 대상.
 * 각 카드: 한국어 표현(ko) + 로마자(roman) + 영어 뜻(en) + 예문(한/영).
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * note 는 영어(학습자 모국어)로 사용 맥락을 설명한다.
 *
 * B2 수준: 의견·감정을 한국어로 표현, 추상적 주제(뉴스·환경·기술·문화),
 * 격식/비격식 구분, 관용적 연결어. 토론·시사 맥락의 표현 중심.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_B2_DECKS: Deck[] = [
  {
    id: "opinion",
    level: "B2",
    title: { ko: "의견·토론", en: "Opinions & Discussion" },
    description: {
      ko: "주장·반박·동의·근거 제시",
      en: "Stating, supporting, and challenging views",
    },
    order: 1,
    icon: "MessagesSquare",
  },
  {
    id: "news",
    level: "B2",
    title: { ko: "뉴스·시사", en: "News & Current Affairs" },
    description: {
      ko: "보도·정책·여론·논란",
      en: "Reporting, policy, and public debate",
    },
    order: 2,
    icon: "Newspaper",
  },
  {
    id: "environment",
    level: "B2",
    title: { ko: "환경", en: "Environment" },
    description: {
      ko: "기후·오염·지속가능성",
      en: "Climate, pollution, and sustainability",
    },
    order: 3,
    icon: "Leaf",
  },
  {
    id: "technology",
    level: "B2",
    title: { ko: "기술·디지털", en: "Technology" },
    description: {
      ko: "인공지능·데이터·온라인 생활",
      en: "AI, data, and digital life",
    },
    order: 4,
    icon: "Cpu",
  },
  {
    id: "culture",
    level: "B2",
    title: { ko: "문화·예술", en: "Culture & Arts" },
    description: {
      ko: "전통·대중문화·전시·공연",
      en: "Tradition, pop culture, and the arts",
    },
    order: 5,
    icon: "Palette",
  },
];

export const KO_B2_CARDS: VocabCard[] = [
  // ── opinion (의견·토론) ──
  {
    id: "ko-b2-opinion-001",
    level: "B2",
    deck: "opinion",
    en: "In my opinion / From my point of view",
    ko: "제 생각에는",
    roman: "je saenggageneun",
    exampleKo: "제 생각에는 그 정책이 효과가 없을 것 같아요.",
    exampleEn: "In my opinion, that policy probably won't work.",
    note: "Polite, neutral way to open an opinion. Softer than 제가 보기에는.",
  },
  {
    id: "ko-b2-opinion-002",
    level: "B2",
    deck: "opinion",
    en: "To be honest / Frankly",
    ko: "솔직히 말하면",
    roman: "soljiki malhamyeon",
    exampleKo: "솔직히 말하면 저는 그 의견에 반대해요.",
    exampleEn: "To be honest, I disagree with that view.",
    note: "Signals a candid, slightly stronger opinion is coming.",
  },
  {
    id: "ko-b2-opinion-003",
    level: "B2",
    deck: "opinion",
    en: "I (partly) agree, but...",
    ko: "어느 정도 동의하지만",
    roman: "eoneu jeongdo donguihajiman",
    exampleKo: "어느 정도 동의하지만 현실적으로는 어려워요.",
    exampleEn: "I agree to some extent, but realistically it's difficult.",
    note: "Diplomatic partial agreement before raising a counterpoint.",
  },
  {
    id: "ko-b2-opinion-004",
    level: "B2",
    deck: "opinion",
    en: "That makes sense, but...",
    ko: "일리가 있지만",
    roman: "illiga itjiman",
    exampleKo: "그 말도 일리가 있지만 부작용도 생각해야 해요.",
    exampleEn: "That point has merit, but we have to consider the side effects.",
    note: "일리가 있다 = 'has a point / is reasonable.' Common in debate.",
  },
  {
    id: "ko-b2-opinion-005",
    level: "B2",
    deck: "opinion",
    en: "On the other hand",
    ko: "반면에",
    roman: "banmyeone",
    exampleKo: "비용은 줄지만 반면에 품질이 떨어질 수 있어요.",
    exampleEn: "Costs go down, but on the other hand quality may drop.",
    note: "Formal connector for contrasting two sides of an argument.",
  },
  {
    id: "ko-b2-opinion-006",
    level: "B2",
    deck: "opinion",
    en: "The reason is that...",
    ko: "그 이유는",
    roman: "geu iyuneun",
    exampleKo: "제가 반대하는 그 이유는 비용 때문이에요.",
    exampleEn: "The reason I'm opposed is the cost.",
    note: "Introduces your grounds; often paired with ...때문이에요.",
  },
  {
    id: "ko-b2-opinion-007",
    level: "B2",
    deck: "opinion",
    en: "I don't think so",
    ko: "그렇게 생각하지 않아요",
    roman: "geureoke saenggakaji anayo",
    exampleKo: "저는 그렇게 생각하지 않아요. 근거가 부족해요.",
    exampleEn: "I don't think so. There isn't enough evidence.",
    note: "Polite disagreement, softer than a flat 아니에요.",
  },
  {
    id: "ko-b2-opinion-008",
    level: "B2",
    deck: "opinion",
    en: "Strictly speaking",
    ko: "엄밀히 따지면",
    roman: "eommilhi ttajimyeon",
    exampleKo: "엄밀히 따지면 그건 사실과 조금 달라요.",
    exampleEn: "Strictly speaking, that's a little different from the facts.",
    note: "Signals you're about to make a precise, careful distinction.",
  },
  {
    id: "ko-b2-opinion-009",
    level: "B2",
    deck: "opinion",
    en: "That's a matter of opinion / It depends on the person",
    ko: "사람마다 다르죠",
    roman: "sarammada dareujyo",
    exampleKo: "취향은 사람마다 다르죠.",
    exampleEn: "Taste differs from person to person.",
    note: "Neutral way to acknowledge there's no single right answer.",
  },
  {
    id: "ko-b2-opinion-010",
    level: "B2",
    deck: "opinion",
    en: "To sum up / In short",
    ko: "결론적으로",
    roman: "gyeollonjeogeuro",
    exampleKo: "결론적으로 저는 찬성하는 입장이에요.",
    exampleEn: "In conclusion, I'm in favor.",
    note: "Formal closer for wrapping up an argument. 입장 = stance.",
  },
  {
    id: "ko-b2-opinion-011",
    level: "B2",
    deck: "opinion",
    en: "Needless to say / It goes without saying",
    ko: "말할 것도 없이",
    roman: "malhal geotdo eopsi",
    exampleKo: "말할 것도 없이 안전이 가장 중요해요.",
    exampleEn: "Needless to say, safety is the most important thing.",
    note: "Emphasizes something you treat as obvious or beyond dispute.",
  },
  {
    id: "ko-b2-opinion-012",
    level: "B2",
    deck: "opinion",
    en: "If anything / Rather",
    ko: "오히려",
    roman: "ohiryeo",
    exampleKo: "규제가 오히려 시장을 망칠 수도 있어요.",
    exampleEn: "Regulation could, if anything, ruin the market.",
    note: "Flags a counter-intuitive turn — 'the opposite of what you'd expect.'",
  },

  // ── news (뉴스·시사) ──
  {
    id: "ko-b2-news-001",
    level: "B2",
    deck: "news",
    en: "According to the report / news",
    ko: "보도에 따르면",
    roman: "bodoe ttareumyeon",
    exampleKo: "보도에 따르면 물가가 다시 올랐다고 해요.",
    exampleEn: "According to the report, prices have risen again.",
    note: "Standard journalistic phrase to cite a source. -다고 해요 = reported speech.",
  },
  {
    id: "ko-b2-news-002",
    level: "B2",
    deck: "news",
    en: "Controversy / dispute",
    ko: "논란",
    roman: "nollan",
    exampleKo: "그 발언이 큰 논란을 일으켰어요.",
    exampleEn: "That remark sparked a big controversy.",
    note: "논란을 일으키다 = 'to spark controversy,' a very common collocation.",
  },
  {
    id: "ko-b2-news-003",
    level: "B2",
    deck: "news",
    en: "Public opinion / sentiment",
    ko: "여론",
    roman: "yeoron",
    exampleKo: "여론이 정부에 등을 돌리고 있어요.",
    exampleEn: "Public opinion is turning against the government.",
    note: "등을 돌리다 = 'to turn one's back on.' Newsy idiom.",
  },
  {
    id: "ko-b2-news-004",
    level: "B2",
    deck: "news",
    en: "Policy",
    ko: "정책",
    roman: "jeongchaek",
    exampleKo: "새 부동산 정책이 다음 달부터 시행돼요.",
    exampleEn: "The new real estate policy takes effect next month.",
    note: "시행되다 = 'to be put into effect / enforced.'",
  },
  {
    id: "ko-b2-news-005",
    level: "B2",
    deck: "news",
    en: "It is expected that... / forecast",
    ko: "전망이에요",
    roman: "jeonmangieyo",
    exampleKo: "올해 경제가 회복될 전망이에요.",
    exampleEn: "The economy is expected to recover this year.",
    note: "...ㄹ 전망이에요 = 'is forecast to.' Common in news writing.",
  },
  {
    id: "ko-b2-news-006",
    level: "B2",
    deck: "news",
    en: "Pros and cons / mixed reactions",
    ko: "찬반이 갈리다",
    roman: "chanbani gallida",
    exampleKo: "이 법안을 두고 찬반이 갈리고 있어요.",
    exampleEn: "Opinions are split for and against this bill.",
    note: "찬반 = for/against; ...을 두고 = 'over (an issue).'",
  },
  {
    id: "ko-b2-news-007",
    level: "B2",
    deck: "news",
    en: "To be on the rise / increasing trend",
    ko: "증가하는 추세예요",
    roman: "jeunggahaneun chuseyeyo",
    exampleKo: "1인 가구가 꾸준히 증가하는 추세예요.",
    exampleEn: "Single-person households are steadily on the rise.",
    note: "추세 = trend; pairs with 증가/감소하는 to describe directions.",
  },
  {
    id: "ko-b2-news-008",
    level: "B2",
    deck: "news",
    en: "Authorities / the relevant agency",
    ko: "당국",
    roman: "dangguk",
    exampleKo: "방역 당국이 새 지침을 발표했어요.",
    exampleEn: "The health authorities announced new guidelines.",
    note: "Formal news word for 'the authorities.' 발표하다 = to announce.",
  },
  {
    id: "ko-b2-news-009",
    level: "B2",
    deck: "news",
    en: "Aftermath / repercussions",
    ko: "여파",
    roman: "yeopa",
    exampleKo: "경기 침체의 여파로 실업률이 올랐어요.",
    exampleEn: "Unemployment rose in the aftermath of the recession.",
    note: "...의 여파로 = 'as a repercussion of.' Often follows a crisis word.",
  },
  {
    id: "ko-b2-news-010",
    level: "B2",
    deck: "news",
    en: "To raise an issue / point out a problem",
    ko: "문제를 제기하다",
    roman: "munjereul jegihada",
    exampleKo: "시민 단체가 안전 문제를 제기했어요.",
    exampleEn: "A civic group raised a safety concern.",
    note: "제기하다 = 'to raise (an objection, issue, lawsuit).' Formal.",
  },
  {
    id: "ko-b2-news-011",
    level: "B2",
    deck: "news",
    en: "It turns out that... / it was revealed",
    ko: "밝혀졌어요",
    roman: "balkyeojyeosseoyo",
    exampleKo: "조사 결과 원인이 인재로 밝혀졌어요.",
    exampleEn: "The investigation revealed the cause was human error.",
    note: "밝혀지다 = 'to come to light.' 인재 = man-made disaster.",
  },

  // ── environment (환경) ──
  {
    id: "ko-b2-environment-001",
    level: "B2",
    deck: "environment",
    en: "Climate change",
    ko: "기후 변화",
    roman: "gihu byeonhwa",
    exampleKo: "기후 변화가 갈수록 심각해지고 있어요.",
    exampleEn: "Climate change is getting more serious over time.",
    note: "갈수록 = 'increasingly / as time goes on.'",
  },
  {
    id: "ko-b2-environment-002",
    level: "B2",
    deck: "environment",
    en: "Global warming",
    ko: "지구 온난화",
    roman: "jigu onnanhwa",
    exampleKo: "지구 온난화로 해수면이 상승하고 있어요.",
    exampleEn: "Sea levels are rising due to global warming.",
    note: "해수면 상승 = 'sea-level rise,' a set phrase in climate talk.",
  },
  {
    id: "ko-b2-environment-003",
    level: "B2",
    deck: "environment",
    en: "Fine dust / air pollution",
    ko: "미세먼지",
    roman: "misemeonji",
    exampleKo: "오늘은 미세먼지가 심해서 마스크를 썼어요.",
    exampleEn: "The fine dust was bad today, so I wore a mask.",
    note: "A daily-life concern in Korea; 미세먼지 농도 = dust concentration level.",
  },
  {
    id: "ko-b2-environment-004",
    level: "B2",
    deck: "environment",
    en: "Recycling / separating waste",
    ko: "분리수거",
    roman: "bullisugeo",
    exampleKo: "한국에서는 분리수거를 철저히 해야 해요.",
    exampleEn: "In Korea you have to sort your recycling thoroughly.",
    note: "분리수거 specifically = separating trash for recycling. 철저히 = thoroughly.",
  },
  {
    id: "ko-b2-environment-005",
    level: "B2",
    deck: "environment",
    en: "Sustainable / eco-friendly",
    ko: "친환경",
    roman: "chinhwangyeong",
    exampleKo: "요즘 친환경 제품을 찾는 사람이 많아요.",
    exampleEn: "Lately many people look for eco-friendly products.",
    note: "친환경 attaches to nouns: 친환경 에너지, 친환경 포장 (packaging).",
  },
  {
    id: "ko-b2-environment-006",
    level: "B2",
    deck: "environment",
    en: "Carbon emissions",
    ko: "탄소 배출",
    roman: "tanso baechul",
    exampleKo: "정부가 탄소 배출을 줄이기로 했어요.",
    exampleEn: "The government decided to cut carbon emissions.",
    note: "탄소 배출량 = emission volume; 배출을 줄이다 = to reduce emissions.",
  },
  {
    id: "ko-b2-environment-007",
    level: "B2",
    deck: "environment",
    en: "Single-use / disposable items",
    ko: "일회용품",
    roman: "ilhoeyongpum",
    exampleKo: "카페에서 일회용품 사용이 제한됐어요.",
    exampleEn: "The use of disposables was restricted in cafes.",
    note: "제한되다 = 'to be restricted.' A real Korean policy topic.",
  },
  {
    id: "ko-b2-environment-008",
    level: "B2",
    deck: "environment",
    en: "Renewable energy",
    ko: "재생 에너지",
    roman: "jaesaeng eneoji",
    exampleKo: "태양광 같은 재생 에너지가 점점 늘고 있어요.",
    exampleEn: "Renewable energy like solar power is steadily growing.",
    note: "태양광 = solar; 풍력 = wind power. 점점 = gradually.",
  },
  {
    id: "ko-b2-environment-009",
    level: "B2",
    deck: "environment",
    en: "Environmental pollution",
    ko: "환경 오염",
    roman: "hwangyeong oyeom",
    exampleKo: "플라스틱이 환경 오염의 주범이에요.",
    exampleEn: "Plastic is a main culprit of environmental pollution.",
    note: "주범 = 'main culprit,' a vivid but common figurative word.",
  },
  {
    id: "ko-b2-environment-010",
    level: "B2",
    deck: "environment",
    en: "To practice / put into practice",
    ko: "실천하다",
    roman: "silcheonhada",
    exampleKo: "작은 일이라도 직접 실천하는 게 중요해요.",
    exampleEn: "It's important to actually practice it, even small things.",
    note: "실천 = turning intentions into action. Common in eco messaging.",
  },
  {
    id: "ko-b2-environment-011",
    level: "B2",
    deck: "environment",
    en: "Conservation / protection",
    ko: "보호",
    roman: "boho",
    exampleKo: "멸종 위기 동물 보호가 시급해요.",
    exampleEn: "Protecting endangered animals is urgent.",
    note: "멸종 위기 = endangered; 시급하다 = to be urgent/pressing.",
  },

  // ── technology (기술·디지털) ──
  {
    id: "ko-b2-technology-001",
    level: "B2",
    deck: "technology",
    en: "Artificial intelligence (AI)",
    ko: "인공지능",
    roman: "ingongjineung",
    exampleKo: "인공지능이 우리 일자리를 바꾸고 있어요.",
    exampleEn: "AI is changing our jobs.",
    note: "Often shortened to the English-letter 'AI' in speech too.",
  },
  {
    id: "ko-b2-technology-002",
    level: "B2",
    deck: "technology",
    en: "Personal data / privacy",
    ko: "개인정보",
    roman: "gaeinjeongbo",
    exampleKo: "개인정보 유출 사고가 또 일어났어요.",
    exampleEn: "There was another personal data leak.",
    note: "유출 = leak; 개인정보 보호 = data protection/privacy.",
  },
  {
    id: "ko-b2-technology-003",
    level: "B2",
    deck: "technology",
    en: "To be convenient / handy",
    ko: "편리하다",
    roman: "pyeollihada",
    exampleKo: "모바일 결제가 정말 편리해졌어요.",
    exampleEn: "Mobile payments have become really convenient.",
    note: "편리하다 (convenient/useful) vs 편하다 (comfortable). Tech tends to use 편리하다.",
  },
  {
    id: "ko-b2-technology-004",
    level: "B2",
    deck: "technology",
    en: "Side effect / downside",
    ko: "부작용",
    roman: "bujagyong",
    exampleKo: "기술 발전에는 부작용도 따라와요.",
    exampleEn: "Technological progress comes with downsides too.",
    note: "Originally 'medical side effect,' now used for any negative by-product.",
  },
  {
    id: "ko-b2-technology-005",
    level: "B2",
    deck: "technology",
    en: "To depend on / be reliant on",
    ko: "의존하다",
    roman: "uijonhada",
    exampleKo: "우리는 스마트폰에 너무 의존하는 것 같아요.",
    exampleEn: "I think we rely on smartphones too much.",
    note: "...에 의존하다 = 'to depend on.' 의존도 = degree of dependence.",
  },
  {
    id: "ko-b2-technology-006",
    level: "B2",
    deck: "technology",
    en: "To replace / take the place of",
    ko: "대체하다",
    roman: "daechehada",
    exampleKo: "기계가 사람을 완전히 대체하기는 어려워요.",
    exampleEn: "It's hard for machines to completely replace people.",
    note: "대체하다 = 'to substitute / replace.' 대체 인력 = replacement workforce.",
  },
  {
    id: "ko-b2-technology-007",
    level: "B2",
    deck: "technology",
    en: "The digital divide / information gap",
    ko: "정보 격차",
    roman: "jeongbo gyeokcha",
    exampleKo: "노인층의 정보 격차가 점점 커지고 있어요.",
    exampleEn: "The information gap for older people keeps widening.",
    note: "격차 = gap/disparity; also 빈부 격차 = wealth gap.",
  },
  {
    id: "ko-b2-technology-008",
    level: "B2",
    deck: "technology",
    en: "To innovate / cutting-edge",
    ko: "혁신적이다",
    roman: "hyeoksinjeogida",
    exampleKo: "그 회사의 기술은 정말 혁신적이에요.",
    exampleEn: "That company's technology is truly innovative.",
    note: "혁신 = innovation; 혁신적인 + noun = innovative.",
  },
  {
    id: "ko-b2-technology-009",
    level: "B2",
    deck: "technology",
    en: "Fake news / misinformation",
    ko: "가짜 뉴스",
    roman: "gajja nyuseu",
    exampleKo: "온라인에 가짜 뉴스가 빠르게 퍼져요.",
    exampleEn: "Fake news spreads fast online.",
    note: "퍼지다 = to spread; 가짜 = fake (vs 진짜 = real).",
  },
  {
    id: "ko-b2-technology-010",
    level: "B2",
    deck: "technology",
    en: "Automation",
    ko: "자동화",
    roman: "jadonghwa",
    exampleKo: "공장 자동화로 생산성이 크게 올랐어요.",
    exampleEn: "Factory automation greatly raised productivity.",
    note: "-화 = '-ization' suffix: 자동화, 디지털화, 세계화 (globalization).",
  },
  {
    id: "ko-b2-technology-011",
    level: "B2",
    deck: "technology",
    en: "To keep up with / catch up to",
    ko: "따라가다",
    roman: "ttaragada",
    exampleKo: "기술 변화 속도를 따라가기가 벅차요.",
    exampleEn: "It's overwhelming to keep up with the pace of tech change.",
    note: "벅차다 = 'to be overwhelming / more than one can handle.'",
  },

  // ── culture (문화·예술) ──
  {
    id: "ko-b2-culture-001",
    level: "B2",
    deck: "culture",
    en: "Traditional culture",
    ko: "전통 문화",
    roman: "jeontong munhwa",
    exampleKo: "한국의 전통 문화에 관심이 많아요.",
    exampleEn: "I'm very interested in Korean traditional culture.",
    note: "전통 = tradition; 전통적인 + noun = traditional.",
  },
  {
    id: "ko-b2-culture-002",
    level: "B2",
    deck: "culture",
    en: "Pop culture / mass culture",
    ko: "대중문화",
    roman: "daejung munhwa",
    exampleKo: "한국 대중문화가 전 세계로 퍼지고 있어요.",
    exampleEn: "Korean pop culture is spreading worldwide.",
    note: "대중 = the masses/public; the 'K' in K-pop is this 대중문화.",
  },
  {
    id: "ko-b2-culture-003",
    level: "B2",
    deck: "culture",
    en: "To be moved / touched (emotionally)",
    ko: "감동을 받다",
    roman: "gamdongeul batda",
    exampleKo: "그 영화의 결말에 큰 감동을 받았어요.",
    exampleEn: "I was deeply moved by the film's ending.",
    note: "감동 = moving emotion; 감동적이다 = to be moving/touching.",
  },
  {
    id: "ko-b2-culture-004",
    level: "B2",
    deck: "culture",
    en: "Exhibition",
    ko: "전시회",
    roman: "jeonsihoe",
    exampleKo: "주말에 사진 전시회를 보러 갔어요.",
    exampleEn: "I went to a photography exhibition over the weekend.",
    note: "전시 = display/exhibit; 전시회 = the exhibition event.",
  },
  {
    id: "ko-b2-culture-005",
    level: "B2",
    deck: "culture",
    en: "Performance / show",
    ko: "공연",
    roman: "gongyeon",
    exampleKo: "어제 본 공연이 정말 인상 깊었어요.",
    exampleEn: "The performance I saw yesterday was really impressive.",
    note: "인상 깊다 = 'to leave a deep impression.' Great for reviews.",
  },
  {
    id: "ko-b2-culture-006",
    level: "B2",
    deck: "culture",
    en: "Work (of art) / piece",
    ko: "작품",
    roman: "jakpum",
    exampleKo: "이 작품은 작가의 개성이 잘 드러나요.",
    exampleEn: "This piece clearly shows the artist's individuality.",
    note: "작품 = a created work (film, novel, painting); 작가 = creator/author.",
  },
  {
    id: "ko-b2-culture-007",
    level: "B2",
    deck: "culture",
    en: "Taste / preference",
    ko: "취향",
    roman: "chwihyang",
    exampleKo: "음악 취향이 저랑 잘 맞네요.",
    exampleEn: "Your taste in music really matches mine.",
    note: "취향이 맞다 = 'tastes align.' 취향 저격 (slang) = right up my alley.",
  },
  {
    id: "ko-b2-culture-008",
    level: "B2",
    deck: "culture",
    en: "To be worth (doing) / worthwhile",
    ko: "...ㄹ 만하다",
    roman: "...l manhada",
    exampleKo: "그 전시는 한번 가 볼 만해요.",
    exampleEn: "That exhibition is worth checking out.",
    note: "Verb stem + -ㄹ/을 만하다 = 'worth doing.' Very natural in recommendations.",
  },
  {
    id: "ko-b2-culture-009",
    level: "B2",
    deck: "culture",
    en: "Trend / a craze",
    ko: "유행",
    roman: "yuhaeng",
    exampleKo: "복고풍이 다시 유행이에요.",
    exampleEn: "The retro style is in fashion again.",
    note: "유행하다 = to be trendy; 복고풍 = retro style.",
  },
  {
    id: "ko-b2-culture-010",
    level: "B2",
    deck: "culture",
    en: "To have an eye for / be discerning",
    ko: "안목이 있다",
    roman: "anmogi itda",
    exampleKo: "그분은 예술에 안목이 있으세요.",
    exampleEn: "She has a discerning eye for art.",
    note: "안목 = a trained, perceptive eye for quality. A compliment.",
  },
  {
    id: "ko-b2-culture-011",
    level: "B2",
    deck: "culture",
    en: "To be passed down / handed down",
    ko: "전해 내려오다",
    roman: "jeonhae naeryeooda",
    exampleKo: "이 풍습은 오래전부터 전해 내려왔어요.",
    exampleEn: "This custom has been handed down from long ago.",
    note: "풍습 = custom; used for traditions, legends, recipes across generations.",
  },
];
