/**
 * B2 (중상급) 한국어 학습 콘텐츠 — 영어권 학습자 대상.
 * 각 카드: 한국어 표현(ko) + 로마자(roman) + 영어 뜻(en) + 예문(한/영).
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * note 는 영어(학습자 모국어)로 사용 맥락을 설명한다.
 *
 * B2 수준: 의견·감정을 한국어로 표현, 추상적 주제(뉴스·환경·기술·문화),
 * 격식/비격식 구분, 관용적 연결어. 토론·시사 맥락의 표현 중심.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_B2_DECKS: Deck[] = [
  {
    id: "opinion",
    level: "B2",
    title: {
      ko: "의견·토론",
      en: "Opinions & Discussion",
      zh: "观点·讨论",
      vi: "Quan điểm · Thảo luận",
    },
    description: {
      ko: "주장·반박·동의·근거 제시",
      en: "Stating, supporting, and challenging views",
      zh: "主张、反驳、赞同、提出依据",
      vi: "Đưa ra lập luận, phản bác, đồng ý, dẫn chứng",
    },
    order: 1,
    icon: "MessagesSquare",
  },
  {
    id: "news",
    level: "B2",
    title: {
      ko: "뉴스·시사",
      en: "News & Current Affairs",
      zh: "新闻·时事",
      vi: "Tin tức · Thời sự",
    },
    description: {
      ko: "보도·정책·여론·논란",
      en: "Reporting, policy, and public debate",
      zh: "报道、政策、舆论、争议",
      vi: "Đưa tin, chính sách, dư luận, tranh cãi",
    },
    order: 2,
    icon: "Newspaper",
  },
  {
    id: "environment",
    level: "B2",
    title: { ko: "환경", en: "Environment", zh: "环境", vi: "Môi trường" },
    description: {
      ko: "기후·오염·지속가능성",
      en: "Climate, pollution, and sustainability",
      zh: "气候、污染、可持续性",
      vi: "Khí hậu, ô nhiễm, tính bền vững",
    },
    order: 3,
    icon: "Leaf",
  },
  {
    id: "technology",
    level: "B2",
    title: {
      ko: "기술·디지털",
      en: "Technology",
      zh: "技术·数字",
      vi: "Công nghệ · Kỹ thuật số",
    },
    description: {
      ko: "인공지능·데이터·온라인 생활",
      en: "AI, data, and digital life",
      zh: "人工智能、数据、在线生活",
      vi: "Trí tuệ nhân tạo, dữ liệu, cuộc sống trực tuyến",
    },
    order: 4,
    icon: "Cpu",
  },
  {
    id: "culture",
    level: "B2",
    title: {
      ko: "문화·예술",
      en: "Culture & Arts",
      zh: "文化·艺术",
      vi: "Văn hóa · Nghệ thuật",
    },
    description: {
      ko: "전통·대중문화·전시·공연",
      en: "Tradition, pop culture, and the arts",
      zh: "传统、大众文化、展览、演出",
      vi: "Truyền thống, văn hóa đại chúng, triển lãm, biểu diễn",
    },
    order: 5,
    icon: "Palette",
  },
];

export const KO_B2_CARDS: VocabCard[] = [
  // ── opinion (의견·토론) ──
  {
    id: "ko-b2-opinion-001",
    level: "B2",
    deck: "opinion",
    en: "In my opinion / From my point of view",
    zh: "在我看来／依我看",
    vi: "Theo tôi nghĩ / Theo quan điểm của tôi",
    ko: "제 생각에는",
    roman: "je saenggageneun",
    exampleKo: "제 생각에는 그 정책이 효과가 없을 것 같아요.",
    exampleEn: "In my opinion, that policy probably won't work.",
    exampleZh: "在我看来，那项政策恐怕不会有效果。",
    exampleVi: "Theo tôi nghĩ, chính sách đó có lẽ sẽ không hiệu quả.",
    note: "Polite, neutral way to open an opinion. Softer than 제가 보기에는.",
    noteZh: "礼貌、中性地引出观点的说法，比 제가 보기에는 更委婉。",
    noteVi: "Cách mở đầu ý kiến lịch sự, trung tính. Nhẹ nhàng hơn 제가 보기에는.",
  },
  {
    id: "ko-b2-opinion-002",
    level: "B2",
    deck: "opinion",
    en: "To be honest / Frankly",
    zh: "老实说／坦白讲",
    vi: "Thành thật mà nói / Nói thẳng ra",
    ko: "솔직히 말하면",
    roman: "soljiki malhamyeon",
    exampleKo: "솔직히 말하면 저는 그 의견에 반대해요.",
    exampleEn: "To be honest, I disagree with that view.",
    exampleZh: "老实说，我反对那个意见。",
    exampleVi: "Thành thật mà nói, tôi phản đối ý kiến đó.",
    note: "Signals a candid, slightly stronger opinion is coming.",
    noteZh: "预示接下来要说一个坦率、语气略强的观点。",
    noteVi: "Báo hiệu sắp đưa ra một ý kiến thẳng thắn, có phần mạnh mẽ hơn.",
  },
  {
    id: "ko-b2-opinion-003",
    level: "B2",
    deck: "opinion",
    en: "I (partly) agree, but...",
    zh: "我（部分）同意，但……",
    vi: "Tôi đồng ý ở một mức độ nào đó, nhưng...",
    ko: "어느 정도 동의하지만",
    roman: "eoneu jeongdo donguihajiman",
    exampleKo: "어느 정도 동의하지만 현실적으로는 어려워요.",
    exampleEn: "I agree to some extent, but realistically it's difficult.",
    exampleZh: "在一定程度上我同意，但现实中很难做到。",
    exampleVi: "Tôi đồng ý ở một mức độ nào đó, nhưng trên thực tế thì khó thực hiện.",
    note: "Diplomatic partial agreement before raising a counterpoint.",
    noteZh: "在提出反驳之前，先婉转地部分表示同意。",
    noteVi: "Đồng ý một phần một cách khéo léo trước khi đưa ra phản biện.",
  },
  {
    id: "ko-b2-opinion-004",
    level: "B2",
    deck: "opinion",
    en: "That makes sense, but...",
    zh: "有道理，但……",
    vi: "Nghe cũng có lý, nhưng...",
    ko: "일리가 있지만",
    roman: "illiga itjiman",
    exampleKo: "그 말도 일리가 있지만 부작용도 생각해야 해요.",
    exampleEn: "That point has merit, but we have to consider the side effects.",
    exampleZh: "那话也有道理，但也得考虑副作用。",
    exampleVi: "Lời đó cũng có lý, nhưng phải xem xét cả tác dụng phụ nữa.",
    note: "일리가 있다 = 'has a point / is reasonable.' Common in debate.",
    noteZh: "일리가 있다 = “有道理／说得在理”，辩论中常用。",
    noteVi: "일리가 있다 = “có lý / hợp lý”. Thường dùng khi tranh luận.",
  },
  {
    id: "ko-b2-opinion-005",
    level: "B2",
    deck: "opinion",
    en: "On the other hand",
    zh: "另一方面",
    vi: "Mặt khác",
    ko: "반면에",
    roman: "banmyeone",
    exampleKo: "비용은 줄지만 반면에 품질이 떨어질 수 있어요.",
    exampleEn: "Costs go down, but on the other hand quality may drop.",
    exampleZh: "成本会降低，但另一方面质量可能会下降。",
    exampleVi: "Chi phí giảm, nhưng mặt khác chất lượng có thể giảm sút.",
    note: "Formal connector for contrasting two sides of an argument.",
    noteZh: "较正式的连接词，用于对比论点的两个方面。",
    noteVi: "Từ nối trang trọng dùng để đối chiếu hai mặt của một lập luận.",
  },
  {
    id: "ko-b2-opinion-006",
    level: "B2",
    deck: "opinion",
    en: "The reason is that...",
    zh: "原因在于……",
    vi: "Lý do là...",
    ko: "그 이유는",
    roman: "geu iyuneun",
    exampleKo: "제가 반대하는 그 이유는 비용 때문이에요.",
    exampleEn: "The reason I'm opposed is the cost.",
    exampleZh: "我反对的原因是成本问题。",
    exampleVi: "Lý do tôi phản đối là vì chi phí.",
    note: "Introduces your grounds; often paired with ...때문이에요.",
    noteZh: "用来引出理由，常与 ……때문이에요 搭配。",
    noteVi: "Dùng để đưa ra căn cứ của mình; thường đi kèm với ...때문이에요.",
  },
  {
    id: "ko-b2-opinion-007",
    level: "B2",
    deck: "opinion",
    en: "I don't think so",
    zh: "我不这么认为",
    vi: "Tôi không nghĩ vậy",
    ko: "그렇게 생각하지 않아요",
    roman: "geureoke saenggakaji anayo",
    exampleKo: "저는 그렇게 생각하지 않아요. 근거가 부족해요.",
    exampleEn: "I don't think so. There isn't enough evidence.",
    exampleZh: "我不这么认为，依据不足。",
    exampleVi: "Tôi không nghĩ vậy. Căn cứ chưa đủ thuyết phục.",
    note: "Polite disagreement, softer than a flat 아니에요.",
    noteZh: "礼貌地表示不同意，比直接说 아니에요 更委婉。",
    noteVi: "Cách bày tỏ không đồng ý một cách lịch sự, nhẹ nhàng hơn so với nói thẳng 아니에요.",
  },
  {
    id: "ko-b2-opinion-008",
    level: "B2",
    deck: "opinion",
    en: "Strictly speaking",
    zh: "严格来说",
    vi: "Nói chính xác thì / Xét cho kỹ thì",
    ko: "엄밀히 따지면",
    roman: "eommilhi ttajimyeon",
    exampleKo: "엄밀히 따지면 그건 사실과 조금 달라요.",
    exampleEn: "Strictly speaking, that's a little different from the facts.",
    exampleZh: "严格来说，那和事实略有出入。",
    exampleVi: "Xét cho kỹ thì, điều đó hơi khác so với sự thật.",
    note: "Signals you're about to make a precise, careful distinction.",
    noteZh: "预示你要做一个精确、审慎的区分。",
    noteVi: "Báo hiệu bạn sắp đưa ra một sự phân biệt chính xác, cẩn trọng.",
  },
  {
    id: "ko-b2-opinion-009",
    level: "B2",
    deck: "opinion",
    en: "That's a matter of opinion / It depends on the person",
    zh: "这因人而异",
    vi: "Cái đó thì tùy người thôi",
    ko: "사람마다 다르죠",
    roman: "sarammada dareujyo",
    exampleKo: "취향은 사람마다 다르죠.",
    exampleEn: "Taste differs from person to person.",
    exampleZh: "口味因人而异嘛。",
    exampleVi: "Sở thích thì tùy mỗi người mà khác nhau.",
    note: "Neutral way to acknowledge there's no single right answer.",
    noteZh: "中性地承认没有唯一正确答案的说法。",
    noteVi: "Cách nói trung lập để thừa nhận rằng không có câu trả lời đúng duy nhất.",
  },
  {
    id: "ko-b2-opinion-010",
    level: "B2",
    deck: "opinion",
    en: "To sum up / In short",
    zh: "总而言之／归根结底",
    vi: "Kết luận lại / Tóm lại",
    ko: "결론적으로",
    roman: "gyeollonjeogeuro",
    exampleKo: "결론적으로 저는 찬성하는 입장이에요.",
    exampleEn: "In conclusion, I'm in favor.",
    exampleZh: "总而言之，我持赞成的立场。",
    exampleVi: "Kết luận lại, tôi đứng về phía ủng hộ.",
    note: "Formal closer for wrapping up an argument. 입장 = stance.",
    noteZh: "正式地收束论点的结语。입장 = 立场。",
    noteVi: "Cách kết thúc trang trọng để tổng kết lập luận. 입장 = lập trường.",
  },
  {
    id: "ko-b2-opinion-011",
    level: "B2",
    deck: "opinion",
    en: "Needless to say / It goes without saying",
    zh: "不用说／不言而喻",
    vi: "Không cần phải nói / Dĩ nhiên là",
    ko: "말할 것도 없이",
    roman: "malhal geotdo eopsi",
    exampleKo: "말할 것도 없이 안전이 가장 중요해요.",
    exampleEn: "Needless to say, safety is the most important thing.",
    exampleZh: "不用说，安全是最重要的。",
    exampleVi: "Không cần phải nói, an toàn là điều quan trọng nhất.",
    note: "Emphasizes something you treat as obvious or beyond dispute.",
    noteZh: "强调某事显而易见、无可争议。",
    noteVi: "Nhấn mạnh điều mà bạn cho là hiển nhiên, không cần bàn cãi.",
  },
  {
    id: "ko-b2-opinion-012",
    level: "B2",
    deck: "opinion",
    en: "If anything / Rather",
    zh: "反倒／反而",
    vi: "Ngược lại / Trái lại",
    ko: "오히려",
    roman: "ohiryeo",
    exampleKo: "규제가 오히려 시장을 망칠 수도 있어요.",
    exampleEn: "Regulation could, if anything, ruin the market.",
    exampleZh: "监管反而可能毁掉市场。",
    exampleVi: "Quy định ngược lại có thể làm hỏng thị trường.",
    note: "Flags a counter-intuitive turn — 'the opposite of what you'd expect.'",
    noteZh: "引出出人意料的转折——“与你预期的相反”。",
    noteVi: "Báo hiệu một bước ngoặt trái ngược dự đoán — “ngược lại với những gì bạn nghĩ”.",
  },

  // ── news (뉴스·시사) ──
  {
    id: "ko-b2-news-001",
    level: "B2",
    deck: "news",
    en: "According to the report / news",
    zh: "据报道",
    vi: "Theo báo cáo / Theo tin đưa",
    ko: "보도에 따르면",
    roman: "bodoe ttareumyeon",
    exampleKo: "보도에 따르면 물가가 다시 올랐다고 해요.",
    exampleEn: "According to the report, prices have risen again.",
    exampleZh: "据报道，物价又上涨了。",
    exampleVi: "Theo tin đưa, giá cả lại tăng lên.",
    note: "Standard journalistic phrase to cite a source. -다고 해요 = reported speech.",
    noteZh: "引用消息来源的标准新闻用语。-다고 해요 = 转述他人的话。",
    noteVi: "Cụm từ báo chí chuẩn để trích dẫn nguồn tin. -다고 해요 = lời nói tường thuật/gián tiếp.",
  },
  {
    id: "ko-b2-news-002",
    level: "B2",
    deck: "news",
    en: "Controversy / dispute",
    zh: "争议",
    vi: "Tranh cãi",
    ko: "논란",
    roman: "nollan",
    exampleKo: "그 발언이 큰 논란을 일으켰어요.",
    exampleEn: "That remark sparked a big controversy.",
    exampleZh: "那番言论引发了很大的争议。",
    exampleVi: "Phát ngôn đó đã gây ra tranh cãi lớn.",
    note: "논란을 일으키다 = 'to spark controversy,' a very common collocation.",
    noteZh: "논란을 일으키다 = “引发争议”，非常常见的搭配。",
    noteVi: "논란을 일으키다 = “gây ra tranh cãi”, cách kết hợp từ rất thường dùng.",
  },
  {
    id: "ko-b2-news-003",
    level: "B2",
    deck: "news",
    en: "Public opinion / sentiment",
    zh: "舆论／民意",
    vi: "Dư luận",
    ko: "여론",
    roman: "yeoron",
    exampleKo: "여론이 정부에 등을 돌리고 있어요.",
    exampleEn: "Public opinion is turning against the government.",
    exampleZh: "舆论正在背离政府。",
    exampleVi: "Dư luận đang quay lưng lại với chính phủ.",
    note: "등을 돌리다 = 'to turn one's back on.' Newsy idiom.",
    noteZh: "등을 돌리다 = “转身背离／抛弃”，新闻常用的惯用语。",
    noteVi: "등을 돌리다 = “quay lưng lại với”. Thành ngữ thường dùng trong tin tức.",
  },
  {
    id: "ko-b2-news-004",
    level: "B2",
    deck: "news",
    en: "Policy",
    zh: "政策",
    vi: "Chính sách",
    ko: "정책",
    roman: "jeongchaek",
    exampleKo: "새 부동산 정책이 다음 달부터 시행돼요.",
    exampleEn: "The new real estate policy takes effect next month.",
    exampleZh: "新的房地产政策从下个月开始实施。",
    exampleVi: "Chính sách bất động sản mới sẽ có hiệu lực từ tháng sau.",
    note: "시행되다 = 'to be put into effect / enforced.'",
    noteZh: "시행되다 = “开始实施／施行”。",
    noteVi: "시행되다 = “được thi hành / có hiệu lực”.",
  },
  {
    id: "ko-b2-news-005",
    level: "B2",
    deck: "news",
    en: "It is expected that... / forecast",
    zh: "预计……",
    vi: "Dự kiến là...",
    ko: "전망이에요",
    roman: "jeonmangieyo",
    exampleKo: "올해 경제가 회복될 전망이에요.",
    exampleEn: "The economy is expected to recover this year.",
    exampleZh: "预计今年经济会复苏。",
    exampleVi: "Dự kiến kinh tế năm nay sẽ phục hồi.",
    note: "...ㄹ 전망이에요 = 'is forecast to.' Common in news writing.",
    noteZh: "……ㄹ 전망이에요 = “预计会……”，新闻报道中常见。",
    noteVi: "...ㄹ 전망이에요 = “được dự báo sẽ...”. Thường dùng trong văn phong báo chí.",
  },
  {
    id: "ko-b2-news-006",
    level: "B2",
    deck: "news",
    en: "Pros and cons / mixed reactions",
    zh: "赞成与反对意见分歧",
    vi: "Ý kiến chia rẽ giữa tán thành và phản đối",
    ko: "찬반이 갈리다",
    roman: "chanbani gallida",
    exampleKo: "이 법안을 두고 찬반이 갈리고 있어요.",
    exampleEn: "Opinions are split for and against this bill.",
    exampleZh: "围绕这项法案，赞成与反对意见不一。",
    exampleVi: "Ý kiến đang chia rẽ giữa tán thành và phản đối xoay quanh dự luật này.",
    note: "찬반 = for/against; ...을 두고 = 'over (an issue).'",
    noteZh: "찬반 = 赞成与反对；……을 두고 = “围绕（某议题）”。",
    noteVi: "찬반 = tán thành/phản đối; ...을 두고 = “xoay quanh (một vấn đề)”.",
  },
  {
    id: "ko-b2-news-007",
    level: "B2",
    deck: "news",
    en: "To be on the rise / increasing trend",
    zh: "呈上升趋势",
    vi: "Đang có xu hướng tăng",
    ko: "증가하는 추세예요",
    roman: "jeunggahaneun chuseyeyo",
    exampleKo: "1인 가구가 꾸준히 증가하는 추세예요.",
    exampleEn: "Single-person households are steadily on the rise.",
    exampleZh: "单人家庭呈持续上升的趋势。",
    exampleVi: "Hộ gia đình một người đang có xu hướng tăng đều đặn.",
    note: "추세 = trend; pairs with 증가/감소하는 to describe directions.",
    noteZh: "추세 = 趋势；与 증가/감소하는 搭配描述走向。",
    noteVi: "추세 = xu hướng; kết hợp với 증가/감소하는 để diễn tả chiều hướng.",
  },
  {
    id: "ko-b2-news-008",
    level: "B2",
    deck: "news",
    en: "Authorities / the relevant agency",
    zh: "当局／有关部门",
    vi: "Nhà chức trách / Cơ quan có thẩm quyền",
    ko: "당국",
    roman: "dangguk",
    exampleKo: "방역 당국이 새 지침을 발표했어요.",
    exampleEn: "The health authorities announced new guidelines.",
    exampleZh: "防疫当局发布了新的指南。",
    exampleVi: "Nhà chức trách phòng dịch đã công bố hướng dẫn mới.",
    note: "Formal news word for 'the authorities.' 발표하다 = to announce.",
    noteZh: "新闻中表示“当局”的正式用词。발표하다 = 发布／宣布。",
    noteVi: "Từ trang trọng trong tin tức chỉ “nhà chức trách”. 발표하다 = công bố/thông báo.",
  },
  {
    id: "ko-b2-news-009",
    level: "B2",
    deck: "news",
    en: "Aftermath / repercussions",
    zh: "余波／影响",
    vi: "Dư chấn / Hệ lụy",
    ko: "여파",
    roman: "yeopa",
    exampleKo: "경기 침체의 여파로 실업률이 올랐어요.",
    exampleEn: "Unemployment rose in the aftermath of the recession.",
    exampleZh: "受经济衰退余波的影响，失业率上升了。",
    exampleVi: "Do dư chấn của suy thoái kinh tế, tỷ lệ thất nghiệp đã tăng lên.",
    note: "...의 여파로 = 'as a repercussion of.' Often follows a crisis word.",
    noteZh: "……의 여파로 = “受……余波的影响”，常接在表示危机的词之后。",
    noteVi: "...의 여파로 = “do hệ lụy của...”. Thường đi sau một từ chỉ khủng hoảng.",
  },
  {
    id: "ko-b2-news-010",
    level: "B2",
    deck: "news",
    en: "To raise an issue / point out a problem",
    zh: "提出问题／提出质疑",
    vi: "Đặt ra vấn đề / Nêu ra vấn đề",
    ko: "문제를 제기하다",
    roman: "munjereul jegihada",
    exampleKo: "시민 단체가 안전 문제를 제기했어요.",
    exampleEn: "A civic group raised a safety concern.",
    exampleZh: "民间团体提出了安全问题。",
    exampleVi: "Một tổ chức dân sự đã nêu ra vấn đề an toàn.",
    note: "제기하다 = 'to raise (an objection, issue, lawsuit).' Formal.",
    noteZh: "제기하다 = “提出（异议、问题、诉讼）”，较正式。",
    noteVi: "제기하다 = “nêu ra (sự phản đối, vấn đề, vụ kiện)”. Mang tính trang trọng.",
  },
  {
    id: "ko-b2-news-011",
    level: "B2",
    deck: "news",
    en: "It turns out that... / it was revealed",
    zh: "查明／真相大白",
    vi: "Đã được làm sáng tỏ / Hóa ra là...",
    ko: "밝혀졌어요",
    roman: "balkyeojyeosseoyo",
    exampleKo: "조사 결과 원인이 인재로 밝혀졌어요.",
    exampleEn: "The investigation revealed the cause was human error.",
    exampleZh: "调查结果表明，原因是人为事故。",
    exampleVi: "Kết quả điều tra cho thấy nguyên nhân là do lỗi con người.",
    note: "밝혀지다 = 'to come to light.' 인재 = man-made disaster.",
    noteZh: "밝혀지다 = “真相大白／被查明”。인재 = 人为灾难／事故。",
    noteVi: "밝혀지다 = “được phơi bày ra ánh sáng”. 인재 = thảm họa do con người gây ra.",
  },

  // ── environment (환경) ──
  {
    id: "ko-b2-environment-001",
    level: "B2",
    deck: "environment",
    en: "Climate change",
    zh: "气候变化",
    vi: "Biến đổi khí hậu",
    ko: "기후 변화",
    roman: "gihu byeonhwa",
    exampleKo: "기후 변화가 갈수록 심각해지고 있어요.",
    exampleEn: "Climate change is getting more serious over time.",
    exampleZh: "气候变化正变得越来越严重。",
    exampleVi: "Biến đổi khí hậu ngày càng trở nên nghiêm trọng.",
    note: "갈수록 = 'increasingly / as time goes on.'",
    noteZh: "갈수록 = “越来越／随着时间推移”。",
    noteVi: "갈수록 = “ngày càng / theo thời gian”.",
  },
  {
    id: "ko-b2-environment-002",
    level: "B2",
    deck: "environment",
    en: "Global warming",
    zh: "全球变暖",
    vi: "Sự nóng lên toàn cầu",
    ko: "지구 온난화",
    roman: "jigu onnanhwa",
    exampleKo: "지구 온난화로 해수면이 상승하고 있어요.",
    exampleEn: "Sea levels are rising due to global warming.",
    exampleZh: "由于全球变暖，海平面正在上升。",
    exampleVi: "Do sự nóng lên toàn cầu, mực nước biển đang dâng cao.",
    note: "해수면 상승 = 'sea-level rise,' a set phrase in climate talk.",
    noteZh: "해수면 상승 = “海平面上升”，谈气候时的固定说法。",
    noteVi: "해수면 상승 = “mực nước biển dâng”, cụm từ cố định khi nói về khí hậu.",
  },
  {
    id: "ko-b2-environment-003",
    level: "B2",
    deck: "environment",
    en: "Fine dust / air pollution",
    zh: "雾霾／细颗粒物",
    vi: "Bụi mịn",
    ko: "미세먼지",
    roman: "misemeonji",
    exampleKo: "오늘은 미세먼지가 심해서 마스크를 썼어요.",
    exampleEn: "The fine dust was bad today, so I wore a mask.",
    exampleZh: "今天雾霾严重，所以戴了口罩。",
    exampleVi: "Hôm nay bụi mịn nhiều nên tôi đã đeo khẩu trang.",
    note: "A daily-life concern in Korea; 미세먼지 농도 = dust concentration level.",
    noteZh: "在韩国是日常生活中的一大担忧；미세먼지 농도 = 细颗粒物浓度。",
    noteVi: "Một mối lo hàng ngày ở Hàn Quốc; 미세먼지 농도 = nồng độ bụi mịn.",
  },
  {
    id: "ko-b2-environment-004",
    level: "B2",
    deck: "environment",
    en: "Recycling / separating waste",
    zh: "垃圾分类回收",
    vi: "Phân loại rác để tái chế",
    ko: "분리수거",
    roman: "bullisugeo",
    exampleKo: "한국에서는 분리수거를 철저히 해야 해요.",
    exampleEn: "In Korea you have to sort your recycling thoroughly.",
    exampleZh: "在韩国必须彻底做好垃圾分类。",
    exampleVi: "Ở Hàn Quốc phải phân loại rác thật kỹ lưỡng.",
    note: "분리수거 specifically = separating trash for recycling. 철저히 = thoroughly.",
    noteZh: "분리수거 特指为回收而进行的垃圾分类。철저히 = 彻底地。",
    noteVi: "분리수거 cụ thể là việc phân loại rác để tái chế. 철저히 = một cách triệt để/kỹ lưỡng.",
  },
  {
    id: "ko-b2-environment-005",
    level: "B2",
    deck: "environment",
    en: "Sustainable / eco-friendly",
    zh: "环保／绿色环保",
    vi: "Thân thiện với môi trường",
    ko: "친환경",
    roman: "chinhwangyeong",
    exampleKo: "요즘 친환경 제품을 찾는 사람이 많아요.",
    exampleEn: "Lately many people look for eco-friendly products.",
    exampleZh: "最近寻找环保产品的人很多。",
    exampleVi: "Dạo này có nhiều người tìm mua sản phẩm thân thiện với môi trường.",
    note: "친환경 attaches to nouns: 친환경 에너지, 친환경 포장 (packaging).",
    noteZh: "친환경 用于修饰名词：친환경 에너지（环保能源）、친환경 포장（环保包装）。",
    noteVi: "친환경 gắn với danh từ: 친환경 에너지 (năng lượng thân thiện môi trường), 친환경 포장 (bao bì thân thiện môi trường).",
  },
  {
    id: "ko-b2-environment-006",
    level: "B2",
    deck: "environment",
    en: "Carbon emissions",
    zh: "碳排放",
    vi: "Phát thải carbon / Khí thải carbon",
    ko: "탄소 배출",
    roman: "tanso baechul",
    exampleKo: "정부가 탄소 배출을 줄이기로 했어요.",
    exampleEn: "The government decided to cut carbon emissions.",
    exampleZh: "政府决定减少碳排放。",
    exampleVi: "Chính phủ đã quyết định cắt giảm phát thải carbon.",
    note: "탄소 배출량 = emission volume; 배출을 줄이다 = to reduce emissions.",
    noteZh: "탄소 배출량 = 排放量；배출을 줄이다 = 减少排放。",
    noteVi: "탄소 배출량 = lượng phát thải; 배출을 줄이다 = giảm phát thải.",
  },
  {
    id: "ko-b2-environment-007",
    level: "B2",
    deck: "environment",
    en: "Single-use / disposable items",
    zh: "一次性用品",
    vi: "Đồ dùng một lần",
    ko: "일회용품",
    roman: "ilhoeyongpum",
    exampleKo: "카페에서 일회용품 사용이 제한됐어요.",
    exampleEn: "The use of disposables was restricted in cafes.",
    exampleZh: "咖啡店限制了一次性用品的使用。",
    exampleVi: "Việc sử dụng đồ dùng một lần ở quán cà phê đã bị hạn chế.",
    note: "제한되다 = 'to be restricted.' A real Korean policy topic.",
    noteZh: "제한되다 = “被限制”。这是韩国现实中的一个政策话题。",
    noteVi: "제한되다 = “bị hạn chế”. Đây là một chủ đề chính sách có thật ở Hàn Quốc.",
  },
  {
    id: "ko-b2-environment-008",
    level: "B2",
    deck: "environment",
    en: "Renewable energy",
    zh: "可再生能源",
    vi: "Năng lượng tái tạo",
    ko: "재생 에너지",
    roman: "jaesaeng eneoji",
    exampleKo: "태양광 같은 재생 에너지가 점점 늘고 있어요.",
    exampleEn: "Renewable energy like solar power is steadily growing.",
    exampleZh: "像太阳能这样的可再生能源正逐渐增多。",
    exampleVi: "Năng lượng tái tạo như năng lượng mặt trời đang tăng dần lên.",
    note: "태양광 = solar; 풍력 = wind power. 점점 = gradually.",
    noteZh: "태양광 = 太阳能；풍력 = 风能。점점 = 逐渐。",
    noteVi: "태양광 = năng lượng mặt trời; 풍력 = năng lượng gió. 점점 = dần dần.",
  },
  {
    id: "ko-b2-environment-009",
    level: "B2",
    deck: "environment",
    en: "Environmental pollution",
    zh: "环境污染",
    vi: "Ô nhiễm môi trường",
    ko: "환경 오염",
    roman: "hwangyeong oyeom",
    exampleKo: "플라스틱이 환경 오염의 주범이에요.",
    exampleEn: "Plastic is a main culprit of environmental pollution.",
    exampleZh: "塑料是环境污染的罪魁祸首。",
    exampleVi: "Nhựa là thủ phạm chính gây ô nhiễm môi trường.",
    note: "주범 = 'main culprit,' a vivid but common figurative word.",
    noteZh: "주범 = “罪魁祸首”，形象却常用的比喻词。",
    noteVi: "주범 = “thủ phạm chính”, một cách diễn đạt hình ảnh nhưng thường dùng.",
  },
  {
    id: "ko-b2-environment-010",
    level: "B2",
    deck: "environment",
    en: "To practice / put into practice",
    zh: "践行／付诸实践",
    vi: "Thực hành / Hành động thực tế",
    ko: "실천하다",
    roman: "silcheonhada",
    exampleKo: "작은 일이라도 직접 실천하는 게 중요해요.",
    exampleEn: "It's important to actually practice it, even small things.",
    exampleZh: "哪怕是小事，亲自付诸实践也很重要。",
    exampleVi: "Dù là việc nhỏ, tự mình thực hành cũng rất quan trọng.",
    note: "실천 = turning intentions into action. Common in eco messaging.",
    noteZh: "실천 = 把想法化为行动，在环保宣传中常见。",
    noteVi: "실천 = biến ý định thành hành động. Thường dùng trong các thông điệp về môi trường.",
  },
  {
    id: "ko-b2-environment-011",
    level: "B2",
    deck: "environment",
    en: "Conservation / protection",
    zh: "保护",
    vi: "Bảo vệ",
    ko: "보호",
    roman: "boho",
    exampleKo: "멸종 위기 동물 보호가 시급해요.",
    exampleEn: "Protecting endangered animals is urgent.",
    exampleZh: "保护濒危动物迫在眉睫。",
    exampleVi: "Bảo vệ động vật có nguy cơ tuyệt chủng là việc cấp bách.",
    note: "멸종 위기 = endangered; 시급하다 = to be urgent/pressing.",
    noteZh: "멸종 위기 = 濒临灭绝；시급하다 = 紧迫／急需。",
    noteVi: "멸종 위기 = có nguy cơ tuyệt chủng; 시급하다 = cấp bách/khẩn cấp.",
  },

  // ── technology (기술·디지털) ──
  {
    id: "ko-b2-technology-001",
    level: "B2",
    deck: "technology",
    en: "Artificial intelligence (AI)",
    zh: "人工智能",
    vi: "Trí tuệ nhân tạo",
    ko: "인공지능",
    roman: "ingongjineung",
    exampleKo: "인공지능이 우리 일자리를 바꾸고 있어요.",
    exampleEn: "AI is changing our jobs.",
    exampleZh: "人工智能正在改变我们的工作。",
    exampleVi: "Trí tuệ nhân tạo đang thay đổi công việc của chúng ta.",
    note: "Often shortened to the English-letter 'AI' in speech too.",
    noteZh: "口语中也常直接用英文字母“AI”来简称。",
    noteVi: "Trong khẩu ngữ cũng thường được viết tắt bằng chữ cái tiếng Anh “AI”.",
  },
  {
    id: "ko-b2-technology-002",
    level: "B2",
    deck: "technology",
    en: "Personal data / privacy",
    zh: "个人信息／隐私",
    vi: "Thông tin cá nhân",
    ko: "개인정보",
    roman: "gaeinjeongbo",
    exampleKo: "개인정보 유출 사고가 또 일어났어요.",
    exampleEn: "There was another personal data leak.",
    exampleZh: "又发生了个人信息泄露事故。",
    exampleVi: "Lại xảy ra sự cố rò rỉ thông tin cá nhân.",
    note: "유출 = leak; 개인정보 보호 = data protection/privacy.",
    noteZh: "유출 = 泄露；개인정보 보호 = 个人信息保护／隐私保护。",
    noteVi: "유출 = rò rỉ; 개인정보 보호 = bảo vệ thông tin cá nhân/quyền riêng tư.",
  },
  {
    id: "ko-b2-technology-003",
    level: "B2",
    deck: "technology",
    en: "To be convenient / handy",
    zh: "便利／方便",
    vi: "Tiện lợi",
    ko: "편리하다",
    roman: "pyeollihada",
    exampleKo: "모바일 결제가 정말 편리해졌어요.",
    exampleEn: "Mobile payments have become really convenient.",
    exampleZh: "移动支付真的变得很方便了。",
    exampleVi: "Thanh toán di động đã trở nên rất tiện lợi.",
    note: "편리하다 (convenient/useful) vs 편하다 (comfortable). Tech tends to use 편리하다.",
    noteZh: "편리하다（便利／好用）与 편하다（舒适）不同。科技语境多用 편리하다。",
    noteVi: "편리하다 (tiện lợi/hữu ích) khác với 편하다 (thoải mái). Trong ngữ cảnh công nghệ thường dùng 편리하다.",
  },
  {
    id: "ko-b2-technology-004",
    level: "B2",
    deck: "technology",
    en: "Side effect / downside",
    zh: "副作用／负面影响",
    vi: "Tác dụng phụ / Mặt trái",
    ko: "부작용",
    roman: "bujagyong",
    exampleKo: "기술 발전에는 부작용도 따라와요.",
    exampleEn: "Technological progress comes with downsides too.",
    exampleZh: "技术进步也会伴随副作用。",
    exampleVi: "Sự phát triển công nghệ cũng đi kèm với những tác dụng phụ.",
    note: "Originally 'medical side effect,' now used for any negative by-product.",
    noteZh: "原指“医疗副作用”，现用于指任何负面的副产物。",
    noteVi: "Vốn có nghĩa là “tác dụng phụ trong y học”, nay dùng cho bất kỳ hệ quả tiêu cực nào.",
  },
  {
    id: "ko-b2-technology-005",
    level: "B2",
    deck: "technology",
    en: "To depend on / be reliant on",
    zh: "依赖／依靠",
    vi: "Phụ thuộc vào",
    ko: "의존하다",
    roman: "uijonhada",
    exampleKo: "우리는 스마트폰에 너무 의존하는 것 같아요.",
    exampleEn: "I think we rely on smartphones too much.",
    exampleZh: "我们好像太依赖智能手机了。",
    exampleVi: "Hình như chúng ta phụ thuộc quá nhiều vào điện thoại thông minh.",
    note: "...에 의존하다 = 'to depend on.' 의존도 = degree of dependence.",
    noteZh: "……에 의존하다 = “依赖……”。의존도 = 依赖程度。",
    noteVi: "...에 의존하다 = “phụ thuộc vào...”. 의존도 = mức độ phụ thuộc.",
  },
  {
    id: "ko-b2-technology-006",
    level: "B2",
    deck: "technology",
    en: "To replace / take the place of",
    zh: "替代／取代",
    vi: "Thay thế",
    ko: "대체하다",
    roman: "daechehada",
    exampleKo: "기계가 사람을 완전히 대체하기는 어려워요.",
    exampleEn: "It's hard for machines to completely replace people.",
    exampleZh: "机器很难完全取代人。",
    exampleVi: "Máy móc khó mà thay thế con người một cách hoàn toàn.",
    note: "대체하다 = 'to substitute / replace.' 대체 인력 = replacement workforce.",
    noteZh: "대체하다 = “替代／取代”。대체 인력 = 替补人力。",
    noteVi: "대체하다 = “thay thế”. 대체 인력 = nhân lực thay thế.",
  },
  {
    id: "ko-b2-technology-007",
    level: "B2",
    deck: "technology",
    en: "The digital divide / information gap",
    zh: "信息鸿沟／数字鸿沟",
    vi: "Khoảng cách thông tin / Khoảng cách số",
    ko: "정보 격차",
    roman: "jeongbo gyeokcha",
    exampleKo: "노인층의 정보 격차가 점점 커지고 있어요.",
    exampleEn: "The information gap for older people keeps widening.",
    exampleZh: "老年群体的信息鸿沟正日益扩大。",
    exampleVi: "Khoảng cách thông tin của người cao tuổi đang ngày càng lớn hơn.",
    note: "격차 = gap/disparity; also 빈부 격차 = wealth gap.",
    noteZh: "격차 = 差距／悬殊；빈부 격차 = 贫富差距。",
    noteVi: "격차 = khoảng cách/chênh lệch; còn có 빈부 격차 = khoảng cách giàu nghèo.",
  },
  {
    id: "ko-b2-technology-008",
    level: "B2",
    deck: "technology",
    en: "To innovate / cutting-edge",
    zh: "创新的／有革新性的",
    vi: "Có tính đổi mới / Mang tính cách tân",
    ko: "혁신적이다",
    roman: "hyeoksinjeogida",
    exampleKo: "그 회사의 기술은 정말 혁신적이에요.",
    exampleEn: "That company's technology is truly innovative.",
    exampleZh: "那家公司的技术真的很有创新性。",
    exampleVi: "Công nghệ của công ty đó thực sự mang tính đổi mới.",
    note: "혁신 = innovation; 혁신적인 + noun = innovative.",
    noteZh: "혁신 = 创新；혁신적인 + 名词 = 有创新性的。",
    noteVi: "혁신 = sự đổi mới; 혁신적인 + danh từ = mang tính đổi mới.",
  },
  {
    id: "ko-b2-technology-009",
    level: "B2",
    deck: "technology",
    en: "Fake news / misinformation",
    zh: "假新闻",
    vi: "Tin giả",
    ko: "가짜 뉴스",
    roman: "gajja nyuseu",
    exampleKo: "온라인에 가짜 뉴스가 빠르게 퍼져요.",
    exampleEn: "Fake news spreads fast online.",
    exampleZh: "假新闻在网上传播得很快。",
    exampleVi: "Tin giả lan truyền nhanh chóng trên mạng.",
    note: "퍼지다 = to spread; 가짜 = fake (vs 진짜 = real).",
    noteZh: "퍼지다 = 传播；가짜 = 假的（与 진짜 = 真的 相对）。",
    noteVi: "퍼지다 = lan truyền; 가짜 = giả (đối lập với 진짜 = thật).",
  },
  {
    id: "ko-b2-technology-010",
    level: "B2",
    deck: "technology",
    en: "Automation",
    zh: "自动化",
    vi: "Tự động hóa",
    ko: "자동화",
    roman: "jadonghwa",
    exampleKo: "공장 자동화로 생산성이 크게 올랐어요.",
    exampleEn: "Factory automation greatly raised productivity.",
    exampleZh: "工厂自动化使生产率大幅提高。",
    exampleVi: "Nhờ tự động hóa nhà máy, năng suất đã tăng đáng kể.",
    note: "-화 = '-ization' suffix: 자동화, 디지털화, 세계화 (globalization).",
    noteZh: "-화 = 相当于“-化”的后缀：자동화（自动化）、디지털화（数字化）、세계화（全球化）。",
    noteVi: "-화 = hậu tố tương đương “-hóa”: 자동화 (tự động hóa), 디지털화 (số hóa), 세계화 (toàn cầu hóa).",
  },
  {
    id: "ko-b2-technology-011",
    level: "B2",
    deck: "technology",
    en: "To keep up with / catch up to",
    zh: "跟上／赶上",
    vi: "Theo kịp",
    ko: "따라가다",
    roman: "ttaragada",
    exampleKo: "기술 변화 속도를 따라가기가 벅차요.",
    exampleEn: "It's overwhelming to keep up with the pace of tech change.",
    exampleZh: "要跟上技术变化的速度很吃力。",
    exampleVi: "Theo kịp tốc độ thay đổi công nghệ thật đuối sức.",
    note: "벅차다 = 'to be overwhelming / more than one can handle.'",
    noteZh: "벅차다 = “吃力／力不从心”。",
    noteVi: "벅차다 = “quá sức / khó có thể kham nổi”.",
  },

  // ── culture (문화·예술) ──
  {
    id: "ko-b2-culture-001",
    level: "B2",
    deck: "culture",
    en: "Traditional culture",
    zh: "传统文化",
    vi: "Văn hóa truyền thống",
    ko: "전통 문화",
    roman: "jeontong munhwa",
    exampleKo: "한국의 전통 문화에 관심이 많아요.",
    exampleEn: "I'm very interested in Korean traditional culture.",
    exampleZh: "我对韩国的传统文化很感兴趣。",
    exampleVi: "Tôi rất quan tâm đến văn hóa truyền thống Hàn Quốc.",
    note: "전통 = tradition; 전통적인 + noun = traditional.",
    noteZh: "전통 = 传统；전통적인 + 名词 = 传统的。",
    noteVi: "전통 = truyền thống; 전통적인 + danh từ = mang tính truyền thống.",
  },
  {
    id: "ko-b2-culture-002",
    level: "B2",
    deck: "culture",
    en: "Pop culture / mass culture",
    zh: "大众文化／流行文化",
    vi: "Văn hóa đại chúng",
    ko: "대중문화",
    roman: "daejung munhwa",
    exampleKo: "한국 대중문화가 전 세계로 퍼지고 있어요.",
    exampleEn: "Korean pop culture is spreading worldwide.",
    exampleZh: "韩国大众文化正在向全世界传播。",
    exampleVi: "Văn hóa đại chúng Hàn Quốc đang lan rộng ra toàn thế giới.",
    note: "대중 = the masses/public; the 'K' in K-pop is this 대중문화.",
    noteZh: "대중 = 大众／公众；K-pop 里的“K”指的就是这种 대중문화。",
    noteVi: "대중 = quần chúng/công chúng; chữ “K” trong K-pop chính là từ 대중문화 này.",
  },
  {
    id: "ko-b2-culture-003",
    level: "B2",
    deck: "culture",
    en: "To be moved / touched (emotionally)",
    zh: "受到感动／被打动",
    vi: "Được cảm động / Bị lay động",
    ko: "감동을 받다",
    roman: "gamdongeul batda",
    exampleKo: "그 영화의 결말에 큰 감동을 받았어요.",
    exampleEn: "I was deeply moved by the film's ending.",
    exampleZh: "我被那部电影的结局深深打动了。",
    exampleVi: "Tôi đã vô cùng cảm động trước cái kết của bộ phim đó.",
    note: "감동 = moving emotion; 감동적이다 = to be moving/touching.",
    noteZh: "감동 = 感动之情；감동적이다 = 令人感动的。",
    noteVi: "감동 = cảm xúc lay động; 감동적이다 = cảm động/lay động lòng người.",
  },
  {
    id: "ko-b2-culture-004",
    level: "B2",
    deck: "culture",
    en: "Exhibition",
    zh: "展览会／展览",
    vi: "Triển lãm",
    ko: "전시회",
    roman: "jeonsihoe",
    exampleKo: "주말에 사진 전시회를 보러 갔어요.",
    exampleEn: "I went to a photography exhibition over the weekend.",
    exampleZh: "周末去看了摄影展。",
    exampleVi: "Cuối tuần tôi đã đi xem một triển lãm ảnh.",
    note: "전시 = display/exhibit; 전시회 = the exhibition event.",
    noteZh: "전시 = 展示／展出；전시회 = 展览会（活动）。",
    noteVi: "전시 = trưng bày/triển lãm; 전시회 = sự kiện triển lãm.",
  },
  {
    id: "ko-b2-culture-005",
    level: "B2",
    deck: "culture",
    en: "Performance / show",
    zh: "演出／表演",
    vi: "Buổi biểu diễn",
    ko: "공연",
    roman: "gongyeon",
    exampleKo: "어제 본 공연이 정말 인상 깊었어요.",
    exampleEn: "The performance I saw yesterday was really impressive.",
    exampleZh: "昨天看的演出真的令人印象深刻。",
    exampleVi: "Buổi biểu diễn tôi xem hôm qua thực sự rất ấn tượng.",
    note: "인상 깊다 = 'to leave a deep impression.' Great for reviews.",
    noteZh: "인상 깊다 = “印象深刻”，很适合用于评价。",
    noteVi: "인상 깊다 = “để lại ấn tượng sâu sắc”. Rất hữu ích khi viết đánh giá.",
  },
  {
    id: "ko-b2-culture-006",
    level: "B2",
    deck: "culture",
    en: "Work (of art) / piece",
    zh: "作品",
    vi: "Tác phẩm",
    ko: "작품",
    roman: "jakpum",
    exampleKo: "이 작품은 작가의 개성이 잘 드러나요.",
    exampleEn: "This piece clearly shows the artist's individuality.",
    exampleZh: "这件作品充分展现了创作者的个性。",
    exampleVi: "Tác phẩm này thể hiện rõ cá tính của tác giả.",
    note: "작품 = a created work (film, novel, painting); 작가 = creator/author.",
    noteZh: "작품 = 创作出的作品（电影、小说、画作）；작가 = 创作者／作者。",
    noteVi: "작품 = một tác phẩm sáng tạo (phim, tiểu thuyết, tranh); 작가 = người sáng tác/tác giả.",
  },
  {
    id: "ko-b2-culture-007",
    level: "B2",
    deck: "culture",
    en: "Taste / preference",
    zh: "喜好／品味",
    vi: "Sở thích / Gu thẩm mỹ",
    ko: "취향",
    roman: "chwihyang",
    exampleKo: "음악 취향이 저랑 잘 맞네요.",
    exampleEn: "Your taste in music really matches mine.",
    exampleZh: "你的音乐品味和我很合。",
    exampleVi: "Gu âm nhạc của bạn hợp với tôi ghê.",
    note: "취향이 맞다 = 'tastes align.' 취향 저격 (slang) = right up my alley.",
    noteZh: "취향이 맞다 = “品味相合”。취향 저격（俚语）= 正中我的喜好。",
    noteVi: "취향이 맞다 = “hợp gu nhau”. 취향 저격 (tiếng lóng) = đúng gu của mình.",
  },
  {
    id: "ko-b2-culture-008",
    level: "B2",
    deck: "culture",
    en: "To be worth (doing) / worthwhile",
    zh: "值得（做）",
    vi: "Đáng để (làm gì đó)",
    ko: "...ㄹ 만하다",
    roman: "...l manhada",
    exampleKo: "그 전시는 한번 가 볼 만해요.",
    exampleEn: "That exhibition is worth checking out.",
    exampleZh: "那个展览值得去看一次。",
    exampleVi: "Triển lãm đó đáng để đi xem một lần.",
    note: "Verb stem + -ㄹ/을 만하다 = 'worth doing.' Very natural in recommendations.",
    noteZh: "动词词干 + -ㄹ/을 만하다 = “值得做”，用于推荐时非常自然。",
    noteVi: "Gốc động từ + -ㄹ/을 만하다 = “đáng để làm”. Rất tự nhiên khi dùng để giới thiệu/gợi ý.",
  },
  {
    id: "ko-b2-culture-009",
    level: "B2",
    deck: "culture",
    en: "Trend / a craze",
    zh: "流行／潮流",
    vi: "Xu hướng / Trào lưu",
    ko: "유행",
    roman: "yuhaeng",
    exampleKo: "복고풍이 다시 유행이에요.",
    exampleEn: "The retro style is in fashion again.",
    exampleZh: "复古风又流行起来了。",
    exampleVi: "Phong cách hoài cổ lại đang thành trào lưu.",
    note: "유행하다 = to be trendy; 복고풍 = retro style.",
    noteZh: "유행하다 = 流行；복고풍 = 复古风。",
    noteVi: "유행하다 = thịnh hành/thành trào lưu; 복고풍 = phong cách hoài cổ.",
  },
  {
    id: "ko-b2-culture-010",
    level: "B2",
    deck: "culture",
    en: "To have an eye for / be discerning",
    zh: "有眼光／有鉴赏力",
    vi: "Có con mắt thẩm mỹ / Có óc thẩm định",
    ko: "안목이 있다",
    roman: "anmogi itda",
    exampleKo: "그분은 예술에 안목이 있으세요.",
    exampleEn: "She has a discerning eye for art.",
    exampleZh: "那位对艺术很有鉴赏力。",
    exampleVi: "Vị đó có con mắt thẩm mỹ rất tinh tế về nghệ thuật.",
    note: "안목 = a trained, perceptive eye for quality. A compliment.",
    noteZh: "안목 = 对品质敏锐、有素养的眼光，是一种称赞。",
    noteVi: "안목 = con mắt tinh tường, đã được rèn luyện để nhận biết chất lượng. Đây là một lời khen.",
  },
  {
    id: "ko-b2-culture-011",
    level: "B2",
    deck: "culture",
    en: "To be passed down / handed down",
    zh: "流传下来／代代相传",
    vi: "Được lưu truyền / Truyền lại qua các thế hệ",
    ko: "전해 내려오다",
    roman: "jeonhae naeryeooda",
    exampleKo: "이 풍습은 오래전부터 전해 내려왔어요.",
    exampleEn: "This custom has been handed down from long ago.",
    exampleZh: "这一习俗从很久以前就流传至今。",
    exampleVi: "Phong tục này đã được lưu truyền từ rất lâu đời.",
    note: "풍습 = custom; used for traditions, legends, recipes across generations.",
    noteZh: "풍습 = 习俗；用于世代相传的传统、传说、食谱等。",
    noteVi: "풍습 = phong tục; dùng cho các truyền thống, truyền thuyết, công thức được truyền qua nhiều thế hệ.",
  },
];
