/**
 * C1 (고급) 한국어 학습 콘텐츠 — 영어권 학습자 대상.
 * 각 카드: 한국어 표현(ko) + 로마자(roman) + 영어 뜻(en) + 예문(한/영).
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * note 는 영어(학습자 모국어)로 사용 맥락을 설명한다.
 *
 * C1 난이도: 업무·전문 상황에서 능숙하게, 논리적 주장, 미묘한 격식,
 * 한자어 어휘 중심.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_C1_DECKS: Deck[] = [
  {
    id: "business",
    level: "C1",
    title: { ko: "비즈니스·회의", en: "Business" },
    description: {
      ko: "협상·보고·의사결정 표현",
      en: "Negotiation, reporting, and decision-making",
    },
    order: 1,
    icon: "Briefcase",
  },
  {
    id: "society",
    level: "C1",
    title: { ko: "사회 이슈", en: "Social Issues" },
    description: {
      ko: "정책·격차·세대 담론",
      en: "Policy, inequality, and generational debate",
    },
    order: 2,
    icon: "Landmark",
  },
  {
    id: "abstract",
    level: "C1",
    title: { ko: "추상적 사고·논리", en: "Abstract Thinking" },
    description: {
      ko: "전제·근거·반론의 논리 구조",
      en: "Premises, evidence, and counterarguments",
    },
    order: 3,
    icon: "Brain",
  },
  {
    id: "media",
    level: "C1",
    title: { ko: "미디어·여론", en: "Media" },
    description: {
      ko: "보도·여론·프레임 분석",
      en: "Coverage, public opinion, and framing",
    },
    order: 4,
    icon: "Newspaper",
  },
];

export const KO_C1_CARDS: VocabCard[] = [
  // ── business (비즈니스·회의 / Business) ──
  {
    id: "ko-c1-business-001",
    level: "C1",
    deck: "business",
    en: "to reach a consensus",
    ko: "합의를 도출하다",
    roman: "habuireul dochulhada",
    exampleKo: "양측은 긴 논의 끝에 합의를 도출했습니다.",
    exampleEn: "After lengthy discussion, both sides reached a consensus.",
    note: "합의 (agreement) + 도출하다 (to derive). Standard boardroom phrasing for arriving at an agreed outcome.",
  },
  {
    id: "ko-c1-business-002",
    level: "C1",
    deck: "business",
    en: "to push ahead with a project",
    ko: "프로젝트를 추진하다",
    roman: "peurojekteureul chujinhada",
    exampleKo: "이사회 승인 후 본격적으로 사업을 추진할 예정입니다.",
    exampleEn: "We plan to push ahead with the project in earnest after board approval.",
    note: "추진하다 implies driving something forward with resources and intent, not just 'doing' it.",
  },
  {
    id: "ko-c1-business-003",
    level: "C1",
    deck: "business",
    en: "to review the matter positively / favorably",
    ko: "긍정적으로 검토하다",
    roman: "geungjeongjeogeuro geomtohada",
    exampleKo: "제안하신 조건을 긍정적으로 검토하겠습니다.",
    exampleEn: "We will review the terms you proposed favorably.",
    note: "A polite, non-committal yes-ish phrase. In Korean business culture it signals openness without a firm promise.",
  },
  {
    id: "ko-c1-business-004",
    level: "C1",
    deck: "business",
    en: "to take the lead / take the initiative",
    ko: "주도권을 잡다",
    roman: "judogwoneul japda",
    exampleKo: "협상에서 주도권을 잡으려면 자료가 탄탄해야 합니다.",
    exampleEn: "To take the lead in negotiations, your data must be solid.",
    note: "주도권 (initiative/control) + 잡다 (to grab). Used for seizing control of a deal or discussion.",
  },
  {
    id: "ko-c1-business-005",
    level: "C1",
    deck: "business",
    en: "to weigh the pros and cons",
    ko: "득실을 따지다",
    roman: "deuksireul ttajida",
    exampleKo: "감정에 휘둘리지 말고 냉정하게 득실을 따져 봅시다.",
    exampleEn: "Let's not be swayed by emotion and coolly weigh the pros and cons.",
    note: "득실 = gains and losses (得失). 따지다 = to scrutinize/calculate. Common in strategic discussions.",
  },
  {
    id: "ko-c1-business-006",
    level: "C1",
    deck: "business",
    en: "to defer / postpone a decision",
    ko: "결정을 보류하다",
    roman: "gyeoljeongeul boryuhada",
    exampleKo: "추가 검토가 필요해 최종 결정을 보류했습니다.",
    exampleEn: "We deferred the final decision because further review was needed.",
    note: "보류하다 (to hold/suspend) is the formal verb for tabling something pending more information.",
  },
  {
    id: "ko-c1-business-007",
    level: "C1",
    deck: "business",
    en: "to secure a competitive edge",
    ko: "경쟁력을 확보하다",
    roman: "gyeongjaengnyeogeul hwakbohada",
    exampleKo: "기술 투자를 통해 시장 경쟁력을 확보해야 합니다.",
    exampleEn: "We must secure a competitive edge in the market through tech investment.",
    note: "경쟁력 (competitiveness) + 확보하다 (to secure). A staple in strategy and planning meetings.",
  },
  {
    id: "ko-c1-business-008",
    level: "C1",
    deck: "business",
    en: "to set up a follow-up meeting",
    ko: "후속 미팅을 잡다",
    roman: "husok mitingeul japda",
    exampleKo: "세부 사항은 후속 미팅을 잡아 논의하시죠.",
    exampleEn: "Let's set up a follow-up meeting to discuss the details.",
    note: "후속 (follow-up, 後續). 잡다 here means 'to schedule'. A natural way to defer details politely.",
  },
  {
    id: "ko-c1-business-009",
    level: "C1",
    deck: "business",
    en: "to streamline / cut down the budget",
    ko: "예산을 절감하다",
    roman: "yesaneul jeolgamhada",
    exampleKo: "불필요한 지출을 줄여 예산을 절감했습니다.",
    exampleEn: "We streamlined the budget by cutting unnecessary spending.",
    note: "절감하다 (to reduce/save, 節減) is more formal than 줄이다 and standard in financial reporting.",
  },
  {
    id: "ko-c1-business-010",
    level: "C1",
    deck: "business",
    en: "to be held accountable / take responsibility",
    ko: "책임을 지다",
    roman: "chaegimeul jida",
    exampleKo: "이번 차질에 대해서는 제가 책임을 지겠습니다.",
    exampleEn: "I will take responsibility for this setback.",
    note: "책임을 지다 = to bear responsibility. Saying this signals accountability and is valued in Korean work culture.",
  },
  {
    id: "ko-c1-business-011",
    level: "C1",
    deck: "business",
    en: "to bring up an agenda item / raise an issue",
    ko: "안건을 상정하다",
    roman: "angeoneul sangjeonghada",
    exampleKo: "다음 회의에 그 안건을 정식으로 상정하겠습니다.",
    exampleEn: "I will formally bring that item onto the agenda at the next meeting.",
    note: "안건 (agenda item, 案件) + 상정하다 (to table/submit, 上程). Formal meeting and committee language.",
  },
  {
    id: "ko-c1-business-012",
    level: "C1",
    deck: "business",
    en: "to clearly define roles and responsibilities",
    ko: "역할과 책임을 분담하다",
    roman: "yeokalgwa chaegimeul bundamhada",
    exampleKo: "혼선을 막으려면 팀원 간 역할과 책임을 분담해야 합니다.",
    exampleEn: "To avoid confusion, we must clearly divide roles and responsibilities among the team.",
    note: "분담하다 (to share/divide a burden, 分擔). Used when assigning ownership across a team.",
  },

  // ── society (사회 이슈 / Social Issues) ──
  {
    id: "ko-c1-society-001",
    level: "C1",
    deck: "society",
    en: "the widening gap between rich and poor",
    ko: "빈부 격차",
    roman: "binbu gyeokcha",
    exampleKo: "빈부 격차가 심화되면서 사회 불만이 커지고 있습니다.",
    exampleEn: "As the wealth gap widens, social discontent is growing.",
    note: "빈부 (rich and poor, 貧富) + 격차 (gap, 隔差). A core term in any discussion of inequality.",
  },
  {
    id: "ko-c1-society-002",
    level: "C1",
    deck: "society",
    en: "an aging society",
    ko: "고령화 사회",
    roman: "goryeonghwa sahoe",
    exampleKo: "고령화 사회로 접어들면서 연금 문제가 대두되고 있습니다.",
    exampleEn: "As we enter an aging society, the pension issue is coming to the fore.",
    note: "고령화 (aging, 高齡化). Korea's rapid demographic shift makes this a frequent headline term.",
  },
  {
    id: "ko-c1-society-003",
    level: "C1",
    deck: "society",
    en: "to come to the fore / become a major issue",
    ko: "대두되다",
    roman: "daedudoeda",
    exampleKo: "청년 실업 문제가 사회적 화두로 대두되었습니다.",
    exampleEn: "Youth unemployment has emerged as a major social issue.",
    note: "대두되다 (to rise to prominence, 擡頭) is used for issues newly gaining attention. More formal than 생기다.",
  },
  {
    id: "ko-c1-society-004",
    level: "C1",
    deck: "society",
    en: "to bridge / resolve a generational gap",
    ko: "세대 갈등을 해소하다",
    roman: "sedae galdeungeul haesohada",
    exampleKo: "세대 갈등을 해소하려면 서로의 입장을 이해해야 합니다.",
    exampleEn: "To resolve the generational conflict, each side must understand the other's position.",
    note: "세대 갈등 (generational conflict). 해소하다 (to dissolve/relieve, 解消) pairs with conflicts and stress.",
  },
  {
    id: "ko-c1-society-005",
    level: "C1",
    deck: "society",
    en: "to strengthen the social safety net",
    ko: "사회 안전망을 강화하다",
    roman: "sahoe anjeonmangeul ganghwahada",
    exampleKo: "취약 계층을 위해 사회 안전망을 강화할 필요가 있습니다.",
    exampleEn: "We need to strengthen the social safety net for vulnerable groups.",
    note: "안전망 (safety net) is a direct calque. 취약 계층 (vulnerable groups) often appears alongside it.",
  },
  {
    id: "ko-c1-society-006",
    level: "C1",
    deck: "society",
    en: "to gather / build public consensus",
    ko: "공감대를 형성하다",
    roman: "gonggamdaereul hyeongseonghada",
    exampleKo: "정책을 추진하기 전에 사회적 공감대를 형성해야 합니다.",
    exampleEn: "Before pushing a policy, we must build public consensus.",
    note: "공감대 (shared empathy/common ground) + 형성하다 (to form, 形成). Key for policy and PR contexts.",
  },
  {
    id: "ko-c1-society-007",
    level: "C1",
    deck: "society",
    en: "the polarization of public opinion",
    ko: "여론의 양극화",
    roman: "yeoronui yanggeukhwa",
    exampleKo: "이번 사안을 두고 여론의 양극화가 뚜렷합니다.",
    exampleEn: "Public opinion is sharply polarized over this issue.",
    note: "양극화 (polarization, 兩極化) applies to opinion, wealth, and politics alike. Very common in op-eds.",
  },
  {
    id: "ko-c1-society-008",
    level: "C1",
    deck: "society",
    en: "to take root as a social norm / settle in",
    ko: "사회적으로 자리 잡다",
    roman: "sahoejeogeuro jari japda",
    exampleKo: "재택근무가 하나의 문화로 사회적으로 자리 잡았습니다.",
    exampleEn: "Remote work has taken root as a cultural norm in society.",
    note: "자리 잡다 (to settle into place) describes a practice becoming established and accepted.",
  },
  {
    id: "ko-c1-society-009",
    level: "C1",
    deck: "society",
    en: "to be marginalized / pushed to the fringes",
    ko: "소외되다",
    roman: "sooedoeda",
    exampleKo: "기술 발전 속에서 노년층이 소외되지 않도록 해야 합니다.",
    exampleEn: "We must ensure the elderly are not marginalized amid technological progress.",
    note: "소외되다 (to be alienated/excluded, 疏外). Central to discussions of the digital divide and inequality.",
  },
  {
    id: "ko-c1-society-010",
    level: "C1",
    deck: "society",
    en: "a pending issue / unresolved task",
    ko: "현안",
    roman: "hyeonan",
    exampleKo: "주거 문제는 정부가 시급히 풀어야 할 현안입니다.",
    exampleEn: "Housing is a pressing issue the government must urgently address.",
    note: "현안 (current pending matter, 懸案). Sounds formal and journalistic; common in news and policy.",
  },
  {
    id: "ko-c1-society-011",
    level: "C1",
    deck: "society",
    en: "to raise public awareness",
    ko: "인식을 제고하다",
    roman: "insigeul jegohada",
    exampleKo: "환경 보호에 대한 시민들의 인식을 제고해야 합니다.",
    exampleEn: "We must raise citizens' awareness of environmental protection.",
    note: "제고하다 (to enhance/raise, 提高) is a formal alternative to 높이다, common in campaigns and reports.",
  },

  // ── abstract (추상적 사고·논리 / Abstract Thinking) ──
  {
    id: "ko-c1-abstract-001",
    level: "C1",
    deck: "abstract",
    en: "based on the premise that ~",
    ko: "~라는 전제하에",
    roman: "~raneun jeonjeha-e",
    exampleKo: "모두가 동의한다는 전제하에 논의를 진행하겠습니다.",
    exampleEn: "I'll proceed on the premise that everyone agrees.",
    note: "전제 (premise, 前提) + 하에 (under). Sets up a conditional assumption for an argument.",
  },
  {
    id: "ko-c1-abstract-002",
    level: "C1",
    deck: "abstract",
    en: "to be logically coherent / consistent",
    ko: "논리적으로 일관되다",
    roman: "nollijeogeuro ilgwandoeda",
    exampleKo: "그의 주장은 처음부터 끝까지 논리적으로 일관됩니다.",
    exampleEn: "His argument is logically consistent from start to finish.",
    note: "일관되다 (to be consistent, 一貫). Praising or critiquing the internal coherence of an argument.",
  },
  {
    id: "ko-c1-abstract-003",
    level: "C1",
    deck: "abstract",
    en: "to back up a claim with evidence",
    ko: "근거를 뒷받침하다",
    roman: "geun-georeul dwitbatchimhada",
    exampleKo: "주장을 뒷받침할 객관적인 근거가 필요합니다.",
    exampleEn: "We need objective evidence to back up the claim.",
    note: "뒷받침하다 (to support/underpin) pairs naturally with 근거 (grounds) and 주장 (claim).",
  },
  {
    id: "ko-c1-abstract-004",
    level: "C1",
    deck: "abstract",
    en: "to draw a conclusion",
    ko: "결론을 도출하다",
    roman: "gyeollon-eul dochulhada",
    exampleKo: "데이터를 종합해 합리적인 결론을 도출했습니다.",
    exampleEn: "We drew a reasonable conclusion by synthesizing the data.",
    note: "도출하다 (to derive, 導出) is the formal verb for reaching conclusions or results from premises.",
  },
  {
    id: "ko-c1-abstract-005",
    level: "C1",
    deck: "abstract",
    en: "to put it the other way around / conversely",
    ko: "역으로 말하면",
    roman: "yeogeuro malhamyeon",
    exampleKo: "역으로 말하면, 규제가 없으면 시장이 혼란해진다는 뜻입니다.",
    exampleEn: "Conversely, it means the market becomes chaotic without regulation.",
    note: "역으로 (in reverse, 逆). A useful connective for reframing or testing the inverse of a point.",
  },
  {
    id: "ko-c1-abstract-006",
    level: "C1",
    deck: "abstract",
    en: "there is room for debate / it's open to dispute",
    ko: "논란의 여지가 있다",
    roman: "nollanui yeojiga itda",
    exampleKo: "그 해석은 여전히 논란의 여지가 있습니다.",
    exampleEn: "That interpretation is still open to debate.",
    note: "여지 (room/leeway, 餘地) + 있다. A measured way to flag that a claim isn't settled.",
  },
  {
    id: "ko-c1-abstract-007",
    level: "C1",
    deck: "abstract",
    en: "to view it from a different angle",
    ko: "다른 관점에서 보다",
    roman: "dareun gwanjeomeseo boda",
    exampleKo: "같은 현상도 다른 관점에서 보면 해석이 달라집니다.",
    exampleEn: "Even the same phenomenon yields a different reading when viewed from another angle.",
    note: "관점 (viewpoint, 觀點). Essential for introducing an alternative interpretation in discussion.",
  },
  {
    id: "ko-c1-abstract-008",
    level: "C1",
    deck: "abstract",
    en: "to be a logical leap / a stretch",
    ko: "비약이 심하다",
    roman: "biyagi simhada",
    exampleKo: "전제에서 결론으로 가는 과정에 비약이 심합니다.",
    exampleEn: "There's a serious logical leap from the premise to the conclusion.",
    note: "비약 (a leap, 飛躍) here is a fallacy of jumping to a conclusion. A precise critique of weak reasoning.",
  },
  {
    id: "ko-c1-abstract-009",
    level: "C1",
    deck: "abstract",
    en: "to be a matter of perspective / it depends how you see it",
    ko: "보기 나름이다",
    roman: "bogi nareumida",
    exampleKo: "성공인지 실패인지는 보기 나름입니다.",
    exampleEn: "Whether it's a success or a failure depends on how you look at it.",
    note: "나름이다 = 'depends on'. A natural, idiomatic way to say something is relative or subjective.",
  },
  {
    id: "ko-c1-abstract-010",
    level: "C1",
    deck: "abstract",
    en: "in essence / at its core",
    ko: "본질적으로",
    roman: "bonjiljeogeuro",
    exampleKo: "이 문제는 본질적으로 신뢰의 문제입니다.",
    exampleEn: "At its core, this is a question of trust.",
    note: "본질 (essence, 本質). Use to cut past surface details to the fundamental point.",
  },
  {
    id: "ko-c1-abstract-011",
    level: "C1",
    deck: "abstract",
    en: "to take ~ for granted / regard as a given",
    ko: "당연시하다",
    roman: "dangyeonsihada",
    exampleKo: "우리는 표현의 자유를 너무 당연시하는 경향이 있습니다.",
    exampleEn: "We tend to take freedom of expression too much for granted.",
    note: "당연시하다 (to treat as obvious, 當然視) flags an unexamined assumption worth questioning.",
  },

  // ── media (미디어·여론 / Media) ──
  {
    id: "ko-c1-media-001",
    level: "C1",
    deck: "media",
    en: "to report in detail / cover extensively",
    ko: "상세히 보도하다",
    roman: "sangsehi bodohada",
    exampleKo: "언론은 사건의 경위를 상세히 보도했습니다.",
    exampleEn: "The media reported the circumstances of the incident in detail.",
    note: "보도하다 (to report, 報道) is the journalistic verb, distinct from everyday 알리다 (to inform).",
  },
  {
    id: "ko-c1-media-002",
    level: "C1",
    deck: "media",
    en: "to spread / circulate (rumors, information)",
    ko: "유포되다",
    roman: "yupodoeda",
    exampleKo: "확인되지 않은 정보가 온라인에 빠르게 유포되었습니다.",
    exampleEn: "Unverified information spread rapidly online.",
    note: "유포되다 (to be disseminated, 流布) often carries a negative nuance — rumors or misinformation.",
  },
  {
    id: "ko-c1-media-003",
    level: "C1",
    deck: "media",
    en: "to gauge / read public opinion",
    ko: "여론을 수렴하다",
    roman: "yeoroneul suryeomhada",
    exampleKo: "정부는 공청회를 열어 여론을 수렴했습니다.",
    exampleEn: "The government held a public hearing to gather public opinion.",
    note: "수렴하다 (to collect/converge, 收斂) means gathering diverse views toward a decision. Formal register.",
  },
  {
    id: "ko-c1-media-004",
    level: "C1",
    deck: "media",
    en: "fake news / false reporting",
    ko: "허위 보도",
    roman: "heowi bodo",
    exampleKo: "허위 보도로 인한 피해가 갈수록 심각해지고 있습니다.",
    exampleEn: "Damage from false reporting is becoming increasingly serious.",
    note: "허위 (false, 虛僞) + 보도 (report). The standard term in legal and media-ethics discussions.",
  },
  {
    id: "ko-c1-media-005",
    level: "C1",
    deck: "media",
    en: "to frame an issue a certain way",
    ko: "프레임을 씌우다",
    roman: "peureimeul ssiuda",
    exampleKo: "특정 진영이 그 사건에 정치적 프레임을 씌웠습니다.",
    exampleEn: "A particular faction framed the incident politically.",
    note: "프레임을 씌우다 = to impose a frame/narrative. 씌우다 (to put on/over) carries a manipulative nuance.",
  },
  {
    id: "ko-c1-media-006",
    level: "C1",
    deck: "media",
    en: "to be reported sensationally / blown up",
    ko: "자극적으로 다루다",
    roman: "jageukjeogeuro daruda",
    exampleKo: "일부 매체가 사건을 지나치게 자극적으로 다뤘습니다.",
    exampleEn: "Some outlets covered the incident far too sensationally.",
    note: "자극적 (sensational/provocative, 刺戟的) + 다루다 (to handle/treat). A critique of tabloid-style coverage.",
  },
  {
    id: "ko-c1-media-007",
    level: "C1",
    deck: "media",
    en: "to shape / foster public opinion",
    ko: "여론을 조성하다",
    roman: "yeoroneul josonghada",
    exampleKo: "광고는 특정 제품에 우호적인 여론을 조성합니다.",
    exampleEn: "Advertising fosters favorable public opinion toward certain products.",
    note: "조성하다 (to create/build up, 造成). Used for deliberately shaping a mood or sentiment.",
  },
  {
    id: "ko-c1-media-008",
    level: "C1",
    deck: "media",
    en: "to verify the facts / fact-check",
    ko: "사실 관계를 확인하다",
    roman: "sasil gwangyereul hwaginhada",
    exampleKo: "보도 전에 반드시 사실 관계를 확인해야 합니다.",
    exampleEn: "The facts must be verified before reporting.",
    note: "사실 관계 (the facts / factual relations) is the set phrase journalists use for what needs checking.",
  },
  {
    id: "ko-c1-media-009",
    level: "C1",
    deck: "media",
    en: "to be in the spotlight / draw attention",
    ko: "이목을 끌다",
    roman: "imogeul kkeulda",
    exampleKo: "그 발언은 단숨에 대중의 이목을 끌었습니다.",
    exampleEn: "That remark instantly drew the public's attention.",
    note: "이목 (eyes and ears → attention, 耳目) + 끌다 (to draw). More literary than 관심을 끌다.",
  },
  {
    id: "ko-c1-media-010",
    level: "C1",
    deck: "media",
    en: "to correct / issue a correction to a report",
    ko: "보도를 정정하다",
    roman: "bodoreul jeongjeonghada",
    exampleKo: "오류가 드러나자 방송사는 즉시 보도를 정정했습니다.",
    exampleEn: "Once the error came to light, the broadcaster immediately corrected the report.",
    note: "정정하다 (to correct/rectify, 訂正) is the formal verb for issuing a correction.",
  },
  {
    id: "ko-c1-media-011",
    level: "C1",
    deck: "media",
    en: "to take ~ at face value / accept uncritically",
    ko: "곧이곧대로 받아들이다",
    roman: "gojigotdaero badadeurida",
    exampleKo: "기사를 곧이곧대로 받아들이기보다 출처를 따져야 합니다.",
    exampleEn: "Rather than taking an article at face value, you should examine the source.",
    note: "곧이곧대로 = literally/uncritically. A native idiom warning against naive acceptance of information.",
  },
];
