/**
 * C1 (고급) 한국어 학습 콘텐츠 — 영어권 학습자 대상.
 * 각 카드: 한국어 표현(ko) + 로마자(roman) + 영어 뜻(en) + 예문(한/영).
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * note 는 영어(학습자 모국어)로 사용 맥락을 설명한다.
 *
 * C1 난이도: 업무·전문 상황에서 능숙하게, 논리적 주장, 미묘한 격식,
 * 한자어 어휘 중심.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_C1_DECKS: Deck[] = [
  {
    id: "business",
    level: "C1",
    title: { ko: "비즈니스·회의", en: "Business", zh: "商务·会议", vi: "Kinh doanh · Họp hành" },
    description: {
      ko: "협상·보고·의사결정 표현",
      en: "Negotiation, reporting, and decision-making",
      zh: "谈判、汇报、决策表达",
      vi: "Cách diễn đạt khi đàm phán, báo cáo, ra quyết định",
    },
    order: 1,
    icon: "Briefcase",
  },
  {
    id: "society",
    level: "C1",
    title: { ko: "사회 이슈", en: "Social Issues", zh: "社会议题", vi: "Vấn đề xã hội" },
    description: {
      ko: "정책·격차·세대 담론",
      en: "Policy, inequality, and generational debate",
      zh: "政策、差距、世代议题",
      vi: "Chính sách, khoảng cách giàu nghèo và tranh luận giữa các thế hệ",
    },
    order: 2,
    icon: "Landmark",
  },
  {
    id: "abstract",
    level: "C1",
    title: { ko: "추상적 사고·논리", en: "Abstract Thinking", zh: "抽象思维·逻辑", vi: "Tư duy trừu tượng · Logic" },
    description: {
      ko: "전제·근거·반론의 논리 구조",
      en: "Premises, evidence, and counterarguments",
      zh: "前提、论据、反驳的逻辑结构",
      vi: "Cấu trúc logic của tiền đề, luận cứ và phản biện",
    },
    order: 3,
    icon: "Brain",
  },
  {
    id: "media",
    level: "C1",
    title: { ko: "미디어·여론", en: "Media", zh: "媒体·舆论", vi: "Truyền thông · Dư luận" },
    description: {
      ko: "보도·여론·프레임 분석",
      en: "Coverage, public opinion, and framing",
      zh: "报道、舆论、框架分析",
      vi: "Phân tích việc đưa tin, dư luận và cách gài khung thông tin",
    },
    order: 4,
    icon: "Newspaper",
  },
];

export const KO_C1_CARDS: VocabCard[] = [
  // ── business (비즈니스·회의 / Business) ──
  {
    id: "ko-c1-business-001",
    level: "C1",
    deck: "business",
    en: "to reach a consensus",
    zh: "达成共识",
    vi: "đạt được sự đồng thuận",
    ko: "합의를 도출하다",
    roman: "habuireul dochulhada",
    exampleKo: "양측은 긴 논의 끝에 합의를 도출했습니다.",
    exampleEn: "After lengthy discussion, both sides reached a consensus.",
    exampleZh: "双方经过长时间讨论，最终达成了共识。",
    exampleVi: "Sau một hồi thảo luận kéo dài, hai bên đã đạt được sự đồng thuận.",
    note: "합의 (agreement) + 도출하다 (to derive). Standard boardroom phrasing for arriving at an agreed outcome.",
    noteZh: "합의（合意）+ 도출하다（得出）。会议桌上表示达成一致结论的标准说法。",
    noteVi: "합의 (thỏa thuận) + 도출하다 (rút ra, đi đến). Cách nói chuẩn mực trong phòng họp khi đạt tới một kết quả đã được nhất trí.",
  },
  {
    id: "ko-c1-business-002",
    level: "C1",
    deck: "business",
    en: "to push ahead with a project",
    zh: "推进项目",
    vi: "xúc tiến dự án",
    ko: "프로젝트를 추진하다",
    roman: "peurojekteureul chujinhada",
    exampleKo: "이사회 승인 후 본격적으로 사업을 추진할 예정입니다.",
    exampleEn: "We plan to push ahead with the project in earnest after board approval.",
    exampleZh: "董事会批准后，我们计划正式推进这个项目。",
    exampleVi: "Sau khi hội đồng quản trị phê duyệt, chúng tôi dự định xúc tiến dự án một cách nghiêm túc.",
    note: "추진하다 implies driving something forward with resources and intent, not just 'doing' it.",
    noteZh: "추진하다（推进）指调动资源、有意图地把事情向前推动，而不只是「做」而已。",
    noteVi: "추진하다 hàm ý chủ động huy động nguồn lực để đẩy việc gì đó tiến lên, chứ không đơn thuần là \"làm\".",
  },
  {
    id: "ko-c1-business-003",
    level: "C1",
    deck: "business",
    en: "to review the matter positively / favorably",
    zh: "积极研究、正面考虑",
    vi: "xem xét một cách tích cực",
    ko: "긍정적으로 검토하다",
    roman: "geungjeongjeogeuro geomtohada",
    exampleKo: "제안하신 조건을 긍정적으로 검토하겠습니다.",
    exampleEn: "We will review the terms you proposed favorably.",
    exampleZh: "我们会积极研究您提出的条件。",
    exampleVi: "Chúng tôi sẽ xem xét một cách tích cực các điều kiện mà quý vị đã đề xuất.",
    note: "A polite, non-committal yes-ish phrase. In Korean business culture it signals openness without a firm promise.",
    noteZh: "一句礼貌、不作承诺、略带肯定的说法。在韩国商务文化中表示持开放态度，但并不作出明确承诺。",
    noteVi: "Một cách nói lịch sự, có phần khích lệ nhưng không cam kết rõ ràng. Trong văn hóa kinh doanh Hàn Quốc, câu này thể hiện thái độ cởi mở mà không hứa hẹn chắc chắn.",
  },
  {
    id: "ko-c1-business-004",
    level: "C1",
    deck: "business",
    en: "to take the lead / take the initiative",
    zh: "掌握主导权",
    vi: "nắm quyền chủ động",
    ko: "주도권을 잡다",
    roman: "judogwoneul japda",
    exampleKo: "협상에서 주도권을 잡으려면 자료가 탄탄해야 합니다.",
    exampleEn: "To take the lead in negotiations, your data must be solid.",
    exampleZh: "要在谈判中掌握主导权，你的资料必须扎实。",
    exampleVi: "Để nắm quyền chủ động trong đàm phán, số liệu của bạn phải thật vững chắc.",
    note: "주도권 (initiative/control) + 잡다 (to grab). Used for seizing control of a deal or discussion.",
    noteZh: "주도권（主导权）+ 잡다（抓住）。用于在交易或讨论中夺取主动权。",
    noteVi: "주도권 (quyền chủ động) + 잡다 (nắm lấy). Dùng khi giành quyền kiểm soát trong một thương vụ hay cuộc thảo luận.",
  },
  {
    id: "ko-c1-business-005",
    level: "C1",
    deck: "business",
    en: "to weigh the pros and cons",
    zh: "权衡得失",
    vi: "cân nhắc được mất",
    ko: "득실을 따지다",
    roman: "deuksireul ttajida",
    exampleKo: "감정에 휘둘리지 말고 냉정하게 득실을 따져 봅시다.",
    exampleEn: "Let's not be swayed by emotion and coolly weigh the pros and cons.",
    exampleZh: "别被情绪左右，让我们冷静地权衡一下得失。",
    exampleVi: "Đừng để cảm xúc chi phối, hãy bình tĩnh cân nhắc kỹ được mất.",
    note: "득실 = gains and losses (得失). 따지다 = to scrutinize/calculate. Common in strategic discussions.",
    noteZh: "득실 = 得失。따지다 = 仔细计较、盘算。常见于战略讨论中。",
    noteVi: "득실 = được và mất (得失). 따지다 = xem xét, tính toán kỹ lưỡng. Thường gặp trong các cuộc thảo luận chiến lược.",
  },
  {
    id: "ko-c1-business-006",
    level: "C1",
    deck: "business",
    en: "to defer / postpone a decision",
    zh: "暂缓决定",
    vi: "tạm hoãn quyết định",
    ko: "결정을 보류하다",
    roman: "gyeoljeongeul boryuhada",
    exampleKo: "추가 검토가 필요해 최종 결정을 보류했습니다.",
    exampleEn: "We deferred the final decision because further review was needed.",
    exampleZh: "由于需要进一步研究，我们暂缓了最终决定。",
    exampleVi: "Vì cần xem xét thêm nên chúng tôi đã tạm hoãn quyết định cuối cùng.",
    note: "보류하다 (to hold/suspend) is the formal verb for tabling something pending more information.",
    noteZh: "보류하다（保留、搁置）是正式用语，指在获得更多信息前先将某事暂时搁置。",
    noteVi: "보류하다 (tạm giữ lại, gác lại) là động từ trang trọng chỉ việc để một việc gì đó lại chờ có thêm thông tin.",
  },
  {
    id: "ko-c1-business-007",
    level: "C1",
    deck: "business",
    en: "to secure a competitive edge",
    zh: "确保竞争力",
    vi: "đảm bảo năng lực cạnh tranh",
    ko: "경쟁력을 확보하다",
    roman: "gyeongjaengnyeogeul hwakbohada",
    exampleKo: "기술 투자를 통해 시장 경쟁력을 확보해야 합니다.",
    exampleEn: "We must secure a competitive edge in the market through tech investment.",
    exampleZh: "我们必须通过技术投资来确保市场竞争力。",
    exampleVi: "Chúng ta phải đảm bảo năng lực cạnh tranh trên thị trường thông qua đầu tư công nghệ.",
    note: "경쟁력 (competitiveness) + 확보하다 (to secure). A staple in strategy and planning meetings.",
    noteZh: "경쟁력（竞争力）+ 확보하다（确保）。战略与规划会议上的常用语。",
    noteVi: "경쟁력 (năng lực cạnh tranh) + 확보하다 (đảm bảo, giành được). Cách diễn đạt quen thuộc trong các cuộc họp chiến lược và lập kế hoạch.",
  },
  {
    id: "ko-c1-business-008",
    level: "C1",
    deck: "business",
    en: "to set up a follow-up meeting",
    zh: "安排后续会议",
    vi: "sắp xếp cuộc họp tiếp theo",
    ko: "후속 미팅을 잡다",
    roman: "husok mitingeul japda",
    exampleKo: "세부 사항은 후속 미팅을 잡아 논의하시죠.",
    exampleEn: "Let's set up a follow-up meeting to discuss the details.",
    exampleZh: "细节部分我们另约后续会议来讨论吧。",
    exampleVi: "Còn chi tiết thì chúng ta hãy sắp xếp một cuộc họp tiếp theo để bàn bạc nhé.",
    note: "후속 (follow-up, 後續). 잡다 here means 'to schedule'. A natural way to defer details politely.",
    noteZh: "후속（后续，後續）。잡다 在这里是「安排、约定」的意思。是把细节礼貌地留待日后的自然说法。",
    noteVi: "후속 (tiếp theo, kế tiếp). Ở đây 잡다 có nghĩa là \"sắp xếp, hẹn\". Đây là cách nói tự nhiên để lịch sự để chi tiết lại bàn sau.",
  },
  {
    id: "ko-c1-business-009",
    level: "C1",
    deck: "business",
    en: "to streamline / cut down the budget",
    zh: "削减预算",
    vi: "cắt giảm ngân sách",
    ko: "예산을 절감하다",
    roman: "yesaneul jeolgamhada",
    exampleKo: "불필요한 지출을 줄여 예산을 절감했습니다.",
    exampleEn: "We streamlined the budget by cutting unnecessary spending.",
    exampleZh: "我们通过削减不必要的开支压缩了预算。",
    exampleVi: "Chúng tôi đã cắt giảm ngân sách bằng cách giảm các khoản chi không cần thiết.",
    note: "절감하다 (to reduce/save, 節減) is more formal than 줄이다 and standard in financial reporting.",
    noteZh: "절감하다（节减，節減）比 줄이다 更正式，是财务报告中的标准用词。",
    noteVi: "절감하다 (tiết giảm) trang trọng hơn 줄이다 (giảm bớt) và là từ chuẩn trong báo cáo tài chính.",
  },
  {
    id: "ko-c1-business-010",
    level: "C1",
    deck: "business",
    en: "to be held accountable / take responsibility",
    zh: "承担责任",
    vi: "chịu trách nhiệm",
    ko: "책임을 지다",
    roman: "chaegimeul jida",
    exampleKo: "이번 차질에 대해서는 제가 책임을 지겠습니다.",
    exampleEn: "I will take responsibility for this setback.",
    exampleZh: "这次的失误由我来承担责任。",
    exampleVi: "Tôi sẽ chịu trách nhiệm về sự cố lần này.",
    note: "책임을 지다 = to bear responsibility. Saying this signals accountability and is valued in Korean work culture.",
    noteZh: "책임을 지다 = 承担责任。说出这句话表明勇于担当，在韩国职场文化中很受重视。",
    noteVi: "책임을 지다 = gánh vác trách nhiệm. Câu nói này thể hiện tinh thần dám chịu trách nhiệm, rất được coi trọng trong văn hóa công sở Hàn Quốc.",
  },
  {
    id: "ko-c1-business-011",
    level: "C1",
    deck: "business",
    en: "to bring up an agenda item / raise an issue",
    zh: "提交议案、提上议程",
    vi: "đưa vấn đề vào chương trình nghị sự",
    ko: "안건을 상정하다",
    roman: "angeoneul sangjeonghada",
    exampleKo: "다음 회의에 그 안건을 정식으로 상정하겠습니다.",
    exampleEn: "I will formally bring that item onto the agenda at the next meeting.",
    exampleZh: "我会在下次会议上正式提交那项议案。",
    exampleVi: "Tôi sẽ chính thức đưa vấn đề đó vào chương trình nghị sự tại cuộc họp tới.",
    note: "안건 (agenda item, 案件) + 상정하다 (to table/submit, 上程). Formal meeting and committee language.",
    noteZh: "안건（议案，案件）+ 상정하다（提交、列入议程，上程）。正式会议和委员会用语。",
    noteVi: "안건 (vấn đề nghị sự) + 상정하다 (trình lên, đưa vào chương trình). Ngôn ngữ trang trọng dùng trong họp hành và ủy ban.",
  },
  {
    id: "ko-c1-business-012",
    level: "C1",
    deck: "business",
    en: "to clearly define roles and responsibilities",
    zh: "分担角色与责任",
    vi: "phân chia vai trò và trách nhiệm",
    ko: "역할과 책임을 분담하다",
    roman: "yeokalgwa chaegimeul bundamhada",
    exampleKo: "혼선을 막으려면 팀원 간 역할과 책임을 분담해야 합니다.",
    exampleEn: "To avoid confusion, we must clearly divide roles and responsibilities among the team.",
    exampleZh: "为避免混乱，团队成员之间必须分担好各自的角色与责任。",
    exampleVi: "Để tránh nhầm lẫn, các thành viên trong nhóm phải phân chia rõ vai trò và trách nhiệm của nhau.",
    note: "분담하다 (to share/divide a burden, 分擔). Used when assigning ownership across a team.",
    noteZh: "분담하다（分担，分擔）。用于在团队中分配职责归属。",
    noteVi: "분담하다 (chia sẻ, phân chia gánh nặng). Dùng khi phân bổ trách nhiệm sở hữu trong một nhóm.",
  },

  // ── society (사회 이슈 / Social Issues) ──
  {
    id: "ko-c1-society-001",
    level: "C1",
    deck: "society",
    en: "the widening gap between rich and poor",
    zh: "贫富差距",
    vi: "khoảng cách giàu nghèo",
    ko: "빈부 격차",
    roman: "binbu gyeokcha",
    exampleKo: "빈부 격차가 심화되면서 사회 불만이 커지고 있습니다.",
    exampleEn: "As the wealth gap widens, social discontent is growing.",
    exampleZh: "随着贫富差距加剧，社会不满情绪日益高涨。",
    exampleVi: "Khi khoảng cách giàu nghèo ngày càng sâu sắc, sự bất mãn trong xã hội cũng gia tăng.",
    note: "빈부 (rich and poor, 貧富) + 격차 (gap, 隔差). A core term in any discussion of inequality.",
    noteZh: "빈부（贫富，貧富）+ 격차（差距，隔差）。讨论不平等问题时的核心词汇。",
    noteVi: "빈부 (giàu và nghèo) + 격차 (khoảng cách). Từ then chốt trong mọi cuộc thảo luận về bất bình đẳng.",
  },
  {
    id: "ko-c1-society-002",
    level: "C1",
    deck: "society",
    en: "an aging society",
    zh: "老龄化社会",
    vi: "xã hội già hóa",
    ko: "고령화 사회",
    roman: "goryeonghwa sahoe",
    exampleKo: "고령화 사회로 접어들면서 연금 문제가 대두되고 있습니다.",
    exampleEn: "As we enter an aging society, the pension issue is coming to the fore.",
    exampleZh: "随着步入老龄化社会，养老金问题日益凸显。",
    exampleVi: "Khi bước vào xã hội già hóa, vấn đề lương hưu đang ngày càng nổi cộm.",
    note: "고령화 (aging, 高齡化). Korea's rapid demographic shift makes this a frequent headline term.",
    noteZh: "고령화（老龄化，高齡化）。韩国人口结构急剧变化，使这个词频频登上新闻头条。",
    noteVi: "고령화 (già hóa). Do cơ cấu dân số Hàn Quốc biến đổi nhanh chóng, đây là từ thường xuyên xuất hiện trên các tiêu đề tin tức.",
  },
  {
    id: "ko-c1-society-003",
    level: "C1",
    deck: "society",
    en: "to come to the fore / become a major issue",
    zh: "凸显、成为焦点",
    vi: "nổi lên, trở thành vấn đề nổi cộm",
    ko: "대두되다",
    roman: "daedudoeda",
    exampleKo: "청년 실업 문제가 사회적 화두로 대두되었습니다.",
    exampleEn: "Youth unemployment has emerged as a major social issue.",
    exampleZh: "青年失业问题已凸显为一大社会议题。",
    exampleVi: "Vấn đề thất nghiệp của thanh niên đã nổi lên như một chủ đề xã hội lớn.",
    note: "대두되다 (to rise to prominence, 擡頭) is used for issues newly gaining attention. More formal than 생기다.",
    noteZh: "대두되다（抬头、凸显，擡頭）用于新近受到关注的问题，比 생기다 更正式。",
    noteVi: "대두되다 (ngóc đầu dậy, nổi lên) dùng cho những vấn đề mới bắt đầu được chú ý, trang trọng hơn 생기다 (xuất hiện, nảy sinh).",
  },
  {
    id: "ko-c1-society-004",
    level: "C1",
    deck: "society",
    en: "to bridge / resolve a generational gap",
    zh: "化解世代矛盾",
    vi: "giải tỏa xung đột thế hệ",
    ko: "세대 갈등을 해소하다",
    roman: "sedae galdeungeul haesohada",
    exampleKo: "세대 갈등을 해소하려면 서로의 입장을 이해해야 합니다.",
    exampleEn: "To resolve the generational conflict, each side must understand the other's position.",
    exampleZh: "要化解世代矛盾，双方必须理解彼此的立场。",
    exampleVi: "Để giải tỏa xung đột thế hệ, hai bên phải hiểu được lập trường của nhau.",
    note: "세대 갈등 (generational conflict). 해소하다 (to dissolve/relieve, 解消) pairs with conflicts and stress.",
    noteZh: "세대 갈등（世代矛盾、代际冲突）。해소하다（化解、消除，解消）常与矛盾、压力搭配。",
    noteVi: "세대 갈등 (xung đột thế hệ). 해소하다 (giải tỏa, xóa bỏ) thường đi kèm với các từ chỉ mâu thuẫn, căng thẳng.",
  },
  {
    id: "ko-c1-society-005",
    level: "C1",
    deck: "society",
    en: "to strengthen the social safety net",
    zh: "强化社会保障网",
    vi: "củng cố mạng lưới an sinh xã hội",
    ko: "사회 안전망을 강화하다",
    roman: "sahoe anjeonmangeul ganghwahada",
    exampleKo: "취약 계층을 위해 사회 안전망을 강화할 필요가 있습니다.",
    exampleEn: "We need to strengthen the social safety net for vulnerable groups.",
    exampleZh: "有必要为弱势群体强化社会保障网。",
    exampleVi: "Cần phải củng cố mạng lưới an sinh xã hội để bảo vệ các nhóm yếu thế.",
    note: "안전망 (safety net) is a direct calque. 취약 계층 (vulnerable groups) often appears alongside it.",
    noteZh: "안전망（安全网、保障网）是直译词。취약 계층（弱势群体）常与之一同出现。",
    noteVi: "안전망 (mạng lưới an toàn/an sinh) là từ dịch trực tiếp. 취약 계층 (nhóm yếu thế) thường xuất hiện cùng với từ này.",
  },
  {
    id: "ko-c1-society-006",
    level: "C1",
    deck: "society",
    en: "to gather / build public consensus",
    zh: "凝聚共识",
    vi: "hình thành sự đồng cảm chung",
    ko: "공감대를 형성하다",
    roman: "gonggamdaereul hyeongseonghada",
    exampleKo: "정책을 추진하기 전에 사회적 공감대를 형성해야 합니다.",
    exampleEn: "Before pushing a policy, we must build public consensus.",
    exampleZh: "在推行政策之前，必须先凝聚社会共识。",
    exampleVi: "Trước khi thúc đẩy một chính sách, cần phải hình thành sự đồng cảm chung trong xã hội.",
    note: "공감대 (shared empathy/common ground) + 형성하다 (to form, 形成). Key for policy and PR contexts.",
    noteZh: "공감대（共鸣、共识基础）+ 형성하다（形成，形成）。政策与公关场合的关键表达。",
    noteVi: "공감대 (nền tảng đồng cảm chung) + 형성하다 (hình thành). Cách diễn đạt then chốt trong bối cảnh chính sách và quan hệ công chúng.",
  },
  {
    id: "ko-c1-society-007",
    level: "C1",
    deck: "society",
    en: "the polarization of public opinion",
    zh: "舆论的两极分化",
    vi: "sự phân cực của dư luận",
    ko: "여론의 양극화",
    roman: "yeoronui yanggeukhwa",
    exampleKo: "이번 사안을 두고 여론의 양극화가 뚜렷합니다.",
    exampleEn: "Public opinion is sharply polarized over this issue.",
    exampleZh: "围绕这一议题，舆论呈现出明显的两极分化。",
    exampleVi: "Xoay quanh vấn đề lần này, sự phân cực của dư luận thể hiện rất rõ rệt.",
    note: "양극화 (polarization, 兩極化) applies to opinion, wealth, and politics alike. Very common in op-eds.",
    noteZh: "양극화（两极分化，兩極化）可用于舆论、财富、政治等方面。社论中非常常见。",
    noteVi: "양극화 (sự phân cực) có thể dùng cho dư luận, tài sản, chính trị. Rất thường gặp trong các bài xã luận.",
  },
  {
    id: "ko-c1-society-008",
    level: "C1",
    deck: "society",
    en: "to take root as a social norm / settle in",
    zh: "在社会上扎根、成为常态",
    vi: "định hình như một chuẩn mực xã hội",
    ko: "사회적으로 자리 잡다",
    roman: "sahoejeogeuro jari japda",
    exampleKo: "재택근무가 하나의 문화로 사회적으로 자리 잡았습니다.",
    exampleEn: "Remote work has taken root as a cultural norm in society.",
    exampleZh: "远程办公已作为一种文化在社会上扎下了根。",
    exampleVi: "Làm việc từ xa đã định hình như một nét văn hóa trong xã hội.",
    note: "자리 잡다 (to settle into place) describes a practice becoming established and accepted.",
    noteZh: "자리 잡다（安顿、扎根）形容一种做法逐渐确立并被接受。",
    noteVi: "자리 잡다 (an vị, bén rễ) diễn tả một tập quán dần được xác lập và được chấp nhận.",
  },
  {
    id: "ko-c1-society-009",
    level: "C1",
    deck: "society",
    en: "to be marginalized / pushed to the fringes",
    zh: "被边缘化",
    vi: "bị gạt ra ngoài lề",
    ko: "소외되다",
    roman: "sooedoeda",
    exampleKo: "기술 발전 속에서 노년층이 소외되지 않도록 해야 합니다.",
    exampleEn: "We must ensure the elderly are not marginalized amid technological progress.",
    exampleZh: "必须确保老年群体不会在技术进步中被边缘化。",
    exampleVi: "Phải đảm bảo rằng người cao tuổi không bị gạt ra ngoài lề trong tiến trình phát triển công nghệ.",
    note: "소외되다 (to be alienated/excluded, 疏外). Central to discussions of the digital divide and inequality.",
    noteZh: "소외되다（被疏远、被排斥，疏外）。是讨论数字鸿沟和不平等问题的核心词。",
    noteVi: "소외되다 (bị xa lánh, bị loại trừ). Là từ trọng tâm khi bàn về khoảng cách số và bất bình đẳng.",
  },
  {
    id: "ko-c1-society-010",
    level: "C1",
    deck: "society",
    en: "a pending issue / unresolved task",
    zh: "当前悬而未决的课题",
    vi: "vấn đề cấp bách đang chờ giải quyết",
    ko: "현안",
    roman: "hyeonan",
    exampleKo: "주거 문제는 정부가 시급히 풀어야 할 현안입니다.",
    exampleEn: "Housing is a pressing issue the government must urgently address.",
    exampleZh: "住房问题是政府亟需解决的当前难题。",
    exampleVi: "Vấn đề nhà ở là vấn đề cấp bách mà chính phủ phải giải quyết khẩn cấp.",
    note: "현안 (current pending matter, 懸案). Sounds formal and journalistic; common in news and policy.",
    noteZh: "현안（悬案、当前课题，懸案）。语气正式、带新闻色彩，常见于新闻和政策报道。",
    noteVi: "현안 (vấn đề còn treo, vấn đề hiện tại). Nghe trang trọng, mang màu sắc báo chí; thường gặp trong tin tức và chính sách.",
  },
  {
    id: "ko-c1-society-011",
    level: "C1",
    deck: "society",
    en: "to raise public awareness",
    zh: "提高认识",
    vi: "nâng cao nhận thức",
    ko: "인식을 제고하다",
    roman: "insigeul jegohada",
    exampleKo: "환경 보호에 대한 시민들의 인식을 제고해야 합니다.",
    exampleEn: "We must raise citizens' awareness of environmental protection.",
    exampleZh: "必须提高市民的环保意识。",
    exampleVi: "Phải nâng cao nhận thức của người dân về bảo vệ môi trường.",
    note: "제고하다 (to enhance/raise, 提高) is a formal alternative to 높이다, common in campaigns and reports.",
    noteZh: "제고하다（提高，提高）是 높이다 的正式替代说法，常见于宣传活动和报告中。",
    noteVi: "제고하다 (nâng cao) là cách nói trang trọng thay cho 높이다, thường gặp trong các chiến dịch truyền thông và báo cáo.",
  },

  // ── abstract (추상적 사고·논리 / Abstract Thinking) ──
  {
    id: "ko-c1-abstract-001",
    level: "C1",
    deck: "abstract",
    en: "based on the premise that ~",
    zh: "在……的前提下",
    vi: "với tiền đề rằng ~",
    ko: "~라는 전제하에",
    roman: "~raneun jeonjeha-e",
    exampleKo: "모두가 동의한다는 전제하에 논의를 진행하겠습니다.",
    exampleEn: "I'll proceed on the premise that everyone agrees.",
    exampleZh: "我将在大家都同意的前提下推进讨论。",
    exampleVi: "Tôi sẽ tiến hành thảo luận với tiền đề rằng tất cả mọi người đều đồng ý.",
    note: "전제 (premise, 前提) + 하에 (under). Sets up a conditional assumption for an argument.",
    noteZh: "전제（前提，前提）+ 하에（在……之下）。为论证设定一个条件性假设。",
    noteVi: "전제 (tiền đề) + 하에 (dưới điều kiện). Thiết lập một giả định có điều kiện cho lập luận.",
  },
  {
    id: "ko-c1-abstract-002",
    level: "C1",
    deck: "abstract",
    en: "to be logically coherent / consistent",
    zh: "逻辑上前后一致",
    vi: "nhất quán về mặt logic",
    ko: "논리적으로 일관되다",
    roman: "nollijeogeuro ilgwandoeda",
    exampleKo: "그의 주장은 처음부터 끝까지 논리적으로 일관됩니다.",
    exampleEn: "His argument is logically consistent from start to finish.",
    exampleZh: "他的论点从头到尾在逻辑上前后一致。",
    exampleVi: "Lập luận của anh ấy nhất quán về mặt logic từ đầu đến cuối.",
    note: "일관되다 (to be consistent, 一貫). Praising or critiquing the internal coherence of an argument.",
    noteZh: "일관되다（一贯、一致，一貫）。用于评价论点内部是否连贯自洽。",
    noteVi: "일관되다 (nhất quán). Dùng để đánh giá tính mạch lạc, tự nhất quán bên trong một lập luận.",
  },
  {
    id: "ko-c1-abstract-003",
    level: "C1",
    deck: "abstract",
    en: "to back up a claim with evidence",
    zh: "用论据支撑主张",
    vi: "củng cố bằng luận cứ",
    ko: "근거를 뒷받침하다",
    roman: "geun-georeul dwitbatchimhada",
    exampleKo: "주장을 뒷받침할 객관적인 근거가 필요합니다.",
    exampleEn: "We need objective evidence to back up the claim.",
    exampleZh: "需要客观的论据来支撑这一主张。",
    exampleVi: "Cần có căn cứ khách quan để củng cố cho luận điểm này.",
    note: "뒷받침하다 (to support/underpin) pairs naturally with 근거 (grounds) and 주장 (claim).",
    noteZh: "뒷받침하다（支撑、佐证）自然地与 근거（论据）和 주장（主张）搭配。",
    noteVi: "뒷받침하다 (hỗ trợ, làm nền tảng cho) thường kết hợp tự nhiên với 근거 (căn cứ) và 주장 (luận điểm).",
  },
  {
    id: "ko-c1-abstract-004",
    level: "C1",
    deck: "abstract",
    en: "to draw a conclusion",
    zh: "得出结论",
    vi: "rút ra kết luận",
    ko: "결론을 도출하다",
    roman: "gyeollon-eul dochulhada",
    exampleKo: "데이터를 종합해 합리적인 결론을 도출했습니다.",
    exampleEn: "We drew a reasonable conclusion by synthesizing the data.",
    exampleZh: "我们综合数据得出了合理的结论。",
    exampleVi: "Chúng tôi đã tổng hợp dữ liệu và rút ra một kết luận hợp lý.",
    note: "도출하다 (to derive, 導出) is the formal verb for reaching conclusions or results from premises.",
    noteZh: "도출하다（导出、得出，導出）是从前提推导出结论或结果的正式动词。",
    noteVi: "도출하다 (rút ra, suy ra) là động từ trang trọng chỉ việc suy luận ra kết luận hoặc kết quả từ tiền đề.",
  },
  {
    id: "ko-c1-abstract-005",
    level: "C1",
    deck: "abstract",
    en: "to put it the other way around / conversely",
    zh: "反过来说",
    vi: "nói ngược lại thì",
    ko: "역으로 말하면",
    roman: "yeogeuro malhamyeon",
    exampleKo: "역으로 말하면, 규제가 없으면 시장이 혼란해진다는 뜻입니다.",
    exampleEn: "Conversely, it means the market becomes chaotic without regulation.",
    exampleZh: "反过来说，就是没有监管市场就会陷入混乱。",
    exampleVi: "Nói ngược lại, điều đó có nghĩa là nếu không có quản lý thì thị trường sẽ trở nên hỗn loạn.",
    note: "역으로 (in reverse, 逆). A useful connective for reframing or testing the inverse of a point.",
    noteZh: "역으로（反过来，逆）。用于重新表述或检验某观点的反面，是有用的连接语。",
    noteVi: "역으로 (theo chiều ngược lại). Từ nối hữu ích để diễn đạt lại hoặc kiểm chứng mặt trái của một quan điểm.",
  },
  {
    id: "ko-c1-abstract-006",
    level: "C1",
    deck: "abstract",
    en: "there is room for debate / it's open to dispute",
    zh: "有争议的余地",
    vi: "còn chỗ để tranh luận",
    ko: "논란의 여지가 있다",
    roman: "nollanui yeojiga itda",
    exampleKo: "그 해석은 여전히 논란의 여지가 있습니다.",
    exampleEn: "That interpretation is still open to debate.",
    exampleZh: "那种解读仍有争议的余地。",
    exampleVi: "Cách diễn giải đó vẫn còn chỗ để tranh luận.",
    note: "여지 (room/leeway, 餘地) + 있다. A measured way to flag that a claim isn't settled.",
    noteZh: "여지（余地，餘地）+ 있다。委婉地指出某个说法尚无定论。",
    noteVi: "여지 (khoảng trống, dư địa) + 있다 (có). Cách nói có chừng mực để chỉ ra rằng một luận điểm chưa ngã ngũ.",
  },
  {
    id: "ko-c1-abstract-007",
    level: "C1",
    deck: "abstract",
    en: "to view it from a different angle",
    zh: "从不同角度看",
    vi: "nhìn từ một góc độ khác",
    ko: "다른 관점에서 보다",
    roman: "dareun gwanjeomeseo boda",
    exampleKo: "같은 현상도 다른 관점에서 보면 해석이 달라집니다.",
    exampleEn: "Even the same phenomenon yields a different reading when viewed from another angle.",
    exampleZh: "同样的现象，从不同角度看，解读也会有所不同。",
    exampleVi: "Cùng một hiện tượng nhưng nếu nhìn từ góc độ khác thì cách diễn giải cũng sẽ khác đi.",
    note: "관점 (viewpoint, 觀點). Essential for introducing an alternative interpretation in discussion.",
    noteZh: "관점（观点，觀點）。在讨论中引出另一种解读时必不可少。",
    noteVi: "관점 (quan điểm, góc nhìn). Thiết yếu khi muốn đưa ra một cách diễn giải khác trong thảo luận.",
  },
  {
    id: "ko-c1-abstract-008",
    level: "C1",
    deck: "abstract",
    en: "to be a logical leap / a stretch",
    zh: "逻辑跳跃太大",
    vi: "bước nhảy logic quá lớn",
    ko: "비약이 심하다",
    roman: "biyagi simhada",
    exampleKo: "전제에서 결론으로 가는 과정에 비약이 심합니다.",
    exampleEn: "There's a serious logical leap from the premise to the conclusion.",
    exampleZh: "从前提到结论的过程中逻辑跳跃太大。",
    exampleVi: "Trong quá trình đi từ tiền đề đến kết luận có một bước nhảy logic quá lớn.",
    note: "비약 (a leap, 飛躍) here is a fallacy of jumping to a conclusion. A precise critique of weak reasoning.",
    noteZh: "비약（飞跃、跳跃，飛躍）在这里指妄下结论的谬误，是对薄弱论证的精准批评。",
    noteVi: "비약 (bước nhảy vọt) ở đây chỉ lỗi ngụy biện vội vàng kết luận. Là lời phê bình chính xác đối với lập luận thiếu chặt chẽ.",
  },
  {
    id: "ko-c1-abstract-009",
    level: "C1",
    deck: "abstract",
    en: "to be a matter of perspective / it depends how you see it",
    zh: "取决于你怎么看",
    vi: "tùy vào cách nhìn nhận",
    ko: "보기 나름이다",
    roman: "bogi nareumida",
    exampleKo: "성공인지 실패인지는 보기 나름입니다.",
    exampleEn: "Whether it's a success or a failure depends on how you look at it.",
    exampleZh: "是成功还是失败，取决于你怎么看。",
    exampleVi: "Đó là thành công hay thất bại thì tùy vào cách nhìn nhận của mỗi người.",
    note: "나름이다 = 'depends on'. A natural, idiomatic way to say something is relative or subjective.",
    noteZh: "나름이다 =「取决于……」。表达某事相对、主观的自然地道说法。",
    noteVi: "나름이다 = \"tùy thuộc vào...\". Cách nói tự nhiên, đậm chất thành ngữ để diễn tả một điều gì đó mang tính tương đối, chủ quan.",
  },
  {
    id: "ko-c1-abstract-010",
    level: "C1",
    deck: "abstract",
    en: "in essence / at its core",
    zh: "本质上",
    vi: "về bản chất",
    ko: "본질적으로",
    roman: "bonjiljeogeuro",
    exampleKo: "이 문제는 본질적으로 신뢰의 문제입니다.",
    exampleEn: "At its core, this is a question of trust.",
    exampleZh: "这个问题本质上是信任的问题。",
    exampleVi: "Về bản chất, vấn đề này là vấn đề về lòng tin.",
    note: "본질 (essence, 本質). Use to cut past surface details to the fundamental point.",
    noteZh: "본질（本质，本質）。用于抛开表面细节、直指根本。",
    noteVi: "본질 (bản chất). Dùng khi muốn bỏ qua các chi tiết bề mặt để đi thẳng vào cốt lõi vấn đề.",
  },
  {
    id: "ko-c1-abstract-011",
    level: "C1",
    deck: "abstract",
    en: "to take ~ for granted / regard as a given",
    zh: "视为理所当然",
    vi: "coi là điều hiển nhiên",
    ko: "당연시하다",
    roman: "dangyeonsihada",
    exampleKo: "우리는 표현의 자유를 너무 당연시하는 경향이 있습니다.",
    exampleEn: "We tend to take freedom of expression too much for granted.",
    exampleZh: "我们往往过于把表达自由视为理所当然。",
    exampleVi: "Chúng ta có xu hướng coi tự do ngôn luận là điều quá hiển nhiên.",
    note: "당연시하다 (to treat as obvious, 當然視) flags an unexamined assumption worth questioning.",
    noteZh: "당연시하다（视为当然，當然視）点出一个未经审视、值得质疑的假设。",
    noteVi: "당연시하다 (coi là đương nhiên) chỉ ra một giả định chưa được xem xét kỹ, đáng để đặt câu hỏi.",
  },

  // ── media (미디어·여론 / Media) ──
  {
    id: "ko-c1-media-001",
    level: "C1",
    deck: "media",
    en: "to report in detail / cover extensively",
    zh: "详细报道",
    vi: "đưa tin chi tiết",
    ko: "상세히 보도하다",
    roman: "sangsehi bodohada",
    exampleKo: "언론은 사건의 경위를 상세히 보도했습니다.",
    exampleEn: "The media reported the circumstances of the incident in detail.",
    exampleZh: "媒体详细报道了事件的来龙去脉。",
    exampleVi: "Truyền thông đã đưa tin chi tiết về diễn biến của sự việc.",
    note: "보도하다 (to report, 報道) is the journalistic verb, distinct from everyday 알리다 (to inform).",
    noteZh: "보도하다（报道，報道）是新闻用语，与日常的 알리다（告知）不同。",
    noteVi: "보도하다 (đưa tin) là động từ dùng trong báo chí, khác với 알리다 (thông báo) dùng trong đời thường.",
  },
  {
    id: "ko-c1-media-002",
    level: "C1",
    deck: "media",
    en: "to spread / circulate (rumors, information)",
    zh: "散布、流传",
    vi: "bị lan truyền, phát tán",
    ko: "유포되다",
    roman: "yupodoeda",
    exampleKo: "확인되지 않은 정보가 온라인에 빠르게 유포되었습니다.",
    exampleEn: "Unverified information spread rapidly online.",
    exampleZh: "未经证实的信息在网上迅速散布开来。",
    exampleVi: "Thông tin chưa được xác thực đã nhanh chóng lan truyền trên mạng.",
    note: "유포되다 (to be disseminated, 流布) often carries a negative nuance — rumors or misinformation.",
    noteZh: "유포되다（散布、流传，流布）常带贬义，多指谣言或不实信息。",
    noteVi: "유포되다 (bị phát tán, lan truyền) thường mang sắc thái tiêu cực — chỉ tin đồn hoặc thông tin sai lệch.",
  },
  {
    id: "ko-c1-media-003",
    level: "C1",
    deck: "media",
    en: "to gauge / read public opinion",
    zh: "汇集、听取舆论",
    vi: "thu thập dư luận",
    ko: "여론을 수렴하다",
    roman: "yeoroneul suryeomhada",
    exampleKo: "정부는 공청회를 열어 여론을 수렴했습니다.",
    exampleEn: "The government held a public hearing to gather public opinion.",
    exampleZh: "政府召开听证会以汇集民意。",
    exampleVi: "Chính phủ đã tổ chức buổi điều trần công khai để thu thập dư luận.",
    note: "수렴하다 (to collect/converge, 收斂) means gathering diverse views toward a decision. Formal register.",
    noteZh: "수렴하다（汇集、收敛，收斂）指集思广益、汇总各方意见以作决定。属正式用语。",
    noteVi: "수렴하다 (thu thập, quy tụ) nghĩa là tập hợp nhiều ý kiến khác nhau để đi đến quyết định. Thuộc văn phong trang trọng.",
  },
  {
    id: "ko-c1-media-004",
    level: "C1",
    deck: "media",
    en: "fake news / false reporting",
    zh: "虚假报道",
    vi: "tin tức sai sự thật",
    ko: "허위 보도",
    roman: "heowi bodo",
    exampleKo: "허위 보도로 인한 피해가 갈수록 심각해지고 있습니다.",
    exampleEn: "Damage from false reporting is becoming increasingly serious.",
    exampleZh: "虚假报道造成的危害日趋严重。",
    exampleVi: "Thiệt hại do tin tức sai sự thật gây ra ngày càng nghiêm trọng.",
    note: "허위 (false, 虛僞) + 보도 (report). The standard term in legal and media-ethics discussions.",
    noteZh: "허위（虚假，虛僞）+ 보도（报道）。是法律和媒体伦理讨论中的标准用语。",
    noteVi: "허위 (giả dối, sai sự thật) + 보도 (đưa tin). Là thuật ngữ chuẩn trong các thảo luận về pháp luật và đạo đức truyền thông.",
  },
  {
    id: "ko-c1-media-005",
    level: "C1",
    deck: "media",
    en: "to frame an issue a certain way",
    zh: "给……扣上某种框架、带节奏",
    vi: "gán khung định kiến",
    ko: "프레임을 씌우다",
    roman: "peureimeul ssiuda",
    exampleKo: "특정 진영이 그 사건에 정치적 프레임을 씌웠습니다.",
    exampleEn: "A particular faction framed the incident politically.",
    exampleZh: "某个阵营给那起事件扣上了政治框架。",
    exampleVi: "Một phe phái nhất định đã gán khung chính trị cho sự việc đó.",
    note: "프레임을 씌우다 = to impose a frame/narrative. 씌우다 (to put on/over) carries a manipulative nuance.",
    noteZh: "프레임을 씌우다 = 强加某种框架、叙事。씌우다（罩上、扣上）带有操纵、误导的意味。",
    noteVi: "프레임을 씌우다 = áp đặt một khung/câu chuyện nào đó. 씌우다 (khoác lên, chụp lên) mang sắc thái thao túng, gây hiểu lầm.",
  },
  {
    id: "ko-c1-media-006",
    level: "C1",
    deck: "media",
    en: "to be reported sensationally / blown up",
    zh: "以耸动方式报道",
    vi: "xử lý theo hướng giật gân",
    ko: "자극적으로 다루다",
    roman: "jageukjeogeuro daruda",
    exampleKo: "일부 매체가 사건을 지나치게 자극적으로 다뤘습니다.",
    exampleEn: "Some outlets covered the incident far too sensationally.",
    exampleZh: "部分媒体对该事件的报道过于耸人听闻。",
    exampleVi: "Một số cơ quan truyền thông đã xử lý sự việc theo hướng giật gân quá mức.",
    note: "자극적 (sensational/provocative, 刺戟的) + 다루다 (to handle/treat). A critique of tabloid-style coverage.",
    noteZh: "자극적（耸动、刺激性的，刺戟的）+ 다루다（处理、对待）。批评小报式的报道手法。",
    noteVi: "자극적 (giật gân, kích động) + 다루다 (xử lý, đối xử). Lời phê phán cách đưa tin kiểu báo lá cải.",
  },
  {
    id: "ko-c1-media-007",
    level: "C1",
    deck: "media",
    en: "to shape / foster public opinion",
    zh: "营造舆论",
    vi: "tạo dựng dư luận",
    ko: "여론을 조성하다",
    roman: "yeoroneul josonghada",
    exampleKo: "광고는 특정 제품에 우호적인 여론을 조성합니다.",
    exampleEn: "Advertising fosters favorable public opinion toward certain products.",
    exampleZh: "广告为特定产品营造有利的舆论。",
    exampleVi: "Quảng cáo tạo dựng dư luận có thiện cảm với một sản phẩm nhất định.",
    note: "조성하다 (to create/build up, 造成). Used for deliberately shaping a mood or sentiment.",
    noteZh: "조성하다（营造、造成，造成）。用于刻意营造某种氛围或情绪。",
    noteVi: "조성하다 (tạo dựng, hình thành). Dùng khi cố ý tạo ra một bầu không khí hay cảm xúc nào đó.",
  },
  {
    id: "ko-c1-media-008",
    level: "C1",
    deck: "media",
    en: "to verify the facts / fact-check",
    zh: "核实事实",
    vi: "xác minh sự thật",
    ko: "사실 관계를 확인하다",
    roman: "sasil gwangyereul hwaginhada",
    exampleKo: "보도 전에 반드시 사실 관계를 확인해야 합니다.",
    exampleEn: "The facts must be verified before reporting.",
    exampleZh: "报道之前务必核实事实真相。",
    exampleVi: "Trước khi đưa tin, nhất định phải xác minh sự thật.",
    note: "사실 관계 (the facts / factual relations) is the set phrase journalists use for what needs checking.",
    noteZh: "사실 관계（事实关系、事实真相）是记者用来指称需要核实内容的固定说法。",
    noteVi: "사실 관계 (tình tiết sự việc, sự thật) là cụm từ cố định mà nhà báo dùng để chỉ nội dung cần kiểm chứng.",
  },
  {
    id: "ko-c1-media-009",
    level: "C1",
    deck: "media",
    en: "to be in the spotlight / draw attention",
    zh: "吸引关注、引人注目",
    vi: "thu hút sự chú ý",
    ko: "이목을 끌다",
    roman: "imogeul kkeulda",
    exampleKo: "그 발언은 단숨에 대중의 이목을 끌었습니다.",
    exampleEn: "That remark instantly drew the public's attention.",
    exampleZh: "那番言论一下子吸引了公众的目光。",
    exampleVi: "Phát ngôn đó lập tức thu hút sự chú ý của công chúng.",
    note: "이목 (eyes and ears → attention, 耳目) + 끌다 (to draw). More literary than 관심을 끌다.",
    noteZh: "이목（耳目→关注，耳目）+ 끌다（吸引）。比 관심을 끌다 更书面。",
    noteVi: "이목 (tai mắt → sự chú ý) + 끌다 (thu hút, kéo). Mang tính văn chương hơn so với 관심을 끌다.",
  },
  {
    id: "ko-c1-media-010",
    level: "C1",
    deck: "media",
    en: "to correct / issue a correction to a report",
    zh: "更正报道",
    vi: "đính chính bản tin",
    ko: "보도를 정정하다",
    roman: "bodoreul jeongjeonghada",
    exampleKo: "오류가 드러나자 방송사는 즉시 보도를 정정했습니다.",
    exampleEn: "Once the error came to light, the broadcaster immediately corrected the report.",
    exampleZh: "错误一经曝光，电视台立即更正了报道。",
    exampleVi: "Ngay khi sai sót bị phát hiện, đài truyền hình đã lập tức đính chính bản tin.",
    note: "정정하다 (to correct/rectify, 訂正) is the formal verb for issuing a correction.",
    noteZh: "정정하다（更正、订正，訂正）是发布更正启事的正式动词。",
    noteVi: "정정하다 (đính chính, sửa lại) là động từ trang trọng dùng khi công bố một bản đính chính.",
  },
  {
    id: "ko-c1-media-011",
    level: "C1",
    deck: "media",
    en: "to take ~ at face value / accept uncritically",
    zh: "全盘照信、不加辨别地接受",
    vi: "tin ngay không suy xét",
    ko: "곧이곧대로 받아들이다",
    roman: "gojigotdaero badadeurida",
    exampleKo: "기사를 곧이곧대로 받아들이기보다 출처를 따져야 합니다.",
    exampleEn: "Rather than taking an article at face value, you should examine the source.",
    exampleZh: "与其对报道全盘照信，不如追究一下消息来源。",
    exampleVi: "Thay vì tin ngay bài báo mà không suy xét, nên xem xét kỹ nguồn tin.",
    note: "곧이곧대로 = literally/uncritically. A native idiom warning against naive acceptance of information.",
    noteZh: "곧이곧대로 = 原封不动地、不加辨别地。是提醒不要轻信信息的固有惯用语。",
    noteVi: "곧이곧대로 = một cách y nguyên, không suy xét. Là thành ngữ thuần Hàn nhắc nhở không nên cả tin vào thông tin.",
  },
];
