/**
 * C2 (전문가 / Proficient) 한국어 학습 콘텐츠 — 영어권 학습자 대상.
 * 각 카드: 한국어 표현(ko) + 로마자(roman) + 영어 뜻(en) + 예문(한/영).
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * note 는 영어(학습자 모국어)로 사용 맥락·뉘앙스를 설명한다.
 *
 * C2 수준: 원어민급 뉘앙스, 관용구·사자성어, 격식체·문어체,
 * 미묘한 어감 차이를 다룬다.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_C2_DECKS: Deck[] = [
  {
    id: "academic",
    level: "C2",
    title: { ko: "전문·학술", en: "Academic", zh: "专业·学术", vi: "Chuyên môn · Học thuật" },
    description: {
      ko: "논문·발표·토론의 학술 어휘",
      en: "Scholarly vocabulary for papers, talks, and debate",
      zh: "论文、发表、讨论的学术词汇",
      vi: "Từ vựng học thuật cho luận văn, thuyết trình và tranh luận",
    },
    order: 1,
    icon: "GraduationCap",
  },
  {
    id: "idioms",
    level: "C2",
    title: { ko: "관용 표현·속담", en: "Idioms & Proverbs", zh: "惯用表达·谚语", vi: "Thành ngữ & Tục ngữ" },
    description: {
      ko: "사자성어와 토박이 속담",
      en: "Four-character idioms and native proverbs",
      zh: "四字成语与本土谚语",
      vi: "Thành ngữ bốn chữ Hán và tục ngữ thuần Hàn",
    },
    order: 2,
    icon: "BookMarked",
  },
  {
    id: "nuance",
    level: "C2",
    title: { ko: "미묘한 뉘앙스", en: "Subtle Nuance", zh: "微妙的语感", vi: "Sắc thái tinh tế" },
    description: {
      ko: "비슷하지만 어감이 다른 표현",
      en: "Near-synonyms with subtly different shades",
      zh: "相似但语感不同的表达",
      vi: "Những cách diễn đạt gần giống nhau nhưng khác sắc thái",
    },
    order: 3,
    icon: "Sparkles",
  },
  {
    id: "formal",
    level: "C2",
    title: { ko: "격식·연설", en: "Formal Speech", zh: "正式·演讲", vi: "Trang trọng · Diễn văn" },
    description: {
      ko: "연설·문어체·공식 격식 표현",
      en: "Oratory, literary register, and official formality",
      zh: "演讲、书面语、正式场合的表达",
      vi: "Diễn văn, văn phong trang trọng và cách diễn đạt nghi thức chính thức",
    },
    order: 4,
    icon: "Megaphone",
  },
];

export const KO_C2_CARDS: VocabCard[] = [
  // ── academic (전문·학술) ──────────────────────────────────────
  {
    id: "ko-c2-academic-001",
    level: "C2",
    deck: "academic",
    en: "to take ~ as a premise / presuppose",
    zh: "以……为前提／预设",
    vi: "coi ... là tiền đề / giả định trước",
    ko: "전제하다",
    roman: "jeonjehada",
    exampleKo: "이 논의는 시장이 합리적이라는 가정을 전제합니다.",
    exampleEn: "This discussion presupposes that the market is rational.",
    exampleZh: "本论述以市场是理性的这一假设为前提。",
    exampleVi: "Luận điểm này lấy giả định thị trường là hợp lý làm tiền đề.",
    note: "Academic staple for stating an underlying assumption before an argument.",
    noteZh: "学术上常用，在论证之前陈述其底层假设。",
    noteVi: "Cách diễn đạt học thuật phổ biến để nêu giả định nền tảng trước khi lập luận.",
  },
  {
    id: "ko-c2-academic-002",
    level: "C2",
    deck: "academic",
    en: "to substantiate / demonstrate (with evidence)",
    zh: "证实／论证（以证据）",
    vi: "chứng thực / chứng minh (bằng bằng chứng)",
    ko: "입증하다",
    roman: "ipjeunghada",
    exampleKo: "연구진은 가설을 실험으로 입증했습니다.",
    exampleEn: "The researchers substantiated the hypothesis through experiment.",
    exampleZh: "研究团队通过实验证实了假设。",
    exampleVi: "Nhóm nghiên cứu đã chứng thực giả thuyết bằng thực nghiệm.",
    note: "Stronger than 보여주다 — implies proof backed by rigorous evidence.",
    noteZh: "比 보여주다（展示）更强，含有以严谨证据加以证明之意。",
    noteVi: "Mạnh hơn 보여주다 (cho thấy) — hàm ý chứng minh bằng bằng chứng chặt chẽ.",
  },
  {
    id: "ko-c2-academic-003",
    level: "C2",
    deck: "academic",
    en: "to be at odds with / contradict",
    zh: "相互抵触／矛盾",
    vi: "mâu thuẫn / xung đột với nhau",
    ko: "상충하다",
    roman: "sangchunghada",
    exampleKo: "두 이론의 결론은 서로 상충합니다.",
    exampleEn: "The conclusions of the two theories are at odds with each other.",
    exampleZh: "两种理论的结论相互抵触。",
    exampleVi: "Kết luận của hai lý thuyết mâu thuẫn với nhau.",
    note: "Formal way to say two findings or interests conflict.",
    noteZh: "正式说法，表示两个结论或利益相互冲突。",
    noteVi: "Cách nói trang trọng để diễn tả hai kết quả hoặc lợi ích xung đột nhau.",
  },
  {
    id: "ko-c2-academic-004",
    level: "C2",
    deck: "academic",
    en: "consideration / point worth weighing",
    zh: "考量事项／需权衡之处",
    vi: "vấn đề cần cân nhắc / điểm cần xem xét",
    ko: "고려 사항",
    roman: "goryeo sahang",
    exampleKo: "정책 설계에서 형평성은 핵심 고려 사항입니다.",
    exampleEn: "Equity is a key consideration in policy design.",
    exampleZh: "在政策设计中，公平性是核心的考量事项。",
    exampleVi: "Tính công bằng là yếu tố cần cân nhắc cốt lõi trong thiết kế chính sách.",
    note: "Set phrase in reports for 'factors to take into account'.",
    noteZh: "报告中的固定用语，指“需纳入考虑的因素”。",
    noteVi: "Cụm từ cố định trong báo cáo, chỉ 'những yếu tố cần được xem xét'.",
  },
  {
    id: "ko-c2-academic-005",
    level: "C2",
    deck: "academic",
    en: "in this regard / on this point",
    zh: "在这一方面／就这一点而言",
    vi: "về mặt này / xét ở điểm này",
    ko: "이러한 측면에서",
    roman: "ireohan cheungmyeoneseo",
    exampleKo: "이러한 측면에서 기존 연구는 한계가 분명합니다.",
    exampleEn: "In this regard, the existing research has clear limitations.",
    exampleZh: "在这一方面，既有研究的局限十分明显。",
    exampleVi: "Về mặt này, các nghiên cứu trước đây có những hạn chế rõ ràng.",
    note: "Smooth connective to pivot a paragraph in academic prose.",
    noteZh: "学术文章中承上启下、转换段落的顺畅衔接语。",
    noteVi: "Từ nối mượt mà để chuyển đoạn trong văn phong học thuật.",
  },
  {
    id: "ko-c2-academic-006",
    level: "C2",
    deck: "academic",
    en: "to be interpreted / read as",
    zh: "被解释／被解读为",
    vi: "được diễn giải / được hiểu là",
    ko: "해석되다",
    roman: "haeseokdoeda",
    exampleKo: "이 결과는 두 가지로 해석될 수 있습니다.",
    exampleEn: "This result can be interpreted in two ways.",
    exampleZh: "这一结果可以有两种解读。",
    exampleVi: "Kết quả này có thể được diễn giải theo hai cách.",
    note: "Passive form preferred in objective academic writing.",
    noteZh: "客观的学术写作中偏好使用的被动形式。",
    noteVi: "Dạng bị động được ưa dùng trong văn phong học thuật khách quan.",
  },
  {
    id: "ko-c2-academic-007",
    level: "C2",
    deck: "academic",
    en: "by extension / furthermore",
    zh: "进而／更进一步",
    vi: "hơn nữa / xa hơn nữa",
    ko: "나아가",
    roman: "naaga",
    exampleKo: "나아가 이 발견은 교육 정책에도 시사점을 줍니다.",
    exampleEn: "Furthermore, this finding has implications for education policy.",
    exampleZh: "更进一步，这一发现对教育政策也具有启示。",
    exampleVi: "Hơn nữa, phát hiện này còn mang lại hàm ý cho chính sách giáo dục.",
    note: "Elevated 'moreover'; signals the argument is broadening in scope.",
    noteZh: "较为文雅的“而且”，表示论述正在扩展范围。",
    noteVi: "Cách nói trang trọng của 'hơn nữa'; báo hiệu lập luận đang được mở rộng phạm vi.",
  },
  {
    id: "ko-c2-academic-008",
    level: "C2",
    deck: "academic",
    en: "implication / suggested meaning",
    zh: "启示／启发意义",
    vi: "hàm ý / ý nghĩa gợi mở",
    ko: "시사점",
    roman: "sisajeom",
    exampleKo: "이 연구가 주는 시사점은 적지 않습니다.",
    exampleEn: "The implications of this study are considerable.",
    exampleZh: "这项研究带来的启示不在少数。",
    exampleVi: "Hàm ý mà nghiên cứu này mang lại không hề nhỏ.",
    note: "Common in conclusions: the 'so what' takeaway of a study.",
    noteZh: "常见于结论部分：研究“意味着什么”的要点。",
    noteVi: "Thường dùng trong phần kết luận: điều rút ra được ('vậy thì sao') từ nghiên cứu.",
  },
  {
    id: "ko-c2-academic-009",
    level: "C2",
    deck: "academic",
    en: "to be limited to / confined to",
    zh: "局限于／限于",
    vi: "bị giới hạn ở / chỉ giới hạn trong",
    ko: "국한되다",
    roman: "gukhandoeda",
    exampleKo: "이 현상은 도시 지역에 국한되지 않습니다.",
    exampleEn: "This phenomenon is not confined to urban areas.",
    exampleZh: "这一现象并不局限于城市地区。",
    exampleVi: "Hiện tượng này không chỉ giới hạn ở khu vực đô thị.",
    note: "Formal; often used in the negative to claim broad applicability.",
    noteZh: "正式用语；常以否定形式使用，以主张其适用范围广泛。",
    noteVi: "Trang trọng; thường dùng ở dạng phủ định để khẳng định phạm vi áp dụng rộng.",
  },
  {
    id: "ko-c2-academic-010",
    level: "C2",
    deck: "academic",
    en: "to originate from / stem from",
    zh: "源于／起因于",
    vi: "bắt nguồn từ / xuất phát từ",
    ko: "기인하다",
    roman: "giinhada",
    exampleKo: "그 차이는 표본의 편향에 기인합니다.",
    exampleEn: "The difference stems from sampling bias.",
    exampleZh: "那一差异源于样本的偏差。",
    exampleVi: "Sự khác biệt đó bắt nguồn từ sai lệch của mẫu.",
    note: "'기인하다 + 에' = to originate from a cause; very academic.",
    noteZh: "“기인하다＋에”表示起因于某原因；非常学术化。",
    noteVi: "'기인하다 + 에' = bắt nguồn từ một nguyên nhân; rất học thuật.",
  },
  {
    id: "ko-c2-academic-011",
    level: "C2",
    deck: "academic",
    en: "to investigate and clarify",
    zh: "查明／阐明",
    vi: "điều tra làm rõ / xác minh làm sáng tỏ",
    ko: "규명하다",
    roman: "gyumyeonghada",
    exampleKo: "이 논문은 원인과 결과의 관계를 규명합니다.",
    exampleEn: "This paper clarifies the relationship between cause and effect.",
    exampleZh: "本论文阐明了原因与结果之间的关系。",
    exampleVi: "Luận văn này làm rõ mối quan hệ giữa nguyên nhân và kết quả.",
    note: "To investigate and establish a fact clearly; stronger than 밝히다.",
    noteZh: "调查并清楚地确立某一事实；比 밝히다（揭示）更强。",
    noteVi: "Điều tra và xác lập một sự thật một cách rõ ràng; mạnh hơn 밝히다 (làm sáng tỏ).",
  },

  // ── idioms (관용 표현·속담) ────────────────────────────────────
  {
    id: "ko-c2-idioms-001",
    level: "C2",
    deck: "idioms",
    en: "self-contradiction (lit. 'spear and shield')",
    zh: "矛盾（字面为“矛与盾”）",
    vi: "mâu thuẫn (nghĩa đen: 'giáo và khiên')",
    ko: "모순",
    roman: "mosun",
    exampleKo: "그 주장은 그 자체로 모순입니다.",
    exampleEn: "That claim is a contradiction in itself.",
    exampleZh: "那一主张本身就是自相矛盾。",
    exampleVi: "Bản thân lập luận đó đã tự mâu thuẫn.",
    note: "From a parable of a vendor selling an all-piercing spear and an impenetrable shield.",
    noteZh: "源自一则寓言：商贩同时叫卖无坚不摧的矛与坚不可破的盾。",
    noteVi: "Bắt nguồn từ câu chuyện ngụ ngôn về người bán hàng rao bán cây giáo đâm xuyên mọi thứ và tấm khiên không gì xuyên thủng được.",
  },
  {
    id: "ko-c2-idioms-002",
    level: "C2",
    deck: "idioms",
    en: "killing two birds with one stone (one stone, two birds)",
    zh: "一石二鸟",
    vi: "nhất tiễn hạ song điêu (một mũi tên hạ hai chim)",
    ko: "일석이조",
    roman: "ilseogijo",
    exampleKo: "재택근무는 시간도 아끼고 건강도 챙기니 일석이조예요.",
    exampleEn: "Working from home saves time and improves health — two birds with one stone.",
    exampleZh: "居家办公既省时间又能兼顾健康，真是一石二鸟。",
    exampleVi: "Làm việc tại nhà vừa tiết kiệm thời gian vừa tốt cho sức khỏe, đúng là nhất cử lưỡng tiện.",
    note: "Four-character idiom; the everyday native equivalent is 꿩 먹고 알 먹기.",
    noteZh: "四字成语；日常本土说法对应 꿩 먹고 알 먹기（吃了野鸡又得蛋）。",
    noteVi: "Thành ngữ bốn chữ Hán; cách nói thuần Hàn thường ngày tương đương là 꿩 먹고 알 먹기 (ăn thịt gà lôi lại được cả trứng).",
  },
  {
    id: "ko-c2-idioms-003",
    level: "C2",
    deck: "idioms",
    en: "going to great lengths through hardship (enduring trials)",
    zh: "苦尽甘来",
    vi: "khổ tận cam lai",
    ko: "고진감래",
    roman: "gojingamnae",
    exampleKo: "고진감래라더니, 오랜 고생 끝에 결실을 맺었네요.",
    exampleEn: "As they say, no pain no gain — long hardship finally bore fruit.",
    exampleZh: "正所谓苦尽甘来，长久的辛劳终于结出了果实。",
    exampleVi: "Đúng là khổ tận cam lai, sau bao gian khổ cuối cùng cũng gặt hái được thành quả.",
    note: "Lit. 'bitterness ends, sweetness comes' — Korean 'no pain, no gain'.",
    noteZh: "字面意为“苦尽则甘来”——相当于“不劳无获”。",
    noteVi: "Nghĩa đen: 'đắng hết thì ngọt đến' — tương đương 'không khổ thì không được' trong tiếng Hàn.",
  },
  {
    id: "ko-c2-idioms-004",
    level: "C2",
    deck: "idioms",
    en: "even monkeys fall from trees (anyone can slip up)",
    zh: "猴子也会从树上掉下来（人人都会失手）",
    vi: "khỉ cũng có lúc rơi khỏi cây (ai cũng có lúc sai sót)",
    ko: "원숭이도 나무에서 떨어진다",
    roman: "wonsungido namueseo tteoreojinda",
    exampleKo: "원숭이도 나무에서 떨어진다고, 전문가도 실수할 때가 있죠.",
    exampleEn: "Even monkeys fall from trees — even experts make mistakes.",
    exampleZh: "常言道猴子也会从树上掉下来，专家也有出错的时候。",
    exampleVi: "Người ta vẫn nói khỉ cũng có lúc rơi khỏi cây, chuyên gia cũng có lúc mắc sai lầm mà.",
    note: "Native proverb to console someone skilled who erred.",
    noteZh: "本土谚语，用于安慰失手的能手。",
    noteVi: "Tục ngữ thuần Hàn dùng để an ủi người giỏi nhưng lỡ mắc sai lầm.",
  },
  {
    id: "ko-c2-idioms-005",
    level: "C2",
    deck: "idioms",
    en: "a frog in a well (a narrow, limited worldview)",
    zh: "井底之蛙（眼界狭隘）",
    vi: "ếch ngồi đáy giếng (tầm nhìn hạn hẹp)",
    ko: "우물 안 개구리",
    roman: "umul an gaeguri",
    exampleKo: "해외에 나가 보니 제가 우물 안 개구리였더라고요.",
    exampleEn: "Going abroad, I realized I'd been a frog in a well.",
    exampleZh: "出国之后才发现，原来我一直是井底之蛙。",
    exampleVi: "Ra nước ngoài rồi tôi mới nhận ra mình đã như ếch ngồi đáy giếng.",
    note: "Describes someone unaware of the wider world; mildly self-deprecating.",
    noteZh: "形容不知外面广阔世界的人；带有轻微的自嘲意味。",
    noteVi: "Miêu tả người không biết đến thế giới rộng lớn bên ngoài; mang chút tự giễu nhẹ nhàng.",
  },
  {
    id: "ko-c2-idioms-006",
    level: "C2",
    deck: "idioms",
    en: "to add insult to injury (lit. 'salt on a wound')",
    zh: "祸不单行／雪上加霜",
    vi: "họa vô đơn chí / càng thêm tồi tệ",
    ko: "엎친 데 덮친 격",
    roman: "eopchin de deopchin gyeok",
    exampleKo: "차도 고장 났는데 비까지 오니 엎친 데 덮친 격이네요.",
    exampleEn: "The car broke down and then it rained — when it rains, it pours.",
    exampleZh: "车抛锚了偏偏又下起雨，真是雪上加霜。",
    exampleVi: "Xe đã hỏng lại còn gặp mưa, đúng là họa vô đơn chí.",
    note: "Native idiom for misfortunes piling up at once.",
    noteZh: "本土惯用语，指种种不幸同时接踵而至。",
    noteVi: "Thành ngữ thuần Hàn chỉ những điều bất hạnh dồn dập xảy đến cùng lúc.",
  },
  {
    id: "ko-c2-idioms-007",
    level: "C2",
    deck: "idioms",
    en: "out of the blue / a bolt from clear sky",
    zh: "晴天霹雳",
    vi: "sét đánh giữa trời quang",
    ko: "청천벽력",
    roman: "cheongcheonbyeongnyeok",
    exampleKo: "해고 통보는 그야말로 청천벽력이었습니다.",
    exampleEn: "The layoff notice was a complete bolt from the blue.",
    exampleZh: "那份解雇通知简直就是晴天霹雳。",
    exampleVi: "Thông báo sa thải quả thực như sét đánh giữa trời quang.",
    note: "Lit. 'thunderbolt from a clear sky' — a sudden, shocking calamity.",
    noteZh: "字面意为“晴朗天空中的霹雳”——突如其来、令人震惊的灾祸。",
    noteVi: "Nghĩa đen: 'tiếng sét từ bầu trời quang đãng' — một tai họa đột ngột, gây sốc.",
  },
  {
    id: "ko-c2-idioms-008",
    level: "C2",
    deck: "idioms",
    en: "consistent from start to finish (one principle throughout)",
    zh: "始终如一",
    vi: "nhất quán từ đầu đến cuối",
    ko: "시종일관",
    roman: "sijongilgwan",
    exampleKo: "그는 시종일관 침착한 태도를 유지했습니다.",
    exampleEn: "He maintained a calm attitude from start to finish.",
    exampleZh: "他始终如一地保持着沉着的态度。",
    exampleVi: "Anh ấy giữ thái độ điềm tĩnh nhất quán từ đầu đến cuối.",
    note: "Praises unwavering consistency; common in formal description.",
    noteZh: "赞许坚定不移的一贯性；常见于正式描述。",
    noteVi: "Ca ngợi sự nhất quán không lay chuyển; thường dùng trong miêu tả trang trọng.",
  },
  {
    id: "ko-c2-idioms-009",
    level: "C2",
    deck: "idioms",
    en: "speaking in a roundabout, evasive way (beating around the bush)",
    zh: "旁敲侧击／绕圈子",
    vi: "nói vòng vo / nói úp mở (đánh trống lảng)",
    ko: "변죽을 울리다",
    roman: "byeonjugeul ullida",
    exampleKo: "변죽만 울리지 말고 본론을 말씀해 주세요.",
    exampleEn: "Stop beating around the bush and get to the point.",
    exampleZh: "别再绕圈子了，请直说正题吧。",
    exampleVi: "Đừng nói vòng vo nữa, hãy nói thẳng vào vấn đề chính.",
    note: "Native idiom; literally 'to ring the rim (not the center) of a gong'.",
    noteZh: "本土惯用语；字面意为“敲锣只敲边（而不敲中心）”。",
    noteVi: "Thành ngữ thuần Hàn; nghĩa đen là 'gõ vào vành (chứ không phải tâm) của chiếc cồng'.",
  },
  {
    id: "ko-c2-idioms-010",
    level: "C2",
    deck: "idioms",
    en: "mutually beneficial; both sides win-win",
    zh: "互帮互助／相互扶持",
    vi: "tương trợ lẫn nhau; đôi bên cùng có lợi",
    ko: "상부상조",
    roman: "sangbusangjo",
    exampleKo: "두 회사는 상부상조하며 함께 성장했습니다.",
    exampleEn: "The two firms grew together by helping each other.",
    exampleZh: "两家公司互帮互助，共同成长。",
    exampleVi: "Hai công ty đã tương trợ lẫn nhau và cùng nhau phát triển.",
    note: "Four-character idiom emphasizing reciprocal aid.",
    noteZh: "强调彼此相助的四字成语。",
    noteVi: "Thành ngữ bốn chữ Hán nhấn mạnh sự giúp đỡ qua lại.",
  },
  {
    id: "ko-c2-idioms-011",
    level: "C2",
    deck: "idioms",
    en: "to make a mountain out of a molehill (exaggerate)",
    zh: "小题大做／夸大其词",
    vi: "thổi phồng sự việc / bé xé ra to",
    ko: "침소봉대",
    roman: "chimsobongdae",
    exampleKo: "작은 실수를 침소봉대해서 말할 필요는 없습니다.",
    exampleEn: "There's no need to blow a small mistake out of proportion.",
    exampleZh: "没必要把小失误夸大其词地说。",
    exampleVi: "Không cần phải thổi phồng một lỗi nhỏ lên như vậy.",
    note: "Lit. 'make a needle into a club' — to overstate something trivial.",
    noteZh: "字面意为“把针说成棒”——把微不足道之事夸大。",
    noteVi: "Nghĩa đen: 'biến cây kim thành cây gậy' — phóng đại một việc nhỏ nhặt.",
  },
  {
    id: "ko-c2-idioms-012",
    level: "C2",
    deck: "idioms",
    en: "a blessing in disguise / fortune is unpredictable",
    zh: "因祸得福",
    vi: "trong cái rủi có cái may / họa lại thành phúc",
    ko: "전화위복",
    roman: "jeonhwawibok",
    exampleKo: "이번 실패가 전화위복이 되어 더 좋은 기회를 얻었어요.",
    exampleEn: "This failure turned out to be a blessing in disguise, opening a better door.",
    exampleZh: "这次失败因祸得福，反而带来了更好的机会。",
    exampleVi: "Thất bại lần này lại hóa ra là trong cái rủi có cái may, mang đến cho tôi cơ hội tốt hơn.",
    note: "Lit. 'turning misfortune into fortune'; very common encouragement.",
    noteZh: "字面意为“转祸为福”；非常常用的鼓励话语。",
    noteVi: "Nghĩa đen: 'biến họa thành phúc'; lời động viên rất thường dùng.",
  },

  // ── nuance (미묘한 뉘앙스) ─────────────────────────────────────
  {
    id: "ko-c2-nuance-001",
    level: "C2",
    deck: "nuance",
    en: "by all means / no matter what (insistent)",
    zh: "非要／无论如何（执意）",
    vi: "bằng mọi giá / nhất quyết (kiên quyết)",
    ko: "기어이",
    roman: "gieoi",
    exampleKo: "그는 기어이 정상에 오르고야 말았다.",
    exampleEn: "He made it to the summit no matter what.",
    exampleZh: "他执意要登顶，最终果然登上了顶峰。",
    exampleVi: "Anh ấy đã nhất quyết leo lên đến đỉnh bằng được.",
    note: "Implies stubborn persistence against odds; stronger than 결국.",
    noteZh: "含有不顾困难、固执坚持之意；比 결국（最终）更强。",
    noteVi: "Hàm ý sự kiên trì bướng bỉnh bất chấp khó khăn; mạnh hơn 결국 (cuối cùng).",
  },
  {
    id: "ko-c2-nuance-002",
    level: "C2",
    deck: "nuance",
    en: "in the end / after all that (resigned)",
    zh: "终究／到头来（无奈）",
    vi: "rốt cuộc / cuối cùng thì (cam chịu)",
    ko: "끝내",
    roman: "kkeunnae",
    exampleKo: "그는 끝내 대답하지 않았다.",
    exampleEn: "In the end, he never answered.",
    exampleZh: "他终究没有回答。",
    exampleVi: "Rốt cuộc anh ấy đã không trả lời.",
    note: "Often carries a tinge of regret or finality, unlike neutral 결국.",
    noteZh: "往往带有一丝遗憾或尘埃落定之感，与中性的 결국 不同。",
    noteVi: "Thường mang chút tiếc nuối hoặc cảm giác kết thúc, khác với 결국 mang tính trung tính.",
  },
  {
    id: "ko-c2-nuance-003",
    level: "C2",
    deck: "nuance",
    en: "supposedly / I hear that (hearsay, reported)",
    zh: "据说／听说好像（传闻）",
    vi: "nghe nói là / hình như là (nghe đồn)",
    ko: "-다나 봐요",
    roman: "-dana bwayo",
    exampleKo: "그 식당이 곧 문을 닫는다나 봐요.",
    exampleEn: "I hear that restaurant is closing soon, apparently.",
    exampleZh: "听说那家餐厅好像快要关门了。",
    exampleVi: "Nghe nói quán ăn đó sắp đóng cửa thì phải.",
    note: "Adds a casual 'so they say, but who knows' distance to hearsay.",
    noteZh: "为传闻添上一层随意的“据说如此、但也说不准”的距离感。",
    noteVi: "Tạo khoảng cách nhẹ nhàng kiểu 'nghe nói vậy, nhưng chưa chắc đã đúng' cho tin đồn.",
  },
  {
    id: "ko-c2-nuance-004",
    level: "C2",
    deck: "nuance",
    en: "rather / on the contrary (contrary to expectation)",
    zh: "反倒／反而（出乎意料）",
    vi: "ngược lại / trái lại (trái với dự đoán)",
    ko: "오히려",
    roman: "ohiryeo",
    exampleKo: "사과했더니 오히려 화를 더 냈어요.",
    exampleEn: "When I apologized, he got even angrier instead.",
    exampleZh: "我道了歉，他反而更生气了。",
    exampleVi: "Tôi đã xin lỗi nhưng anh ấy lại càng nổi giận hơn.",
    note: "Flags a result opposite to what you'd reasonably expect.",
    noteZh: "标示出与合理预期相反的结果。",
    noteVi: "Đánh dấu một kết quả trái ngược với những gì ta thường mong đợi.",
  },
  {
    id: "ko-c2-nuance-005",
    level: "C2",
    deck: "nuance",
    en: "after all / when it comes down to it",
    zh: "反正／横竖",
    vi: "dù sao thì / đằng nào thì",
    ko: "어차피",
    roman: "eochapi",
    exampleKo: "어차피 늦었으니 천천히 갑시다.",
    exampleEn: "We're late anyway, so let's take our time.",
    exampleZh: "反正已经迟了，我们就慢慢走吧。",
    exampleVi: "Dù sao cũng đã muộn rồi, thôi thì cứ từ từ mà đi.",
    note: "Resigned 'since the outcome is fixed regardless'; very colloquial.",
    noteZh: "无奈地表示“反正结果都一样”；非常口语化。",
    noteVi: "Mang tính cam chịu, kiểu 'vì đằng nào kết quả cũng vậy'; rất khẩu ngữ.",
  },
  {
    id: "ko-c2-nuance-006",
    level: "C2",
    deck: "nuance",
    en: "somehow / for some reason (vague unease)",
    zh: "不知怎么地／莫名地",
    vi: "không hiểu sao / tự dưng thấy (cảm giác mơ hồ)",
    ko: "왠지",
    roman: "waenji",
    exampleKo: "왠지 오늘은 일이 잘 풀릴 것 같아요.",
    exampleEn: "Somehow I feel things will go well today.",
    exampleZh: "不知怎么地，总觉得今天事情会很顺。",
    exampleVi: "Không hiểu sao hôm nay tôi cảm thấy mọi việc sẽ suôn sẻ.",
    note: "A gut feeling you can't fully explain; note 왠지 vs. 웬일 spelling.",
    noteZh: "一种说不清道不明的直觉；注意 왠지 与 웬일 的拼写区别。",
    noteVi: "Một linh cảm không thể giải thích trọn vẹn; lưu ý cách viết 왠지 khác với 웬일.",
  },
  {
    id: "ko-c2-nuance-007",
    level: "C2",
    deck: "nuance",
    en: "as expected / sure enough (confirming a hunch)",
    zh: "果然／不愧是",
    vi: "quả nhiên / đúng như dự đoán (xác nhận linh cảm)",
    ko: "역시",
    roman: "yeoksi",
    exampleKo: "역시 네 말이 맞았어.",
    exampleEn: "Sure enough, you were right.",
    exampleZh: "果然还是你说得对。",
    exampleVi: "Quả nhiên lời cậu nói đúng.",
    note: "Confirms what you suspected; also a warm compliment ('I knew you'd deliver').",
    noteZh: "印证心中所料；也可作暖心的称赞（“我就知道你行”）。",
    noteVi: "Xác nhận điều mình đã nghi ngờ; cũng có thể là lời khen ấm áp ('tôi biết ngay là cậu sẽ làm được').",
  },
  {
    id: "ko-c2-nuance-008",
    level: "C2",
    deck: "nuance",
    en: "if anything / relatively speaking",
    zh: "倒不如／宁可",
    vi: "thà rằng / thà là",
    ko: "차라리",
    roman: "charari",
    exampleKo: "이럴 바엔 차라리 안 하는 게 나아요.",
    exampleEn: "If it's going to be like this, I'd rather not do it at all.",
    exampleZh: "既然这样，倒不如干脆不做。",
    exampleVi: "Nếu thế này thì thà không làm còn hơn.",
    note: "Picks the lesser evil among unsatisfactory options.",
    noteZh: "在都不理想的选项中挑出相对较好的那个。",
    noteVi: "Chọn phương án ít tệ hơn trong số các lựa chọn không như ý.",
  },
  {
    id: "ko-c2-nuance-009",
    level: "C2",
    deck: "nuance",
    en: "needless to say / it goes without saying",
    zh: "不言而喻／自不待言",
    vi: "không cần phải nói / hiển nhiên là",
    ko: "두말할 나위 없이",
    roman: "dumalhal nawi eopsi",
    exampleKo: "두말할 나위 없이 그가 최고의 후보입니다.",
    exampleEn: "Needless to say, he is the best candidate.",
    exampleZh: "不言而喻，他是最佳人选。",
    exampleVi: "Không cần phải nói thêm, anh ấy chính là ứng viên xuất sắc nhất.",
    note: "Elevated set phrase; 나위 (room/need) appears almost only here.",
    noteZh: "文雅的固定短语；나위（余地／必要）几乎只用于此处。",
    noteVi: "Cụm từ cố định mang tính trang trọng; 나위 (khoảng trống/sự cần thiết) gần như chỉ xuất hiện trong cụm này.",
  },
  {
    id: "ko-c2-nuance-010",
    level: "C2",
    deck: "nuance",
    en: "barely / only just (a hair's breadth)",
    zh: "勉强／好不容易",
    vi: "chật vật lắm mới / vừa đủ (trong gang tấc)",
    ko: "가까스로",
    roman: "gakkaseuro",
    exampleKo: "막차를 가까스로 탔어요.",
    exampleEn: "I barely caught the last train.",
    exampleZh: "我好不容易赶上了末班车。",
    exampleVi: "Tôi đã chật vật lắm mới bắt kịp chuyến tàu cuối.",
    note: "Emphasizes a narrow, effortful margin; stronger than 겨우.",
    noteZh: "强调差之毫厘、费尽力气才达成；比 겨우 更强。",
    noteVi: "Nhấn mạnh việc đạt được trong gang tấc, phải cố gắng vất vả; mạnh hơn 겨우.",
  },
  {
    id: "ko-c2-nuance-011",
    level: "C2",
    deck: "nuance",
    en: "albeit belatedly / however late",
    zh: "尽管迟了／虽为时已晚",
    vi: "dù có muộn màng / dù đã trễ",
    ko: "뒤늦게나마",
    roman: "dwineutgenama",
    exampleKo: "뒤늦게나마 사과의 말씀을 드립니다.",
    exampleEn: "Belated as it is, I offer my apology.",
    exampleZh: "尽管迟了，我还是要向您致歉。",
    exampleVi: "Dù có muộn màng, tôi xin gửi lời xin lỗi.",
    note: "-나마 = 'even if only'; softens that the action comes too late.",
    noteZh: "-나마＝“即便只是”；缓和了动作来得太迟这一点。",
    noteVi: "-나마 = 'dù chỉ là'; làm dịu đi việc hành động đến quá muộn.",
  },
  {
    id: "ko-c2-nuance-012",
    level: "C2",
    deck: "nuance",
    en: "to a fault / excessively (in a way that backfires)",
    zh: "过分地／过度地",
    vi: "quá mức / thái quá (đến mức phản tác dụng)",
    ko: "지나치게",
    roman: "jinachige",
    exampleKo: "그는 지나치게 신중해서 기회를 놓치곤 해요.",
    exampleEn: "He is cautious to a fault and often misses opportunities.",
    exampleZh: "他过分谨慎，常常因此错失机会。",
    exampleVi: "Anh ấy thận trọng quá mức nên thường bỏ lỡ cơ hội.",
    note: "Implies an otherwise good trait pushed past the healthy limit.",
    noteZh: "暗示某个本是优点的特质被推过了健康的限度。",
    noteVi: "Hàm ý một đặc điểm vốn tốt bị đẩy vượt quá giới hạn hợp lý.",
  },

  // ── formal (격식·연설) ────────────────────────────────────────
  {
    id: "ko-c2-formal-001",
    level: "C2",
    deck: "formal",
    en: "to express deep gratitude (humble, formal)",
    zh: "致以深切的谢意（谦辞、正式）",
    vi: "xin gửi lời cảm ơn sâu sắc (khiêm nhường, trang trọng)",
    ko: "심심한 감사를 드립니다",
    roman: "simsimhan gamsareul deurimnida",
    exampleKo: "참석해 주신 여러분께 심심한 감사를 드립니다.",
    exampleEn: "I extend my profound gratitude to everyone who attended.",
    exampleZh: "谨向拨冗出席的各位致以深切的谢意。",
    exampleVi: "Xin gửi lời cảm ơn sâu sắc đến tất cả quý vị đã tham dự.",
    note: "심심하다 here = 'deep/heartfelt' (深甚), not 'bored' — a classic formal phrase.",
    noteZh: "此处 심심하다＝“深切／诚挚”（深甚），并非“无聊”——经典的正式用语。",
    noteVi: "심심하다 ở đây nghĩa là 'sâu sắc/chân thành' (深甚), không phải 'buồn chán' — một cách diễn đạt trang trọng kinh điển.",
  },
  {
    id: "ko-c2-formal-002",
    level: "C2",
    deck: "formal",
    en: "to ask for your generous understanding",
    zh: "恳请您宽宏谅解",
    vi: "kính mong quý vị lượng thứ / thông cảm rộng lượng",
    ko: "너른 양해를 부탁드립니다",
    roman: "neoreun yanghaereul butakdeurimnida",
    exampleKo: "준비 과정의 미흡함에 너른 양해를 부탁드립니다.",
    exampleEn: "We ask for your generous understanding of any shortcomings.",
    exampleZh: "筹备过程中若有不周之处，恳请您宽宏谅解。",
    exampleVi: "Kính mong quý vị lượng thứ cho những thiếu sót trong quá trình chuẩn bị.",
    note: "Standard apology-and-request line in official notices and speeches.",
    noteZh: "官方通告和演讲中致歉兼请求的标准用语。",
    noteVi: "Câu xin lỗi kèm yêu cầu tiêu chuẩn trong thông báo chính thức và bài phát biểu.",
  },
  {
    id: "ko-c2-formal-003",
    level: "C2",
    deck: "formal",
    en: "to humbly state / submit (in writing)",
    zh: "谨此奉告／谨陈",
    vi: "xin kính cẩn trình bày / kính bẩm",
    ko: "삼가 아룁니다",
    roman: "samga aryumnida",
    exampleKo: "고인의 명복을 빌며 삼가 아룁니다.",
    exampleEn: "Praying for the repose of the deceased, I humbly write these words.",
    exampleZh: "谨祈逝者安息，特此谨陈。",
    exampleVi: "Xin cầu nguyện cho hương hồn người quá cố được an nghỉ, tôi kính cẩn viết những lời này.",
    note: "삼가 = 'respectfully/humbly'; very ceremonial, used in eulogies and formal letters.",
    noteZh: "삼가＝“恭敬地／谨”；极为庄重，用于悼词和正式书信。",
    noteVi: "삼가 = 'một cách cung kính/khiêm nhường'; rất trang trọng, dùng trong điếu văn và thư từ chính thức.",
  },
  {
    id: "ko-c2-formal-004",
    level: "C2",
    deck: "formal",
    en: "to take this opportunity to (formal preamble)",
    zh: "借此机会",
    vi: "nhân dịp này / mượn dịp này",
    ko: "이 자리를 빌려",
    roman: "i jarireul billyeo",
    exampleKo: "이 자리를 빌려 그동안의 노고에 감사드립니다.",
    exampleEn: "I would like to take this opportunity to thank you for your hard work.",
    exampleZh: "借此机会，谨向各位一直以来的辛劳致谢。",
    exampleVi: "Nhân dịp này, tôi xin cảm ơn những nỗ lực của quý vị trong suốt thời gian qua.",
    note: "Set opener in speeches to insert a word of thanks; note 빌려, not 빌어.",
    noteZh: "演讲中插入致谢的固定开场白；注意是 빌려，而非 빌어。",
    noteVi: "Câu mở đầu cố định trong bài phát biểu để chèn lời cảm ơn; lưu ý là 빌려, không phải 빌어.",
  },
  {
    id: "ko-c2-formal-005",
    level: "C2",
    deck: "formal",
    en: "henceforth / from this point on (formal)",
    zh: "今后／此后（正式）",
    vi: "từ nay về sau / sắp tới (trang trọng)",
    ko: "향후",
    roman: "hyanghu",
    exampleKo: "향후 계획에 대해 말씀드리겠습니다.",
    exampleEn: "I will now speak about our plans going forward.",
    exampleZh: "下面我来谈谈今后的计划。",
    exampleVi: "Tôi xin trình bày về kế hoạch sắp tới.",
    note: "Sino-Korean 'henceforth'; crisper and more official than 앞으로.",
    noteZh: "汉字词的“今后”；比 앞으로 更简练、更正式。",
    noteVi: "Từ Hán Hàn nghĩa là 'từ nay về sau'; ngắn gọn và chính thức hơn 앞으로.",
  },
  {
    id: "ko-c2-formal-006",
    level: "C2",
    deck: "formal",
    en: "to come to a conclusion / draw to a close",
    zh: "以……代替／作结",
    vi: "thay thế để kết thúc / khép lại bằng",
    ko: "갈음하다",
    roman: "gareumhada",
    exampleKo: "이것으로 인사말을 갈음하고자 합니다.",
    exampleEn: "With this, I would like to conclude my opening remarks.",
    exampleZh: "谨以此代替致辞，就此作结。",
    exampleVi: "Xin phép được khép lại lời chào mở đầu bằng những lời này.",
    note: "'To substitute / let one thing stand in for another'; signature speech-closing verb.",
    noteZh: "“以一物替代另一物”；收束演讲的标志性动词。",
    noteVi: "'Thay thế / để một thứ đại diện cho thứ khác'; động từ đặc trưng để kết thúc bài phát biểu.",
  },
  {
    id: "ko-c2-formal-007",
    level: "C2",
    deck: "formal",
    en: "to revere / hold in deep respect",
    zh: "敬佩不已／无比敬仰",
    vi: "vô cùng kính trọng / kính trọng không nguôi",
    ko: "존경해 마지않다",
    roman: "jongyeonghae majianta",
    exampleKo: "제가 존경해 마지않는 선생님을 모셨습니다.",
    exampleEn: "I have invited a teacher whom I deeply revere.",
    exampleZh: "我们请到了我敬佩不已的老师。",
    exampleVi: "Tôi đã mời đến vị thầy mà tôi vô cùng kính trọng.",
    note: "-아/어 마지않다 = 'cannot help but ~'; an emphatic, literary intensifier.",
    noteZh: "-아/어 마지않다＝“不禁／不已”；带有强调意味的书面语加强表达。",
    noteVi: "-아/어 마지않다 = 'không thể không ~'; cách nhấn mạnh mang tính văn chương.",
  },
  {
    id: "ko-c2-formal-008",
    level: "C2",
    deck: "formal",
    en: "to wish for your continued prosperity",
    zh: "祝愿（贵方）事业蒸蒸日上",
    vi: "kính chúc sự phát triển thịnh vượng mãi mãi",
    ko: "무궁한 발전을 기원합니다",
    roman: "mugunghan baljeoneul giwonhamnida",
    exampleKo: "귀사의 무궁한 발전을 기원합니다.",
    exampleEn: "We wish your company everlasting prosperity.",
    exampleZh: "祝愿贵公司事业蒸蒸日上、前程无量。",
    exampleVi: "Kính chúc quý công ty phát triển thịnh vượng mãi mãi.",
    note: "Boilerplate closing for business letters and congratulatory addresses.",
    noteZh: "商务信函和贺辞中固定的结尾套语。",
    noteVi: "Câu kết mẫu dùng trong thư từ kinh doanh và bài phát biểu chúc mừng.",
  },
  {
    id: "ko-c2-formal-009",
    level: "C2",
    deck: "formal",
    en: "to be deeply moved / overcome with emotion",
    zh: "感慨万千／百感交集",
    vi: "cảm khái vô cùng / xúc động khôn xiết",
    ko: "감개무량하다",
    roman: "gamgaemuryanghada",
    exampleKo: "이 상을 받게 되어 감개무량합니다.",
    exampleEn: "I am overwhelmed with emotion to receive this award.",
    exampleZh: "能获得这个奖项，我感慨万千。",
    exampleVi: "Tôi vô cùng xúc động khi nhận được giải thưởng này.",
    note: "Four-character idiom for being flooded with deep feeling; common in acceptance speeches.",
    noteZh: "形容深情涌动的四字成语；常见于获奖感言。",
    noteVi: "Thành ngữ bốn chữ Hán diễn tả cảm xúc dâng trào; thường dùng trong bài phát biểu nhận giải.",
  },
  {
    id: "ko-c2-formal-010",
    level: "C2",
    deck: "formal",
    en: "to be unworthy of such praise (humble)",
    zh: "过奖了／实不敢当（谦辞）",
    vi: "lời khen quá lời (khiêm nhường)",
    ko: "과분한 말씀입니다",
    roman: "gwabunhan malsseumimnida",
    exampleKo: "그렇게 칭찬해 주시니 과분한 말씀입니다.",
    exampleEn: "Such praise is more than I deserve.",
    exampleZh: "您这样夸奖，实在是过奖了。",
    exampleVi: "Ngài khen như vậy thật là quá lời.",
    note: "Humble deflection of a compliment; 과분하다 = 'excessive for one's station'.",
    noteZh: "谦逊地推辞赞美；과분하다＝“超出自己的身份／分量”。",
    noteVi: "Cách khiêm tốn từ chối lời khen; 과분하다 = 'vượt quá vị trí của bản thân'.",
  },
  {
    id: "ko-c2-formal-011",
    level: "C2",
    deck: "formal",
    en: "to request your kind attention / cooperation",
    zh: "恳请您予以配合",
    vi: "kính mong sự hợp tác của quý vị",
    ko: "협조를 당부드립니다",
    roman: "hyeopjoreul dangbudeurimnida",
    exampleKo: "원활한 진행을 위해 여러분의 협조를 당부드립니다.",
    exampleEn: "We earnestly request your cooperation for a smooth proceeding.",
    exampleZh: "为使活动顺利进行，恳请各位予以配合。",
    exampleVi: "Để buổi lễ diễn ra suôn sẻ, kính mong sự hợp tác của quý vị.",
    note: "당부하다 = 'to earnestly request/urge'; weightier than 부탁하다.",
    noteZh: "당부하다＝“恳切地请求／叮嘱”；比 부탁하다 更郑重。",
    noteVi: "당부하다 = 'khẩn thiết yêu cầu/nhắc nhở'; mang tính trang trọng hơn 부탁하다.",
  },
];
