/**
 * C2 (전문가 / Proficient) 한국어 학습 콘텐츠 — 영어권 학습자 대상.
 * 각 카드: 한국어 표현(ko) + 로마자(roman) + 영어 뜻(en) + 예문(한/영).
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * note 는 영어(학습자 모국어)로 사용 맥락·뉘앙스를 설명한다.
 *
 * C2 수준: 원어민급 뉘앙스, 관용구·사자성어, 격식체·문어체,
 * 미묘한 어감 차이를 다룬다.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_C2_DECKS: Deck[] = [
  {
    id: "academic",
    level: "C2",
    title: { ko: "전문·학술", en: "Academic" },
    description: {
      ko: "논문·발표·토론의 학술 어휘",
      en: "Scholarly vocabulary for papers, talks, and debate",
    },
    order: 1,
    icon: "GraduationCap",
  },
  {
    id: "idioms",
    level: "C2",
    title: { ko: "관용 표현·속담", en: "Idioms & Proverbs" },
    description: {
      ko: "사자성어와 토박이 속담",
      en: "Four-character idioms and native proverbs",
    },
    order: 2,
    icon: "BookMarked",
  },
  {
    id: "nuance",
    level: "C2",
    title: { ko: "미묘한 뉘앙스", en: "Subtle Nuance" },
    description: {
      ko: "비슷하지만 어감이 다른 표현",
      en: "Near-synonyms with subtly different shades",
    },
    order: 3,
    icon: "Sparkles",
  },
  {
    id: "formal",
    level: "C2",
    title: { ko: "격식·연설", en: "Formal Speech" },
    description: {
      ko: "연설·문어체·공식 격식 표현",
      en: "Oratory, literary register, and official formality",
    },
    order: 4,
    icon: "Megaphone",
  },
];

export const KO_C2_CARDS: VocabCard[] = [
  // ── academic (전문·학술) ──────────────────────────────────────
  {
    id: "ko-c2-academic-001",
    level: "C2",
    deck: "academic",
    en: "to take ~ as a premise / presuppose",
    ko: "전제하다",
    roman: "jeonjehada",
    exampleKo: "이 논의는 시장이 합리적이라는 가정을 전제합니다.",
    exampleEn: "This discussion presupposes that the market is rational.",
    note: "Academic staple for stating an underlying assumption before an argument.",
  },
  {
    id: "ko-c2-academic-002",
    level: "C2",
    deck: "academic",
    en: "to substantiate / demonstrate (with evidence)",
    ko: "입증하다",
    roman: "ipjeunghada",
    exampleKo: "연구진은 가설을 실험으로 입증했습니다.",
    exampleEn: "The researchers substantiated the hypothesis through experiment.",
    note: "Stronger than 보여주다 — implies proof backed by rigorous evidence.",
  },
  {
    id: "ko-c2-academic-003",
    level: "C2",
    deck: "academic",
    en: "to be at odds with / contradict",
    ko: "상충하다",
    roman: "sangchunghada",
    exampleKo: "두 이론의 결론은 서로 상충합니다.",
    exampleEn: "The conclusions of the two theories are at odds with each other.",
    note: "Formal way to say two findings or interests conflict.",
  },
  {
    id: "ko-c2-academic-004",
    level: "C2",
    deck: "academic",
    en: "consideration / point worth weighing",
    ko: "고려 사항",
    roman: "goryeo sahang",
    exampleKo: "정책 설계에서 형평성은 핵심 고려 사항입니다.",
    exampleEn: "Equity is a key consideration in policy design.",
    note: "Set phrase in reports for 'factors to take into account'.",
  },
  {
    id: "ko-c2-academic-005",
    level: "C2",
    deck: "academic",
    en: "in this regard / on this point",
    ko: "이러한 측면에서",
    roman: "ireohan cheungmyeoneseo",
    exampleKo: "이러한 측면에서 기존 연구는 한계가 분명합니다.",
    exampleEn: "In this regard, the existing research has clear limitations.",
    note: "Smooth connective to pivot a paragraph in academic prose.",
  },
  {
    id: "ko-c2-academic-006",
    level: "C2",
    deck: "academic",
    en: "to be interpreted / read as",
    ko: "해석되다",
    roman: "haeseokdoeda",
    exampleKo: "이 결과는 두 가지로 해석될 수 있습니다.",
    exampleEn: "This result can be interpreted in two ways.",
    note: "Passive form preferred in objective academic writing.",
  },
  {
    id: "ko-c2-academic-007",
    level: "C2",
    deck: "academic",
    en: "by extension / furthermore",
    ko: "나아가",
    roman: "naaga",
    exampleKo: "나아가 이 발견은 교육 정책에도 시사점을 줍니다.",
    exampleEn: "Furthermore, this finding has implications for education policy.",
    note: "Elevated 'moreover'; signals the argument is broadening in scope.",
  },
  {
    id: "ko-c2-academic-008",
    level: "C2",
    deck: "academic",
    en: "implication / suggested meaning",
    ko: "시사점",
    roman: "sisajeom",
    exampleKo: "이 연구가 주는 시사점은 적지 않습니다.",
    exampleEn: "The implications of this study are considerable.",
    note: "Common in conclusions: the 'so what' takeaway of a study.",
  },
  {
    id: "ko-c2-academic-009",
    level: "C2",
    deck: "academic",
    en: "to be limited to / confined to",
    ko: "국한되다",
    roman: "gukhandoeda",
    exampleKo: "이 현상은 도시 지역에 국한되지 않습니다.",
    exampleEn: "This phenomenon is not confined to urban areas.",
    note: "Formal; often used in the negative to claim broad applicability.",
  },
  {
    id: "ko-c2-academic-010",
    level: "C2",
    deck: "academic",
    en: "to originate from / stem from",
    ko: "기인하다",
    roman: "giinhada",
    exampleKo: "그 차이는 표본의 편향에 기인합니다.",
    exampleEn: "The difference stems from sampling bias.",
    note: "'기인하다 + 에' = to originate from a cause; very academic.",
  },
  {
    id: "ko-c2-academic-011",
    level: "C2",
    deck: "academic",
    en: "to investigate and clarify",
    ko: "규명하다",
    roman: "gyumyeonghada",
    exampleKo: "이 논문은 원인과 결과의 관계를 규명합니다.",
    exampleEn: "This paper clarifies the relationship between cause and effect.",
    note: "To investigate and establish a fact clearly; stronger than 밝히다.",
  },

  // ── idioms (관용 표현·속담) ────────────────────────────────────
  {
    id: "ko-c2-idioms-001",
    level: "C2",
    deck: "idioms",
    en: "self-contradiction (lit. 'spear and shield')",
    ko: "모순",
    roman: "mosun",
    exampleKo: "그 주장은 그 자체로 모순입니다.",
    exampleEn: "That claim is a contradiction in itself.",
    note: "From a parable of a vendor selling an all-piercing spear and an impenetrable shield.",
  },
  {
    id: "ko-c2-idioms-002",
    level: "C2",
    deck: "idioms",
    en: "killing two birds with one stone (one stone, two birds)",
    ko: "일석이조",
    roman: "ilseogijo",
    exampleKo: "재택근무는 시간도 아끼고 건강도 챙기니 일석이조예요.",
    exampleEn: "Working from home saves time and improves health — two birds with one stone.",
    note: "Four-character idiom; the everyday native equivalent is 꿩 먹고 알 먹기.",
  },
  {
    id: "ko-c2-idioms-003",
    level: "C2",
    deck: "idioms",
    en: "going to great lengths through hardship (enduring trials)",
    ko: "고진감래",
    roman: "gojingamnae",
    exampleKo: "고진감래라더니, 오랜 고생 끝에 결실을 맺었네요.",
    exampleEn: "As they say, no pain no gain — long hardship finally bore fruit.",
    note: "Lit. 'bitterness ends, sweetness comes' — Korean 'no pain, no gain'.",
  },
  {
    id: "ko-c2-idioms-004",
    level: "C2",
    deck: "idioms",
    en: "even monkeys fall from trees (anyone can slip up)",
    ko: "원숭이도 나무에서 떨어진다",
    roman: "wonsungido namueseo tteoreojinda",
    exampleKo: "원숭이도 나무에서 떨어진다고, 전문가도 실수할 때가 있죠.",
    exampleEn: "Even monkeys fall from trees — even experts make mistakes.",
    note: "Native proverb to console someone skilled who erred.",
  },
  {
    id: "ko-c2-idioms-005",
    level: "C2",
    deck: "idioms",
    en: "a frog in a well (a narrow, limited worldview)",
    ko: "우물 안 개구리",
    roman: "umul an gaeguri",
    exampleKo: "해외에 나가 보니 제가 우물 안 개구리였더라고요.",
    exampleEn: "Going abroad, I realized I'd been a frog in a well.",
    note: "Describes someone unaware of the wider world; mildly self-deprecating.",
  },
  {
    id: "ko-c2-idioms-006",
    level: "C2",
    deck: "idioms",
    en: "to add insult to injury (lit. 'salt on a wound')",
    ko: "엎친 데 덮친 격",
    roman: "eopchin de deopchin gyeok",
    exampleKo: "차도 고장 났는데 비까지 오니 엎친 데 덮친 격이네요.",
    exampleEn: "The car broke down and then it rained — when it rains, it pours.",
    note: "Native idiom for misfortunes piling up at once.",
  },
  {
    id: "ko-c2-idioms-007",
    level: "C2",
    deck: "idioms",
    en: "out of the blue / a bolt from clear sky",
    ko: "청천벽력",
    roman: "cheongcheonbyeongnyeok",
    exampleKo: "해고 통보는 그야말로 청천벽력이었습니다.",
    exampleEn: "The layoff notice was a complete bolt from the blue.",
    note: "Lit. 'thunderbolt from a clear sky' — a sudden, shocking calamity.",
  },
  {
    id: "ko-c2-idioms-008",
    level: "C2",
    deck: "idioms",
    en: "consistent from start to finish (one principle throughout)",
    ko: "시종일관",
    roman: "sijongilgwan",
    exampleKo: "그는 시종일관 침착한 태도를 유지했습니다.",
    exampleEn: "He maintained a calm attitude from start to finish.",
    note: "Praises unwavering consistency; common in formal description.",
  },
  {
    id: "ko-c2-idioms-009",
    level: "C2",
    deck: "idioms",
    en: "speaking in a roundabout, evasive way (beating around the bush)",
    ko: "변죽을 울리다",
    roman: "byeonjugeul ullida",
    exampleKo: "변죽만 울리지 말고 본론을 말씀해 주세요.",
    exampleEn: "Stop beating around the bush and get to the point.",
    note: "Native idiom; literally 'to ring the rim (not the center) of a gong'.",
  },
  {
    id: "ko-c2-idioms-010",
    level: "C2",
    deck: "idioms",
    en: "mutually beneficial; both sides win-win",
    ko: "상부상조",
    roman: "sangbusangjo",
    exampleKo: "두 회사는 상부상조하며 함께 성장했습니다.",
    exampleEn: "The two firms grew together by helping each other.",
    note: "Four-character idiom emphasizing reciprocal aid.",
  },
  {
    id: "ko-c2-idioms-011",
    level: "C2",
    deck: "idioms",
    en: "to make a mountain out of a molehill (exaggerate)",
    ko: "침소봉대",
    roman: "chimsobongdae",
    exampleKo: "작은 실수를 침소봉대해서 말할 필요는 없습니다.",
    exampleEn: "There's no need to blow a small mistake out of proportion.",
    note: "Lit. 'make a needle into a club' — to overstate something trivial.",
  },
  {
    id: "ko-c2-idioms-012",
    level: "C2",
    deck: "idioms",
    en: "a blessing in disguise / fortune is unpredictable",
    ko: "전화위복",
    roman: "jeonhwawibok",
    exampleKo: "이번 실패가 전화위복이 되어 더 좋은 기회를 얻었어요.",
    exampleEn: "This failure turned out to be a blessing in disguise, opening a better door.",
    note: "Lit. 'turning misfortune into fortune'; very common encouragement.",
  },

  // ── nuance (미묘한 뉘앙스) ─────────────────────────────────────
  {
    id: "ko-c2-nuance-001",
    level: "C2",
    deck: "nuance",
    en: "by all means / no matter what (insistent)",
    ko: "기어이",
    roman: "gieoi",
    exampleKo: "그는 기어이 정상에 오르고야 말았다.",
    exampleEn: "He made it to the summit no matter what.",
    note: "Implies stubborn persistence against odds; stronger than 결국.",
  },
  {
    id: "ko-c2-nuance-002",
    level: "C2",
    deck: "nuance",
    en: "in the end / after all that (resigned)",
    ko: "끝내",
    roman: "kkeunnae",
    exampleKo: "그는 끝내 대답하지 않았다.",
    exampleEn: "In the end, he never answered.",
    note: "Often carries a tinge of regret or finality, unlike neutral 결국.",
  },
  {
    id: "ko-c2-nuance-003",
    level: "C2",
    deck: "nuance",
    en: "supposedly / I hear that (hearsay, reported)",
    ko: "-다나 봐요",
    roman: "-dana bwayo",
    exampleKo: "그 식당이 곧 문을 닫는다나 봐요.",
    exampleEn: "I hear that restaurant is closing soon, apparently.",
    note: "Adds a casual 'so they say, but who knows' distance to hearsay.",
  },
  {
    id: "ko-c2-nuance-004",
    level: "C2",
    deck: "nuance",
    en: "rather / on the contrary (contrary to expectation)",
    ko: "오히려",
    roman: "ohiryeo",
    exampleKo: "사과했더니 오히려 화를 더 냈어요.",
    exampleEn: "When I apologized, he got even angrier instead.",
    note: "Flags a result opposite to what you'd reasonably expect.",
  },
  {
    id: "ko-c2-nuance-005",
    level: "C2",
    deck: "nuance",
    en: "after all / when it comes down to it",
    ko: "어차피",
    roman: "eochapi",
    exampleKo: "어차피 늦었으니 천천히 갑시다.",
    exampleEn: "We're late anyway, so let's take our time.",
    note: "Resigned 'since the outcome is fixed regardless'; very colloquial.",
  },
  {
    id: "ko-c2-nuance-006",
    level: "C2",
    deck: "nuance",
    en: "somehow / for some reason (vague unease)",
    ko: "왠지",
    roman: "waenji",
    exampleKo: "왠지 오늘은 일이 잘 풀릴 것 같아요.",
    exampleEn: "Somehow I feel things will go well today.",
    note: "A gut feeling you can't fully explain; note 왠지 vs. 웬일 spelling.",
  },
  {
    id: "ko-c2-nuance-007",
    level: "C2",
    deck: "nuance",
    en: "as expected / sure enough (confirming a hunch)",
    ko: "역시",
    roman: "yeoksi",
    exampleKo: "역시 네 말이 맞았어.",
    exampleEn: "Sure enough, you were right.",
    note: "Confirms what you suspected; also a warm compliment ('I knew you'd deliver').",
  },
  {
    id: "ko-c2-nuance-008",
    level: "C2",
    deck: "nuance",
    en: "if anything / relatively speaking",
    ko: "차라리",
    roman: "charari",
    exampleKo: "이럴 바엔 차라리 안 하는 게 나아요.",
    exampleEn: "If it's going to be like this, I'd rather not do it at all.",
    note: "Picks the lesser evil among unsatisfactory options.",
  },
  {
    id: "ko-c2-nuance-009",
    level: "C2",
    deck: "nuance",
    en: "needless to say / it goes without saying",
    ko: "두말할 나위 없이",
    roman: "dumalhal nawi eopsi",
    exampleKo: "두말할 나위 없이 그가 최고의 후보입니다.",
    exampleEn: "Needless to say, he is the best candidate.",
    note: "Elevated set phrase; 나위 (room/need) appears almost only here.",
  },
  {
    id: "ko-c2-nuance-010",
    level: "C2",
    deck: "nuance",
    en: "barely / only just (a hair's breadth)",
    ko: "가까스로",
    roman: "gakkaseuro",
    exampleKo: "막차를 가까스로 탔어요.",
    exampleEn: "I barely caught the last train.",
    note: "Emphasizes a narrow, effortful margin; stronger than 겨우.",
  },
  {
    id: "ko-c2-nuance-011",
    level: "C2",
    deck: "nuance",
    en: "albeit belatedly / however late",
    ko: "뒤늦게나마",
    roman: "dwineutgenama",
    exampleKo: "뒤늦게나마 사과의 말씀을 드립니다.",
    exampleEn: "Belated as it is, I offer my apology.",
    note: "-나마 = 'even if only'; softens that the action comes too late.",
  },
  {
    id: "ko-c2-nuance-012",
    level: "C2",
    deck: "nuance",
    en: "to a fault / excessively (in a way that backfires)",
    ko: "지나치게",
    roman: "jinachige",
    exampleKo: "그는 지나치게 신중해서 기회를 놓치곤 해요.",
    exampleEn: "He is cautious to a fault and often misses opportunities.",
    note: "Implies an otherwise good trait pushed past the healthy limit.",
  },

  // ── formal (격식·연설) ────────────────────────────────────────
  {
    id: "ko-c2-formal-001",
    level: "C2",
    deck: "formal",
    en: "to express deep gratitude (humble, formal)",
    ko: "심심한 감사를 드립니다",
    roman: "simsimhan gamsareul deurimnida",
    exampleKo: "참석해 주신 여러분께 심심한 감사를 드립니다.",
    exampleEn: "I extend my profound gratitude to everyone who attended.",
    note: "심심하다 here = 'deep/heartfelt' (深甚), not 'bored' — a classic formal phrase.",
  },
  {
    id: "ko-c2-formal-002",
    level: "C2",
    deck: "formal",
    en: "to ask for your generous understanding",
    ko: "너른 양해를 부탁드립니다",
    roman: "neoreun yanghaereul butakdeurimnida",
    exampleKo: "준비 과정의 미흡함에 너른 양해를 부탁드립니다.",
    exampleEn: "We ask for your generous understanding of any shortcomings.",
    note: "Standard apology-and-request line in official notices and speeches.",
  },
  {
    id: "ko-c2-formal-003",
    level: "C2",
    deck: "formal",
    en: "to humbly state / submit (in writing)",
    ko: "삼가 아룁니다",
    roman: "samga aryumnida",
    exampleKo: "고인의 명복을 빌며 삼가 아룁니다.",
    exampleEn: "Praying for the repose of the deceased, I humbly write these words.",
    note: "삼가 = 'respectfully/humbly'; very ceremonial, used in eulogies and formal letters.",
  },
  {
    id: "ko-c2-formal-004",
    level: "C2",
    deck: "formal",
    en: "to take this opportunity to (formal preamble)",
    ko: "이 자리를 빌려",
    roman: "i jarireul billyeo",
    exampleKo: "이 자리를 빌려 그동안의 노고에 감사드립니다.",
    exampleEn: "I would like to take this opportunity to thank you for your hard work.",
    note: "Set opener in speeches to insert a word of thanks; note 빌려, not 빌어.",
  },
  {
    id: "ko-c2-formal-005",
    level: "C2",
    deck: "formal",
    en: "henceforth / from this point on (formal)",
    ko: "향후",
    roman: "hyanghu",
    exampleKo: "향후 계획에 대해 말씀드리겠습니다.",
    exampleEn: "I will now speak about our plans going forward.",
    note: "Sino-Korean 'henceforth'; crisper and more official than 앞으로.",
  },
  {
    id: "ko-c2-formal-006",
    level: "C2",
    deck: "formal",
    en: "to come to a conclusion / draw to a close",
    ko: "갈음하다",
    roman: "gareumhada",
    exampleKo: "이것으로 인사말을 갈음하고자 합니다.",
    exampleEn: "With this, I would like to conclude my opening remarks.",
    note: "'To substitute / let one thing stand in for another'; signature speech-closing verb.",
  },
  {
    id: "ko-c2-formal-007",
    level: "C2",
    deck: "formal",
    en: "to revere / hold in deep respect",
    ko: "존경해 마지않다",
    roman: "jongyeonghae majianta",
    exampleKo: "제가 존경해 마지않는 선생님을 모셨습니다.",
    exampleEn: "I have invited a teacher whom I deeply revere.",
    note: "-아/어 마지않다 = 'cannot help but ~'; an emphatic, literary intensifier.",
  },
  {
    id: "ko-c2-formal-008",
    level: "C2",
    deck: "formal",
    en: "to wish for your continued prosperity",
    ko: "무궁한 발전을 기원합니다",
    roman: "mugunghan baljeoneul giwonhamnida",
    exampleKo: "귀사의 무궁한 발전을 기원합니다.",
    exampleEn: "We wish your company everlasting prosperity.",
    note: "Boilerplate closing for business letters and congratulatory addresses.",
  },
  {
    id: "ko-c2-formal-009",
    level: "C2",
    deck: "formal",
    en: "to be deeply moved / overcome with emotion",
    ko: "감개무량하다",
    roman: "gamgaemuryanghada",
    exampleKo: "이 상을 받게 되어 감개무량합니다.",
    exampleEn: "I am overwhelmed with emotion to receive this award.",
    note: "Four-character idiom for being flooded with deep feeling; common in acceptance speeches.",
  },
  {
    id: "ko-c2-formal-010",
    level: "C2",
    deck: "formal",
    en: "to be unworthy of such praise (humble)",
    ko: "과분한 말씀입니다",
    roman: "gwabunhan malsseumimnida",
    exampleKo: "그렇게 칭찬해 주시니 과분한 말씀입니다.",
    exampleEn: "Such praise is more than I deserve.",
    note: "Humble deflection of a compliment; 과분하다 = 'excessive for one's station'.",
  },
  {
    id: "ko-c2-formal-011",
    level: "C2",
    deck: "formal",
    en: "to request your kind attention / cooperation",
    ko: "협조를 당부드립니다",
    roman: "hyeopjoreul dangbudeurimnida",
    exampleKo: "원활한 진행을 위해 여러분의 협조를 당부드립니다.",
    exampleEn: "We earnestly request your cooperation for a smooth proceeding.",
    note: "당부하다 = 'to earnestly request/urge'; weightier than 부탁하다.",
  },
];
