/**
 * C2 (전문가) 한국어 학습 단어(어휘) 카드 — vocab-a1 파일럿 확대 배치.
 * data-ko/c2.ts 등 학술·격식 표현 덱과 별개로, 개별 단어만 다루는 단어장 덱이다.
 *
 * 각 카드: 한국어 단어(ko, 사전형) + 로마자(roman) + 영어/중국어/베트남어 뜻(en/zh/vi)
 * + 예문(4개 언어). 동사/형용사는 사전형(-다)으로 표제하고, 예문은 이 레벨 단어가
 * 실제로 쓰이는 학술·문어 맥락에 맞춰 주로 격식체(-습니다/-ㅂ니다)를 쓴다.
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준
 * (자음동화·비음화·연음 등 표준 발음 변화는 표기에 반영: 예 맥락 → maengnak).
 * 표제어(ko)는 data-ko/index.ts 의 중복 제거 대상이라, 기존 c2.ts(학술·격식 표현) 및
 * vocab-c1.ts(고급 단어) 등 다른 덱의 표제어와 겹치지 않게 선정했다.
 *
 * TOPIK 6급 수준: 학술·문어체 한자어 명사, 격식 동사/형용사, 사자성어를 다룬다.
 * note 는 c2.ts/vocab-c1.ts 와 동일하게 영어로 뉘앙스·용례를 설명한다(이 레벨은
 * 단어 뜻만으론 부족해 사용 맥락 설명이 필요하다).
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_VOCAB_C2_DECKS: Deck[] = [
  {
    id: "vocab-c2",
    level: "C2",
    title: {
      ko: "고급 한자어·사자성어",
      en: "Advanced Sino-Korean & Idioms",
      zh: "高级汉字词·四字成语",
      vi: "Từ Hán Hàn nâng cao & Thành ngữ",
    },
    description: {
      ko: "학술·문어체 어휘와 사자성어",
      en: "Academic, literary vocabulary and four-character idioms",
      zh: "学术、书面语词汇与四字成语",
      vi: "Từ vựng học thuật, văn viết và thành ngữ bốn chữ",
    },
    order: 5,
    icon: "BookText",
  },
];

export const KO_VOCAB_C2_CARDS: VocabCard[] = [
  // ─── 학술·전문 한자어 명사 ─────────────────────────────────────────────
  {
    id: "ko-vocab-c2-001",
    level: "C2",
    deck: "vocab-c2",
    en: "insight / discernment",
    zh: "洞察力",
    vi: "khả năng thấu hiểu sâu sắc / sự tinh tường",
    ko: "통찰력",
    roman: "tongchallyeok",
    exampleKo: "그 학자는 뛰어난 통찰력으로 문제의 본질을 꿰뚫었습니다.",
    exampleEn: "The scholar's remarkable insight cut straight to the heart of the problem.",
    exampleZh: "那位学者以卓越的洞察力看穿了问题的本质。",
    exampleVi: "Học giả đó đã nhìn thấu bản chất của vấn đề bằng khả năng thấu hiểu sâu sắc đáng kinh ngạc.",
    note: "Combines 통(通, penetrate) + 찰(察, observe) + 력(力, power) — often paired with 뛰어나다 or 있다.",
    noteZh: "由 통（通，洞悉）+ 찰（察，观察）+ 력（力，能力）组成——常与 뛰어나다 或 있다 搭配使用。",
    noteVi: "Kết hợp từ 통 (thông suốt) + 찰 (quan sát) + 력 (sức mạnh) — thường đi cùng 뛰어나다 hoặc 있다.",
  },
  {
    id: "ko-vocab-c2-002",
    level: "C2",
    deck: "vocab-c2",
    en: "paradox",
    zh: "悖论",
    vi: "nghịch lý",
    ko: "역설",
    roman: "yeokseol",
    exampleKo: "그 정책은 형평성을 내세우면서도 오히려 불평등을 심화시키는 역설을 낳았습니다.",
    exampleEn: "The policy, while championing equity, ironically produced the paradox of deepening inequality.",
    exampleZh: "那项政策标榜公平，却反而造成了加深不平等的悖论。",
    exampleVi: "Chính sách đó tuy đề cao sự công bằng nhưng lại tạo ra nghịch lý là làm sâu sắc thêm bất bình đẳng.",
    note: "Don't confuse this noun with the verb 역설하다 ('to argue emphatically') — same spelling, unrelated meaning.",
    noteZh: "不要与动词 역설하다（表示「极力主张」）混淆——拼写相同，但含义无关。",
    noteVi: "Đừng nhầm với động từ 역설하다 ('lập luận mạnh mẽ') — viết giống nhau nhưng nghĩa khác nhau.",
  },
  {
    id: "ko-vocab-c2-003",
    level: "C2",
    deck: "vocab-c2",
    en: "bias / skew (a systematic slant, e.g., in data or judgment)",
    zh: "偏向／偏差",
    vi: "sự thiên lệch / độ chệch",
    ko: "편향",
    roman: "pyeonhyang",
    exampleKo: "이 설문 조사는 표본의 편향이 심해서 신뢰하기 어렵습니다.",
    exampleEn: "This survey is hard to trust because its sample bias is severe.",
    exampleZh: "这份问卷调查的样本偏差很严重，难以令人信服。",
    exampleVi: "Cuộc khảo sát này khó tin cậy vì độ chệch của mẫu quá lớn.",
    note: "More technical than 편견 (personal prejudice) — 편향 describes a systematic skew, often in data, sampling, or media.",
    noteZh: "比 편견（个人偏见）更具技术性——편향 指数据、抽样或媒体报道中的系统性偏差。",
    noteVi: "Mang tính kỹ thuật hơn 편견 (định kiến cá nhân) — 편향 chỉ độ lệch mang tính hệ thống, thường trong dữ liệu, lấy mẫu hoặc truyền thông.",
  },
  {
    id: "ko-vocab-c2-004",
    level: "C2",
    deck: "vocab-c2",
    en: "validity / soundness (of an argument or plan)",
    zh: "妥当性／合理性",
    vi: "tính hợp lý / tính xác đáng",
    ko: "타당성",
    roman: "tadangseong",
    exampleKo: "위원회는 그 제안의 타당성을 면밀히 검토했습니다.",
    exampleEn: "The committee closely reviewed the validity of the proposal.",
    exampleZh: "委员会仔细审查了该提案的妥当性。",
    exampleVi: "Ủy ban đã xem xét kỹ lưỡng tính hợp lý của đề xuất đó.",
    note: "The go-to word for evaluating whether an argument, plan, or proposal holds up logically.",
    noteZh: "评估论证、计划或提案在逻辑上是否站得住脚时的常用词。",
    noteVi: "Từ thường dùng để đánh giá xem một lập luận, kế hoạch hay đề xuất có hợp lý về mặt logic hay không.",
  },
  {
    id: "ko-vocab-c2-005",
    level: "C2",
    deck: "vocab-c2",
    en: "conventional wisdom / common belief",
    zh: "通常观念／固有观念",
    vi: "quan niệm thông thường / nhận thức phổ biến",
    ko: "통념",
    roman: "tongnyeom",
    exampleKo: "이 연구는 기존의 통념을 뒤엎는 결과를 보여 줍니다.",
    exampleEn: "This study shows results that overturn conventional wisdom.",
    exampleZh: "这项研究呈现出颠覆既有通念的结果。",
    exampleVi: "Nghiên cứu này cho thấy kết quả lật ngược quan niệm thông thường trước đây.",
    note: "Often appears with 기존 ('existing') and 깨다/뒤엎다 ('to break/overturn') in argumentative writing.",
    noteZh: "在论说文中常与 기존（既有的）以及 깨다／뒤엎다（打破／颠覆）连用。",
    noteVi: "Thường xuất hiện cùng 기존 ('hiện có') và 깨다/뒤엎다 ('phá vỡ/lật đổ') trong văn nghị luận.",
  },
  {
    id: "ko-vocab-c2-006",
    level: "C2",
    deck: "vocab-c2",
    en: "implication / connotation (an underlying meaning)",
    zh: "含义／内涵",
    vi: "hàm ý / ý nghĩa ngầm",
    ko: "함의",
    roman: "hamui",
    exampleKo: "이 발언에는 정치적 함의가 담겨 있습니다.",
    exampleEn: "This remark carries a political implication.",
    exampleZh: "这番话中蕴含着政治含义。",
    exampleVi: "Phát ngôn này chứa đựng hàm ý chính trị.",
    note: "Focuses on a meaning implied beneath the surface, distinct from 시사점 (a takeaway lesson drawn from a result).",
    noteZh: "强调隐藏在表面之下的含义，与 시사점（从结果中得出的启示）有所不同。",
    noteVi: "Nhấn mạnh ý nghĩa ẩn giấu bên dưới bề mặt, khác với 시사점 (bài học rút ra từ một kết quả).",
  },
  {
    id: "ko-vocab-c2-007",
    level: "C2",
    deck: "vocab-c2",
    en: "ideology",
    zh: "理念／意识形态",
    vi: "hệ tư tưởng / ý thức hệ",
    ko: "이념",
    roman: "inyeom",
    exampleKo: "두 정당은 서로 다른 이념을 바탕으로 정책을 세웁니다.",
    exampleEn: "The two parties build their policies on differing ideologies.",
    exampleZh: "两个政党基于不同的理念制定各自的政策。",
    exampleVi: "Hai đảng xây dựng chính sách dựa trên những hệ tư tưởng khác nhau.",
    note: "More abstract and system-level than 생각 ('thought') — used for political or philosophical belief systems.",
    noteZh: "比 생각（想法）更抽象、更具体系性——用于政治或哲学层面的信念体系。",
    noteVi: "Trừu tượng và mang tính hệ thống hơn 생각 (suy nghĩ) — dùng cho hệ thống niềm tin chính trị hoặc triết học.",
  },
  {
    id: "ko-vocab-c2-008",
    level: "C2",
    deck: "vocab-c2",
    en: "equity / fairness",
    zh: "公平性／均衡性",
    vi: "tính công bằng / sự cân bằng",
    ko: "형평성",
    roman: "hyeongpyeongseong",
    exampleKo: "채용 과정에서 형평성을 유지하는 것이 중요합니다.",
    exampleEn: "Maintaining equity in the hiring process is important.",
    exampleZh: "在招聘过程中保持公平性十分重要。",
    exampleVi: "Việc duy trì tính công bằng trong quá trình tuyển dụng là điều quan trọng.",
    note: "형평성 (equitable fairness that weighs context) is subtly different from 평등 (equality) — a distinction common in policy debates.",
    noteZh: "형평성（权衡具体情况的公平）与 평등（平等）略有不同——这是政策讨论中常见的区分。",
    noteVi: "형평성 (sự công bằng có cân nhắc bối cảnh) khác một chút so với 평등 (bình đẳng) — sự phân biệt thường gặp trong tranh luận chính sách.",
  },

  // ─── 격식·문어체 동사 (사전형) ──────────────────────────────────────────
  {
    id: "ko-vocab-c2-009",
    level: "C2",
    deck: "vocab-c2",
    en: "to neglect / to treat as unimportant",
    zh: "忽视／等闲视之",
    vi: "xem nhẹ / lơ là",
    ko: "등한시하다",
    roman: "deunghansihada",
    exampleKo: "건강 관리를 등한시하다가 큰 병을 얻는 경우가 많습니다.",
    exampleEn: "Many people end up with a serious illness after neglecting their health.",
    exampleZh: "很多人因为忽视健康管理而患上重病。",
    exampleVi: "Nhiều người mắc bệnh nặng vì đã lơ là việc chăm sóc sức khỏe.",
    note: "Literally 'to view as 등한(等閑, of little importance)' — a bookish way to say something was neglected.",
    noteZh: "字面意为「视为等闲（不重要）」——书面语中表示某事被忽视、怠慢的说法。",
    noteVi: "Nghĩa đen là 'xem như 등한 (không quan trọng)' — cách nói mang tính văn chương để diễn tả việc gì đó bị xem nhẹ.",
  },
  {
    id: "ko-vocab-c2-010",
    level: "C2",
    deck: "vocab-c2",
    en: "to keenly feel / to realize deeply",
    zh: "痛感／深切感受到",
    vi: "cảm nhận sâu sắc / thấm thía",
    ko: "통감하다",
    roman: "tonggamhada",
    exampleKo: "실패를 겪고 나서야 준비 부족을 통감했습니다.",
    exampleEn: "Only after failing did I keenly feel how unprepared I had been.",
    exampleZh: "经历失败之后，我才痛感自己准备不足。",
    exampleVi: "Chỉ sau khi thất bại tôi mới thấm thía sự thiếu chuẩn bị của bản thân.",
    note: "Stronger than 느끼다 ('to feel') — implies the realization strikes deep, often after a hard experience.",
    noteZh: "比 느끼다（感觉到）更强烈——暗示这种领悟触动很深，往往是在经历磨难之后。",
    noteVi: "Mạnh hơn 느끼다 ('cảm thấy') — hàm ý sự nhận ra thấm thía sâu sắc, thường sau một trải nghiệm khó khăn.",
  },
  {
    id: "ko-vocab-c2-011",
    level: "C2",
    deck: "vocab-c2",
    en: "to give rise to / to provoke (a problem or reaction)",
    zh: "引起／引发",
    vi: "gây ra / khơi mào",
    ko: "야기하다",
    roman: "yagihada",
    exampleKo: "그 발언이 큰 논쟁을 야기했습니다.",
    exampleEn: "That remark gave rise to a huge controversy.",
    exampleZh: "那番言论引发了巨大的争议。",
    exampleVi: "Phát ngôn đó đã khơi mào một cuộc tranh cãi lớn.",
    note: "More neutral than 초래하다, which almost always implies a negative outcome — 야기하다 can introduce any reaction, including debate.",
    noteZh: "比几乎总是暗示负面结果的 초래하다 更中性——야기하다 可以引出任何反应，包括争论或讨论。",
    noteVi: "Trung tính hơn 초래하다 (thường ngụ ý hậu quả tiêu cực) — 야기하다 có thể dẫn đến bất kỳ phản ứng nào, kể cả tranh luận.",
  },
  {
    id: "ko-vocab-c2-012",
    level: "C2",
    deck: "vocab-c2",
    en: "to disregard / to leave out of consideration",
    zh: "置之度外／忽视不顾",
    vi: "bỏ ngoài tai / không đếm xỉa đến",
    ko: "도외시하다",
    roman: "doeisihada",
    exampleKo: "현실을 도외시한 계획은 성공하기 어렵습니다.",
    exampleEn: "A plan that disregards reality is unlikely to succeed.",
    exampleZh: "无视现实的计划很难获得成功。",
    exampleVi: "Một kế hoạch bỏ ngoài tai thực tế thì khó có thể thành công.",
    note: "Literally 'to view (시) as outside (도외) [consideration]' — a bookish way to say something is ignored.",
    noteZh: "字面意为「视为度外（之事）」（시=视/看，도외=度外）——书面语中表示某事被忽视的说法。",
    noteVi: "Nghĩa đen là 'xem (시) như nằm ngoài (도외) [phạm vi xem xét]' — cách nói mang tính văn chương để diễn tả việc gì đó bị bỏ qua.",
  },
  {
    id: "ko-vocab-c2-013",
    level: "C2",
    deck: "vocab-c2",
    en: "to deny",
    zh: "否认",
    vi: "phủ nhận",
    ko: "부인하다",
    roman: "buinhada",
    exampleKo: "그는 끝까지 혐의를 부인했습니다.",
    exampleEn: "He denied the accusation to the very end.",
    exampleZh: "他始终否认这项指控。",
    exampleVi: "Anh ta đã phủ nhận cáo buộc đến cùng.",
    note: "부인 here (否認, 'denial') is a different word from 부인 (夫人, 'wife') — context makes the meaning clear.",
    noteZh: "此处的 부인（否认）与另一个同形词 부인（夫人，妻子）是不同的词——语境可辨明词义。",
    noteVi: "부인 ở đây (否認, 'phủ nhận') là từ khác với 부인 (夫人, 'vợ') — ngữ cảnh sẽ giúp phân biệt rõ nghĩa.",
  },
  {
    id: "ko-vocab-c2-014",
    level: "C2",
    deck: "vocab-c2",
    en: "to avoid / to steer away from (as a matter of principle)",
    zh: "摒弃／不提倡",
    vi: "tránh / không nên (theo nguyên tắc)",
    ko: "지양하다",
    roman: "jiyanghada",
    exampleKo: "불필요한 경쟁은 지양하고 협력을 추구해야 합니다.",
    exampleEn: "We should avoid unnecessary competition and pursue cooperation instead.",
    exampleZh: "应当摒弃不必要的竞争，追求合作。",
    exampleVi: "Nên tránh sự cạnh tranh không cần thiết và theo đuổi sự hợp tác.",
    note: "The conceptual opposite of 지향하다 ('to aim for') — a classic paired contrast in TOPIK writing.",
    noteZh: "与 지향하다（以……为目标）在概念上相对——TOPIK写作中常见的经典对照词组。",
    noteVi: "Đối lập về khái niệm với 지향하다 ('hướng đến') — một cặp từ tương phản kinh điển trong bài viết TOPIK.",
  },
  {
    id: "ko-vocab-c2-015",
    level: "C2",
    deck: "vocab-c2",
    en: "to correspond to / to be commensurate with",
    zh: "相应／对应",
    vi: "tương ứng với",
    ko: "상응하다",
    roman: "sangeunghada",
    exampleKo: "노력에 상응하는 대가를 받아야 마땅합니다.",
    exampleEn: "You deserve a reward commensurate with your effort.",
    exampleZh: "理应获得与努力相应的回报。",
    exampleVi: "Đáng lẽ phải nhận được phần thưởng tương ứng với nỗ lực đã bỏ ra.",
    note: "Common in the set phrase ~에 상응하는 (commensurate with ~), especially about rewards, penalties, or responsibility.",
    noteZh: "常见于固定搭配「~에 상응하는」（与……相应的），尤其用于奖励、处罚或责任方面。",
    noteVi: "Thường gặp trong cụm cố định ~에 상응하는 (tương xứng với ~), đặc biệt khi nói về phần thưởng, hình phạt hoặc trách nhiệm.",
  },
  {
    id: "ko-vocab-c2-016",
    level: "C2",
    deck: "vocab-c2",
    en: "to lean to one side / to be biased",
    zh: "偏向／有失偏颇",
    vi: "nghiêng về một phía / thiên lệch",
    ko: "치우치다",
    roman: "chiuchida",
    exampleKo: "보도는 어느 한쪽으로 치우치지 않아야 합니다.",
    exampleEn: "Reporting should not be biased toward either side.",
    exampleZh: "报道不应该偏向任何一方。",
    exampleVi: "Việc đưa tin không nên nghiêng về bất kỳ phía nào.",
    note: "Takes ~으로/~에 ('치우치다 to X') to name the direction of the bias.",
    noteZh: "与 ~으로／~에 连用（치우치다 偏向某方向），用于指明偏向的方向。",
    noteVi: "Đi với ~으로/~에 ('치우치다 nghiêng về phía X') để chỉ hướng thiên lệch.",
  },

  // ─── 격식·문어체 형용사 (사전형) ────────────────────────────────────────
  {
    id: "ko-vocab-c2-017",
    level: "C2",
    deck: "vocab-c2",
    en: "to be widespread / to be rampant",
    zh: "蔓延／泛滥",
    vi: "lan tràn / phổ biến rộng rãi (theo hướng tiêu cực)",
    ko: "만연하다",
    roman: "manyeonhada",
    exampleKo: "사회 전반에 불신이 만연해 있습니다.",
    exampleEn: "Distrust is widespread throughout society.",
    exampleZh: "不信任的情绪在整个社会蔓延开来。",
    exampleVi: "Sự bất tín đang lan tràn khắp xã hội.",
    note: "Almost always negative — spreads like disease, corruption, or bad habits, not good things.",
    noteZh: "几乎总是带贬义——用于疾病、腐败或不良习气的蔓延，而非好事。",
    noteVi: "Hầu như luôn mang nghĩa tiêu cực — dùng cho bệnh dịch, tham nhũng hay thói xấu lan tràn, không dùng cho điều tốt.",
  },
  {
    id: "ko-vocab-c2-018",
    level: "C2",
    deck: "vocab-c2",
    en: "to be poor / to be substandard (conditions or environment)",
    zh: "恶劣",
    vi: "tồi tệ / kém chất lượng (điều kiện, môi trường)",
    ko: "열악하다",
    roman: "yeorakhada",
    exampleKo: "많은 노동자들이 여전히 열악한 환경에서 일하고 있습니다.",
    exampleEn: "Many workers are still working in poor conditions.",
    exampleZh: "许多劳动者仍然在恶劣的环境中工作。",
    exampleVi: "Nhiều người lao động vẫn đang làm việc trong môi trường tồi tệ.",
    note: "Almost always modifies 환경, 조건, 시설 (environment, conditions, facilities) — describes a setting, not a person's ability.",
    noteZh: "几乎只用来修饰「환경」「조건」「시설」（环境、条件、设施）——形容处境，而非人的能力。",
    noteVi: "Hầu như chỉ dùng để bổ nghĩa cho 환경, 조건, 시설 (môi trường, điều kiện, cơ sở vật chất) — miêu tả hoàn cảnh, không phải năng lực con người.",
  },
  {
    id: "ko-vocab-c2-019",
    level: "C2",
    deck: "vocab-c2",
    en: "to be immense / to be enormous (of influence or impact)",
    zh: "极大／深远",
    vi: "to lớn / sâu rộng (ảnh hưởng)",
    ko: "지대하다",
    roman: "jidaehada",
    exampleKo: "그 발견이 과학계에 미친 영향은 지대합니다.",
    exampleEn: "The impact that discovery had on the scientific community is immense.",
    exampleZh: "那项发现对科学界产生的影响极为深远。",
    exampleVi: "Ảnh hưởng mà phát hiện đó mang lại cho giới khoa học là vô cùng to lớn.",
    note: "Almost exclusively modifies 영향 ('influence') — rarely used for physical size.",
    noteZh: "几乎只用来修饰 영향（影响）——很少用于形容物理大小。",
    noteVi: "Hầu như chỉ dùng để bổ nghĩa cho 영향 ('ảnh hưởng') — hiếm khi dùng để chỉ kích thước vật lý.",
  },
  {
    id: "ko-vocab-c2-020",
    level: "C2",
    deck: "vocab-c2",
    en: "to be special / to be particular (extraordinary care or affection)",
    zh: "特别／格外",
    vi: "đặc biệt / khác thường",
    ko: "각별하다",
    roman: "gakbyeolhada",
    exampleKo: "선생님은 늘 저에게 각별한 관심을 보여 주셨습니다.",
    exampleEn: "My teacher always showed me particular attention.",
    exampleZh: "老师总是对我表示出格外的关心。",
    exampleVi: "Thầy giáo luôn dành cho tôi sự quan tâm đặc biệt.",
    note: "More literary and warmer in tone than 특별하다 — often describes personal care or affection.",
    noteZh: "比 특별하다 更具文采、语气更温暖——常用于描述个人的关心或情谊。",
    noteVi: "Mang tính văn chương và ấm áp hơn 특별하다 — thường miêu tả sự quan tâm hay tình cảm cá nhân.",
  },
  {
    id: "ko-vocab-c2-021",
    level: "C2",
    deck: "vocab-c2",
    en: "to be a long way off / to be distant (of a goal)",
    zh: "遥远／还差得远",
    vi: "còn xa vời / còn lâu mới đạt được",
    ko: "요원하다",
    roman: "yowonhada",
    exampleKo: "완전한 해결책을 찾기까지는 아직 요원해 보입니다.",
    exampleEn: "Finding a complete solution still looks like a long way off.",
    exampleZh: "要找到彻底的解决方案，看来还遥遥无期。",
    exampleVi: "Việc tìm ra giải pháp trọn vẹn vẫn có vẻ còn xa vời.",
    note: "Describes a goal that feels distant despite effort — common in phrases like '해결이 요원하다.'",
    noteZh: "形容尽管付出努力，目标仍显遥远——常见于「해결이 요원하다」（解决遥遥无期）等说法。",
    noteVi: "Miêu tả một mục tiêu vẫn cảm thấy xa vời dù đã cố gắng — thường gặp trong cụm '해결이 요원하다' (còn lâu mới giải quyết được).",
  },
  {
    id: "ko-vocab-c2-022",
    level: "C2",
    deck: "vocab-c2",
    en: "to be cool-headed / to be coolly rational",
    zh: "冷静理智／冷峻透彻",
    vi: "bình tĩnh sáng suốt / lý trí lạnh lùng",
    ko: "냉철하다",
    roman: "naengcheolhada",
    exampleKo: "위기일수록 냉철하게 상황을 분석해야 합니다.",
    exampleEn: "The more of a crisis it is, the more coolly you must analyze the situation.",
    exampleZh: "越是危机时刻，越要冷静理智地分析局势。",
    exampleVi: "Càng trong khủng hoảng càng phải phân tích tình hình một cách bình tĩnh sáng suốt.",
    note: "Blends 냉정하다 (composed) and 철저하다 (thorough) — praised as a trait for leaders in a crisis.",
    noteZh: "融合了 냉정하다（沉着）与 철저하다（彻底）的语感——常用来称赞危机中领导者的特质。",
    noteVi: "Kết hợp sắc thái của 냉정하다 (điềm tĩnh) và 철저하다 (triệt để) — thường dùng khen ngợi phẩm chất của người lãnh đạo trong khủng hoảng.",
  },

  // ─── 사자성어 ──────────────────────────────────────────────────────────
  {
    id: "ko-vocab-c2-023",
    level: "C2",
    deck: "vocab-c2",
    en: "to reap what one sows (one's own fault brings its own consequence)",
    zh: "自作自受",
    vi: "tự làm tự chịu / gieo gió gặt bão",
    ko: "자업자득",
    roman: "jaeopjadeuk",
    exampleKo: "게을러서 시험에 떨어진 거니 자업자득이죠.",
    exampleEn: "You failed the exam because you were lazy — you reap what you sow.",
    exampleZh: "因为懒惰而考试不及格，真是自作自受。",
    exampleVi: "Thi trượt vì lười biếng thì đúng là tự làm tự chịu thôi.",
    note: "Often used pointedly, close to the English 'you brought this on yourself.'",
    noteZh: "常带有直接指责的语气，接近中文的「自食其果」。",
    noteVi: "Thường dùng với sắc thái chỉ trích thẳng, gần với câu 'tự mình chuốc lấy' trong tiếng Việt.",
  },
  {
    id: "ko-vocab-c2-024",
    level: "C2",
    deck: "vocab-c2",
    en: "the more, the better",
    zh: "多多益善",
    vi: "càng nhiều càng tốt",
    ko: "다다익선",
    roman: "dadaikseon",
    exampleKo: "비상금은 다다익선이니 조금씩이라도 모아 두세요.",
    exampleEn: "Emergency funds are a case of the more the better, so save a bit at a time.",
    exampleZh: "应急资金是多多益善，请一点一点地积攒起来吧。",
    exampleVi: "Quỹ khẩn cấp thì càng nhiều càng tốt, hãy tích góp dần từng chút một nhé.",
    note: "Traces back to a story about Han Xin boasting he could command any number of troops.",
    noteZh: "典出韩信「多多益善」的典故——他自夸统兵越多越好。",
    noteVi: "Bắt nguồn từ câu chuyện Hàn Tín khoe rằng ông có thể chỉ huy bao nhiêu quân cũng được.",
  },
  {
    id: "ko-vocab-c2-025",
    level: "C2",
    deck: "vocab-c2",
    en: "a meeting of hearts and minds (mutual understanding without words)",
    zh: "心心相印／心领神会",
    vi: "tâm đầu ý hợp / hiểu nhau không cần lời",
    ko: "이심전심",
    roman: "isimjeonsim",
    exampleKo: "오랜 친구라 그런지 우리는 이심전심으로 통했습니다.",
    exampleEn: "Perhaps because we're old friends, we understood each other without words.",
    exampleZh: "也许是因为我们是老朋友，彼此心心相印，无需多言。",
    exampleVi: "Có lẽ vì là bạn cũ lâu năm nên chúng tôi hiểu nhau mà không cần nói ra.",
    note: "Originally a Buddhist term for wordless transmission of understanding between minds.",
    noteZh: "原为佛教用语，指心与心之间不立文字的意会相通。",
    noteVi: "Vốn là thuật ngữ Phật giáo chỉ sự truyền đạt hiểu biết giữa hai tâm trí mà không cần lời nói.",
  },
  {
    id: "ko-vocab-c2-026",
    level: "C2",
    deck: "vocab-c2",
    en: "icing on the cake (adding excellence to what is already excellent)",
    zh: "锦上添花",
    vi: "như gấm thêu hoa (thêm phần hoàn hảo)",
    ko: "금상첨화",
    roman: "geumsangcheomhwa",
    exampleKo: "맛도 좋은데 가격까지 저렴하니 금상첨화네요.",
    exampleEn: "It tastes great, and the price is low too — icing on the cake.",
    exampleZh: "味道好，价格又便宜，真是锦上添花。",
    exampleVi: "Vừa ngon vừa rẻ, đúng là như gấm thêu hoa.",
    note: "Literally 'adding flowers on top of brocade' — layering excellence onto something already excellent.",
    noteZh: "字面意为「锦缎之上再添花朵」——在已经很好的事物上再添一层美好。",
    noteVi: "Nghĩa đen là 'thêm hoa lên trên gấm' — làm cho một điều đã tốt đẹp trở nên hoàn hảo hơn nữa.",
  },
  {
    id: "ko-vocab-c2-027",
    level: "C2",
    deck: "vocab-c2",
    en: "penny-wise, pound-foolish (greed for a small gain causes a big loss)",
    zh: "因小失大",
    vi: "tham bát bỏ mâm / vì lợi nhỏ mà mất lớn",
    ko: "소탐대실",
    roman: "sotamdaesil",
    exampleKo: "값싼 부품을 쓰다가 기계가 고장 났으니 소탐대실인 셈이죠.",
    exampleEn: "Using cheap parts and breaking the machine was a case of penny-wise, pound-foolish.",
    exampleZh: "用了便宜的零件结果弄坏了机器，真是因小失大。",
    exampleVi: "Dùng linh kiện rẻ tiền rồi làm hỏng cả máy, đúng là tham bát bỏ mâm.",
    note: "Literally 'small greed, big loss' — a common warning against short-term thinking.",
    noteZh: "字面意为「贪小失大」——常用来警示短视的行为。",
    noteVi: "Nghĩa đen là 'tham nhỏ, mất lớn' — lời cảnh báo thường gặp về lối suy nghĩ thiển cận.",
  },
  {
    id: "ko-vocab-c2-028",
    level: "C2",
    deck: "vocab-c2",
    en: "improvisation (adapting to circumstances on the spot)",
    zh: "随机应变",
    vi: "ứng biến / tùy cơ ứng biến",
    ko: "임기응변",
    roman: "imgieungbyeon",
    exampleKo: "갑작스러운 질문에도 그는 임기응변으로 잘 대답했습니다.",
    exampleEn: "Even faced with a sudden question, he answered well by improvising.",
    exampleZh: "即使面对突如其来的提问，他也随机应变地作出了很好的回答。",
    exampleVi: "Dù bị hỏi bất ngờ, anh ấy vẫn trả lời rất tốt nhờ khả năng ứng biến.",
    note: "Praises quick thinking under pressure — can turn negative if it implies a lack of real preparation.",
    noteZh: "称赞在压力下随机应变的能力——但若暗示缺乏真正的准备，也可能带贬义。",
    noteVi: "Khen ngợi khả năng phản ứng nhanh dưới áp lực — nhưng có thể mang nghĩa tiêu cực nếu ngụ ý thiếu sự chuẩn bị thực sự.",
  },
  {
    id: "ko-vocab-c2-029",
    level: "C2",
    deck: "vocab-c2",
    en: "to be forewarned is to be forearmed (preparedness averts disaster)",
    zh: "有备无患",
    vi: "có chuẩn bị thì không lo hoạn nạn",
    ko: "유비무환",
    roman: "yubimuhwan",
    exampleKo: "유비무환이라고, 미리 대비해서 나쁠 것은 없습니다.",
    exampleEn: "As they say, being prepared can't hurt — better safe than sorry.",
    exampleZh: "常言道有备无患，提前做好准备总没有坏处。",
    exampleVi: "Người ta vẫn nói có chuẩn bị thì không lo hoạn nạn, chuẩn bị trước thì chẳng có gì thiệt cả.",
    note: "A classical saying (from the Chinese Shujing) that's still an everyday motivational phrase in Korean.",
    noteZh: "源自中国典籍《书经》的古语，至今仍是韩语中常用的励志说法。",
    noteVi: "Câu nói cổ điển (bắt nguồn từ Kinh Thư của Trung Quốc) nhưng vẫn là câu nói động viên thường ngày trong tiếng Hàn.",
  },
  {
    id: "ko-vocab-c2-030",
    level: "C2",
    deck: "vocab-c2",
    en: "to be half in doubt (half believing, half doubting)",
    zh: "半信半疑",
    vi: "nửa tin nửa ngờ",
    ko: "반신반의",
    roman: "bansinbanui",
    exampleKo: "처음에는 그 소문을 반신반의했습니다.",
    exampleEn: "At first, I was half in doubt about that rumor.",
    exampleZh: "一开始我对那个传闻还半信半疑。",
    exampleVi: "Ban đầu tôi đã nửa tin nửa ngờ về tin đồn đó.",
    note: "Literally 'half belief, half doubt' — describes a mind caught between trust and suspicion.",
    noteZh: "字面意为「一半相信、一半怀疑」——形容内心在信任与怀疑之间摇摆。",
    noteVi: "Nghĩa đen là 'nửa tin nửa ngờ' — miêu tả trạng thái tâm lý phân vân giữa tin tưởng và nghi ngờ.",
  },
];
