/**
 * A1 (입문) 한국어 학습 단어(어휘) 카드 — 파일럿 (#47).
 * data-ko/a1.ts 등 회화 표현 덱과 별개로, 개별 단어만 다루는 단어장 덱이다.
 * 구조·품질 확인용 1차 배치 — 이후 a2~c2 로 같은 패턴을 확대할 예정.
 *
 * 각 카드: 한국어 단어(ko, 사전형) + 로마자(roman) + 영어/중국어/베트남어 뜻(en/zh/vi)
 * + 예문(4개 언어). 동사/형용사는 사전형(-다)으로 표제하고, 예문에서는 자연스러운
 * 활용형을 쓴다 (예: 크다 → 예문 "커요").
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * 표제어(ko)는 data-ko/index.ts 의 중복 제거 대상이라, 기존 a1~c2 회화 카드의
 * 표제어와 겹치지 않게 선정했다 (예: 숫자/가족 호칭은 이미 표현 덱에 있어 제외).
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_VOCAB_A1_DECKS: Deck[] = [
  {
    id: "vocab-a1",
    level: "A1",
    title: {
      ko: "기초 단어",
      en: "Basic Words",
      zh: "基础单词",
      vi: "Từ vựng cơ bản",
    },
    description: {
      ko: "일상 필수 명사·동사·형용사",
      en: "Everyday essential nouns, verbs, and adjectives",
      zh: "日常必备名词、动词、形容词",
      vi: "Danh từ, động từ, tính từ thiết yếu hàng ngày",
    },
    order: 6,
    icon: "BookText",
  },
];

export const KO_VOCAB_A1_CARDS: VocabCard[] = [
  // ─── 명사 ──────────────────────────────────────────────────────────────
  {
    id: "ko-vocab-a1-001",
    level: "A1",
    deck: "vocab-a1",
    en: "person",
    zh: "人",
    vi: "người",
    ko: "사람",
    roman: "saram",
    exampleKo: "저 사람은 누구예요?",
    exampleEn: "Who is that person?",
    exampleZh: "那个人是谁？",
    exampleVi: "Người kia là ai?",
  },
  {
    id: "ko-vocab-a1-002",
    level: "A1",
    deck: "vocab-a1",
    en: "name",
    zh: "名字",
    vi: "tên",
    ko: "이름",
    roman: "ireum",
    exampleKo: "이름을 여기에 써 주세요.",
    exampleEn: "Please write your name here.",
    exampleZh: "请把名字写在这里。",
    exampleVi: "Vui lòng viết tên vào đây.",
  },
  {
    id: "ko-vocab-a1-003",
    level: "A1",
    deck: "vocab-a1",
    en: "friend",
    zh: "朋友",
    vi: "bạn bè",
    ko: "친구",
    roman: "chingu",
    exampleKo: "저는 친구가 많아요.",
    exampleEn: "I have many friends.",
    exampleZh: "我有很多朋友。",
    exampleVi: "Tôi có nhiều bạn bè.",
  },
  {
    id: "ko-vocab-a1-004",
    level: "A1",
    deck: "vocab-a1",
    en: "school",
    zh: "学校",
    vi: "trường học",
    ko: "학교",
    roman: "hakgyo",
    exampleKo: "학교가 어디에 있어요?",
    exampleEn: "Where is the school?",
    exampleZh: "学校在哪里？",
    exampleVi: "Trường học ở đâu?",
  },
  {
    id: "ko-vocab-a1-005",
    level: "A1",
    deck: "vocab-a1",
    en: "time",
    zh: "时间",
    vi: "thời gian",
    ko: "시간",
    roman: "sigan",
    exampleKo: "지금 시간 있어요?",
    exampleEn: "Do you have time now?",
    exampleZh: "你现在有时间吗？",
    exampleVi: "Bây giờ bạn có thời gian không?",
  },
  {
    id: "ko-vocab-a1-006",
    level: "A1",
    deck: "vocab-a1",
    en: "money",
    zh: "钱",
    vi: "tiền",
    ko: "돈",
    roman: "don",
    exampleKo: "돈이 조금 있어요.",
    exampleEn: "I have a little money.",
    exampleZh: "我有一点钱。",
    exampleVi: "Tôi có một ít tiền.",
  },
  {
    id: "ko-vocab-a1-007",
    level: "A1",
    deck: "vocab-a1",
    en: "house / home",
    zh: "家",
    vi: "nhà",
    ko: "집",
    roman: "jip",
    exampleKo: "저는 지금 집에 있어요.",
    exampleEn: "I'm at home now.",
    exampleZh: "我现在在家。",
    exampleVi: "Bây giờ tôi đang ở nhà.",
  },
  {
    id: "ko-vocab-a1-008",
    level: "A1",
    deck: "vocab-a1",
    en: "company",
    zh: "公司",
    vi: "công ty",
    ko: "회사",
    roman: "hoesa",
    exampleKo: "회사가 여기서 가까워요.",
    exampleEn: "The company is close from here.",
    exampleZh: "公司离这里很近。",
    exampleVi: "Công ty gần đây.",
  },
  {
    id: "ko-vocab-a1-009",
    level: "A1",
    deck: "vocab-a1",
    en: "country",
    zh: "国家",
    vi: "đất nước",
    ko: "나라",
    roman: "nara",
    exampleKo: "어느 나라에서 왔어요?",
    exampleEn: "Which country are you from?",
    exampleZh: "你来自哪个国家？",
    exampleVi: "Bạn đến từ nước nào?",
  },
  {
    id: "ko-vocab-a1-010",
    level: "A1",
    deck: "vocab-a1",
    en: "food",
    zh: "食物",
    vi: "thức ăn",
    ko: "음식",
    roman: "eumsik",
    exampleKo: "이 음식은 정말 맛있어요.",
    exampleEn: "This food is really delicious.",
    exampleZh: "这个食物真好吃。",
    exampleVi: "Món ăn này thật sự rất ngon.",
  },

  // ─── 동사 (사전형) ─────────────────────────────────────────────────────
  {
    id: "ko-vocab-a1-011",
    level: "A1",
    deck: "vocab-a1",
    en: "to go",
    zh: "去",
    vi: "đi",
    ko: "가다",
    roman: "gada",
    exampleKo: "저는 매일 학교에 가요.",
    exampleEn: "I go to school every day.",
    exampleZh: "我每天去学校。",
    exampleVi: "Tôi đi học mỗi ngày.",
  },
  {
    id: "ko-vocab-a1-012",
    level: "A1",
    deck: "vocab-a1",
    en: "to come",
    zh: "来",
    vi: "đến",
    ko: "오다",
    roman: "oda",
    exampleKo: "내일 우리 집에 오세요.",
    exampleEn: "Please come to my house tomorrow.",
    exampleZh: "明天请来我家。",
    exampleVi: "Ngày mai hãy đến nhà tôi nhé.",
  },
  {
    id: "ko-vocab-a1-013",
    level: "A1",
    deck: "vocab-a1",
    en: "to eat",
    zh: "吃",
    vi: "ăn",
    ko: "먹다",
    roman: "meokda",
    exampleKo: "아침에 뭐 먹어요?",
    exampleEn: "What do you eat in the morning?",
    exampleZh: "你早上吃什么？",
    exampleVi: "Buổi sáng bạn ăn gì?",
  },
  {
    id: "ko-vocab-a1-014",
    level: "A1",
    deck: "vocab-a1",
    en: "to drink",
    zh: "喝",
    vi: "uống",
    ko: "마시다",
    roman: "masida",
    exampleKo: "저는 물을 자주 마셔요.",
    exampleEn: "I drink water often.",
    exampleZh: "我经常喝水。",
    exampleVi: "Tôi thường xuyên uống nước.",
  },
  {
    id: "ko-vocab-a1-015",
    level: "A1",
    deck: "vocab-a1",
    en: "to see / to watch",
    zh: "看",
    vi: "xem / nhìn",
    ko: "보다",
    roman: "boda",
    exampleKo: "저녁에 영화를 봐요.",
    exampleEn: "I watch a movie in the evening.",
    exampleZh: "我晚上看电影。",
    exampleVi: "Buổi tối tôi xem phim.",
  },
  {
    id: "ko-vocab-a1-016",
    level: "A1",
    deck: "vocab-a1",
    en: "to do",
    zh: "做",
    vi: "làm",
    ko: "하다",
    roman: "hada",
    exampleKo: "주말에 보통 뭐 해요?",
    exampleEn: "What do you usually do on weekends?",
    exampleZh: "你周末通常做什么？",
    exampleVi: "Cuối tuần bạn thường làm gì?",
  },
  {
    id: "ko-vocab-a1-017",
    level: "A1",
    deck: "vocab-a1",
    en: "to exist / to have",
    zh: "有 / 在",
    vi: "có / ở",
    ko: "있다",
    roman: "itda",
    exampleKo: "질문 있어요?",
    exampleEn: "Do you have a question?",
    exampleZh: "你有问题吗？",
    exampleVi: "Bạn có câu hỏi không?",
    note: "있다 means both 'to exist / be located' and 'to have', depending on context.",
    noteZh: "있다既可表示“存在/在场”，也可表示“拥有”，具体意思取决于语境。",
    noteVi: "있다 vừa có nghĩa là \"tồn tại / ở đâu đó\", vừa có nghĩa là \"có\", tùy theo ngữ cảnh.",
  },
  {
    id: "ko-vocab-a1-018",
    level: "A1",
    deck: "vocab-a1",
    en: "to not exist / to not have",
    zh: "没有",
    vi: "không có",
    ko: "없다",
    roman: "eopda",
    exampleKo: "시간이 없어요.",
    exampleEn: "I don't have time.",
    exampleZh: "我没有时间。",
    exampleVi: "Tôi không có thời gian.",
  },
  {
    id: "ko-vocab-a1-019",
    level: "A1",
    deck: "vocab-a1",
    en: "to sleep",
    zh: "睡觉",
    vi: "ngủ",
    ko: "자다",
    roman: "jada",
    exampleKo: "저는 보통 열한 시에 자요.",
    exampleEn: "I usually sleep at eleven.",
    exampleZh: "我通常十一点睡觉。",
    exampleVi: "Tôi thường ngủ lúc mười một giờ.",
  },
  {
    id: "ko-vocab-a1-020",
    level: "A1",
    deck: "vocab-a1",
    en: "to buy",
    zh: "买",
    vi: "mua",
    ko: "사다",
    roman: "sada",
    exampleKo: "시장에서 과일을 사요.",
    exampleEn: "I buy fruit at the market.",
    exampleZh: "我在市场买水果。",
    exampleVi: "Tôi mua trái cây ở chợ.",
  },

  // ─── 형용사 (사전형) ───────────────────────────────────────────────────
  {
    id: "ko-vocab-a1-021",
    level: "A1",
    deck: "vocab-a1",
    en: "to be big",
    zh: "大",
    vi: "to / lớn",
    ko: "크다",
    roman: "keuda",
    exampleKo: "이 가방은 커요.",
    exampleEn: "This bag is big.",
    exampleZh: "这个包很大。",
    exampleVi: "Cái túi này to.",
    note: "Korean descriptive words like 크다 end in -다 and conjugate just like action verbs.",
    noteZh: "韩语形容词（如크다）以-다结尾，变位方式和动词相同。",
    noteVi: "Tính từ tiếng Hàn (như 크다) kết thúc bằng -다 và chia giống hệt động từ hành động.",
  },
  {
    id: "ko-vocab-a1-022",
    level: "A1",
    deck: "vocab-a1",
    en: "to be small",
    zh: "小",
    vi: "nhỏ",
    ko: "작다",
    roman: "jakda",
    exampleKo: "제 방은 작아요.",
    exampleEn: "My room is small.",
    exampleZh: "我的房间很小。",
    exampleVi: "Phòng của tôi nhỏ.",
  },
  {
    id: "ko-vocab-a1-023",
    level: "A1",
    deck: "vocab-a1",
    en: "to be many / a lot",
    zh: "多",
    vi: "nhiều",
    ko: "많다",
    roman: "manta",
    exampleKo: "오늘 할 일이 많아요.",
    exampleEn: "I have a lot of work to do today.",
    exampleZh: "我今天要做的事情很多。",
    exampleVi: "Hôm nay tôi có nhiều việc phải làm.",
  },
  {
    id: "ko-vocab-a1-024",
    level: "A1",
    deck: "vocab-a1",
    en: "to be good",
    zh: "好",
    vi: "tốt / hay",
    ko: "좋다",
    roman: "jota",
    exampleKo: "이 노래가 정말 좋아요.",
    exampleEn: "This song is really good.",
    exampleZh: "这首歌真好听。",
    exampleVi: "Bài hát này thật sự rất hay.",
  },
  {
    id: "ko-vocab-a1-025",
    level: "A1",
    deck: "vocab-a1",
    en: "to be bad",
    zh: "坏 / 不好",
    vi: "xấu / tệ",
    ko: "나쁘다",
    roman: "nappeuda",
    exampleKo: "오늘 기분이 나빠요.",
    exampleEn: "I feel bad today.",
    exampleZh: "我今天心情不好。",
    exampleVi: "Hôm nay tôi cảm thấy tệ.",
  },
  {
    id: "ko-vocab-a1-026",
    level: "A1",
    deck: "vocab-a1",
    en: "to be pretty",
    zh: "漂亮",
    vi: "xinh đẹp",
    ko: "예쁘다",
    roman: "yeppeuda",
    exampleKo: "이 꽃이 정말 예뻐요.",
    exampleEn: "This flower is really pretty.",
    exampleZh: "这朵花真漂亮。",
    exampleVi: "Bông hoa này thật sự rất xinh đẹp.",
  },
  {
    id: "ko-vocab-a1-027",
    level: "A1",
    deck: "vocab-a1",
    en: "to be delicious",
    zh: "好吃",
    vi: "ngon",
    ko: "맛있다",
    roman: "masitda",
    exampleKo: "이 김치찌개 맛있어요.",
    exampleEn: "This kimchi stew is delicious.",
    exampleZh: "这个泡菜汤很好吃。",
    exampleVi: "Món canh kim chi này ngon lắm.",
    note: "Literally 'taste' (맛) + 'to exist' (있다) — 'to have (good) taste'.",
    noteZh: "字面意思是“味道”(맛) + “有”(있다)，即“有（好）味道”。",
    noteVi: "Nghĩa đen là \"vị\" (맛) + \"có\" (있다) — tức là \"có vị (ngon)\".",
  },
  {
    id: "ko-vocab-a1-028",
    level: "A1",
    deck: "vocab-a1",
    en: "to be difficult",
    zh: "难",
    vi: "khó",
    ko: "어렵다",
    roman: "eoryeopda",
    exampleKo: "한국어 문법이 조금 어려워요.",
    exampleEn: "Korean grammar is a little difficult.",
    exampleZh: "韩语语法有点难。",
    exampleVi: "Ngữ pháp tiếng Hàn hơi khó.",
  },
  {
    id: "ko-vocab-a1-029",
    level: "A1",
    deck: "vocab-a1",
    en: "to be easy",
    zh: "容易",
    vi: "dễ",
    ko: "쉽다",
    roman: "swipda",
    exampleKo: "이 문제는 쉬워요.",
    exampleEn: "This question is easy.",
    exampleZh: "这个问题很容易。",
    exampleVi: "Câu hỏi này dễ.",
  },
  {
    id: "ko-vocab-a1-030",
    level: "A1",
    deck: "vocab-a1",
    en: "to be busy",
    zh: "忙",
    vi: "bận",
    ko: "바쁘다",
    roman: "bappeuda",
    exampleKo: "요즘 정말 바빠요.",
    exampleEn: "I'm really busy these days.",
    exampleZh: "我最近真的很忙。",
    exampleVi: "Dạo này tôi thật sự rất bận.",
  },
];
