/**
 * B1 (중급) 한국어 학습 단어(어휘) 카드 — vocab-a1 파일럿 확대 배치.
 * data-ko/b1.ts 등 회화 표현 덱과 별개로, 개별 단어만 다루는 단어장 덱이다.
 *
 * 각 카드: 한국어 단어(ko, 사전형) + 로마자(roman) + 영어/중국어/베트남어 뜻(en/zh/vi)
 * + 예문(4개 언어). 동사/형용사는 사전형(-다)으로 표제하고, 예문에서는 자연스러운
 * 활용형을 쓴다.
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준
 * (된소리되기는 표기에 반영하지 않음 — 예: 습관 seupgwan, 결정하다 gyeoljeonghada).
 * 표제어(ko)는 data-ko/index.ts 의 중복 제거 대상이라, 기존 회화 카드(a1~c2)와
 * vocab-a1 표제어와 겹치지 않게 선정했다 — TOPIK 3급 수준의 추상명사·사회생활·
 * 의견표현 동사/형용사 위주.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_VOCAB_B1_DECKS: Deck[] = [
  {
    id: "vocab-b1",
    level: "B1",
    title: {
      ko: "중급 단어",
      en: "Intermediate Words",
      zh: "中级单词",
      vi: "Từ vựng trung cấp",
    },
    description: {
      ko: "사회생활·의견표현 필수 어휘",
      en: "Essential vocabulary for social life and expressing opinions",
      zh: "社会生活、表达意见必备词汇",
      vi: "Từ vựng thiết yếu cho đời sống xã hội và diễn đạt ý kiến",
    },
    order: 6,
    icon: "BookText",
  },
];

export const KO_VOCAB_B1_CARDS: VocabCard[] = [
  // ─── 명사 ──────────────────────────────────────────────────────────────
  {
    id: "ko-vocab-b1-001",
    level: "B1",
    deck: "vocab-b1",
    en: "society",
    zh: "社会",
    vi: "xã hội",
    ko: "사회",
    roman: "sahoe",
    exampleKo: "저는 사회 문제에 관심이 많아요.",
    exampleEn: "I'm very interested in social issues.",
    exampleZh: "我对社会问题很感兴趣。",
    exampleVi: "Tôi rất quan tâm đến các vấn đề xã hội.",
  },
  {
    id: "ko-vocab-b1-002",
    level: "B1",
    deck: "vocab-b1",
    en: "culture",
    zh: "文化",
    vi: "văn hóa",
    ko: "문화",
    roman: "munhwa",
    exampleKo: "나라마다 문화가 달라요.",
    exampleEn: "Culture is different from country to country.",
    exampleZh: "每个国家的文化都不一样。",
    exampleVi: "Mỗi nước có một nền văn hóa khác nhau.",
  },
  {
    id: "ko-vocab-b1-003",
    level: "B1",
    deck: "vocab-b1",
    en: "experience",
    zh: "经验",
    vi: "kinh nghiệm",
    ko: "경험",
    roman: "gyeongheom",
    exampleKo: "그 일은 저에게 좋은 경험이 됐어요.",
    exampleEn: "That job turned out to be a good experience for me.",
    exampleZh: "那件事对我来说是一次很好的经验。",
    exampleVi: "Việc đó trở thành một kinh nghiệm tốt đối với tôi.",
  },
  {
    id: "ko-vocab-b1-004",
    level: "B1",
    deck: "vocab-b1",
    en: "habit",
    zh: "习惯",
    vi: "thói quen",
    ko: "습관",
    roman: "seupgwan",
    exampleKo: "저는 아침에 일찍 일어나는 습관이 있어요.",
    exampleEn: "I have a habit of waking up early in the morning.",
    exampleZh: "我有早上早起的习惯。",
    exampleVi: "Tôi có thói quen dậy sớm vào buổi sáng.",
  },
  {
    id: "ko-vocab-b1-005",
    level: "B1",
    deck: "vocab-b1",
    en: "personality",
    zh: "性格",
    vi: "tính cách",
    ko: "성격",
    roman: "seonggyeok",
    exampleKo: "제 동생은 성격이 밝고 활발해요.",
    exampleEn: "My younger sibling has a bright, lively personality.",
    exampleZh: "我弟弟妹妹性格开朗又活泼。",
    exampleVi: "Em tôi có tính cách vui vẻ và năng động.",
  },
  {
    id: "ko-vocab-b1-006",
    level: "B1",
    deck: "vocab-b1",
    en: "relationship",
    zh: "关系",
    vi: "mối quan hệ",
    ko: "관계",
    roman: "gwangye",
    exampleKo: "동료들과 좋은 관계를 유지하는 게 중요해요.",
    exampleEn: "It's important to maintain a good relationship with your coworkers.",
    exampleZh: "和同事保持良好的关系很重要。",
    exampleVi: "Việc duy trì mối quan hệ tốt với đồng nghiệp rất quan trọng.",
  },
  {
    id: "ko-vocab-b1-007",
    level: "B1",
    deck: "vocab-b1",
    en: "environment",
    zh: "环境",
    vi: "môi trường",
    ko: "환경",
    roman: "hwangyeong",
    exampleKo: "우리는 환경을 보호해야 해요.",
    exampleEn: "We need to protect the environment.",
    exampleZh: "我们应该保护环境。",
    exampleVi: "Chúng ta cần bảo vệ môi trường.",
  },
  {
    id: "ko-vocab-b1-008",
    level: "B1",
    deck: "vocab-b1",
    en: "attitude",
    zh: "态度",
    vi: "thái độ",
    ko: "태도",
    roman: "taedo",
    exampleKo: "그 사람은 일할 때 태도가 진지해요.",
    exampleEn: "That person has a serious attitude when working.",
    exampleZh: "那个人工作时态度很认真。",
    exampleVi: "Người đó có thái độ nghiêm túc khi làm việc.",
  },
  {
    id: "ko-vocab-b1-009",
    level: "B1",
    deck: "vocab-b1",
    en: "opinion",
    zh: "意见",
    vi: "ý kiến",
    ko: "의견",
    roman: "uigyeon",
    exampleKo: "이 문제에 대한 의견을 말씀해 주세요.",
    exampleEn: "Please share your opinion on this issue.",
    exampleZh: "请说一下您对这个问题的意见。",
    exampleVi: "Xin hãy cho biết ý kiến của bạn về vấn đề này.",
  },
  {
    id: "ko-vocab-b1-010",
    level: "B1",
    deck: "vocab-b1",
    en: "reason",
    zh: "理由",
    vi: "lý do",
    ko: "이유",
    roman: "iyu",
    exampleKo: "늦은 이유를 설명해 주시겠어요?",
    exampleEn: "Could you explain the reason you're late?",
    exampleZh: "能说明一下迟到的理由吗？",
    exampleVi: "Bạn có thể giải thích lý do đến trễ được không?",
  },
  {
    id: "ko-vocab-b1-011",
    level: "B1",
    deck: "vocab-b1",
    en: "goal",
    zh: "目标",
    vi: "mục tiêu",
    ko: "목표",
    roman: "mokpyo",
    exampleKo: "올해 목표를 세웠어요.",
    exampleEn: "I set a goal for this year.",
    exampleZh: "我定了今年的目标。",
    exampleVi: "Tôi đã đặt ra mục tiêu cho năm nay.",
  },
  {
    id: "ko-vocab-b1-012",
    level: "B1",
    deck: "vocab-b1",
    en: "opportunity",
    zh: "机会",
    vi: "cơ hội",
    ko: "기회",
    roman: "gihoe",
    exampleKo: "이번이 좋은 기회인 것 같아요.",
    exampleEn: "This seems like a good opportunity.",
    exampleZh: "这次好像是个好机会。",
    exampleVi: "Lần này có vẻ là một cơ hội tốt.",
  },
  {
    id: "ko-vocab-b1-013",
    level: "B1",
    deck: "vocab-b1",
    en: "responsibility",
    zh: "责任",
    vi: "trách nhiệm",
    ko: "책임",
    roman: "chaegim",
    exampleKo: "이 일은 제가 책임을 지고 하겠습니다.",
    exampleEn: "I'll take responsibility for this and get it done.",
    exampleZh: "这件事我会负责任地完成。",
    exampleVi: "Việc này tôi sẽ chịu trách nhiệm thực hiện.",
    note: "책임을 지다 = to take/bear responsibility for something.",
    noteZh: "책임을 지다 = 承担责任。",
    noteVi: "책임을 지다 = gánh vác/chịu trách nhiệm về việc gì đó.",
  },
  {
    id: "ko-vocab-b1-014",
    level: "B1",
    deck: "vocab-b1",
    en: "condition / requirement",
    zh: "条件",
    vi: "điều kiện",
    ko: "조건",
    roman: "jogeon",
    exampleKo: "이 회사는 근무 조건이 좋은 편이에요.",
    exampleEn: "This company's working conditions are pretty good.",
    exampleZh: "这家公司的工作条件算是不错的。",
    exampleVi: "Điều kiện làm việc ở công ty này khá tốt.",
  },
  {
    id: "ko-vocab-b1-015",
    level: "B1",
    deck: "vocab-b1",
    en: "situation",
    zh: "情况",
    vi: "tình huống",
    ko: "상황",
    roman: "sanghwang",
    exampleKo: "지금 상황이 좀 복잡해요.",
    exampleEn: "The situation is a bit complicated right now.",
    exampleZh: "现在情况有点复杂。",
    exampleVi: "Tình huống hiện tại hơi phức tạp.",
  },
  {
    id: "ko-vocab-b1-016",
    level: "B1",
    deck: "vocab-b1",
    en: "information",
    zh: "信息",
    vi: "thông tin",
    ko: "정보",
    roman: "jeongbo",
    exampleKo: "인터넷에서 필요한 정보를 찾았어요.",
    exampleEn: "I found the information I needed on the internet.",
    exampleZh: "我在网上找到了需要的信息。",
    exampleVi: "Tôi đã tìm được thông tin cần thiết trên mạng.",
  },

  // ─── 동사 (사전형) ─────────────────────────────────────────────────────
  {
    id: "ko-vocab-b1-017",
    level: "B1",
    deck: "vocab-b1",
    en: "to argue / to claim",
    zh: "主张",
    vi: "chủ trương / khẳng định",
    ko: "주장하다",
    roman: "jujanghada",
    exampleKo: "그는 자신이 옳다고 주장했어요.",
    exampleEn: "He claimed that he was right.",
    exampleZh: "他主张自己是对的。",
    exampleVi: "Anh ấy khẳng định rằng mình đúng.",
    note: "주장하다 = to state one's position firmly, often in a discussion or debate.",
    noteZh: "주장하다表示在讨论或辩论中坚定地表明自己的立场。",
    noteVi: "주장하다 nghĩa là khẳng định lập trường của mình một cách chắc chắn, thường trong tranh luận.",
  },
  {
    id: "ko-vocab-b1-018",
    level: "B1",
    deck: "vocab-b1",
    en: "to express",
    zh: "表达",
    vi: "diễn đạt / thể hiện",
    ko: "표현하다",
    roman: "pyohyeonhada",
    exampleKo: "감정을 말로 표현하는 게 쉽지 않아요.",
    exampleEn: "It's not easy to express your feelings in words.",
    exampleZh: "用言语表达感情并不容易。",
    exampleVi: "Diễn đạt cảm xúc bằng lời không phải là điều dễ dàng.",
  },
  {
    id: "ko-vocab-b1-019",
    level: "B1",
    deck: "vocab-b1",
    en: "to understand",
    zh: "理解",
    vi: "hiểu / thông cảm",
    ko: "이해하다",
    roman: "ihaehada",
    exampleKo: "선생님 설명을 듣고 이해했어요.",
    exampleEn: "I understood after listening to the teacher's explanation.",
    exampleZh: "听了老师的讲解后我理解了。",
    exampleVi: "Nghe thầy cô giải thích xong tôi đã hiểu.",
    note: "알다 knows a fact; 이해하다 understands a reason, situation, or feeling.",
    noteZh: "알다指知道某个事实；이해하다指理解原因、情况或心情。",
    noteVi: "알다 nghĩa là biết một sự việc; 이해하다 nghĩa là hiểu lý do, tình huống hoặc cảm xúc.",
  },
  {
    id: "ko-vocab-b1-020",
    level: "B1",
    deck: "vocab-b1",
    en: "to decide",
    zh: "决定",
    vi: "quyết định",
    ko: "결정하다",
    roman: "gyeoljeonghada",
    exampleKo: "다음 달에 이사하기로 결정했어요.",
    exampleEn: "I decided to move next month.",
    exampleZh: "我决定下个月搬家。",
    exampleVi: "Tôi đã quyết định chuyển nhà vào tháng sau.",
  },
  {
    id: "ko-vocab-b1-021",
    level: "B1",
    deck: "vocab-b1",
    en: "to develop / to advance",
    zh: "发展",
    vi: "phát triển",
    ko: "발전하다",
    roman: "baljeonhada",
    exampleKo: "그 회사는 빠르게 발전하고 있어요.",
    exampleEn: "That company is developing quickly.",
    exampleZh: "那家公司正在快速发展。",
    exampleVi: "Công ty đó đang phát triển nhanh chóng.",
  },
  {
    id: "ko-vocab-b1-022",
    level: "B1",
    deck: "vocab-b1",
    en: "to make an effort / to try hard",
    zh: "努力",
    vi: "nỗ lực / cố gắng",
    ko: "노력하다",
    roman: "noryeokhada",
    exampleKo: "목표를 이루려고 매일 노력하고 있어요.",
    exampleEn: "I'm making an effort every day to reach my goal.",
    exampleZh: "为了实现目标，我每天都在努力。",
    exampleVi: "Tôi đang nỗ lực mỗi ngày để đạt được mục tiêu.",
  },
  {
    id: "ko-vocab-b1-023",
    level: "B1",
    deck: "vocab-b1",
    en: "to participate",
    zh: "参与",
    vi: "tham gia",
    ko: "참여하다",
    roman: "chamyeohada",
    exampleKo: "이번 행사에 많은 사람들이 참여했어요.",
    exampleEn: "Many people participated in this event.",
    exampleZh: "很多人参与了这次活动。",
    exampleVi: "Nhiều người đã tham gia sự kiện lần này.",
    note: "참여하다 focuses on joining/taking part; 참석하다 is closer to 'attending' a set event.",
    noteZh: "참여하다侧重'加入、参与其中'；참석하다更接近'出席'某个既定活动。",
    noteVi: "참여하다 nhấn mạnh việc 'tham gia vào'; 참석하다 gần nghĩa 'có mặt, dự' một sự kiện đã định sẵn hơn.",
  },
  {
    id: "ko-vocab-b1-024",
    level: "B1",
    deck: "vocab-b1",
    en: "to oppose / to be against",
    zh: "反对",
    vi: "phản đối",
    ko: "반대하다",
    roman: "bandaehada",
    exampleKo: "부모님이 제 유학을 반대하셨어요.",
    exampleEn: "My parents were against me studying abroad.",
    exampleZh: "父母反对我出国留学。",
    exampleVi: "Bố mẹ đã phản đối việc tôi đi du học.",
  },
  {
    id: "ko-vocab-b1-025",
    level: "B1",
    deck: "vocab-b1",
    en: "to compare",
    zh: "比较",
    vi: "so sánh",
    ko: "비교하다",
    roman: "bigyohada",
    exampleKo: "가격을 비교하고 나서 결정하세요.",
    exampleEn: "Compare the prices before you decide.",
    exampleZh: "请比较一下价格之后再决定。",
    exampleVi: "Hãy so sánh giá cả rồi mới quyết định.",
  },
  {
    id: "ko-vocab-b1-026",
    level: "B1",
    deck: "vocab-b1",
    en: "to consider",
    zh: "考虑",
    vi: "cân nhắc",
    ko: "고려하다",
    roman: "goryeohada",
    exampleKo: "이직을 진지하게 고려하고 있어요.",
    exampleEn: "I'm seriously considering changing jobs.",
    exampleZh: "我正在认真考虑跳槽。",
    exampleVi: "Tôi đang cân nhắc nghiêm túc việc chuyển việc.",
  },

  // ─── 형용사 (사전형) ───────────────────────────────────────────────────
  {
    id: "ko-vocab-b1-027",
    level: "B1",
    deck: "vocab-b1",
    en: "to be important",
    zh: "重要",
    vi: "quan trọng",
    ko: "중요하다",
    roman: "jungyohada",
    exampleKo: "건강이 무엇보다 중요해요.",
    exampleEn: "Health is more important than anything else.",
    exampleZh: "健康比什么都重要。",
    exampleVi: "Sức khỏe quan trọng hơn bất cứ điều gì.",
  },
  {
    id: "ko-vocab-b1-028",
    level: "B1",
    deck: "vocab-b1",
    en: "to be diverse / various",
    zh: "多样",
    vi: "đa dạng",
    ko: "다양하다",
    roman: "dayanghada",
    exampleKo: "이 식당은 메뉴가 다양해요.",
    exampleEn: "This restaurant has a diverse menu.",
    exampleZh: "这家餐厅的菜单很多样。",
    exampleVi: "Nhà hàng này có thực đơn rất đa dạng.",
  },
  {
    id: "ko-vocab-b1-029",
    level: "B1",
    deck: "vocab-b1",
    en: "to be complicated / complex",
    zh: "复杂",
    vi: "phức tạp",
    ko: "복잡하다",
    roman: "bokjaphada",
    exampleKo: "지하철 노선도가 너무 복잡해요.",
    exampleEn: "The subway map is too complicated.",
    exampleZh: "地铁线路图太复杂了。",
    exampleVi: "Sơ đồ tuyến tàu điện ngầm quá phức tạp.",
  },
  {
    id: "ko-vocab-b1-030",
    level: "B1",
    deck: "vocab-b1",
    en: "to be familiar with / used to",
    zh: "熟悉 / 习惯",
    vi: "quen thuộc / quen với",
    ko: "익숙하다",
    roman: "iksukhada",
    exampleKo: "이제 한국 생활에 많이 익숙해졌어요.",
    exampleEn: "I've become quite used to life in Korea now.",
    exampleZh: "现在我已经很习惯韩国的生活了。",
    exampleVi: "Bây giờ tôi đã khá quen với cuộc sống ở Hàn Quốc.",
    note: "익숙하다 pairs with the particle 에 (익숙해지다 = to become used to something).",
    noteZh: "익숙하다与助词에搭配（익숙해지다=变得习惯于……）。",
    noteVi: "익숙하다 đi cùng trợ từ 에 (익숙해지다 = trở nên quen với điều gì đó).",
  },
];
