/**
 * A2 (초급) 한국어 학습 단어(어휘) 카드 — A1 파일럿(#47, vocab-a1.ts) 확대.
 * data-ko/a2.ts 등 회화 표현 덱과 별개로, 개별 단어만 다루는 단어장 덱이다.
 *
 * 각 카드: 한국어 단어(ko, 사전형) + 로마자(roman) + 영어/중국어/베트남어 뜻(en/zh/vi)
 * + 예문(4개 언어). 동사/형용사는 사전형(-다)으로 표제하고, 예문에서는 자연스러운
 * 활용형을 쓴다 (예: 걷다 → 예문 "걸어가요").
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * 표제어(ko)는 data-ko/index.ts 의 중복 제거 대상이라, 기존 a1~c2 회화 카드 및
 * vocab-a1 단어 카드의 표제어와 겹치지 않게 선정했다 — 장소 명사·시간/빈도 부사·
 * 동사·감정 형용사 위주로 A1 단어장보다 한 단계 위 일상 어휘를 다룬다.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_VOCAB_A2_DECKS: Deck[] = [
  {
    id: "vocab-a2",
    level: "A2",
    title: {
      ko: "생활 단어",
      en: "Everyday Words",
      zh: "生活单词",
      vi: "Từ vựng đời sống",
    },
    description: {
      ko: "장소·시간·감정 표현 등 한 단계 확장된 일상 어휘",
      en: "Places, time, and emotions — a step up in everyday vocabulary",
      zh: "场所、时间、情感等更进一层的日常词汇",
      vi: "Từ vựng đời sống nâng cao hơn: địa điểm, thời gian, cảm xúc",
    },
    order: 6,
    icon: "BookText",
  },
];

export const KO_VOCAB_A2_CARDS: VocabCard[] = [
  // ─── 장소 명사 ─────────────────────────────────────────────────────────
  {
    id: "ko-vocab-a2-001",
    level: "A2",
    deck: "vocab-a2",
    en: "hospital",
    zh: "医院",
    vi: "bệnh viện",
    ko: "병원",
    roman: "byeongwon",
    exampleKo: "저는 지금 병원에 가요.",
    exampleEn: "I am going to the hospital now.",
    exampleZh: "我现在去医院。",
    exampleVi: "Bây giờ tôi đi bệnh viện.",
  },
  {
    id: "ko-vocab-a2-002",
    level: "A2",
    deck: "vocab-a2",
    en: "bank",
    zh: "银行",
    vi: "ngân hàng",
    ko: "은행",
    roman: "eunhaeng",
    exampleKo: "은행은 몇 시에 열어요?",
    exampleEn: "What time does the bank open?",
    exampleZh: "银行几点开门？",
    exampleVi: "Ngân hàng mở cửa lúc mấy giờ?",
  },
  {
    id: "ko-vocab-a2-003",
    level: "A2",
    deck: "vocab-a2",
    en: "park",
    zh: "公园",
    vi: "công viên",
    ko: "공원",
    roman: "gongwon",
    exampleKo: "주말에 공원에서 산책해요.",
    exampleEn: "I take a walk in the park on weekends.",
    exampleZh: "我周末在公园散步。",
    exampleVi: "Cuối tuần tôi đi dạo ở công viên.",
  },
  {
    id: "ko-vocab-a2-004",
    level: "A2",
    deck: "vocab-a2",
    en: "market",
    zh: "市场",
    vi: "chợ",
    ko: "시장",
    roman: "sijang",
    exampleKo: "시장에서 채소를 팔아요.",
    exampleEn: "They sell vegetables at the market.",
    exampleZh: "市场里卖蔬菜。",
    exampleVi: "Người ta bán rau ở chợ.",
  },
  {
    id: "ko-vocab-a2-005",
    level: "A2",
    deck: "vocab-a2",
    en: "airport",
    zh: "机场",
    vi: "sân bay",
    ko: "공항",
    roman: "gonghang",
    exampleKo: "공항까지 얼마나 걸려요?",
    exampleEn: "How long does it take to the airport?",
    exampleZh: "到机场要多长时间？",
    exampleVi: "Đến sân bay mất bao lâu?",
  },
  {
    id: "ko-vocab-a2-006",
    level: "A2",
    deck: "vocab-a2",
    en: "post office",
    zh: "邮局",
    vi: "bưu điện",
    ko: "우체국",
    roman: "ucheguk",
    exampleKo: "우체국에서 소포를 보내요.",
    exampleEn: "I send a package at the post office.",
    exampleZh: "我在邮局寄包裹。",
    exampleVi: "Tôi gửi bưu kiện ở bưu điện.",
  },
  {
    id: "ko-vocab-a2-007",
    level: "A2",
    deck: "vocab-a2",
    en: "convenience store",
    zh: "便利店",
    vi: "cửa hàng tiện lợi",
    ko: "편의점",
    roman: "pyeonuijeom",
    exampleKo: "편의점에서 물을 샀어요.",
    exampleEn: "I bought water at the convenience store.",
    exampleZh: "我在便利店买了水。",
    exampleVi: "Tôi đã mua nước ở cửa hàng tiện lợi.",
  },

  // ─── 시간·빈도 부사 ────────────────────────────────────────────────────
  {
    id: "ko-vocab-a2-008",
    level: "A2",
    deck: "vocab-a2",
    en: "every day",
    zh: "每天",
    vi: "mỗi ngày",
    ko: "매일",
    roman: "maeil",
    exampleKo: "저는 매일 운동해요.",
    exampleEn: "I exercise every day.",
    exampleZh: "我每天运动。",
    exampleVi: "Tôi tập thể dục mỗi ngày.",
  },
  {
    id: "ko-vocab-a2-009",
    level: "A2",
    deck: "vocab-a2",
    en: "yet / still",
    zh: "还",
    vi: "vẫn chưa",
    ko: "아직",
    roman: "ajik",
    exampleKo: "아직 안 끝났어요.",
    exampleEn: "It's not finished yet.",
    exampleZh: "还没结束。",
    exampleVi: "Vẫn chưa xong.",
  },
  {
    id: "ko-vocab-a2-010",
    level: "A2",
    deck: "vocab-a2",
    en: "already",
    zh: "已经",
    vi: "đã ... rồi",
    ko: "벌써",
    roman: "beolsseo",
    exampleKo: "벌써 열두 시예요.",
    exampleEn: "It's already twelve o'clock.",
    exampleZh: "已经十二点了。",
    exampleVi: "Đã mười hai giờ rồi.",
  },
  {
    id: "ko-vocab-a2-011",
    level: "A2",
    deck: "vocab-a2",
    en: "later",
    zh: "以后",
    vi: "lát nữa",
    ko: "나중에",
    roman: "najunge",
    exampleKo: "나중에 다시 전화할게요.",
    exampleEn: "I'll call you again later.",
    exampleZh: "我以后再打电话给你。",
    exampleVi: "Lát nữa tôi sẽ gọi lại.",
  },
  {
    id: "ko-vocab-a2-012",
    level: "A2",
    deck: "vocab-a2",
    en: "sometimes",
    zh: "偶尔",
    vi: "thỉnh thoảng",
    ko: "가끔",
    roman: "gakkeum",
    exampleKo: "저는 가끔 늦게 자요.",
    exampleEn: "I sometimes go to bed late.",
    exampleZh: "我偶尔很晚才睡觉。",
    exampleVi: "Thỉnh thoảng tôi ngủ muộn.",
  },
  {
    id: "ko-vocab-a2-013",
    level: "A2",
    deck: "vocab-a2",
    en: "often",
    zh: "经常",
    vi: "thường xuyên",
    ko: "자주",
    roman: "jaju",
    exampleKo: "저는 이 식당에 자주 와요.",
    exampleEn: "I often come to this restaurant.",
    exampleZh: "我经常来这家餐厅。",
    exampleVi: "Tôi thường xuyên đến nhà hàng này.",
  },
  {
    id: "ko-vocab-a2-014",
    level: "A2",
    deck: "vocab-a2",
    en: "always",
    zh: "总是",
    vi: "luôn luôn",
    ko: "항상",
    roman: "hangsang",
    exampleKo: "그 사람은 항상 웃어요.",
    exampleEn: "That person always smiles.",
    exampleZh: "那个人总是在笑。",
    exampleVi: "Người đó luôn luôn cười.",
  },

  // ─── 동사 (사전형) ─────────────────────────────────────────────────────
  {
    id: "ko-vocab-a2-015",
    level: "A2",
    deck: "vocab-a2",
    en: "to meet",
    zh: "见面",
    vi: "gặp",
    ko: "만나다",
    roman: "mannada",
    exampleKo: "내일 친구를 만나요.",
    exampleEn: "I'm meeting a friend tomorrow.",
    exampleZh: "我明天要见朋友。",
    exampleVi: "Ngày mai tôi gặp bạn.",
  },
  {
    id: "ko-vocab-a2-016",
    level: "A2",
    deck: "vocab-a2",
    en: "to wait",
    zh: "等",
    vi: "chờ / đợi",
    ko: "기다리다",
    roman: "gidarida",
    exampleKo: "여기서 잠깐 기다려 주세요.",
    exampleEn: "Please wait here for a moment.",
    exampleZh: "请在这里稍等一下。",
    exampleVi: "Xin hãy đợi ở đây một chút.",
  },
  {
    id: "ko-vocab-a2-017",
    level: "A2",
    deck: "vocab-a2",
    en: "to learn",
    zh: "学习",
    vi: "học",
    ko: "배우다",
    roman: "baeuda",
    exampleKo: "저는 한국어를 배워요.",
    exampleEn: "I am learning Korean.",
    exampleZh: "我在学习韩语。",
    exampleVi: "Tôi đang học tiếng Hàn.",
  },
  {
    id: "ko-vocab-a2-018",
    level: "A2",
    deck: "vocab-a2",
    en: "to teach",
    zh: "教",
    vi: "dạy",
    ko: "가르치다",
    roman: "gareuchida",
    exampleKo: "저는 아이들에게 영어를 가르쳐요.",
    exampleEn: "I teach English to children.",
    exampleZh: "我教孩子们英语。",
    exampleVi: "Tôi dạy tiếng Anh cho trẻ em.",
  },
  {
    id: "ko-vocab-a2-019",
    level: "A2",
    deck: "vocab-a2",
    en: "to help",
    zh: "帮助",
    vi: "giúp đỡ",
    ko: "도와주다",
    roman: "dowajuda",
    exampleKo: "짐 옮기는 것 좀 도와주세요.",
    exampleEn: "Please help me carry the luggage.",
    exampleZh: "请帮我搬一下行李。",
    exampleVi: "Hãy giúp tôi mang hành lý.",
    note: "도와주다 combines 돕다 ('to help') + 주다 ('to give') — helping or asking for help on someone's behalf.",
    noteZh: "도와주다 = 돕다（帮助）+ 주다（给）— 表示为别人提供或请求帮助。",
    noteVi: "도와주다 = 돕다 (giúp) + 주다 (cho) — dùng khi giúp đỡ hoặc nhờ ai đó giúp đỡ.",
  },
  {
    id: "ko-vocab-a2-020",
    level: "A2",
    deck: "vocab-a2",
    en: "to walk",
    zh: "走路",
    vi: "đi bộ",
    ko: "걷다",
    roman: "geotda",
    exampleKo: "저는 학교까지 걸어가요.",
    exampleEn: "I walk to school.",
    exampleZh: "我走路去学校。",
    exampleVi: "Tôi đi bộ đến trường.",
    note: "걷다 is a ㄷ-irregular verb — the stem 걷 changes to 걸 before a vowel (걸어요, not 걷어요).",
    noteZh: "걷다 是ㄷ不规则动词，词干걷在元音前变为걸（如걸어요，而不是걷어요）。",
    noteVi: "걷다 là động từ bất quy tắc ㄷ — gốc 걷 đổi thành 걸 trước nguyên âm (걸어요, không phải 걷어요).",
  },
  {
    id: "ko-vocab-a2-021",
    level: "A2",
    deck: "vocab-a2",
    en: "to ride / to get on",
    zh: "乘坐",
    vi: "đi (bằng phương tiện)",
    ko: "타다",
    roman: "tada",
    exampleKo: "저는 버스를 타고 회사에 가요.",
    exampleEn: "I go to work by bus.",
    exampleZh: "我坐公交车去公司。",
    exampleVi: "Tôi đi làm bằng xe buýt.",
  },
  {
    id: "ko-vocab-a2-022",
    level: "A2",
    deck: "vocab-a2",
    en: "to make",
    zh: "做 / 制作",
    vi: "làm / chế tạo",
    ko: "만들다",
    roman: "mandeulda",
    exampleKo: "제가 저녁을 만들게요.",
    exampleEn: "I'll make dinner.",
    exampleZh: "我来做晚饭吧。",
    exampleVi: "Để tôi làm bữa tối.",
  },
  {
    id: "ko-vocab-a2-023",
    level: "A2",
    deck: "vocab-a2",
    en: "to find / to look for",
    zh: "找",
    vi: "tìm",
    ko: "찾다",
    roman: "chatda",
    exampleKo: "지갑을 못 찾았어요.",
    exampleEn: "I couldn't find my wallet.",
    exampleZh: "我没找到钱包。",
    exampleVi: "Tôi không tìm thấy ví.",
  },

  // ─── 형용사·감정 표현 (사전형) ─────────────────────────────────────────
  {
    id: "ko-vocab-a2-024",
    level: "A2",
    deck: "vocab-a2",
    en: "to be glad / happy",
    zh: "高兴",
    vi: "vui mừng",
    ko: "기쁘다",
    roman: "gippeuda",
    exampleKo: "합격해서 정말 기뻐요.",
    exampleEn: "I'm so glad I passed.",
    exampleZh: "我通过了，真高兴。",
    exampleVi: "Tôi rất vui vì đã đỗ.",
  },
  {
    id: "ko-vocab-a2-025",
    level: "A2",
    deck: "vocab-a2",
    en: "to be sad",
    zh: "伤心 / 悲伤",
    vi: "buồn",
    ko: "슬프다",
    roman: "seulpeuda",
    exampleKo: "이 영화는 정말 슬퍼요.",
    exampleEn: "This movie is really sad.",
    exampleZh: "这部电影真悲伤。",
    exampleVi: "Bộ phim này thật sự rất buồn.",
  },
  {
    id: "ko-vocab-a2-026",
    level: "A2",
    deck: "vocab-a2",
    en: "to get angry",
    zh: "生气",
    vi: "tức giận",
    ko: "화나다",
    roman: "hwanada",
    exampleKo: "동생이 제 물건을 써서 화났어요.",
    exampleEn: "I got angry because my sibling used my things.",
    exampleZh: "弟弟妹妹用了我的东西，我很生气。",
    exampleVi: "Tôi tức giận vì em dùng đồ của tôi.",
    note: "화나다 combines 화 ('anger') + 나다 ('to arise') — literally 'anger arises'.",
    noteZh: "화나다 由 화（怒气）+ 나다（产生）组成，字面意思接近怒气上涌。",
    noteVi: "화나다 gồm 화 (sự tức giận) + 나다 (nảy sinh) — nghĩa đen là cơn giận nổi lên.",
  },
  {
    id: "ko-vocab-a2-027",
    level: "A2",
    deck: "vocab-a2",
    en: "to be tired",
    zh: "疲惫 / 累",
    vi: "mệt",
    ko: "피곤하다",
    roman: "pigonhada",
    exampleKo: "요즘 일이 많아서 피곤해요.",
    exampleEn: "I'm tired because I have a lot of work these days.",
    exampleZh: "最近工作很多，很累。",
    exampleVi: "Dạo này nhiều việc nên tôi mệt.",
  },
  {
    id: "ko-vocab-a2-028",
    level: "A2",
    deck: "vocab-a2",
    en: "to be scary / to be afraid",
    zh: "可怕 / 害怕",
    vi: "sợ / đáng sợ",
    ko: "무섭다",
    roman: "museopda",
    exampleKo: "밤에 혼자 걸으면 무서워요.",
    exampleEn: "It's scary to walk alone at night.",
    exampleZh: "晚上一个人走路很可怕。",
    exampleVi: "Đi bộ một mình vào ban đêm thì đáng sợ.",
  },
  {
    id: "ko-vocab-a2-029",
    level: "A2",
    deck: "vocab-a2",
    en: "to be comfortable",
    zh: "舒服 / 方便",
    vi: "thoải mái",
    ko: "편하다",
    roman: "pyeonhada",
    exampleKo: "이 의자는 정말 편해요.",
    exampleEn: "This chair is really comfortable.",
    exampleZh: "这把椅子真舒服。",
    exampleVi: "Cái ghế này thật sự rất thoải mái.",
  },
  {
    id: "ko-vocab-a2-030",
    level: "A2",
    deck: "vocab-a2",
    en: "to be close / to be near",
    zh: "近",
    vi: "gần",
    ko: "가깝다",
    roman: "gakkapda",
    exampleKo: "제 집은 회사에서 가까워요.",
    exampleEn: "My house is close to the company.",
    exampleZh: "我家离公司很近。",
    exampleVi: "Nhà tôi gần công ty.",
  },
];
