/**
 * C1 (고급) 한국어 학습 단어(어휘) 카드 — vocab-a1 파일럿 확대 배치.
 * data-ko/c1.ts 등 회화 표현 덱과 별개로, 개별 단어만 다루는 단어장 덱이다.
 *
 * 각 카드: 한국어 단어(ko, 사전형) + 로마자(roman) + 영어/중국어/베트남어 뜻(en/zh/vi)
 * + 예문(4개 언어). 동사/형용사는 사전형(-다)으로 표제하고, 예문에서는 자연스러운
 * 활용형을 쓴다 (예: 막대하다 → 예문 "막대한").
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * 표제어(ko)는 data-ko/index.ts 의 중복 제거 대상이라, 기존 c1(회화)·c2(전문가) 등
 * 다른 덱의 표제어와 겹치지 않게 선정했다.
 *
 * C1 난이도(TOPIK 5급 참고): 업무·사회·논리 담론에서 쓰이는 전문·추상·한자어
 * 중심 어휘. 등급은 참고용이며 뜻·예문은 자체 작성했다.
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_VOCAB_C1_DECKS: Deck[] = [
  {
    id: "vocab-c1",
    level: "C1",
    title: {
      ko: "고급 단어",
      en: "Advanced Words",
      zh: "高级单词",
      vi: "Từ vựng cao cấp",
    },
    description: {
      ko: "전문·추상·논리 담론에 쓰이는 한자어 중심 어휘",
      en: "Sino-Korean vocabulary for professional, abstract, and logical discourse",
      zh: "用于专业、抽象、逻辑论述的汉字词汇",
      vi: "Từ vựng gốc Hán dùng trong diễn ngôn chuyên môn, trừu tượng và luận lý",
    },
    order: 5,
    icon: "Library",
  },
];

export const KO_VOCAB_C1_CARDS: VocabCard[] = [
  // ─── 명사 ──────────────────────────────────────────────────────────────
  {
    id: "ko-vocab-c1-001",
    level: "C1",
    deck: "vocab-c1",
    en: "actual situation / state of affairs",
    zh: "实际情况",
    vi: "thực trạng",
    ko: "실태",
    roman: "siltae",
    exampleKo: "정부는 청년 실업의 실태를 조사했습니다.",
    exampleEn: "The government investigated the actual state of youth unemployment.",
    exampleZh: "政府调查了青年失业的实际情况。",
    exampleVi: "Chính phủ đã điều tra thực trạng thất nghiệp của thanh niên.",
    note: "실 (real, 實) + 태 (state, 態) — common in the fixed phrase 실태 조사 (fact-finding survey).",
    noteZh: "실（实，實）+ 태（态，態）——常用于固定搭配「실태 조사」（实况调查）。",
    noteVi: "실 (thực, có thật) + 태 (trạng thái) — thường dùng trong cụm cố định 실태 조사 (điều tra thực trạng).",
  },
  {
    id: "ko-vocab-c1-002",
    level: "C1",
    deck: "vocab-c1",
    en: "purpose / underlying intent",
    zh: "宗旨、主旨",
    vi: "mục đích, chủ ý",
    ko: "취지",
    roman: "chwiji",
    exampleKo: "이 제도를 도입한 취지를 먼저 설명드리겠습니다.",
    exampleEn: "Let me first explain the purpose behind introducing this system.",
    exampleZh: "我先说明一下引入这项制度的宗旨。",
    exampleVi: "Trước tiên tôi xin giải thích mục đích của việc áp dụng chế độ này.",
    note: "Often used as 취지에서 (with the intent of ~) or 취지를 살리다 (to honor the original intent).",
    noteZh: "常用作「취지에서」（出于……的宗旨）或「취지를 살리다」（贯彻本意）。",
    noteVi: "Thường dùng trong 취지에서 (với mục đích là) hoặc 취지를 살리다 (giữ đúng tinh thần ban đầu).",
  },
  {
    id: "ko-vocab-c1-003",
    level: "C1",
    deck: "vocab-c1",
    en: "prejudice / bias",
    zh: "偏见",
    vi: "định kiến",
    ko: "편견",
    roman: "pyeongyeon",
    exampleKo: "나이에 대한 편견 없이 능력으로 평가해야 합니다.",
    exampleEn: "We should judge by ability, without prejudice about age.",
    exampleZh: "应该不带年龄偏见，只凭能力来评价。",
    exampleVi: "Cần đánh giá dựa trên năng lực mà không có định kiến về tuổi tác.",
    note: "편 (leaning, 偏) + 견 (view, 見) — literally 'a view leaning to one side'.",
    noteZh: "편（偏，偏）+ 견（见，見）——字面意思是「偏向一方的看法」。",
    noteVi: "편 (nghiêng, thiên lệch) + 견 (cái nhìn) — nghĩa đen là \"cái nhìn lệch về một phía\".",
  },
  {
    id: "ko-vocab-c1-004",
    level: "C1",
    deck: "vocab-c1",
    en: "loophole / weak point",
    zh: "漏洞、破绽",
    vi: "kẽ hở, điểm yếu",
    ko: "허점",
    roman: "heojeom",
    exampleKo: "변호인은 검찰 측 주장의 허점을 파고들었습니다.",
    exampleEn: "The defense attorney zeroed in on the loopholes in the prosecution's argument.",
    exampleZh: "辩护律师抓住了检方主张的漏洞穷追不舍。",
    exampleVi: "Luật sư bào chữa đã khai thác triệt để những kẽ hở trong lập luận của bên công tố.",
    note: "허 (empty, 虛) + 점 (point, 點) — a 'gap point' in logic, security, or a plan.",
    noteZh: "허（虚，虛）+ 점（点，點）——指逻辑、安保或计划中的「空隙点」。",
    noteVi: "허 (trống rỗng) + 점 (điểm) — chỉ \"điểm hở\" trong logic, an ninh hoặc kế hoạch.",
  },
  {
    id: "ko-vocab-c1-005",
    level: "C1",
    deck: "vocab-c1",
    en: "harmful effect / evil",
    zh: "弊端、危害",
    vi: "tác hại, tệ hại",
    ko: "폐해",
    roman: "pyehae",
    exampleKo: "과도한 경쟁이 낳는 폐해를 간과해서는 안 됩니다.",
    exampleEn: "We must not overlook the harmful effects caused by excessive competition.",
    exampleZh: "不能忽视过度竞争所带来的弊端。",
    exampleVi: "Không được bỏ qua những tác hại do cạnh tranh quá mức gây ra.",
    note: "폐 (harm, 弊) + 해 (harm, 害) — doubling the idea of harm, stronger than 문제점 (problem).",
    noteZh: "폐（弊，弊）+ 해（害，害）——两个表「害」的字组合，语气比 문제점（问题点）更强烈。",
    noteVi: "폐 (tệ hại) + 해 (gây hại) — ghép hai chữ đều mang nghĩa \"hại\", ngữ khí mạnh hơn 문제점 (vấn đề).",
  },
  {
    id: "ko-vocab-c1-006",
    level: "C1",
    deck: "vocab-c1",
    en: "established practice / convention",
    zh: "惯例",
    vi: "thông lệ",
    ko: "관행",
    roman: "gwanhaeng",
    exampleKo: "오래된 관행이라도 불합리하면 바꿔야 합니다.",
    exampleEn: "Even a long-standing practice should be changed if it's unreasonable.",
    exampleZh: "即使是由来已久的惯例，若不合理也应该改变。",
    exampleVi: "Dù là thông lệ đã có từ lâu, nếu bất hợp lý thì vẫn phải thay đổi.",
    note: "관 (accustomed, 慣) + 행 (act, 行) — a way of doing things settled by custom, not law.",
    noteZh: "관（惯，慣）+ 행（行为，行）——由习惯而非法律确立的做事方式。",
    noteVi: "관 (quen, thói quen) + 행 (hành động) — cách làm việc được xác lập theo thói quen chứ không phải luật lệ.",
  },
  {
    id: "ko-vocab-c1-007",
    level: "C1",
    deck: "vocab-c1",
    en: "insight",
    zh: "洞察",
    vi: "sự thấu hiểu, cái nhìn sâu sắc",
    ko: "통찰",
    roman: "tongchal",
    exampleKo: "그 책은 인간관계에 대한 깊은 통찰을 보여줍니다.",
    exampleEn: "That book shows deep insight into human relationships.",
    exampleZh: "那本书展现了对人际关系的深刻洞察。",
    exampleVi: "Cuốn sách đó thể hiện sự thấu hiểu sâu sắc về mối quan hệ giữa con người.",
    note: "Often paired with 력 as 통찰력 (insight, power of discernment) — both forms are common.",
    noteZh: "常与「력」结合成「통찰력」（洞察力），两种形式都很常见。",
    noteVi: "Thường kết hợp với \"력\" thành 통찰력 (khả năng thấu hiểu) — cả hai dạng đều thông dụng.",
  },
  {
    id: "ko-vocab-c1-008",
    level: "C1",
    deck: "vocab-c1",
    en: "context",
    zh: "脉络、背景",
    vi: "bối cảnh, mạch văn",
    ko: "맥락",
    roman: "maengnak",
    exampleKo: "그 발언은 전체 맥락에서 이해해야 합니다.",
    exampleEn: "That remark should be understood in its full context.",
    exampleZh: "那句话应该放在整体脉络中理解。",
    exampleVi: "Phát ngôn đó cần được hiểu trong bối cảnh tổng thể.",
    note: "맥 (vein, 脈) + 락 (connect, 絡) — literally 'connected veins', the thread linking ideas.",
    noteZh: "맥（脉，脈）+ 락（络，絡）——字面为「相连的脉络」，即贯穿事物的线索。",
    noteVi: "맥 (mạch) + 락 (kết nối) — nghĩa đen là \"mạch nối liền\", tức là sợi dây liên kết các ý.",
  },

  // ─── 동사 (사전형) ─────────────────────────────────────────────────────
  {
    id: "ko-vocab-c1-009",
    level: "C1",
    deck: "vocab-c1",
    en: "to overlook",
    zh: "忽视",
    vi: "bỏ qua, xem nhẹ",
    ko: "간과하다",
    roman: "gangwahada",
    exampleKo: "작은 신호라도 간과하면 큰 사고로 이어질 수 있습니다.",
    exampleEn: "Even overlooking a small warning sign can lead to a major accident.",
    exampleZh: "哪怕忽视一个小小的信号，也可能酿成重大事故。",
    exampleVi: "Chỉ cần bỏ qua một dấu hiệu nhỏ cũng có thể dẫn đến tai nạn lớn.",
    note: "간 (careless, 看) + 과 (pass by, 過) — to let something pass without proper attention.",
    noteZh: "간（看）+ 과（经过，過）——让事情轻易滑过而未加以留意。",
    noteVi: "간 (nhìn qua loa) + 과 (đi qua) — để một điều gì đó trôi qua mà không chú ý đúng mức.",
  },
  {
    id: "ko-vocab-c1-010",
    level: "C1",
    deck: "vocab-c1",
    en: "to bring about / cause",
    zh: "招致、导致",
    vi: "gây ra, dẫn đến",
    ko: "초래하다",
    roman: "choraehada",
    exampleKo: "무리한 확장은 결국 자금난을 초래했습니다.",
    exampleEn: "Reckless expansion eventually brought about a cash crunch.",
    exampleZh: "过度扩张最终导致了资金短缺。",
    exampleVi: "Việc mở rộng quá mức cuối cùng đã gây ra tình trạng thiếu vốn.",
    note: "Almost always used for undesirable outcomes, as in 결과를 초래하다 (to bring about a result).",
    noteZh: "几乎总是用于不良后果——如「결과를 초래하다」（招致后果）。",
    noteVi: "Hầu như luôn dùng cho hậu quả không mong muốn — như 결과를 초래하다 (gây ra hậu quả).",
  },
  {
    id: "ko-vocab-c1-011",
    level: "C1",
    deck: "vocab-c1",
    en: "to promote / strive for",
    zh: "谋求",
    vi: "mưu cầu, thúc đẩy",
    ko: "도모하다",
    roman: "domohada",
    exampleKo: "양국은 경제 협력 강화를 도모하기로 했습니다.",
    exampleEn: "The two countries agreed to work toward strengthening economic cooperation.",
    exampleZh: "两国决定谋求加强经济合作。",
    exampleVi: "Hai nước đã nhất trí thúc đẩy tăng cường hợp tác kinh tế.",
    note: "A formal verb for actively seeking a goal — common in diplomatic and organizational language.",
    noteZh: "正式用语，表示积极谋求某目标，常见于外交和组织用语。",
    noteVi: "Động từ trang trọng chỉ việc chủ động theo đuổi mục tiêu, thường dùng trong ngôn ngữ ngoại giao và tổ chức.",
  },
  {
    id: "ko-vocab-c1-012",
    level: "C1",
    deck: "vocab-c1",
    en: "to exclude / rule out",
    zh: "排除",
    vi: "loại trừ",
    ko: "배제하다",
    roman: "baejehada",
    exampleKo: "어떤 가능성도 배제하지 않고 검토하고 있습니다.",
    exampleEn: "We're reviewing every possibility without ruling anything out.",
    exampleZh: "我们正在审视每一种可能性，不排除任何选项。",
    exampleVi: "Chúng tôi đang xem xét mọi khả năng mà không loại trừ bất kỳ điều gì.",
    note: "배 (reject, 排) + 제 (remove, 除) — to actively push something out of consideration.",
    noteZh: "배（排，排）+ 제（除，除）——主动将某事物排除在考虑范围之外。",
    noteVi: "배 (đẩy ra) + 제 (loại bỏ) — chủ động đẩy điều gì đó ra khỏi phạm vi xem xét.",
  },
  {
    id: "ko-vocab-c1-013",
    level: "C1",
    deck: "vocab-c1",
    en: "to regard as / deem",
    zh: "视为",
    vi: "coi là",
    ko: "간주하다",
    roman: "ganjuhada",
    exampleKo: "답변이 없으면 동의한 것으로 간주하겠습니다.",
    exampleEn: "If there's no response, we will consider it as agreement.",
    exampleZh: "如果没有回复，将视为同意。",
    exampleVi: "Nếu không có phản hồi, chúng tôi sẽ coi như đã đồng ý.",
    note: "Used to formally classify or treat something as a given status — common in contracts and rules.",
    noteZh: "用于正式地将某事物归类或视为某种状态，常见于合同和规定中。",
    noteVi: "Dùng để chính thức xếp loại hoặc coi một điều gì đó ở một trạng thái nhất định, thường gặp trong hợp đồng và quy định.",
  },
  {
    id: "ko-vocab-c1-014",
    level: "C1",
    deck: "vocab-c1",
    en: "to be oriented toward / aim for",
    zh: "以…为目标、志向于",
    vi: "hướng đến",
    ko: "지향하다",
    roman: "jihyanghada",
    exampleKo: "우리 회사는 지속 가능한 성장을 지향합니다.",
    exampleEn: "Our company is oriented toward sustainable growth.",
    exampleZh: "我们公司以可持续增长为目标。",
    exampleVi: "Công ty chúng tôi hướng đến sự tăng trưởng bền vững.",
    note: "지 (point, 指) + 향 (direction, 向) — describes a guiding direction or ideal, not a one-off action.",
    noteZh: "지（指向，指）+ 향（方向，向）——描述一种指引方向或理想，而非具体行动。",
    noteVi: "지 (chỉ) + 향 (hướng) — diễn tả một hướng đi hay lý tưởng dẫn dắt, không phải một hành động cụ thể.",
  },
  {
    id: "ko-vocab-c1-015",
    level: "C1",
    deck: "vocab-c1",
    en: "to hinder / impede",
    zh: "阻碍",
    vi: "cản trở",
    ko: "저해하다",
    roman: "jeohaehada",
    exampleKo: "지나친 규제는 오히려 혁신을 저해할 수 있습니다.",
    exampleEn: "Excessive regulation can actually hinder innovation.",
    exampleZh: "过度监管反而可能阻碍创新。",
    exampleVi: "Quy định quá mức có thể lại cản trở sự đổi mới.",
    note: "Pairs with abstract nouns like 성장, 발전, 혁신 (growth, development, innovation).",
    noteZh: "常与「성장」「발전」「혁신」（成长、发展、创新）等抽象名词搭配。",
    noteVi: "Thường đi cùng các danh từ trừu tượng như 성장, 발전, 혁신 (tăng trưởng, phát triển, đổi mới).",
  },
  {
    id: "ko-vocab-c1-016",
    level: "C1",
    deck: "vocab-c1",
    en: "to specify / state explicitly",
    zh: "明确规定、明示",
    vi: "quy định rõ, nêu rõ",
    ko: "명시하다",
    roman: "myeongsihada",
    exampleKo: "계약서에 환불 조건을 명확히 명시해야 합니다.",
    exampleEn: "The refund conditions must be clearly specified in the contract.",
    exampleZh: "必须在合同中明确写明退款条件。",
    exampleVi: "Phải nêu rõ điều kiện hoàn tiền trong hợp đồng.",
    note: "명 (clear, 明) + 시 (show, 示) — used for written, unambiguous statements in documents.",
    noteZh: "명（明，明）+ 시（示，示）——用于文件中清楚、明确的书面陈述。",
    noteVi: "명 (rõ ràng) + 시 (chỉ ra) — dùng cho các phát biểu rõ ràng, không mập mờ trong văn bản.",
  },
  {
    id: "ko-vocab-c1-017",
    level: "C1",
    deck: "vocab-c1",
    en: "to take into account",
    zh: "考虑到",
    vi: "xem xét đến, cân nhắc đến",
    ko: "감안하다",
    roman: "gamanhada",
    exampleKo: "물가 상승률을 감안하면 실질 임금은 줄었습니다.",
    exampleEn: "Taking inflation into account, real wages have actually decreased.",
    exampleZh: "考虑到物价上涨率，实际工资其实是下降的。",
    exampleVi: "Nếu xem xét đến tỷ lệ lạm phát, tiền lương thực tế đã giảm.",
    note: "Often opens a clause: ~을 감안하면 (taking ~ into account, ...).",
    noteZh: "常用于句首从句：「~을 감안하면」（考虑到……的话）。",
    noteVi: "Thường mở đầu một mệnh đề: \"~을 감안하면\" (nếu xét đến ~, thì...).",
  },
  {
    id: "ko-vocab-c1-018",
    level: "C1",
    deck: "vocab-c1",
    en: "to conform to / accord with",
    zh: "符合",
    vi: "phù hợp với",
    ko: "부합하다",
    roman: "buhaphada",
    exampleKo: "이 제안은 회사의 장기 전략에 부합합니다.",
    exampleEn: "This proposal is consistent with the company's long-term strategy.",
    exampleZh: "这项提案符合公司的长期战略。",
    exampleVi: "Đề xuất này phù hợp với chiến lược dài hạn của công ty.",
    note: "More formal than 맞다 (to fit/match) — common in reports and evaluations.",
    noteZh: "比 맞다（符合、吻合）更正式，常见于报告和评估中。",
    noteVi: "Trang trọng hơn 맞다 (khớp, phù hợp); thường gặp trong báo cáo và đánh giá.",
  },
  {
    id: "ko-vocab-c1-019",
    level: "C1",
    deck: "vocab-c1",
    en: "to be linked / tied to",
    zh: "与…联系在一起",
    vi: "gắn liền với",
    ko: "결부되다",
    roman: "gyeolbudoeda",
    exampleKo: "이 문제는 여러 이해관계와 복잡하게 결부되어 있습니다.",
    exampleEn: "This issue is intricately tied to various interests.",
    exampleZh: "这个问题与多方利益复杂地纠缠在一起。",
    exampleVi: "Vấn đề này gắn liền một cách phức tạp với nhiều mối lợi ích khác nhau.",
    note: "결 (tie, 結) + 부 (attach, 附) — two things becoming inseparably linked.",
    noteZh: "결（结，結）+ 부（附，附）——指两件事变得密不可分地联系在一起。",
    noteVi: "결 (buộc lại) + 부 (gắn vào) — hàm ý hai điều gì đó trở nên gắn kết không thể tách rời.",
  },
  {
    id: "ko-vocab-c1-020",
    level: "C1",
    deck: "vocab-c1",
    en: "to advocate / profess",
    zh: "标榜",
    vi: "tự nhận là, đề xướng",
    ko: "표방하다",
    roman: "pyobanghada",
    exampleKo: "그 단체는 정치적 중립을 표방하고 있습니다.",
    exampleEn: "That organization professes political neutrality.",
    exampleZh: "该团体标榜政治中立。",
    exampleVi: "Tổ chức đó tự nhận mình đứng trung lập về chính trị.",
    note: "Often carries a skeptical nuance — publicly claiming a stance that may or may not be genuine.",
    noteZh: "常带有一丝怀疑的语气——公开宣称某种立场，但未必名副其实。",
    noteVi: "Thường mang sắc thái hoài nghi — công khai tuyên bố một lập trường, nhưng chưa chắc đã thực chất.",
  },

  // ─── 형용사 (사전형) ───────────────────────────────────────────────────
  {
    id: "ko-vocab-c1-021",
    level: "C1",
    deck: "vocab-c1",
    en: "to be enormous / immense",
    zh: "巨大",
    vi: "to lớn, khổng lồ",
    ko: "막대하다",
    roman: "makdaehada",
    exampleKo: "이번 홍수로 막대한 피해가 발생했습니다.",
    exampleEn: "This flood caused enormous damage.",
    exampleZh: "这次洪水造成了巨大的损失。",
    exampleVi: "Trận lũ lụt lần này đã gây ra thiệt hại to lớn.",
    note: "Typically modifies 손실, 피해, 비용 (loss, damage, cost) — a scale that's hard to measure.",
    noteZh: "通常修饰「손실」「피해」「비용」（损失、损害、费用）——形容规模大到难以衡量。",
    noteVi: "Thường bổ nghĩa cho 손실, 피해, 비용 (tổn thất, thiệt hại, chi phí) — quy mô lớn đến mức khó đo đếm.",
  },
  {
    id: "ko-vocab-c1-022",
    level: "C1",
    deck: "vocab-c1",
    en: "to be extreme / severe",
    zh: "极其严重、剧烈",
    vi: "cực kỳ nghiêm trọng, gay gắt",
    ko: "극심하다",
    roman: "geuksimhada",
    exampleKo: "가뭄이 극심해서 농작물 피해가 큽니다.",
    exampleEn: "The drought is so severe that crop damage is significant.",
    exampleZh: "干旱极其严重，农作物损失很大。",
    exampleVi: "Hạn hán quá gay gắt nên thiệt hại cây trồng rất lớn.",
    note: "극 (extreme, 極) + 심 (severe, 甚) — a degree pushed to its limit, for pain, shortage, or conflict.",
    noteZh: "극（极，極）+ 심（甚，甚）——形容程度达到极限，可用于疼痛、短缺或冲突。",
    noteVi: "극 (cực điểm) + 심 (nghiêm trọng) — diễn tả mức độ bị đẩy đến giới hạn, dùng cho cơn đau, sự thiếu hụt hoặc xung đột.",
  },
  {
    id: "ko-vocab-c1-023",
    level: "C1",
    deck: "vocab-c1",
    en: "to be insufficient / inadequate",
    zh: "不足、欠缺",
    vi: "chưa đầy đủ, thiếu sót",
    ko: "미흡하다",
    roman: "miheuphada",
    exampleKo: "재난 대응이 여전히 미흡하다는 지적이 나옵니다.",
    exampleEn: "Critics point out that disaster response is still inadequate.",
    exampleZh: "有人指出灾难应对措施仍然不足。",
    exampleVi: "Có ý kiến chỉ ra rằng công tác ứng phó thảm họa vẫn còn thiếu sót.",
    note: "A measured, formal way to criticize something as 'not quite enough' without being harsh.",
    noteZh: "一种委婉、正式地批评「还不够」的说法，语气并不激烈。",
    noteVi: "Cách nói có chừng mực, trang trọng để phê bình điều gì đó \"chưa đủ\" mà không quá gay gắt.",
  },
  {
    id: "ko-vocab-c1-024",
    level: "C1",
    deck: "vocab-c1",
    en: "to be vast / extensive",
    zh: "庞大",
    vi: "đồ sộ, rộng lớn",
    ko: "방대하다",
    roman: "bangdaehada",
    exampleKo: "이 연구는 방대한 양의 자료를 분석했습니다.",
    exampleEn: "This study analyzed a vast amount of data.",
    exampleZh: "这项研究分析了庞大的数据量。",
    exampleVi: "Nghiên cứu này đã phân tích một khối lượng dữ liệu đồ sộ.",
    note: "Describes scale or volume (data, knowledge, scope), not the physical size of an object.",
    noteZh: "形容规模或数量之大（数据、知识、范围），而非物体本身的体积。",
    noteVi: "Diễn tả quy mô/khối lượng lớn (dữ liệu, kiến thức, phạm vi), không phải kích thước vật lý của một vật thể.",
  },
  {
    id: "ko-vocab-c1-025",
    level: "C1",
    deck: "vocab-c1",
    en: "to be smooth",
    zh: "顺畅",
    vi: "suôn sẻ",
    ko: "원활하다",
    roman: "wonhwalhada",
    exampleKo: "부서 간 소통이 원활해야 업무 효율이 오릅니다.",
    exampleEn: "Work efficiency rises only when communication between departments is smooth.",
    exampleZh: "只有部门之间的沟通顺畅，工作效率才会提高。",
    exampleVi: "Hiệu suất công việc chỉ tăng khi giao tiếp giữa các bộ phận diễn ra suôn sẻ.",
    note: "Common with 소통, 진행, 운영 (communication, progress, operation).",
    noteZh: "常与「소통」「진행」「운영」（沟通、进展、运营）搭配使用。",
    noteVi: "Thường đi kèm với 소통, 진행, 운영 (giao tiếp, tiến triển, vận hành).",
  },
  {
    id: "ko-vocab-c1-026",
    level: "C1",
    deck: "vocab-c1",
    en: "to be inevitable / unavoidable",
    zh: "不可避免",
    vi: "không thể tránh khỏi",
    ko: "불가피하다",
    roman: "bulgapihada",
    exampleKo: "수요 감소로 가격 인상이 불가피해 보입니다.",
    exampleEn: "With demand falling, a price hike seems unavoidable.",
    exampleZh: "由于需求下降，涨价似乎已不可避免。",
    exampleVi: "Do nhu cầu giảm, việc tăng giá dường như là không thể tránh khỏi.",
    note: "불 (not, 不) + 가피 (avoidable, 可避) — a formal negation, stronger than 어쩔 수 없다.",
    noteZh: "불（不，不）+ 가피（可避免，可避）——正式的否定表达，语气比「어쩔 수 없다」更强。",
    noteVi: "불 (không) + 가피 (có thể tránh) — cách phủ định trang trọng, ngữ khí mạnh hơn 어쩔 수 없다 (không còn cách nào khác).",
  },
  {
    id: "ko-vocab-c1-027",
    level: "C1",
    deck: "vocab-c1",
    en: "to be pressing / badly needed",
    zh: "迫切",
    vi: "cấp thiết, tha thiết",
    ko: "절실하다",
    roman: "jeolsilhada",
    exampleKo: "지금 이 지역에는 의료 지원이 절실합니다.",
    exampleEn: "Medical support is desperately needed in this region right now.",
    exampleZh: "目前该地区迫切需要医疗支援。",
    exampleVi: "Hiện tại khu vực này đang cấp thiết cần hỗ trợ y tế.",
    note: "Conveys both urgency and depth of feeling — used for pressing needs and heartfelt wishes alike.",
    noteZh: "兼具紧迫感与情感深度——既可用于需求，也可用于真切的心愿。",
    noteVi: "Vừa mang tính cấp bách, vừa thể hiện chiều sâu cảm xúc — dùng cho cả nhu cầu lẫn ước nguyện chân thành.",
  },
  {
    id: "ko-vocab-c1-028",
    level: "C1",
    deck: "vocab-c1",
    en: "to be acute / sharply opposed",
    zh: "尖锐",
    vi: "gay gắt, sắc bén",
    ko: "첨예하다",
    roman: "cheomyehada",
    exampleKo: "두 나라의 입장 차이가 첨예하게 대립하고 있습니다.",
    exampleEn: "The two countries' positions are sharply and acutely opposed.",
    exampleZh: "两国的立场差异呈现出尖锐的对立。",
    exampleVi: "Sự khác biệt lập trường giữa hai nước đang đối lập một cách gay gắt.",
    note: "첨 (sharp point, 尖) + 예 (sharp, 銳) — doubling 'sharpness' for high-stakes conflict.",
    noteZh: "첨（尖，尖）+ 예（锐，銳）——两个表「尖锐」的字组合，用于高风险的对立冲突。",
    noteVi: "첨 (nhọn) + 예 (sắc) — ghép hai chữ đều mang nghĩa \"sắc nhọn\", dùng cho xung đột căng thẳng cao độ.",
  },

  // ─── 부사 ──────────────────────────────────────────────────────────────
  {
    id: "ko-vocab-c1-029",
    level: "C1",
    deck: "vocab-c1",
    en: "as far as possible",
    zh: "尽可能",
    vi: "càng nhiều càng tốt, nếu có thể",
    ko: "가급적",
    roman: "gageupjeok",
    exampleKo: "가급적 빨리 답변을 드리겠습니다.",
    exampleEn: "I will get back to you as soon as possible.",
    exampleZh: "我会尽可能尽快给您答复。",
    exampleVi: "Tôi sẽ trả lời quý vị nhanh nhất có thể.",
    note: "A softer, more formal alternative to 최대한 — common in polite business requests.",
    noteZh: "比「최대한」（最大限度）更柔和、更正式，常见于礼貌的商务请求中。",
    noteVi: "Một cách nói nhẹ nhàng, trang trọng hơn so với 최대한 (tối đa) — thường dùng trong các yêu cầu công việc lịch sự.",
  },
  {
    id: "ko-vocab-c1-030",
    level: "C1",
    deck: "vocab-c1",
    en: "for instance / so to speak",
    zh: "比如说",
    vi: "chẳng hạn như",
    ko: "이를테면",
    roman: "ireultemyeon",
    exampleKo: "이를테면 재택근무 같은 유연한 제도가 필요합니다.",
    exampleEn: "We need flexible systems, such as remote work, for instance.",
    exampleZh: "比如说，我们需要居家办公这样灵活的制度。",
    exampleVi: "Chẳng hạn như, chúng ta cần những chế độ linh hoạt như làm việc từ xa.",
    note: "A literary connective introducing an example — more formal than 예를 들면.",
    noteZh: "用于引出例子的书面连接词，比「예를 들면」更正式。",
    noteVi: "Từ nối mang tính văn chương dùng để đưa ra ví dụ; trang trọng hơn 예를 들면.",
  },
];
