/**
 * B2 (중상급) 한국어 학습 단어(어휘) 카드 — vocab-a1 파일럿 확대.
 * data-ko/b2.ts 등 회화 표현 덱과 별개로, 개별 단어만 다루는 단어장 덱이다.
 *
 * 각 카드: 한국어 단어(ko, 사전형) + 로마자(roman) + 영어/중국어/베트남어 뜻(en/zh/vi)
 * + 예문(4개 언어). 동사/형용사는 사전형(-다)으로 표제하고, 예문에서는 자연스러운
 * 활용형을 쓴다.
 *
 * 로마자는 국립국어원 로마자 표기법(Revised Romanization) 기준.
 * 표제어(ko)는 data-ko/index.ts 의 중복 제거 대상이라, 기존 b2.ts 회화 표현
 * 표제어와 겹치지 않게 선정했다 (시사·직장 명사, 논리 연결어, 뉘앙스 형용사,
 * 관련 동사 중심 — TOPIK 4급 수준 참고, 뜻·예문은 자체 작성).
 */
import type { VocabCard, Deck } from "@/types/card";

export const KO_VOCAB_B2_DECKS: Deck[] = [
  {
    id: "vocab-b2",
    level: "B2",
    title: {
      ko: "중상급 단어",
      en: "Upper-Intermediate Words",
      zh: "中高级单词",
      vi: "Từ vựng trung cao cấp",
    },
    description: {
      ko: "시사·직장 명사, 논리 연결어, 뉘앙스 형용사",
      en: "Current-affairs and workplace nouns, logical connectors, and nuanced adjectives",
      zh: "时事、职场名词，逻辑连接词，细腻形容词",
      vi: "Danh từ thời sự, công sở, từ nối logic và tính từ giàu sắc thái",
    },
    order: 6,
    icon: "BookText",
  },
];

export const KO_VOCAB_B2_CARDS: VocabCard[] = [
  // ─── 시사·사회 명사 ────────────────────────────────────────────────────
  {
    id: "ko-vocab-b2-001",
    level: "B2",
    deck: "vocab-b2",
    en: "competition",
    zh: "竞争",
    vi: "cạnh tranh",
    ko: "경쟁",
    roman: "gyeongjaeng",
    exampleKo: "이 시장은 경쟁이 아주 치열해요.",
    exampleEn: "Competition in this market is very fierce.",
    exampleZh: "这个市场的竞争非常激烈。",
    exampleVi: "Sự cạnh tranh trong thị trường này rất khốc liệt.",
  },
  {
    id: "ko-vocab-b2-002",
    level: "B2",
    deck: "vocab-b2",
    en: "conflict",
    zh: "矛盾／冲突",
    vi: "xung đột / mâu thuẫn",
    ko: "갈등",
    roman: "galdeung",
    exampleKo: "두 팀 사이에 갈등이 생겼어요.",
    exampleEn: "A conflict arose between the two teams.",
    exampleZh: "两个团队之间产生了矛盾。",
    exampleVi: "Đã nảy sinh mâu thuẫn giữa hai đội.",
    note: "갈등이 생기다 = 'a conflict arises.' Also 갈등을 겪다 = to go through conflict.",
    noteZh: "갈등이 생기다 = \"产生矛盾\"。也可用 갈등을 겪다 表示\"经历矛盾\"。",
    noteVi: "갈등이 생기다 = \"nảy sinh mâu thuẫn\". Cũng có thể dùng 갈등을 겪다 nghĩa là \"trải qua xung đột\".",
  },
  {
    id: "ko-vocab-b2-003",
    level: "B2",
    deck: "vocab-b2",
    en: "negotiation",
    zh: "谈判",
    vi: "đàm phán",
    ko: "협상",
    roman: "hyeopsang",
    exampleKo: "양측이 다시 협상을 시작했어요.",
    exampleEn: "Both sides started negotiating again.",
    exampleZh: "双方重新开始了谈判。",
    exampleVi: "Hai bên đã bắt đầu đàm phán lại.",
  },
  {
    id: "ko-vocab-b2-004",
    level: "B2",
    deck: "vocab-b2",
    en: "standard / criterion",
    zh: "标准",
    vi: "tiêu chuẩn",
    ko: "기준",
    roman: "gijun",
    exampleKo: "평가 기준이 너무 애매해요.",
    exampleEn: "The evaluation criteria are too vague.",
    exampleZh: "评价标准太模糊了。",
    exampleVi: "Tiêu chuẩn đánh giá quá mơ hồ.",
    note: "기준을 세우다 = to set a standard; ...을 기준으로 = 'based on...'",
    noteZh: "기준을 세우다 = \"制定标准\"；……을 기준으로 = \"以……为标准\"。",
    noteVi: "기준을 세우다 = \"đặt ra tiêu chuẩn\"; ...을 기준으로 = \"dựa trên tiêu chuẩn...\"",
  },
  {
    id: "ko-vocab-b2-005",
    level: "B2",
    deck: "vocab-b2",
    en: "statistics",
    zh: "统计",
    vi: "thống kê",
    ko: "통계",
    roman: "tonggye",
    exampleKo: "새로운 통계 자료가 발표됐어요.",
    exampleEn: "New statistical data was released.",
    exampleZh: "新的统计数据发布了。",
    exampleVi: "Số liệu thống kê mới đã được công bố.",
  },
  {
    id: "ko-vocab-b2-006",
    level: "B2",
    deck: "vocab-b2",
    en: "rate / proportion",
    zh: "比例",
    vi: "tỷ lệ",
    ko: "비율",
    roman: "biyul",
    exampleKo: "여성 지원자의 비율이 늘었어요.",
    exampleEn: "The proportion of female applicants has increased.",
    exampleZh: "女性应聘者的比例增加了。",
    exampleVi: "Tỷ lệ ứng viên nữ đã tăng lên.",
  },
  {
    id: "ko-vocab-b2-007",
    level: "B2",
    deck: "vocab-b2",
    en: "countermeasure / solution",
    zh: "对策",
    vi: "biện pháp đối phó",
    ko: "대책",
    roman: "daechaek",
    exampleKo: "정부가 새로운 대책을 마련했어요.",
    exampleEn: "The government came up with a new countermeasure.",
    exampleZh: "政府制定了新的对策。",
    exampleVi: "Chính phủ đã đưa ra biện pháp đối phó mới.",
    note: "대책을 마련하다/세우다 = 'to come up with a countermeasure.' Common in news.",
    noteZh: "대책을 마련하다/세우다 = \"制定对策\"，新闻中常见。",
    noteVi: "대책을 마련하다/세우다 = \"đưa ra biện pháp đối phó\". Thường dùng trong tin tức.",
  },
  {
    id: "ko-vocab-b2-008",
    level: "B2",
    deck: "vocab-b2",
    en: "phenomenon",
    zh: "现象",
    vi: "hiện tượng",
    ko: "현상",
    roman: "hyeonsang",
    exampleKo: "이런 현상은 도시에서 흔히 볼 수 있어요.",
    exampleEn: "This phenomenon is commonly seen in cities.",
    exampleZh: "这种现象在城市里很常见。",
    exampleVi: "Hiện tượng này thường thấy ở thành phố.",
  },

  // ─── 직장 명사 ─────────────────────────────────────────────────────────
  {
    id: "ko-vocab-b2-009",
    level: "B2",
    deck: "vocab-b2",
    en: "(work) duties / tasks",
    zh: "业务／工作",
    vi: "công việc / nghiệp vụ",
    ko: "업무",
    roman: "eommu",
    exampleKo: "오늘은 업무가 너무 많아요.",
    exampleEn: "I have way too much work today.",
    exampleZh: "今天的工作太多了。",
    exampleVi: "Hôm nay công việc nhiều quá.",
    note: "More formal/office-specific than 일. 업무를 처리하다 = to handle tasks.",
    noteZh: "比 일 更正式、更偏向公司事务的说法。업무를 처리하다 = 处理业务。",
    noteVi: "Trang trọng hơn và mang tính công sở hơn so với 일. 업무를 처리하다 = xử lý công việc.",
  },
  {
    id: "ko-vocab-b2-010",
    level: "B2",
    deck: "vocab-b2",
    en: "promotion (at work)",
    zh: "升职",
    vi: "thăng chức",
    ko: "승진",
    roman: "seungjin",
    exampleKo: "드디어 이번에 승진했어요.",
    exampleEn: "I finally got promoted this time.",
    exampleZh: "这次终于升职了。",
    exampleVi: "Cuối cùng lần này tôi đã được thăng chức.",
    note: "승진하다 = to get promoted; 승진 시험 = promotion exam.",
    noteZh: "승진하다 = 升职（动词形式）；승진 시험 = 晋升考试。",
    noteVi: "승진하다 = được thăng chức (dạng động từ); 승진 시험 = kỳ thi thăng chức.",
  },
  {
    id: "ko-vocab-b2-011",
    level: "B2",
    deck: "vocab-b2",
    en: "achievement / results",
    zh: "成果／业绩",
    vi: "thành quả / kết quả công việc",
    ko: "성과",
    roman: "seonggwa",
    exampleKo: "이번 프로젝트에서 좋은 성과를 냈어요.",
    exampleEn: "We produced good results in this project.",
    exampleZh: "这次项目取得了很好的成果。",
    exampleVi: "Chúng tôi đã đạt được thành quả tốt trong dự án lần này.",
    note: "성과를 내다/거두다 = 'to produce/achieve results.' Very common in work reviews.",
    noteZh: "성과를 내다/거두다 = \"取得成果\"，在工作评价中很常见。",
    noteVi: "성과를 내다/거두다 = \"đạt được thành quả\". Rất thường dùng khi đánh giá công việc.",
  },
  {
    id: "ko-vocab-b2-012",
    level: "B2",
    deck: "vocab-b2",
    en: "ability / competence",
    zh: "能力",
    vi: "năng lực",
    ko: "능력",
    roman: "neungnyeok",
    exampleKo: "그분은 업무 능력이 뛰어나요.",
    exampleEn: "That person's work ability is outstanding.",
    exampleZh: "那位的工作能力很出众。",
    exampleVi: "Người đó có năng lực làm việc xuất sắc.",
  },
  {
    id: "ko-vocab-b2-013",
    level: "B2",
    deck: "vocab-b2",
    en: "organization",
    zh: "组织",
    vi: "tổ chức",
    ko: "조직",
    roman: "jojik",
    exampleKo: "우리 조직은 소통을 중요하게 생각해요.",
    exampleEn: "Our organization values communication highly.",
    exampleZh: "我们组织很重视沟通。",
    exampleVi: "Tổ chức của chúng tôi coi trọng việc giao tiếp.",
  },
  {
    id: "ko-vocab-b2-014",
    level: "B2",
    deck: "vocab-b2",
    en: "contract",
    zh: "合同",
    vi: "hợp đồng",
    ko: "계약",
    roman: "gyeyak",
    exampleKo: "이번 달에 새 계약을 맺었어요.",
    exampleEn: "We signed a new contract this month.",
    exampleZh: "这个月签了新合同。",
    exampleVi: "Tháng này chúng tôi đã ký hợp đồng mới.",
    note: "계약을 맺다/체결하다 = to sign a contract.",
    noteZh: "계약을 맺다/체결하다 = 签订合同。",
    noteVi: "계약을 맺다/체결하다 = ký kết hợp đồng.",
  },

  // ─── 논리 연결어 ───────────────────────────────────────────────────────
  {
    id: "ko-vocab-b2-015",
    level: "B2",
    deck: "vocab-b2",
    en: "therefore / thus",
    zh: "因此",
    vi: "do đó / vì vậy",
    ko: "따라서",
    roman: "ttaraseo",
    exampleKo: "비가 많이 왔어요. 따라서 행사가 취소됐어요.",
    exampleEn: "It rained a lot. Therefore, the event was canceled.",
    exampleZh: "下了很大的雨。因此活动被取消了。",
    exampleVi: "Trời đã mưa rất to. Do đó sự kiện đã bị hủy.",
    note: "Formal connector linking a cause to its logical result. Common in writing/reports.",
    noteZh: "连接原因和结果的正式连接词，常用于书面/报告。",
    noteVi: "Từ nối trang trọng liên kết nguyên nhân với kết quả logic. Thường dùng trong văn viết/báo cáo.",
  },
  {
    id: "ko-vocab-b2-016",
    level: "B2",
    deck: "vocab-b2",
    en: "moreover / on top of that",
    zh: "而且／再加上",
    vi: "hơn nữa / thêm vào đó",
    ko: "게다가",
    roman: "gedaga",
    exampleKo: "길이 막혔어요. 게다가 비까지 왔어요.",
    exampleEn: "Traffic was jammed. On top of that, it even rained.",
    exampleZh: "堵车了，而且还下了雨。",
    exampleVi: "Đường bị kẹt. Hơn nữa trời còn mưa nữa.",
    note: "Adds an extra, often worse, fact to what was just said.",
    noteZh: "在刚才所说的内容上再补充一个（通常更糟的）事实。",
    noteVi: "Bổ sung thêm một sự việc (thường là tệ hơn) vào điều vừa nói.",
  },
  {
    id: "ko-vocab-b2-017",
    level: "B2",
    deck: "vocab-b2",
    en: "namely / that is",
    zh: "即／也就是说",
    vi: "tức là",
    ko: "즉",
    roman: "jeuk",
    exampleKo: "그 회의, 즉 내일 열리는 회의는 취소됐어요.",
    exampleEn: "That meeting -- namely, the one tomorrow -- was canceled.",
    exampleZh: "那个会议，即明天举行的会议，已经取消了。",
    exampleVi: "Cuộc họp đó, tức là cuộc họp diễn ra vào ngày mai, đã bị hủy.",
    note: "Restates or clarifies what was just mentioned. More formal than 다시 말해서.",
    noteZh: "用于重新表述或说明刚才提到的内容，比 다시 말해서 更正式。",
    noteVi: "Dùng để diễn đạt lại hoặc làm rõ điều vừa nhắc đến. Trang trọng hơn 다시 말해서.",
  },
  {
    id: "ko-vocab-b2-018",
    level: "B2",
    deck: "vocab-b2",
    en: "in the end / eventually",
    zh: "最终／结果",
    vi: "cuối cùng / rốt cuộc",
    ko: "결국",
    roman: "gyeolguk",
    exampleKo: "결국 우리 팀이 우승했어요.",
    exampleEn: "In the end, our team won the championship.",
    exampleZh: "最终我们队获得了冠军。",
    exampleVi: "Cuối cùng đội chúng tôi đã vô địch.",
  },
  {
    id: "ko-vocab-b2-019",
    level: "B2",
    deck: "vocab-b2",
    en: "anyway / in any case",
    zh: "总之／无论如何",
    vi: "dù sao thì / dù thế nào đi nữa",
    ko: "어쨌든",
    roman: "eojjaetdeun",
    exampleKo: "어쨌든 오늘까지는 끝내야 해요.",
    exampleEn: "Anyway, we have to finish it by today.",
    exampleZh: "总之今天之内必须完成。",
    exampleVi: "Dù sao thì cũng phải hoàn thành trước hôm nay.",
    note: "Wraps up a topic regardless of details already discussed. Very common in speech.",
    noteZh: "无论之前讨论了什么细节，用来总结话题，口语中很常用。",
    noteVi: "Dùng để kết lại chủ đề bất kể các chi tiết đã bàn trước đó. Rất thường dùng trong khẩu ngữ.",
  },
  {
    id: "ko-vocab-b2-020",
    level: "B2",
    deck: "vocab-b2",
    en: "above all / most importantly",
    zh: "首先／最重要的是",
    vi: "trên hết / quan trọng nhất là",
    ko: "무엇보다",
    roman: "mueotboda",
    exampleKo: "무엇보다 건강이 제일 중요해요.",
    exampleEn: "Above all, health is the most important thing.",
    exampleZh: "首先，健康是最重要的。",
    exampleVi: "Trên hết, sức khỏe là quan trọng nhất.",
    note: "Literally 'more than anything' -- used to flag your top priority.",
    noteZh: "字面意思是\"比任何事物都……\"，用来强调你最优先的事项。",
    noteVi: "Nghĩa đen là \"hơn bất cứ điều gì\" -- dùng để nhấn mạnh ưu tiên hàng đầu.",
  },

  // ─── 뉘앙스 형용사 ─────────────────────────────────────────────────────
  {
    id: "ko-vocab-b2-021",
    level: "B2",
    deck: "vocab-b2",
    en: "to be ambiguous / unclear",
    zh: "模糊不清",
    vi: "mơ hồ / không rõ ràng",
    ko: "애매하다",
    roman: "aemaehada",
    exampleKo: "설명이 좀 애매해서 이해가 안 돼요.",
    exampleEn: "The explanation is a bit ambiguous, so I don't understand it.",
    exampleZh: "说明有点模糊，所以听不懂。",
    exampleVi: "Giải thích hơi mơ hồ nên tôi không hiểu.",
  },
  {
    id: "ko-vocab-b2-022",
    level: "B2",
    deck: "vocab-b2",
    en: "to be clear / distinct",
    zh: "清晰／明确",
    vi: "rõ ràng / rõ rệt",
    ko: "뚜렷하다",
    roman: "tturyeotada",
    exampleKo: "올해는 사계절이 뚜렷했어요.",
    exampleEn: "This year the four seasons were distinct.",
    exampleZh: "今年四季分明。",
    exampleVi: "Năm nay bốn mùa rõ rệt.",
    note: "Opposite of 애매하다 -- describes something sharply defined, not vague.",
    noteZh: "与 애매하다 相反，形容界限分明、不含糊的事物。",
    noteVi: "Trái nghĩa với 애매하다 -- mô tả điều gì đó rõ ràng, không mơ hồ.",
  },
  {
    id: "ko-vocab-b2-023",
    level: "B2",
    deck: "vocab-b2",
    en: "to be fierce / intense",
    zh: "激烈",
    vi: "khốc liệt / gay gắt",
    ko: "치열하다",
    roman: "chiyeolhada",
    exampleKo: "요즘 취업 경쟁이 정말 치열해요.",
    exampleEn: "The competition for jobs these days is really fierce.",
    exampleZh: "最近求职竞争真的很激烈。",
    exampleVi: "Dạo này cạnh tranh xin việc thực sự rất khốc liệt.",
  },
  {
    id: "ko-vocab-b2-024",
    level: "B2",
    deck: "vocab-b2",
    en: "to be prudent / cautious",
    zh: "慎重／谨慎",
    vi: "thận trọng / cẩn trọng",
    ko: "신중하다",
    roman: "sinjunghada",
    exampleKo: "중요한 결정이니까 신중하게 생각해 보세요.",
    exampleEn: "It's an important decision, so please think it over carefully.",
    exampleZh: "这是重要的决定，请慎重考虑。",
    exampleVi: "Đây là quyết định quan trọng nên hãy suy nghĩ thật thận trọng.",
    note: "Praises careful, unhurried judgment -- opposite of 무모하다 (reckless).",
    noteZh: "形容深思熟虑、不草率的判断，与 무모하다（鲁莽）相反。",
    noteVi: "Khen ngợi sự phán đoán cẩn thận, không vội vàng -- trái nghĩa với 무모하다 (liều lĩnh).",
  },
  {
    id: "ko-vocab-b2-025",
    level: "B2",
    deck: "vocab-b2",
    en: "to be picky / fussy",
    zh: "挑剔／苛刻",
    vi: "khó tính / khắt khe",
    ko: "까다롭다",
    roman: "kkadaropda",
    exampleKo: "그 고객은 조건이 정말 까다로워요.",
    exampleEn: "That client's conditions are really picky.",
    exampleZh: "那位客户的条件真的很苛刻。",
    exampleVi: "Điều kiện của khách hàng đó thực sự rất khắt khe.",
    note: "Can describe a fussy person OR a complicated procedure/requirement.",
    noteZh: "既可形容挑剔的人，也可形容复杂繁琐的程序／要求。",
    noteVi: "Có thể mô tả một người khó tính HOẶC một thủ tục/yêu cầu phức tạp.",
  },
  {
    id: "ko-vocab-b2-026",
    level: "B2",
    deck: "vocab-b2",
    en: "to be burdensome / to feel pressured",
    zh: "有负担／有压力",
    vi: "cảm thấy gánh nặng / áp lực",
    ko: "부담스럽다",
    roman: "budamseureopda",
    exampleKo: "그 가격은 저한테 좀 부담스러워요.",
    exampleEn: "That price feels like a bit of a burden to me.",
    exampleZh: "那个价格对我来说有点负担。",
    exampleVi: "Mức giá đó khiến tôi cảm thấy hơi áp lực.",
    note: "부담 = burden/pressure (noun); 부담스럽다 = the adjective, 'to feel burdened by.'",
    noteZh: "부담 = 负担／压力（名词）；부담스럽다 = 形容词，表示\"感到有负担\"。",
    noteVi: "부담 = gánh nặng/áp lực (danh từ); 부담스럽다 = tính từ, nghĩa là \"cảm thấy bị gánh nặng\".",
  },

  // ─── 동사 ──────────────────────────────────────────────────────────────
  {
    id: "ko-vocab-b2-027",
    level: "B2",
    deck: "vocab-b2",
    en: "to rebut / refute",
    zh: "反驳",
    vi: "phản bác / bác bỏ",
    ko: "반박하다",
    roman: "banbakada",
    exampleKo: "그는 상대방의 의견을 조목조목 반박했어요.",
    exampleEn: "He refuted the other person's opinion point by point.",
    exampleZh: "他逐条反驳了对方的意见。",
    exampleVi: "Anh ấy đã phản bác từng điểm một ý kiến của đối phương.",
    note: "반박 (noun) = a rebuttal; 반박하다 = to make that rebuttal, often in a debate.",
    noteZh: "반박（名词）= 反驳（论点）；반박하다 = 提出反驳，常用于辩论。",
    noteVi: "반박 (danh từ) = lời phản bác; 반박하다 = đưa ra lời phản bác đó, thường dùng khi tranh luận.",
  },
  {
    id: "ko-vocab-b2-028",
    level: "B2",
    deck: "vocab-b2",
    en: "to emphasize",
    zh: "强调",
    vi: "nhấn mạnh",
    ko: "강조하다",
    roman: "gangjohada",
    exampleKo: "선생님은 예습의 중요성을 강조하셨어요.",
    exampleEn: "The teacher emphasized the importance of preparation.",
    exampleZh: "老师强调了预习的重要性。",
    exampleVi: "Giáo viên đã nhấn mạnh tầm quan trọng của việc chuẩn bị bài trước.",
  },
  {
    id: "ko-vocab-b2-029",
    level: "B2",
    deck: "vocab-b2",
    en: "to review / examine",
    zh: "审查／审核",
    vi: "xem xét / rà soát",
    ko: "검토하다",
    roman: "geomtohada",
    exampleKo: "제안서를 꼼꼼히 검토했어요.",
    exampleEn: "I reviewed the proposal thoroughly.",
    exampleZh: "仔细审核了提案。",
    exampleVi: "Tôi đã rà soát kỹ lưỡng bản đề xuất.",
    note: "검토 = careful review before a decision; common in 검토 중이에요 (it's under review).",
    noteZh: "검토 = 做决定前的仔细审查；常用于 검토 중이에요（正在审核中）。",
    noteVi: "검토 = việc xem xét kỹ trước khi quyết định; thường dùng trong 검토 중이에요 (đang được xem xét).",
  },
  {
    id: "ko-vocab-b2-030",
    level: "B2",
    deck: "vocab-b2",
    en: "to overcome",
    zh: "克服",
    vi: "vượt qua / khắc phục",
    ko: "극복하다",
    roman: "geukbokada",
    exampleKo: "많은 어려움을 극복하고 여기까지 왔어요.",
    exampleEn: "I overcame many difficulties to get here.",
    exampleZh: "克服了很多困难才走到这一步。",
    exampleVi: "Tôi đã vượt qua nhiều khó khăn để đến được đây.",
  },
];
