/**
 * A1 한국어 대화 응답 카드.
 * template/blanks 는 학습 언어(한국어)로 작성, en 은 뜻, note 는 영어 설명.
 */
import type { Dialogue } from "@/types/dialogue";

export const KO_DLG_A1: Dialogue[] = [
  {
    id: "ko-dlg-a1-greetings-001",
    level: "A1",
    situation: "greetings",
    context: { ko: "처음 만난 사람과 인사", en: "Greeting someone you just met", zh: "初次见面时打招呼", vi: "Chào hỏi người mới gặp lần đầu" },
    prompt: { ko: "안녕하세요! 만나서 반갑습니다.", en: "Hello! Nice to meet you.", zh: "你好！很高兴认识你。", vi: "Xin chào! Rất vui được gặp bạn." },
    template: "안녕하세요, 저도 {0}.",
    blanks: [
      [
        {
          ko: "반갑습니다",
          en: "glad to meet you (polite)",
          zh: "很高兴认识你",
          vi: "rất vui được gặp (lịch sự)",
          note: "Standard polite register.",
          noteZh: "标准礼貌语体。",
          noteVi: "Cách nói lịch sự tiêu chuẩn.",
        },
        {
          ko: "반가워요",
          en: "glad to meet you (softer)",
          zh: "很高兴认识你（更柔和）",
          vi: "rất vui được gặp (nhẹ nhàng hơn)",
          note: "A little softer, still polite.",
          noteZh: "语气更柔和，但仍然礼貌。",
          noteVi: "Nhẹ nhàng hơn một chút, nhưng vẫn lịch sự.",
        },
      ],
    ],
    example: {
      ko: "안녕하세요, 저도 반갑습니다.",
      en: "Hello, I'm glad to meet you too.",
      zh: "你好，我也很高兴认识你。",
      vi: "Xin chào, tôi cũng rất vui được gặp bạn.",
    },
    alternatives: [
      {
        ko: "처음 뵙겠습니다.",
        en: "How do you do? (first meeting)",
        zh: "初次见面，请多关照。",
        vi: "Rất hân hạnh được gặp bạn lần đầu.",
        note: "Very formal first-meeting greeting.",
        noteZh: "非常正式的初次见面问候语。",
        noteVi: "Lời chào rất trang trọng khi gặp mặt lần đầu.",
      },
      {
        ko: "말씀 많이 들었어요.",
        en: "I've heard a lot about you.",
        zh: "久仰大名。",
        vi: "Tôi đã nghe nói nhiều về bạn.",
        note: "Friendly, when you already know of them.",
        noteZh: "当你已经听说过对方时，用来表示友好。",
        noteVi: "Thân thiện, dùng khi bạn đã biết về người đó từ trước.",
      },
    ],
  },
  {
    id: "ko-dlg-a1-greetings-002",
    level: "A1",
    situation: "greetings",
    context: { ko: "도움을 받았을 때", en: "When someone helps you", zh: "得到帮助时", vi: "Khi được ai đó giúp đỡ" },
    prompt: { ko: "여기 있습니다. 도와드릴게요.", en: "Here you go. Let me help you.", zh: "给您。我来帮您。", vi: "Đây ạ. Để tôi giúp bạn." },
    template: "{0}, 정말 {1}.",
    blanks: [
      [
        {
          ko: "감사합니다",
          en: "thank you (formal)",
          zh: "谢谢（正式）",
          vi: "cảm ơn (trang trọng)",
          note: "Formal, safe everywhere.",
          noteZh: "正式用语，任何场合都适用。",
          noteVi: "Trang trọng, dùng an toàn ở mọi nơi.",
        },
        {
          ko: "고맙습니다",
          en: "thank you (warm)",
          zh: "谢谢（亲切）",
          vi: "cảm ơn (ấm áp)",
          note: "Warm and natural.",
          noteZh: "亲切自然。",
          noteVi: "Ấm áp và tự nhiên.",
        },
      ],
      [
        {
          ko: "감사해요",
          en: "I appreciate it",
          zh: "我很感激",
          vi: "tôi rất cảm kích",
          note: "Polite, conversational.",
          noteZh: "礼貌，口语化。",
          noteVi: "Lịch sự, mang tính hội thoại.",
        },
        { ko: "고마워요", en: "thanks", zh: "谢谢", vi: "cảm ơn nhé", note: "Casual-polite.", noteZh: "随和又礼貌。", noteVi: "Thân mật nhưng lịch sự." },
      ],
    ],
    example: {
      ko: "감사합니다, 정말 감사해요.",
      en: "Thank you, I really appreciate it.",
      zh: "谢谢，真的很感激。",
      vi: "Cảm ơn, tôi thật sự rất cảm kích.",
    },
    alternatives: [
      {
        ko: "덕분이에요.",
        en: "It's thanks to you.",
        zh: "多亏了您。",
        vi: "Nhờ có bạn cả đấy.",
        note: "Gives the other person credit.",
        noteZh: "把功劳归于对方。",
        noteVi: "Ghi nhận công lao của đối phương.",
      },
    ],
  },
  {
    id: "ko-dlg-a1-self-intro-001",
    level: "A1",
    situation: "self-intro",
    context: { ko: "이름을 물어볼 때", en: "When someone asks your name", zh: "被问到姓名时", vi: "Khi ai đó hỏi tên bạn" },
    prompt: { ko: "안녕하세요, 이름이 뭐예요?", en: "Hello, what's your name?", zh: "你好，你叫什么名字？", vi: "Xin chào, bạn tên là gì?" },
    template: "안녕하세요, 저는 {0}.",
    blanks: [
      [
        {
          ko: "사라예요",
          en: "Sarah (after a vowel)",
          zh: "是莎拉（元音结尾）",
          vi: "là Sarah (sau nguyên âm)",
          note: "Use 예요 when the name ends in a vowel.",
          noteZh: "名字以元音结尾时用예요。",
          noteVi: "Dùng 예요 khi tên kết thúc bằng nguyên âm.",
        },
        {
          ko: "민준이에요",
          en: "Minjun (after a consonant)",
          zh: "是民俊（辅音结尾）",
          vi: "là Minjun (sau phụ âm)",
          note: "Use 이에요 when the name ends in a consonant.",
          noteZh: "名字以辅音结尾时用이에요。",
          noteVi: "Dùng 이에요 khi tên kết thúc bằng phụ âm.",
        },
      ],
    ],
    example: {
      ko: "안녕하세요, 저는 사라예요.",
      en: "Hello, I'm Sarah.",
      zh: "你好，我是莎拉。",
      vi: "Xin chào, tôi là Sarah.",
    },
    alternatives: [
      {
        ko: "제 이름은 사라예요.",
        en: "My name is Sarah.",
        zh: "我的名字是莎拉。",
        vi: "Tên tôi là Sarah.",
        note: "More explicit, names yourself directly.",
        noteZh: "更明确，直接说出自己的名字。",
        noteVi: "Rõ ràng hơn, nói thẳng tên của mình.",
      },
      {
        ko: "사라라고 해요.",
        en: "I'm called Sarah.",
        zh: "我叫莎拉。",
        vi: "Tôi tên là Sarah.",
        note: "Slightly more formal self-introduction.",
        noteZh: "稍微更正式的自我介绍方式。",
        noteVi: "Cách tự giới thiệu trang trọng hơn một chút.",
      },
    ],
  },
  {
    id: "ko-dlg-a1-numbers-001",
    level: "A1",
    situation: "numbers",
    context: { ko: "가게에서 가격을 물어볼 때", en: "Asking a price at a shop", zh: "在商店询问价格时", vi: "Khi hỏi giá ở cửa hàng" },
    prompt: { ko: "어서 오세요! 뭐 드릴까요?", en: "Welcome! What can I get you?", zh: "欢迎光临！您需要点什么？", vi: "Xin chào quý khách! Quý khách cần gì ạ?" },
    template: "이거 {0} 주세요. 얼마예요?",
    blanks: [
      [
        {
          ko: "한 개",
          en: "one (item)",
          zh: "一个",
          vi: "một cái",
          note: "하나 becomes 한 before the counter 개.",
          noteZh: "하나在量词개前变成한。",
          noteVi: "하나 biến thành 한 khi đứng trước lượng từ 개.",
        },
        {
          ko: "두 개",
          en: "two (items)",
          zh: "两个",
          vi: "hai cái",
          note: "둘 becomes 두 before the counter 개.",
          noteZh: "둘在量词개前变成두。",
          noteVi: "둘 biến thành 두 khi đứng trước lượng từ 개.",
        },
        {
          ko: "세 개",
          en: "three (items)",
          zh: "三个",
          vi: "ba cái",
          note: "셋 becomes 세 before the counter 개.",
          noteZh: "셋在量词개前变成세。",
          noteVi: "셋 biến thành 세 khi đứng trước lượng từ 개.",
        },
      ],
    ],
    example: {
      ko: "이거 한 개 주세요. 얼마예요?",
      en: "I'll have one of these. How much is it?",
      zh: "请给我一个这个。多少钱？",
      vi: "Cho tôi một cái này. Bao nhiêu tiền ạ?",
    },
    alternatives: [
      {
        ko: "모두 얼마예요?",
        en: "How much is it all together?",
        zh: "一共多少钱？",
        vi: "Tất cả bao nhiêu tiền?",
        note: "Asks for the total.",
        noteZh: "询问总金额。",
        noteVi: "Hỏi tổng số tiền.",
      },
      {
        ko: "카드 돼요?",
        en: "Can I pay by card?",
        zh: "可以刷卡吗？",
        vi: "Có thể trả bằng thẻ không?",
        note: "Handy when paying.",
        noteZh: "付款时很实用的说法。",
        noteVi: "Hữu ích khi thanh toán.",
      },
    ],
  },
  {
    id: "ko-dlg-a1-food-001",
    level: "A1",
    situation: "food",
    context: { ko: "식당에서 주문할 때", en: "Ordering at a restaurant", zh: "在餐厅点餐时", vi: "Khi gọi món ở nhà hàng" },
    prompt: { ko: "주문하시겠어요?", en: "Are you ready to order?", zh: "您要点餐了吗？", vi: "Quý khách muốn gọi món chưa ạ?" },
    template: "네, {0} 주세요.",
    blanks: [
      [
        {
          ko: "비빔밥",
          en: "bibimbap",
          zh: "拌饭",
          vi: "cơm trộn bibimbap",
          note: "A popular rice dish — a safe first order.",
          noteZh: "很受欢迎的拌饭料理，第一次点餐的稳妥之选。",
          noteVi: "Món cơm nổi tiếng — lựa chọn an toàn cho lần gọi món đầu tiên.",
        },
        {
          ko: "불고기",
          en: "bulgogi (marinated beef)",
          zh: "烤牛肉（韩式烤肉）",
          vi: "thịt bò nướng bulgogi",
          note: "Sweet grilled beef, usually not spicy.",
          noteZh: "略带甜味的烤牛肉，通常不辣。",
          noteVi: "Thịt bò nướng ướp ngọt, thường không cay.",
        },
        {
          ko: "냉면",
          en: "naengmyeon (cold noodles)",
          zh: "冷面",
          vi: "mì lạnh naengmyeon",
          note: "Chilled buckwheat noodles, great in summer.",
          noteZh: "冰镇荞麦面，夏天吃很棒。",
          noteVi: "Mì kiều mạch lạnh, rất tuyệt vào mùa hè.",
        },
      ],
    ],
    example: {
      ko: "네, 비빔밥 주세요.",
      en: "Yes, I'll have bibimbap.",
      zh: "好的，请给我拌饭。",
      vi: "Vâng, cho tôi cơm trộn bibimbap.",
    },
    alternatives: [
      {
        ko: "이거 매워요?",
        en: "Is this spicy?",
        zh: "这个辣吗？",
        vi: "Món này có cay không?",
        note: "Useful if you want to check the spice level.",
        noteZh: "想确认辣度时很有用。",
        noteVi: "Hữu ích khi bạn muốn kiểm tra độ cay.",
      },
      {
        ko: "물 좀 주세요.",
        en: "Some water, please.",
        zh: "请给我一点水。",
        vi: "Cho tôi xin chút nước.",
        note: "Politely ask for water with 좀.",
        noteZh: "用좀礼貌地要水。",
        noteVi: "Dùng 좀 để yêu cầu nước một cách lịch sự.",
      },
    ],
  },
  {
    id: "ko-dlg-a1-family-001",
    level: "A1",
    situation: "family",
    context: { ko: "가족에 대해 이야기할 때", en: "Talking about your family", zh: "谈论家人时", vi: "Khi nói về gia đình của bạn" },
    prompt: { ko: "가족이 몇 명이에요?", en: "How many people are in your family?", zh: "您家有几口人？", vi: "Gia đình bạn có mấy người?" },
    template: "{0}이에요. {1} 있어요.",
    blanks: [
      [
        {
          ko: "세 명",
          en: "three people",
          zh: "三个人",
          vi: "ba người",
          note: "Native number 세 + counter 명 (people).",
          noteZh: "固有数词세＋量词명（人）。",
          noteVi: "Số đếm thuần Hàn 세 + lượng từ 명 (người).",
        },
        {
          ko: "네 명",
          en: "four people",
          zh: "四个人",
          vi: "bốn người",
          note: "Native number 네 + counter 명 (people).",
          noteZh: "固有数词네＋量词명（人）。",
          noteVi: "Số đếm thuần Hàn 네 + lượng từ 명 (người).",
        },
      ],
      [
        {
          ko: "동생이 한 명",
          en: "one younger sibling",
          zh: "一个弟弟（或妹妹）",
          vi: "một em (trai/gái)",
          note: "동생 works for a younger brother or sister.",
          noteZh: "동생可指弟弟或妹妹。",
          noteVi: "동생 dùng cho cả em trai lẫn em gái.",
        },
        {
          ko: "형이 한 명",
          en: "one older brother (male speaker)",
          zh: "一个哥哥（男性说话者）",
          vi: "một anh trai (người nói là nam)",
          note: "A male speaker says 형 for an older brother.",
          noteZh: "男性称呼哥哥用형。",
          noteVi: "Người nói là nam giới gọi anh trai là 형.",
        },
        {
          ko: "언니가 한 명",
          en: "one older sister (female speaker)",
          zh: "一个姐姐（女性说话者）",
          vi: "một chị gái (người nói là nữ)",
          note: "A female speaker says 언니 for an older sister.",
          noteZh: "女性称呼姐姐用언니。",
          noteVi: "Người nói là nữ giới gọi chị gái là 언니.",
        },
      ],
    ],
    example: {
      ko: "네 명이에요. 동생이 한 명 있어요.",
      en: "There are four of us. I have one younger sibling.",
      zh: "是四个人。我有一个弟弟（或妹妹）。",
      vi: "Là bốn người. Tôi có một đứa em.",
    },
    alternatives: [
      {
        ko: "형제가 없어요.",
        en: "I don't have any siblings.",
        zh: "我没有兄弟姐妹。",
        vi: "Tôi không có anh chị em.",
        note: "Use 없어요 to say you have none.",
        noteZh: "用없어요表示什么都没有。",
        noteVi: "Dùng 없어요 để nói rằng không có gì cả.",
      },
      {
        ko: "부모님과 같이 살아요.",
        en: "I live with my parents.",
        zh: "我和父母一起住。",
        vi: "Tôi sống cùng bố mẹ.",
        note: "부모님 = parents (honorific).",
        noteZh: "부모님即父母（敬语）。",
        noteVi: "부모님 nghĩa là bố mẹ (dạng kính ngữ).",
      },
    ],
  },
];
