/**
 * A2 한국어 대화 응답 카드.
 * template/blanks 는 학습 언어(한국어)로 작성, en 은 뜻, note 는 영어 설명.
 */
import type { Dialogue } from "@/types/dialogue";

export const KO_DLG_A2: Dialogue[] = [
  // ───────── shopping ─────────
  {
    id: "ko-dlg-a2-shopping-001",
    level: "A2",
    situation: "shopping",
    context: { ko: "가게에서 가격을 물어볼 때", en: "Asking the price in a store", zh: "在店里询问价格时", vi: "Khi hỏi giá ở cửa hàng" },
    prompt: { ko: "어서 오세요. 찾으시는 거 있으세요?", en: "Welcome. Are you looking for something?", zh: "欢迎光临。您在找什么吗？", vi: "Xin chào quý khách. Quý khách đang tìm gì không?" },
    template: "이거 {0}? 그리고 {1}.",
    blanks: [
      [
        {
          ko: "얼마예요",
          en: "how much is it",
          zh: "多少钱",
          vi: "bao nhiêu tiền",
          note: "The core question for any price.",
          noteZh: "问价格最核心的问句。",
          noteVi: "Câu hỏi cốt lõi cho bất kỳ mức giá nào.",
        },
        {
          ko: "세일해요",
          en: "is this on sale",
          zh: "在打折吗",
          vi: "có đang giảm giá không",
          note: "Ask if there's a discount.",
          noteZh: "询问是否有折扣。",
          noteVi: "Hỏi xem có được giảm giá không.",
        },
      ],
      [
        {
          ko: "한번 볼게요",
          en: "I'll take a look",
          zh: "我看一下",
          vi: "tôi xem thử đã",
          note: "Polite, no pressure to buy.",
          noteZh: "礼貌，不急着买。",
          noteVi: "Lịch sự, không tạo áp lực phải mua.",
        },
        {
          ko: "조금 비싸네요",
          en: "it's a little pricey",
          zh: "有点贵呢",
          vi: "hơi đắt nhỉ",
          note: "-네요 softly reacts to what you notice.",
          noteZh: "-네요用于对察觉到的事委婉表态。",
          noteVi: "-네요 dùng để phản ứng nhẹ nhàng với điều bạn nhận ra.",
        },
      ],
    ],
    example: {
      ko: "이거 얼마예요? 그리고 한번 볼게요.",
      en: "How much is this? And I'll take a look.",
      zh: "这个多少钱？我先看一下。",
      vi: "Cái này bao nhiêu tiền? Và tôi xem thử đã.",
    },
    alternatives: [
      {
        ko: "그냥 구경하는 거예요.",
        en: "I'm just looking.",
        zh: "我只是看看。",
        vi: "Tôi chỉ xem thôi.",
        note: "Friendly way to decline help.",
        noteZh: "婉拒帮忙的友好说法。",
        noteVi: "Cách thân thiện để từ chối sự giúp đỡ.",
      },
      {
        ko: "다른 색깔도 있어요?",
        en: "Do you have other colors?",
        zh: "还有别的颜色吗？",
        vi: "Có màu khác không?",
        note: "색깔 = color.",
        noteZh: "색깔即颜色。",
        noteVi: "색깔 = màu sắc.",
      },
    ],
  },
  {
    id: "ko-dlg-a2-shopping-002",
    level: "A2",
    situation: "shopping",
    context: { ko: "계산할 때", en: "When paying at the counter", zh: "结账时", vi: "Khi thanh toán" },
    prompt: { ko: "모두 이만 오천 원입니다. 어떻게 결제하시겠어요?", en: "It's 25,000 won total. How would you like to pay?", zh: "一共两万五千韩元。您想怎么付款？", vi: "Tổng cộng là 25.000 won. Quý khách muốn thanh toán như thế nào?" },
    template: "{0}. 영수증도 {1}.",
    blanks: [
      [
        {
          ko: "카드로 할게요",
          en: "I'll pay by card",
          zh: "我刷卡",
          vi: "tôi trả bằng thẻ",
          note: "(으)로 marks the payment method.",
          noteZh: "(으)로表示付款方式。",
          noteVi: "(으)로 đánh dấu phương thức thanh toán.",
        },
        {
          ko: "현금으로 낼게요",
          en: "I'll pay in cash",
          zh: "我付现金",
          vi: "tôi trả bằng tiền mặt",
          note: "현금 = cash; 내다 = to pay.",
          noteZh: "현금即现金；내다即支付。",
          noteVi: "현금 = tiền mặt; 내다 = trả (tiền).",
        },
      ],
      [
        { ko: "주세요", en: "please give me", zh: "请给我", vi: "cho tôi xin", note: "Standard polite request.", noteZh: "标准的礼貌请求。", noteVi: "Cách yêu cầu lịch sự thông thường." },
        { ko: "받을게요", en: "I'll take it", zh: "我要", vi: "tôi sẽ nhận", note: "Stating you'll accept it.", noteZh: "表示你会收下。", noteVi: "Thể hiện rằng bạn sẽ nhận lấy nó." },
      ],
    ],
    example: {
      ko: "카드로 할게요. 영수증도 주세요.",
      en: "I'll pay by card. Please give me a receipt too.",
      zh: "我刷卡。也请给我收据。",
      vi: "Tôi trả bằng thẻ. Cho tôi xin cả hóa đơn nữa.",
    },
    alternatives: [
      {
        ko: "봉투 하나 주세요.",
        en: "Please give me a bag.",
        zh: "请给我一个袋子。",
        vi: "Cho tôi xin một cái túi.",
        note: "봉투 = bag; often costs extra in Korea.",
        noteZh: "봉투即袋子；在韩国常需另外付费。",
        noteVi: "봉투 = túi; ở Hàn Quốc thường phải trả thêm tiền.",
      },
      {
        ko: "할인 되나요?",
        en: "Is there a discount?",
        zh: "能打折吗？",
        vi: "Có được giảm giá không?",
        note: "되나요? = is it possible?",
        noteZh: "되나요?意为“可以吗？”。",
        noteVi: "되나요? nghĩa là 'có được không?'.",
      },
    ],
  },

  // ───────── transport ─────────
  {
    id: "ko-dlg-a2-transport-001",
    level: "A2",
    situation: "transport",
    context: { ko: "길을 물어볼 때", en: "Asking for directions", zh: "问路时", vi: "Khi hỏi đường" },
    prompt: { ko: "어디 찾으세요? 도와드릴까요?", en: "What are you looking for? Can I help you?", zh: "您找哪里？需要帮忙吗？", vi: "Anh/chị tìm gì vậy? Tôi giúp được không?" },
    template: "네, {0}? {1}.",
    blanks: [
      [
        {
          ko: "지하철역이 어디예요",
          en: "where is the subway station",
          zh: "地铁站在哪里",
          vi: "ga tàu điện ngầm ở đâu",
          note: "역 = station.",
          noteZh: "역即站。",
          noteVi: "역 = ga.",
        },
        {
          ko: "버스 정류장이 어디예요",
          en: "where is the bus stop",
          zh: "公交车站在哪里",
          vi: "trạm xe buýt ở đâu",
          note: "정류장 = stop.",
          noteZh: "정류장即车站。",
          noteVi: "정류장 = trạm dừng.",
        },
      ],
      [
        {
          ko: "여기서 멀어요",
          en: "is it far from here",
          zh: "离这里远吗",
          vi: "có xa đây không",
          note: "멀다 = far.",
          noteZh: "멀다即远。",
          noteVi: "멀다 = xa.",
        },
        {
          ko: "걸어갈 수 있어요",
          en: "can I walk there",
          zh: "可以走过去吗",
          vi: "có thể đi bộ đến đó không",
          note: "걸어가다 = to go on foot.",
          noteZh: "걸어가다即步行前往。",
          noteVi: "걸어가다 = đi bộ đến.",
        },
      ],
    ],
    example: {
      ko: "네, 지하철역이 어디예요? 여기서 멀어요?",
      en: "Yes, where is the subway station? Is it far from here?",
      zh: "是的，地铁站在哪里？离这里远吗？",
      vi: "Vâng, ga tàu điện ngầm ở đâu ạ? Có xa đây không?",
    },
    alternatives: [
      {
        ko: "쭉 가면 돼요?",
        en: "Do I just go straight?",
        zh: "一直往前走就行吗？",
        vi: "Cứ đi thẳng là được phải không?",
        note: "쭉 = straight; -면 돼요? = is it okay if…?",
        noteZh: "쭉即一直；-면 돼요?意为“……就可以吗？”。",
        noteVi: "쭉 = thẳng; -면 돼요? nghĩa là '...thì có được không?'.",
      },
      {
        ko: "택시를 타는 게 나아요?",
        en: "Is it better to take a taxi?",
        zh: "打车会更好吗？",
        vi: "Đi taxi thì tốt hơn phải không?",
        note: "-는 게 나아요? = is it better to…?",
        noteZh: "-는 게 나아요?意为“……会更好吗？”。",
        noteVi: "-는 게 나아요? nghĩa là '...thì tốt hơn phải không?'.",
      },
    ],
  },
  {
    id: "ko-dlg-a2-transport-002",
    level: "A2",
    situation: "transport",
    context: { ko: "택시 안에서", en: "Inside a taxi", zh: "在出租车里", vi: "Ở trong taxi" },
    prompt: { ko: "안녕하세요, 어디로 모실까요?", en: "Hello, where would you like to go?", zh: "您好，请问去哪里？", vi: "Xin chào, quý khách muốn đi đâu ạ?" },
    template: "{0} 가 주세요. {1}.",
    blanks: [
      [
        {
          ko: "이 주소로",
          en: "to this address",
          zh: "去这个地址",
          vi: "đến địa chỉ này",
          note: "주소 = address; show it on your phone.",
          noteZh: "주소即地址；可以用手机给司机看。",
          noteVi: "주소 = địa chỉ; có thể cho tài xế xem trên điện thoại.",
        },
        {
          ko: "서울역으로",
          en: "to Seoul Station",
          zh: "去首尔站",
          vi: "đến ga Seoul",
          note: "Destination + (으)로 = toward.",
          noteZh: "目的地＋(으)로意为“往……”。",
          noteVi: "Điểm đến + (으)로 nghĩa là 'hướng về phía...'.",
        },
      ],
      [
        {
          ko: "좀 빨리 가 주세요",
          en: "please go a bit quickly",
          zh: "请快一点",
          vi: "đi nhanh một chút giúp tôi",
          note: "빨리 = quickly; polite urgency.",
          noteZh: "빨리即快；礼貌地表示着急。",
          noteVi: "빨리 = nhanh; cách thể hiện sự vội vàng một cách lịch sự.",
        },
        {
          ko: "천천히 가도 돼요",
          en: "you can go slowly",
          zh: "慢慢开也没关系",
          vi: "đi từ từ cũng được",
          note: "천천히 = slowly; no rush.",
          noteZh: "천천히即慢慢地；不着急。",
          noteVi: "천천히 = từ từ; không cần vội.",
        },
      ],
    ],
    example: {
      ko: "이 주소로 가 주세요. 좀 빨리 가 주세요.",
      en: "Please take me to this address. Please go a bit quickly.",
      zh: "请带我去这个地址。请开快一点。",
      vi: "Cho tôi đến địa chỉ này. Đi nhanh một chút giúp tôi.",
    },
    alternatives: [
      {
        ko: "여기서 세워 주세요.",
        en: "Please stop here.",
        zh: "请在这里停。",
        vi: "Dừng lại ở đây giúp tôi.",
        note: "세우다 = to pull over.",
        noteZh: "세우다意为“靠边停车”。",
        noteVi: "세우다 nghĩa là 'tấp xe vào lề'.",
      },
      {
        ko: "얼마나 걸려요?",
        en: "How long will it take?",
        zh: "要多长时间？",
        vi: "Mất bao lâu?",
        note: "걸리다 = to take time.",
        noteZh: "걸리다意为“花费时间”。",
        noteVi: "걸리다 nghĩa là 'mất thời gian'.",
      },
    ],
  },

  // ───────── time-date ─────────
  {
    id: "ko-dlg-a2-time-date-001",
    level: "A2",
    situation: "time-date",
    context: { ko: "약속 시간을 정할 때", en: "Setting a time to meet", zh: "约定见面时间时", vi: "Khi hẹn giờ gặp mặt" },
    prompt: { ko: "내일 시간 괜찮으세요? 언제 만날까요?", en: "Are you free tomorrow? When shall we meet?", zh: "您明天有空吗？我们什么时候见面？", vi: "Ngày mai anh/chị rảnh không? Khi nào chúng ta gặp nhau?" },
    template: "{0} 어때요? {1} 봐요.",
    blanks: [
      [
        {
          ko: "오후 세 시",
          en: "3 p.m.",
          zh: "下午三点",
          vi: "ba giờ chiều",
          note: "오후 = p.m.; hours use native numbers + 시.",
          noteZh: "오후即下午；“点”用固有数词加시。",
          noteVi: "오후 = buổi chiều; giờ dùng số đếm thuần Hàn + 시.",
        },
        {
          ko: "점심 시간",
          en: "lunchtime",
          zh: "午饭时间",
          vi: "giờ ăn trưa",
          note: "점심 = lunch.",
          noteZh: "점심即午饭。",
          noteVi: "점심 = bữa trưa.",
        },
      ],
      [
        {
          ko: "카페에서",
          en: "at the cafe",
          zh: "在咖啡馆",
          vi: "ở quán cà phê",
          note: "에서 marks where an action happens.",
          noteZh: "에서表示动作发生的地点。",
          noteVi: "에서 đánh dấu nơi hành động diễn ra.",
        },
        {
          ko: "지하철역 앞에서",
          en: "in front of the subway station",
          zh: "在地铁站前面",
          vi: "trước ga tàu điện ngầm",
          note: "앞 = front.",
          noteZh: "앞即前面。",
          noteVi: "앞 = phía trước.",
        },
      ],
    ],
    example: {
      ko: "오후 세 시 어때요? 카페에서 봐요.",
      en: "How about 3 p.m.? Let's meet at the cafe.",
      zh: "下午三点怎么样？我们在咖啡馆见。",
      vi: "Ba giờ chiều thế nào? Gặp nhau ở quán cà phê nhé.",
    },
    alternatives: [
      {
        ko: "저는 주말이 더 좋아요.",
        en: "The weekend is better for me.",
        zh: "我更喜欢周末。",
        vi: "Tôi thích cuối tuần hơn.",
        note: "더 좋아요 = is better.",
        noteZh: "더 좋아요意为“更好”。",
        noteVi: "더 좋아요 nghĩa là 'tốt hơn'.",
      },
      {
        ko: "조금 늦어도 괜찮아요?",
        en: "Is it okay if I'm a little late?",
        zh: "我稍微晚一点可以吗？",
        vi: "Tôi đến muộn một chút có được không?",
        note: "-아/어도 괜찮아요? asks permission.",
        noteZh: "-아/어도 괜찮아요?用来请求许可。",
        noteVi: "-아/어도 괜찮아요? dùng để xin phép.",
      },
    ],
  },

  // ───────── weather ─────────
  {
    id: "ko-dlg-a2-weather-001",
    level: "A2",
    situation: "weather",
    context: { ko: "날씨에 대해 이야기할 때", en: "Chatting about the weather", zh: "聊天气时", vi: "Khi nói chuyện về thời tiết" },
    prompt: { ko: "오늘 날씨 정말 좋죠? 어디 가세요?", en: "The weather's really nice today, right? Where are you headed?", zh: "今天天气真好，对吧？您去哪里？", vi: "Hôm nay thời tiết đẹp thật nhỉ? Anh/chị đi đâu vậy?" },
    template: "네, 날씨가 {0}. 그래서 {1}.",
    blanks: [
      [
        {
          ko: "너무 좋아요",
          en: "so nice",
          zh: "非常好",
          vi: "đẹp lắm",
          note: "너무 + adjective = really/too.",
          noteZh: "너무＋形容词意为“非常/太”。",
          noteVi: "너무 + tính từ nghĩa là 'thật sự/quá'.",
        },
        {
          ko: "따뜻해요",
          en: "warm",
          zh: "很暖和",
          vi: "ấm áp",
          note: "따뜻하다 = pleasantly warm.",
          noteZh: "따뜻하다指“暖和舒适”。",
          noteVi: "따뜻하다 chỉ 'sự ấm áp dễ chịu'.",
        },
      ],
      [
        {
          ko: "공원에 가요",
          en: "I'm going to the park",
          zh: "我去公园",
          vi: "tôi đi công viên",
          note: "공원 = park.",
          noteZh: "공원即公园。",
          noteVi: "공원 = công viên.",
        },
        {
          ko: "산책하려고요",
          en: "I'm planning to take a walk",
          zh: "我打算散步",
          vi: "tôi định đi dạo",
          note: "-(으)려고요 = intending to.",
          noteZh: "-(으)려고요意为“打算”。",
          noteVi: "-(으)려고요 nghĩa là 'định làm'.",
        },
      ],
    ],
    example: {
      ko: "네, 날씨가 너무 좋아요. 그래서 공원에 가요.",
      en: "Yes, the weather is so nice. So I'm going to the park.",
      zh: "是的，天气非常好。所以我去公园。",
      vi: "Vâng, thời tiết đẹp lắm. Nên tôi đi công viên.",
    },
    alternatives: [
      {
        ko: "내일은 비가 올 것 같아요.",
        en: "It might rain tomorrow.",
        zh: "明天好像会下雨。",
        vi: "Có lẽ ngày mai sẽ mưa.",
        note: "-(으)ㄹ 것 같아요 = it seems / I think.",
        noteZh: "-(으)ㄹ 것 같아요意为“好像/我觉得”。",
        noteVi: "-(으)ㄹ 것 같아요 nghĩa là 'có vẻ như/tôi nghĩ'.",
      },
      {
        ko: "요즘 날씨가 너무 더워요.",
        en: "The weather is so hot these days.",
        zh: "最近天气太热了。",
        vi: "Dạo này thời tiết nóng quá.",
        note: "요즘 = these days.",
        noteZh: "요즘意为“最近”。",
        noteVi: "요즘 nghĩa là 'dạo này'.",
      },
    ],
  },
];
