/**
 * B1 한국어 대화 응답 카드.
 * template/blanks 는 학습 언어(한국어)로 작성, en 은 뜻, note 는 영어 설명.
 *
 * B1: 이유·의견·연결 표현을 넣어 더 자연스러운 응답을 만든다.
 */
import type { Dialogue } from "@/types/dialogue";

export const KO_DLG_B1: Dialogue[] = [
  // ─────────────────────────────── work ───────────────────────────────
  {
    id: "ko-dlg-b1-work-001",
    level: "B1",
    situation: "work",
    context: {
      ko: "동료가 도움을 요청할 때",
      en: "When a coworker asks for help",
      zh: "当同事请求帮忙时",
      vi: "Khi đồng nghiệp nhờ giúp đỡ",
    },
    prompt: {
      ko: "혹시 이 보고서 좀 같이 봐 주실 수 있어요?",
      en: "Could you take a look at this report with me?",
      zh: "您能和我一起看看这份报告吗？",
      vi: "Anh/chị có thể xem giúp tôi bản báo cáo này được không?",
    },
    template: "네, {0}. 지금 {1}.",
    blanks: [
      [
        {
          ko: "그럼요",
          en: "of course",
          zh: "当然可以",
          vi: "Tất nhiên rồi",
          note: "Warm, willing agreement.",
          noteZh: "热情、乐意的应允。",
          noteVi: "Sự đồng ý nhiệt tình, sẵn lòng.",
        },
        {
          ko: "물론이죠",
          en: "certainly",
          zh: "那当然",
          vi: "Đương nhiên rồi",
          note: "Confident and polite.",
          noteZh: "自信而礼貌。",
          noteVi: "Tự tin và lịch sự.",
        },
      ],
      [
        {
          ko: "도와드릴게요",
          en: "I'll help you (humble)",
          zh: "我来帮您",
          vi: "Tôi sẽ giúp anh/chị",
          note: "드리다 shows respect to the asker.",
          noteZh: "드리다 体现对请求者的尊敬。",
          noteVi: "드리다 thể hiện sự tôn trọng đối với người nhờ vả.",
        },
        {
          ko: "같이 볼까요",
          en: "shall we look together",
          zh: "我们一起看吧",
          vi: "Cùng xem nhé",
          note: "Suggests doing it together.",
          noteZh: "提议一起做。",
          noteVi: "Đề nghị cùng nhau làm.",
        },
      ],
    ],
    example: {
      ko: "네, 그럼요. 지금 도와드릴게요.",
      en: "Yes, of course. I'll help you now.",
      zh: "好，当然可以。我现在就帮您。",
      vi: "Vâng, tất nhiên rồi. Tôi sẽ giúp anh/chị ngay bây giờ.",
    },
    alternatives: [
      {
        ko: "잠깐만요, 이것만 끝내고요.",
        en: "Just a moment, let me finish this first.",
        zh: "稍等一下，我先把这个做完。",
        vi: "Đợi một chút, để tôi làm xong cái này đã.",
        note: "Polite way to ask them to wait briefly.",
        noteZh: "礼貌地请对方稍等片刻。",
        noteVi: "Cách lịch sự để nhờ đối phương chờ một lát.",
      },
      {
        ko: "어떤 부분이 어려우세요?",
        en: "Which part is giving you trouble?",
        zh: "您是哪部分觉得难呢？",
        vi: "Phần nào anh/chị thấy khó vậy?",
        note: "Shows you want to focus on the real problem.",
        noteZh: "表示想聚焦真正的问题。",
        noteVi: "Thể hiện mong muốn tập trung vào vấn đề thực sự.",
      },
    ],
  },
  {
    id: "ko-dlg-b1-work-002",
    level: "B1",
    situation: "work",
    context: {
      ko: "회의에서 의견을 물을 때",
      en: "When asked for your opinion in a meeting",
      zh: "在会议上被问及意见时",
      vi: "Khi được hỏi ý kiến trong cuộc họp",
    },
    prompt: {
      ko: "이 일정에 대해 어떻게 생각하세요?",
      en: "What do you think about this schedule?",
      zh: "您对这个日程安排怎么看？",
      vi: "Anh/chị nghĩ sao về lịch trình này?",
    },
    template: "제 생각에는 {0} 것 같아요. {1}.",
    blanks: [
      [
        {
          ko: "조금 빠듯할",
          en: "a bit tight",
          zh: "有点紧",
          vi: "Hơi gấp",
          note: "빠듯하다 = barely enough (time/budget).",
          noteZh: "빠듯하다 = （时间／预算）勉强够。",
          noteVi: "빠듯하다 = (thời gian/ngân sách) vừa đủ, eo hẹp.",
        },
        {
          ko: "괜찮을",
          en: "fine / okay",
          zh: "没问题",
          vi: "Ổn",
          note: "Neutral agreement.",
          noteZh: "中性的认可。",
          noteVi: "Sự đồng tình trung lập.",
        },
      ],
      [
        {
          ko: "마감을 일주일만 미루면 좋겠어요",
          en: "I'd like to push the deadline by a week",
          zh: "希望能把截止日期推迟一周",
          vi: "Tôi mong có thể lùi hạn chót thêm một tuần",
          note: "-(으)면 좋겠어요 expresses a soft wish.",
          noteZh: "-(으)면 좋겠어요 表达委婉的愿望。",
          noteVi: "-(으)면 좋겠어요 diễn đạt một mong muốn nhẹ nhàng.",
        },
        {
          ko: "이대로 진행해도 될 것 같아요",
          en: "I think we can proceed as is",
          zh: "我觉得就这样进行也可以",
          vi: "Tôi nghĩ cứ tiến hành như vậy cũng được",
          note: "이대로 = as it is, in this way.",
          noteZh: "이대로 = 就这样／照这个样子。",
          noteVi: "이대로 = cứ như vậy/theo cách này.",
        },
      ],
    ],
    example: {
      ko: "제 생각에는 조금 빠듯할 것 같아요. 마감을 일주일만 미루면 좋겠어요.",
      en: "In my opinion it seems a bit tight. I'd like to push the deadline by a week.",
      zh: "在我看来时间有点紧。希望能把截止日期推迟一周。",
      vi: "Theo tôi thì có vẻ hơi gấp. Tôi mong có thể lùi hạn chót thêm một tuần.",
    },
    alternatives: [
      {
        ko: "팀원들과 한번 의논해 볼게요.",
        en: "Let me discuss it with the team.",
        zh: "我跟团队成员商量一下。",
        vi: "Tôi sẽ bàn bạc với các thành viên trong nhóm.",
        note: "Buys time and shows collaboration.",
        noteZh: "既争取时间又体现协作。",
        noteVi: "Vừa tranh thủ thời gian vừa thể hiện tinh thần hợp tác.",
      },
      {
        ko: "저는 큰 문제 없다고 봐요.",
        en: "I don't see any major problem.",
        zh: "我认为没什么大问题。",
        vi: "Tôi cho rằng không có vấn đề gì lớn.",
        note: "-다고 보다 = 'to see/regard that...'.",
        noteZh: "-다고 보다 = '认为／看作……'。",
        noteVi: "-다고 보다 = 'cho rằng/xem là...'.",
      },
    ],
  },

  // ────────────────────────────── health ──────────────────────────────
  {
    id: "ko-dlg-b1-health-001",
    level: "B1",
    situation: "health",
    context: {
      ko: "병원에서 증상을 설명할 때",
      en: "Describing symptoms at the clinic",
      zh: "在医院描述症状时",
      vi: "Khi mô tả triệu chứng ở bệnh viện",
    },
    prompt: {
      ko: "어디가 어떻게 불편하세요?",
      en: "What seems to be the problem?",
      zh: "您哪里怎么不舒服？",
      vi: "Anh/chị thấy khó chịu ở đâu và như thế nào?",
    },
    template: "{0}부터 {1}.",
    blanks: [
      [
        {
          ko: "어제",
          en: "yesterday",
          zh: "昨天",
          vi: "Hôm qua",
          note: "Time + 부터 = 'since/from'.",
          noteZh: "时间 + 부터 = '从……起'。",
          noteVi: "Thời gian + 부터 = 'từ...'.",
        },
        {
          ko: "사흘 전",
          en: "three days ago",
          zh: "三天前",
          vi: "Ba ngày trước",
          note: "사흘 = three days (native Korean count).",
          noteZh: "사흘 = 三天（韩语固有数词）。",
          noteVi: "사흘 = ba ngày (số đếm thuần Hàn).",
        },
      ],
      [
        {
          ko: "열이 나고 목이 아파요",
          en: "I have a fever and a sore throat",
          zh: "发烧，嗓子也疼",
          vi: "Tôi bị sốt và đau họng",
          note: "-고 connects two symptoms naturally.",
          noteZh: "-고 自然地连接两个症状。",
          noteVi: "-고 kết nối hai triệu chứng một cách tự nhiên.",
        },
        {
          ko: "기침이 심해요",
          en: "I have a bad cough",
          zh: "咳嗽得厉害",
          vi: "Tôi ho rất nặng",
          note: "심하다 = severe, intense.",
          noteZh: "심하다 = 严重、剧烈。",
          noteVi: "심하다 = nghiêm trọng, dữ dội.",
        },
      ],
    ],
    example: {
      ko: "어제부터 열이 나고 목이 아파요.",
      en: "Since yesterday I've had a fever and a sore throat.",
      zh: "从昨天开始发烧，嗓子也疼。",
      vi: "Từ hôm qua tôi bị sốt và đau họng.",
    },
    alternatives: [
      {
        ko: "소화가 잘 안 되는 것 같아요.",
        en: "I don't think I'm digesting well.",
        zh: "我好像消化不太好。",
        vi: "Hình như tôi bị khó tiêu.",
        note: "소화가 안 되다 = to have indigestion.",
        noteZh: "소화가 안 되다 = 消化不良。",
        noteVi: "소화가 안 되다 = bị khó tiêu.",
      },
      {
        ko: "약을 먹어도 잘 안 나아요.",
        en: "Even after taking medicine, I'm not getting better.",
        zh: "就算吃了药也不见好。",
        vi: "Dù uống thuốc rồi mà vẫn không đỡ.",
        note: "-아/어도 = 'even if/though'.",
        noteZh: "-아/어도 = '即使／尽管'。",
        noteVi: "-아/어도 = 'dù/mặc dù'.",
      },
    ],
  },

  // ────────────────────────────── travel ──────────────────────────────
  {
    id: "ko-dlg-b1-travel-001",
    level: "B1",
    situation: "travel",
    context: {
      ko: "길을 물어볼 때",
      en: "Asking for directions",
      zh: "问路时",
      vi: "Khi hỏi đường",
    },
    prompt: {
      ko: "어디 찾으세요? 도와드릴까요?",
      en: "Are you looking for somewhere? Can I help?",
      zh: "您在找什么地方吗？需要帮忙吗？",
      vi: "Anh/chị đang tìm chỗ nào ạ? Tôi giúp được không?",
    },
    template: "네, {0} 어떻게 {1}?",
    blanks: [
      [
        {
          ko: "시청까지",
          en: "to City Hall",
          zh: "到市政厅",
          vi: "Đến tòa thị chính",
          note: "Destination + 까지 = 'all the way to'.",
          noteZh: "目的地 + 까지 = '一直到'。",
          noteVi: "Điểm đến + 까지 = 'cho đến tận'.",
        },
        {
          ko: "이 주소로",
          en: "to this address",
          zh: "去这个地址",
          vi: "Đến địa chỉ này",
          note: "주소 = address; 로 marks direction.",
          noteZh: "주소 = 地址；로 表示方向。",
          noteVi: "주소 = địa chỉ; 로 đánh dấu hướng đi.",
        },
      ],
      [
        {
          ko: "가는지 알 수 있을까요",
          en: "could I find out how to get there",
          zh: "能告诉我怎么走吗",
          vi: "có thể cho tôi biết đi thế nào không",
          note: "-는지 알 수 있을까요 = a polite indirect question.",
          noteZh: "-는지 알 수 있을까요 = 礼貌的间接疑问。",
          noteVi: "-는지 알 수 있을까요 = câu hỏi gián tiếp lịch sự.",
        },
        {
          ko: "가면 되나요",
          en: "should I go / is it the way to go",
          zh: "该怎么走呢",
          vi: "đi vậy có được không",
          note: "-(으)면 되나요 = 'is it okay if I...'.",
          noteZh: "-(으)면 되나요 = '这样做可以吗'。",
          noteVi: "-(으)면 되나요 = 'làm vậy có được không'.",
        },
      ],
    ],
    example: {
      ko: "네, 시청까지 어떻게 가는지 알 수 있을까요?",
      en: "Yes, could I find out how to get to City Hall?",
      zh: "是的，能告诉我到市政厅怎么走吗？",
      vi: "Vâng, anh/chị có thể cho tôi biết đến tòa thị chính đi thế nào không?",
    },
    alternatives: [
      {
        ko: "여기에서 먼가요?",
        en: "Is it far from here?",
        zh: "离这里远吗？",
        vi: "Từ đây có xa không?",
        note: "먼가요 from 멀다 (to be far).",
        noteZh: "먼가요 来自 멀다（远）。",
        noteVi: "먼가요 xuất phát từ 멀다 (xa).",
      },
      {
        ko: "걸어서 갈 수 있어요?",
        en: "Can I get there on foot?",
        zh: "走着能到吗？",
        vi: "Đi bộ có tới được không?",
        note: "걸어서 = on foot, by walking.",
        noteZh: "걸어서 = 步行、走着。",
        noteVi: "걸어서 = đi bộ.",
      },
    ],
  },

  // ───────────────────────────── feelings ─────────────────────────────
  {
    id: "ko-dlg-b1-feelings-001",
    level: "B1",
    situation: "feelings",
    context: {
      ko: "친구가 힘든 일을 털어놓을 때",
      en: "When a friend shares something difficult",
      zh: "当朋友倾诉烦心事时",
      vi: "Khi bạn bè tâm sự chuyện khó khăn",
    },
    prompt: {
      ko: "요즘 일이 너무 안 풀려서 좀 힘들어.",
      en: "Things haven't been working out lately, so I'm a bit down.",
      zh: "最近事情很不顺，我有点难受。",
      vi: "Dạo này mọi việc không suôn sẻ nên tớ hơi mệt mỏi.",
    },
    template: "{0}. 너무 {1}.",
    blanks: [
      [
        {
          ko: "그 마음 이해해",
          en: "I understand how you feel",
          zh: "我理解你的心情",
          vi: "Tớ hiểu cảm giác đó",
          note: "Casual form for a close friend.",
          noteZh: "对亲近朋友使用的非敬语形式。",
          noteVi: "Dạng thân mật dùng cho bạn bè thân thiết.",
        },
        {
          ko: "많이 속상했겠다",
          en: "you must have been really upset",
          zh: "你一定很难过吧",
          vi: "Chắc là cậu buồn lắm",
          note: "-겠다 guesses at the other's feeling — shows empathy.",
          noteZh: "-겠다 推测对方的感受，表达共情。",
          noteVi: "-겠다 đoán cảm giác của đối phương — thể hiện sự đồng cảm.",
        },
      ],
      [
        {
          ko: "걱정하지 마",
          en: "don't worry",
          zh: "别担心",
          vi: "đừng lo lắng",
          note: "Reassuring, casual.",
          noteZh: "安慰的、随意的说法。",
          noteVi: "Cách nói an ủi, thân mật.",
        },
        {
          ko: "힘들어하지 마",
          en: "don't take it too hard",
          zh: "别太往心里去",
          vi: "đừng để trong lòng quá",
          note: "Pairs with 너무 — 'don't dwell on it too much.'",
          noteZh: "与 너무 搭配——'别太钻牛角尖'。",
          noteVi: "Kết hợp với 너무 — 'đừng suy nghĩ quá nhiều về nó'.",
        },
      ],
    ],
    example: {
      ko: "많이 속상했겠다. 너무 걱정하지 마.",
      en: "You must have been really upset. Don't worry too much.",
      zh: "你一定很难过吧。别太担心了。",
      vi: "Chắc là cậu buồn lắm. Đừng lo lắng quá.",
    },
    alternatives: [
      {
        ko: "필요하면 언제든 얘기해.",
        en: "Talk to me anytime you need to.",
        zh: "需要的话随时找我聊。",
        vi: "Cần gì thì cứ nói với tớ bất cứ lúc nào.",
        note: "언제든 = anytime; warm offer of support.",
        noteZh: "언제든 = 随时；温暖的支持表态。",
        noteVi: "언제든 = bất cứ lúc nào; lời đề nghị hỗ trợ ấm áp.",
      },
      {
        ko: "다 잘될 거야.",
        en: "Everything will work out.",
        zh: "一切都会好起来的。",
        vi: "Mọi chuyện rồi sẽ ổn thôi.",
        note: "-(으)ㄹ 거야 = casual future 'will'.",
        noteZh: "-(으)ㄹ 거야 = 非敬语的将来时'会'。",
        noteVi: "-(으)ㄹ 거야 = thì tương lai 'sẽ' ở dạng thân mật.",
      },
    ],
  },

  // ──────────────────────────── appointment ───────────────────────────
  {
    id: "ko-dlg-b1-appointment-001",
    level: "B1",
    situation: "appointment",
    context: {
      ko: "약속을 미뤄야 할 때",
      en: "When you need to reschedule",
      zh: "当你需要改约时",
      vi: "Khi cần dời lịch hẹn",
    },
    prompt: {
      ko: "내일 약속, 그대로 괜찮으시죠?",
      en: "Tomorrow's appointment is still fine, right?",
      zh: "明天的约会照旧没问题吧？",
      vi: "Lịch hẹn ngày mai vẫn giữ nguyên được chứ ạ?",
    },
    template: "죄송한데, {0} 약속을 {1}?",
    blanks: [
      [
        {
          ko: "갑자기 일이 생겨서",
          en: "because something suddenly came up",
          zh: "因为突然有事",
          vi: "vì đột nhiên có việc",
          note: "Gives a polite reason before the request.",
          noteZh: "在提出请求前先给出礼貌的理由。",
          noteVi: "Đưa ra lý do lịch sự trước khi nhờ vả.",
        },
        {
          ko: "몸이 안 좋아서",
          en: "because I'm not feeling well",
          zh: "因为身体不舒服",
          vi: "vì cơ thể không khỏe",
          note: "몸이 안 좋다 = to feel unwell.",
          noteZh: "몸이 안 좋다 = 身体不适。",
          noteVi: "몸이 안 좋다 = cảm thấy không khỏe.",
        },
      ],
      [
        {
          ko: "다음 주로 미뤄도 될까요",
          en: "could we push it to next week",
          zh: "能推迟到下周吗",
          vi: "có thể dời sang tuần sau được không",
          note: "-아/어도 될까요 = 'would it be okay if...'.",
          noteZh: "-아/어도 될까요 = '这样做可以吗'。",
          noteVi: "-아/어도 될까요 = 'làm vậy có được không'.",
        },
        {
          ko: "다른 날로 바꿀 수 있을까요",
          en: "could we change it to another day",
          zh: "能改到别的日子吗",
          vi: "có thể đổi sang ngày khác được không",
          note: "바꾸다 = to change/swap.",
          noteZh: "바꾸다 = 更改／调换。",
          noteVi: "바꾸다 = thay đổi/hoán đổi.",
        },
      ],
    ],
    example: {
      ko: "죄송한데, 갑자기 일이 생겨서 약속을 다음 주로 미뤄도 될까요?",
      en: "I'm sorry, but something came up — could we push the appointment to next week?",
      zh: "不好意思，我突然有事，约会能推迟到下周吗？",
      vi: "Xin lỗi, tôi đột nhiên có việc, có thể dời lịch hẹn sang tuần sau được không?",
    },
    alternatives: [
      {
        ko: "언제가 괜찮으신지 알려 주세요.",
        en: "Please let me know when works for you.",
        zh: "请告诉我您什么时候方便。",
        vi: "Xin hãy cho tôi biết khi nào anh/chị thuận tiện.",
        note: "Hands the choice of time to the other person.",
        noteZh: "把选择时间的权利交给对方。",
        noteVi: "Trao quyền chọn thời gian cho đối phương.",
      },
      {
        ko: "정말 죄송합니다. 다음에 제가 살게요.",
        en: "I'm really sorry. I'll treat you next time.",
        zh: "真的很抱歉。下次我请客。",
        vi: "Thực sự xin lỗi. Lần sau tôi sẽ mời.",
        note: "제가 살게요 = 'I'll pay/treat' — a friendly make-up offer.",
        noteZh: "제가 살게요 = '我请客／我买单'，友好的补偿表示。",
        noteVi: "제가 살게요 = 'tôi sẽ mời/tôi trả tiền' — lời đề nghị bù đắp thân thiện.",
      },
    ],
  },
];
