/**
 * B2 한국어 대화 응답 카드.
 * template/blanks 는 학습 언어(한국어)로 작성, en 은 뜻, note 는 영어 설명.
 *
 * B2: 의견 제시·반박·근거, 추상적 주제(시사·환경·기술·문화), 격식 연결어.
 * 빈칸 2~3개로 논리적 응답을 조합한다.
 */
import type { Dialogue } from "@/types/dialogue";

export const KO_DLG_B2: Dialogue[] = [
  {
    id: "ko-dlg-b2-opinion-001",
    level: "B2",
    situation: "opinion",
    context: {
      ko: "토론 중 상대 의견에 부분적으로 반박",
      en: "Partly pushing back on someone's view in a discussion",
      zh: "在讨论中对对方的观点部分反驳",
      vi: "Phản bác một phần ý kiến của đối phương trong khi thảo luận",
    },
    prompt: {
      ko: "재택근무가 생산성을 떨어뜨린다고 생각해요.",
      en: "I think working from home lowers productivity.",
      zh: "我认为居家办公会降低生产率。",
      vi: "Tôi nghĩ làm việc tại nhà làm giảm năng suất.",
    },
    template: "{0} {1}, 저는 오히려 효율이 높아진다고 봐요.",
    blanks: [
      [
        {
          ko: "그 말도 일리가 있지만",
          en: "that has a point, but",
          zh: "那话也有道理，但",
          vi: "lời đó cũng có lý, nhưng",
          note: "Acknowledges merit before disagreeing — diplomatic.",
          noteZh: "在表示不同意之前先承认对方有道理——很委婉。",
          noteVi: "Thừa nhận điểm hợp lý trước khi bày tỏ không đồng ý — mang tính ngoại giao, khéo léo.",
        },
        {
          ko: "어느 정도 동의하지만",
          en: "I agree to some extent, but",
          zh: "在一定程度上同意，但",
          vi: "tôi đồng ý một phần, nhưng",
          note: "Concedes partially, softens the counterpoint.",
          noteZh: "先部分让步，缓和接下来的反驳。",
          noteVi: "Nhượng bộ một phần, làm dịu đi phản biện sắp đưa ra.",
        },
      ],
      [
        {
          ko: "솔직히 말하면",
          en: "to be honest",
          zh: "老实说",
          vi: "thành thật mà nói",
          note: "Adds candor; signals a sincere counter-opinion.",
          noteZh: "增添坦率感，预示一个真诚的相反观点。",
          noteVi: "Thêm phần thẳng thắn; báo hiệu một ý kiến trái chiều chân thành sắp đến.",
        },
        {
          ko: "제 생각에는",
          en: "in my opinion",
          zh: "在我看来",
          vi: "theo tôi nghĩ",
          note: "Neutral, polite framing of your stance.",
          noteZh: "中性、礼貌地表达你的立场。",
          noteVi: "Cách trình bày lập trường một cách trung lập, lịch sự.",
        },
      ],
    ],
    example: {
      ko: "그 말도 일리가 있지만 솔직히 말하면, 저는 오히려 효율이 높아진다고 봐요.",
      en: "That has a point, but to be honest, I actually think efficiency goes up.",
      zh: "那话也有道理，但老实说，我反而认为效率会提高。",
      vi: "Lời đó cũng có lý, nhưng thành thật mà nói, tôi lại cho rằng hiệu quả sẽ tăng lên.",
    },
    alternatives: [
      {
        ko: "꼭 그렇다고 보기는 어려워요.",
        en: "I wouldn't say that's necessarily the case.",
        zh: "很难说一定是这样。",
        vi: "Khó mà nói chắc chắn là như vậy.",
        note: "Gentle, hedged disagreement.",
        noteZh: "温和、留有余地的不同意。",
        noteVi: "Cách không đồng ý nhẹ nhàng, có chừa đường lùi.",
      },
      {
        ko: "사람마다 다르지 않을까요?",
        en: "Doesn't it depend on the person?",
        zh: "这不是因人而异吗？",
        vi: "Chẳng phải cái đó tùy người hay sao?",
        note: "Deflects to individual differences to avoid a clash.",
        noteZh: "把话题引向个体差异，以避免正面冲突。",
        noteVi: "Hướng chủ đề sang sự khác biệt cá nhân để tránh xung đột trực tiếp.",
      },
    ],
  },
  {
    id: "ko-dlg-b2-opinion-002",
    level: "B2",
    situation: "opinion",
    context: {
      ko: "의견을 묻는 질문에 근거와 함께 답하기",
      en: "Answering an opinion question with reasons",
      zh: "对征询意见的提问，连同理由一起回答",
      vi: "Trả lời câu hỏi xin ý kiến kèm theo lý do",
    },
    prompt: {
      ko: "이 정책에 대해 어떻게 생각하세요?",
      en: "What do you think about this policy?",
      zh: "您对这项政策怎么看？",
      vi: "Bạn nghĩ sao về chính sách này?",
    },
    template: "저는 {0}. 그 이유는 {1} 때문이에요.",
    blanks: [
      [
        {
          ko: "찬성하는 입장이에요",
          en: "I'm in favor",
          zh: "我持赞成的立场",
          vi: "đứng về phía ủng hộ",
          note: "찬성 = support; 입장 = stance/position.",
          noteZh: "찬성 = 赞成；입장 = 立场／态度。",
          noteVi: "찬성 = ủng hộ; 입장 = lập trường/thái độ.",
        },
        {
          ko: "반대하는 입장이에요",
          en: "I'm opposed",
          zh: "我持反对的立场",
          vi: "đứng về phía phản đối",
          note: "반대 = oppose. Same frame, opposite stance.",
          noteZh: "반대 = 反对。句式相同，立场相反。",
          noteVi: "반대 = phản đối. Cùng cấu trúc câu, lập trường ngược lại.",
        },
      ],
      [
        {
          ko: "장기적으로 도움이 되기",
          en: "it helps in the long run",
          zh: "从长远看有帮助",
          vi: "vì có ích về lâu dài",
          note: "장기적으로 = in the long term — a B2 connector.",
          noteZh: "장기적으로 = 从长远看——B2 常用的连接词。",
          noteVi: "장기적으로 = về lâu dài — một từ nối thường dùng ở trình độ B2.",
        },
        {
          ko: "부작용이 클 수 있기",
          en: "the side effects could be large",
          zh: "副作用可能很大",
          vi: "vì tác dụng phụ có thể lớn",
          note: "Pairs naturally with the 반대 stance.",
          noteZh: "与“반대（反对）”的立场自然搭配。",
          noteVi: "Kết hợp tự nhiên với lập trường 반대 (phản đối).",
        },
      ],
    ],
    example: {
      ko: "저는 찬성하는 입장이에요. 그 이유는 장기적으로 도움이 되기 때문이에요.",
      en: "I'm in favor. The reason is that it helps in the long run.",
      zh: "我持赞成的立场。原因是从长远看它有帮助。",
      vi: "Tôi đứng về phía ủng hộ. Lý do là vì nó có ích về lâu dài.",
    },
    alternatives: [
      {
        ko: "아직 판단하기 이른 것 같아요.",
        en: "I think it's too early to judge.",
        zh: "我觉得现在下判断还为时过早。",
        vi: "Tôi nghĩ còn quá sớm để đánh giá.",
        note: "Polite way to withhold a firm opinion.",
        noteZh: "礼貌地暂不表明明确观点的说法。",
        noteVi: "Cách nói lịch sự để tạm chưa đưa ra ý kiến rõ ràng.",
      },
      {
        ko: "조금 더 지켜봐야 할 것 같아요.",
        en: "I think we need to wait and see a bit more.",
        zh: "我觉得还得再观望一阵。",
        vi: "Tôi nghĩ cần phải quan sát thêm một chút nữa.",
        note: "지켜보다 = to watch how things unfold.",
        noteZh: "지켜보다 = 观察事态如何发展。",
        noteVi: "지켜보다 = quan sát xem sự việc diễn biến ra sao.",
      },
    ],
  },
  {
    id: "ko-dlg-b2-news-001",
    level: "B2",
    situation: "news",
    context: {
      ko: "최근 뉴스에 대해 반응하기",
      en: "Reacting to a recent news story",
      zh: "对近期新闻作出回应",
      vi: "Phản ứng trước một tin tức gần đây",
    },
    prompt: {
      ko: "그 사건이 큰 논란이 됐다고 하던데요.",
      en: "I heard that incident became a big controversy.",
      zh: "听说那起事件引发了很大的争议。",
      vi: "Nghe nói sự việc đó đã trở thành một tranh cãi lớn.",
    },
    template: "네, {0}. {1} 찬반이 갈리는 것 같아요.",
    blanks: [
      [
        {
          ko: "보도에 따르면 심각한 상황이래요",
          en: "according to reports, it's serious",
          zh: "据报道情况很严重",
          vi: "theo báo cáo thì tình hình nghiêm trọng",
          note: "보도에 따르면 = 'according to reports,' newsy register.",
          noteZh: "보도에 따르면 = “据报道”，新闻语体。",
          noteVi: "보도에 따르면 = “theo báo cáo”, văn phong báo chí.",
        },
        {
          ko: "여론이 많이 안 좋아졌어요",
          en: "public opinion has soured a lot",
          zh: "舆论变得很不好",
          vi: "dư luận đã trở nên rất xấu",
          note: "여론 = public opinion — a core news word.",
          noteZh: "여론 = 舆论——核心新闻词汇。",
          noteVi: "여론 = dư luận — từ vựng cốt lõi trong tin tức.",
        },
      ],
      [
        {
          ko: "이 문제를 두고",
          en: "over this issue",
          zh: "围绕这个问题",
          vi: "xoay quanh vấn đề này",
          note: "...을 두고 = 'over (a contested issue).'",
          noteZh: "……을 두고 = “围绕（有争议的议题）”。",
          noteVi: "...을 두고 = “xoay quanh (một vấn đề đang gây tranh cãi)”.",
        },
        {
          ko: "사람들 사이에서",
          en: "among people",
          zh: "在人们之间",
          vi: "giữa mọi người với nhau",
          note: "More everyday phrasing for the same idea.",
          noteZh: "表达同样意思的更日常的说法。",
          noteVi: "Cách diễn đạt đời thường hơn cho cùng một ý.",
        },
      ],
    ],
    example: {
      ko: "네, 보도에 따르면 심각한 상황이래요. 이 문제를 두고 찬반이 갈리는 것 같아요.",
      en: "Yes, according to reports it's serious. Opinions seem split for and against over this issue.",
      zh: "是啊，据报道情况很严重。围绕这个问题，大家似乎赞成与反对意见不一。",
      vi: "Vâng, theo báo cáo thì tình hình nghiêm trọng. Có vẻ ý kiến đang chia rẽ giữa tán thành và phản đối xoay quanh vấn đề này.",
    },
    alternatives: [
      {
        ko: "당국이 곧 입장을 밝힐 것 같아요.",
        en: "The authorities will probably state their position soon.",
        zh: "当局大概很快会表明立场。",
        vi: "Có lẽ nhà chức trách sẽ sớm nêu rõ lập trường.",
        note: "입장을 밝히다 = to clarify one's official stance.",
        noteZh: "입장을 밝히다 = 表明自己的官方立场。",
        noteVi: "입장을 밝히다 = làm rõ lập trường chính thức của mình.",
      },
      {
        ko: "여파가 한동안 이어질 것 같아요.",
        en: "The repercussions will likely continue for a while.",
        zh: "余波可能会持续一段时间。",
        vi: "Có lẽ dư chấn sẽ còn tiếp diễn một thời gian.",
        note: "여파 = aftermath; 이어지다 = to continue.",
        noteZh: "여파 = 余波；이어지다 = 持续。",
        noteVi: "여파 = dư chấn; 이어지다 = tiếp diễn/kéo dài.",
      },
    ],
  },
  {
    id: "ko-dlg-b2-environment-001",
    level: "B2",
    situation: "environment",
    context: {
      ko: "환경 보호 실천에 대해 이야기",
      en: "Talking about taking eco-friendly action",
      zh: "谈论践行环保的话题",
      vi: "Nói chuyện về việc thực hành bảo vệ môi trường",
    },
    prompt: {
      ko: "요즘 환경을 위해 따로 실천하는 게 있어요?",
      en: "Are you doing anything in particular for the environment these days?",
      zh: "最近你有没有特别为环境做些什么？",
      vi: "Dạo này bạn có làm gì riêng cho môi trường không?",
    },
    template: "네, {0} 줄이려고 노력하고, {1} 신경 써요.",
    blanks: [
      [
        {
          ko: "일회용품 사용을",
          en: "the use of disposables",
          zh: "一次性用品的使用",
          vi: "việc sử dụng đồ dùng một lần",
          note: "일회용품 = single-use items, a real Korean policy topic.",
          noteZh: "일회용품 = 一次性用品，是韩国现实中的一个政策话题。",
          noteVi: "일회용품 = đồ dùng một lần, một chủ đề chính sách có thật ở Hàn Quốc.",
        },
        {
          ko: "탄소 배출을",
          en: "carbon emissions",
          zh: "碳排放",
          vi: "phát thải carbon",
          note: "More formal, bigger-picture framing.",
          noteZh: "更正式、更宏观的说法。",
          noteVi: "Cách nói trang trọng hơn, mang tính bao quát hơn.",
        },
      ],
      [
        {
          ko: "분리수거에도",
          en: "to separating recycling too",
          zh: "对垃圾分类也",
          vi: "cả việc phân loại rác nữa",
          note: "분리수거 = sorting recycling — daily life in Korea.",
          noteZh: "분리수거 = 垃圾分类回收——韩国的日常生活。",
          noteVi: "분리수거 = phân loại rác để tái chế — sinh hoạt hàng ngày ở Hàn Quốc.",
        },
        {
          ko: "친환경 제품에도",
          en: "to eco-friendly products too",
          zh: "对环保产品也",
          vi: "cả sản phẩm thân thiện môi trường nữa",
          note: "친환경 = eco-friendly, attaches to nouns.",
          noteZh: "친환경 = 环保，用于修饰名词。",
          noteVi: "친환경 = thân thiện với môi trường, gắn với danh từ.",
        },
      ],
    ],
    example: {
      ko: "네, 일회용품 사용을 줄이려고 노력하고, 분리수거에도 신경 써요.",
      en: "Yes, I try to cut down on disposables, and I'm careful about sorting recycling too.",
      zh: "嗯，我尽量减少一次性用品的使用，也很注意垃圾分类。",
      vi: "Vâng, tôi cố gắng giảm sử dụng đồ dùng một lần, và cũng chú ý đến việc phân loại rác.",
    },
    alternatives: [
      {
        ko: "작은 일이라도 실천하는 게 중요하니까요.",
        en: "Because it matters to act, even on small things.",
        zh: "因为哪怕是小事，付诸行动也很重要。",
        vi: "Vì dù là việc nhỏ, hành động thực tế cũng quan trọng mà.",
        note: "실천하다 = to put into practice — key eco verb.",
        noteZh: "실천하다 = 付诸实践——关键的环保动词。",
        noteVi: "실천하다 = biến thành hành động thực tế — động từ chủ chốt trong chủ đề môi trường.",
      },
      {
        ko: "대중교통을 주로 이용하려고 해요.",
        en: "I try to mainly use public transport.",
        zh: "我尽量主要乘坐公共交通。",
        vi: "Tôi cố gắng chủ yếu sử dụng phương tiện công cộng.",
        note: "대중교통 = public transit; a concrete habit.",
        noteZh: "대중교통 = 公共交通；一个具体的习惯。",
        noteVi: "대중교통 = phương tiện giao thông công cộng; một thói quen cụ thể.",
      },
    ],
  },
  {
    id: "ko-dlg-b2-technology-001",
    level: "B2",
    situation: "technology",
    context: {
      ko: "인공지능의 영향에 대해 토론",
      en: "Discussing the impact of AI",
      zh: "讨论人工智能的影响",
      vi: "Thảo luận về ảnh hưởng của trí tuệ nhân tạo",
    },
    prompt: {
      ko: "인공지능이 결국 사람 일자리를 다 없앨까요?",
      en: "Will AI ultimately wipe out all human jobs?",
      zh: "人工智能最终会把人的工作岗位全都消灭掉吗？",
      vi: "Cuối cùng trí tuệ nhân tạo có xóa sổ hết việc làm của con người không?",
    },
    template: "글쎄요, {0}. 다만 {1} 부작용도 무시할 수는 없어요.",
    blanks: [
      [
        {
          ko: "완전히 대체하기는 어렵다고 봐요",
          en: "I think it's hard to fully replace people",
          zh: "我认为很难完全取代人",
          vi: "tôi cho rằng khó mà thay thế hoàn toàn",
          note: "대체하다 = to replace; -다고 봐요 = 'I take the view that.'",
          noteZh: "대체하다 = 取代；-다고 봐요 = “我认为／我持……的看法”。",
          noteVi: "대체하다 = thay thế; -다고 봐요 = “tôi cho rằng / tôi có quan điểm rằng”.",
        },
        {
          ko: "오히려 새 일자리도 생길 거예요",
          en: "new jobs will appear, if anything",
          zh: "反而还会催生新的工作岗位",
          vi: "ngược lại còn sẽ sinh ra việc làm mới",
          note: "오히려 = 'if anything / on the contrary.'",
          noteZh: "오히려 = “反而／恰恰相反”。",
          noteVi: "오히려 = “ngược lại / trái lại”.",
        },
      ],
      [
        {
          ko: "지나치게 의존하는",
          en: "relying on it too much",
          zh: "过度依赖",
          vi: "phụ thuộc quá mức",
          note: "...에 의존하다 = to depend on; 지나치게 = excessively.",
          noteZh: "……에 의존하다 = 依赖；지나치게 = 过度地。",
          noteVi: "...에 의존하다 = phụ thuộc vào; 지나치게 = một cách quá mức.",
        },
        {
          ko: "정보 격차가 커지는",
          en: "the information gap widening",
          zh: "信息鸿沟扩大",
          vi: "khoảng cách thông tin ngày càng lớn",
          note: "정보 격차 = the digital/information divide.",
          noteZh: "정보 격차 = 数字／信息鸿沟。",
          noteVi: "정보 격차 = khoảng cách số/thông tin.",
        },
      ],
    ],
    example: {
      ko: "글쎄요, 완전히 대체하기는 어렵다고 봐요. 다만 지나치게 의존하는 부작용도 무시할 수는 없어요.",
      en: "Well, I think it's hard to fully replace people. That said, we can't ignore the downside of relying on it too much.",
      zh: "这个嘛，我认为很难完全取代人。不过过度依赖的副作用也不容忽视。",
      vi: "Ừm, tôi cho rằng khó mà thay thế hoàn toàn con người. Nhưng cũng không thể bỏ qua tác dụng phụ của việc phụ thuộc quá mức.",
    },
    alternatives: [
      {
        ko: "기술 변화 속도를 따라가기가 벅차요.",
        en: "It's overwhelming to keep up with the pace of tech change.",
        zh: "要跟上技术变化的速度很吃力。",
        vi: "Theo kịp tốc độ thay đổi công nghệ thật đuối sức.",
        note: "따라가다 = to keep up; 벅차다 = overwhelming.",
        noteZh: "따라가다 = 跟上；벅차다 = 吃力／力不从心。",
        noteVi: "따라가다 = theo kịp; 벅차다 = quá sức/đuối sức.",
      },
      {
        ko: "결국 사람의 역할이 바뀌는 거겠죠.",
        en: "In the end, the human role will just shift.",
        zh: "归根结底，人的角色只是会发生转变吧。",
        vi: "Rốt cuộc thì vai trò của con người chỉ là sẽ thay đổi thôi.",
        note: "Frames change as transformation, not elimination.",
        noteZh: "把变化诠释为转型，而非被淘汰。",
        noteVi: "Diễn giải sự thay đổi như một sự chuyển đổi, chứ không phải bị đào thải.",
      },
    ],
  },
  {
    id: "ko-dlg-b2-culture-001",
    level: "B2",
    situation: "culture",
    context: {
      ko: "전시나 공연 추천하기",
      en: "Recommending an exhibition or performance",
      zh: "推荐展览或演出",
      vi: "Giới thiệu triển lãm hoặc buổi biểu diễn",
    },
    prompt: {
      ko: "주말에 볼 만한 전시 있을까요?",
      en: "Is there an exhibition worth seeing this weekend?",
      zh: "周末有什么值得一看的展览吗？",
      vi: "Cuối tuần có triển lãm nào đáng xem không?",
    },
    template: "네, {0}. 작가의 {1} 잘 드러나서 가 볼 만해요.",
    blanks: [
      [
        {
          ko: "요즘 하는 사진전을 추천해요",
          en: "I recommend the photo exhibition on now",
          zh: "我推荐最近在办的摄影展",
          vi: "tôi giới thiệu triển lãm ảnh đang diễn ra dạo này",
          note: "사진전 = photography exhibition; 추천하다 = to recommend.",
          noteZh: "사진전 = 摄影展；추천하다 = 推荐。",
          noteVi: "사진전 = triển lãm ảnh; 추천하다 = giới thiệu/gợi ý.",
        },
        {
          ko: "근처 미술관 전시가 좋았어요",
          en: "the show at the nearby museum was good",
          zh: "附近美术馆的展览很不错",
          vi: "triển lãm ở bảo tàng mỹ thuật gần đây khá hay",
          note: "미술관 = art museum/gallery.",
          noteZh: "미술관 = 美术馆／画廊。",
          noteVi: "미술관 = bảo tàng/phòng trưng bày mỹ thuật.",
        },
      ],
      [
        {
          ko: "개성이",
          en: "individuality",
          zh: "个性",
          vi: "cá tính",
          note: "개성 = a distinct personal style.",
          noteZh: "개성 = 与众不同的个人风格。",
          noteVi: "개성 = phong cách cá nhân riêng biệt.",
        },
        {
          ko: "감각이",
          en: "artistic sensibility",
          zh: "艺术感觉",
          vi: "cảm quan nghệ thuật",
          note: "감각 = a refined sense/feel for things.",
          noteZh: "감각 = 对事物细腻的感觉／审美。",
          noteVi: "감각 = cảm nhận/óc thẩm mỹ tinh tế về sự vật.",
        },
      ],
    ],
    example: {
      ko: "네, 요즘 하는 사진전을 추천해요. 작가의 개성이 잘 드러나서 가 볼 만해요.",
      en: "Yes, I recommend the photo exhibition on now. The artist's individuality really shows, so it's worth going.",
      zh: "嗯，我推荐最近在办的摄影展。作者的个性展现得很充分，值得一看。",
      vi: "Vâng, tôi giới thiệu triển lãm ảnh đang diễn ra dạo này. Cá tính của tác giả thể hiện rất rõ nên đáng để xem.",
    },
    alternatives: [
      {
        ko: "취향에 따라 다르겠지만 저는 좋았어요.",
        en: "It depends on your taste, but I liked it.",
        zh: "虽然因人的喜好而异，但我挺喜欢的。",
        vi: "Tùy vào sở thích mỗi người, nhưng tôi thì thích.",
        note: "취향 = taste/preference; hedges a recommendation.",
        noteZh: "취향 = 喜好／品味；给推荐留有余地。",
        noteVi: "취향 = sở thích/gu; giúp lời giới thiệu có chừa đường lùi.",
      },
      {
        ko: "인상 깊은 작품이 많았어요.",
        en: "There were many impressive pieces.",
        zh: "有很多令人印象深刻的作品。",
        vi: "Có nhiều tác phẩm để lại ấn tượng sâu sắc.",
        note: "인상 깊다 = to leave a deep impression; 작품 = work.",
        noteZh: "인상 깊다 = 印象深刻；작품 = 作品。",
        noteVi: "인상 깊다 = để lại ấn tượng sâu sắc; 작품 = tác phẩm.",
      },
    ],
  },
];
