/**
 * C1 한국어 대화 응답 카드.
 * template/blanks 는 학습 언어(한국어)로 작성, en 은 뜻, note 는 영어 설명.
 *
 * C1: 업무·전문 상황의 능숙한 응답, 논리적 주장, 미묘한 격식, 한자어 어휘.
 * 빈칸 수 3~4개로 고급 조합 학습.
 */
import type { Dialogue } from "@/types/dialogue";

export const KO_DLG_C1: Dialogue[] = [
  {
    id: "ko-dlg-c1-business-001",
    level: "C1",
    situation: "business",
    context: {
      ko: "회의에서 제안에 신중하게 답하기",
      en: "Responding cautiously to a proposal in a meeting",
      zh: "在会议上谨慎地回应提案",
      vi: "Trả lời thận trọng trước một đề xuất trong cuộc họp",
    },
    prompt: {
      ko: "이번 분기 안에 신규 사업을 추진하는 게 어떻겠습니까?",
      en: "How about pushing ahead with the new project within this quarter?",
      zh: "本季度内推进新业务，您看怎么样？",
      vi: "Chúng ta xúc tiến dự án kinh doanh mới trong quý này thì thế nào?",
    },
    template: "{0} 검토가 필요하지만, {1} 긍정적으로 {2}.",
    blanks: [
      [
        {
          ko: "추가적인",
          en: "additional",
          zh: "额外的",
          vi: "bổ sung",
          note: "추가적 (additional, 追加的) sounds measured and formal.",
          noteZh: "추가적（额外的、追加的，追加的）语气稳重而正式。",
          noteVi: "추가적 (bổ sung, thêm vào) nghe có vẻ thận trọng và trang trọng.",
        },
        {
          ko: "면밀한",
          en: "careful / thorough",
          zh: "缜密的",
          vi: "kỹ lưỡng",
          note: "면밀하다 (meticulous, 綿密) emphasizes due diligence.",
          noteZh: "면밀하다（缜密，綿密）强调审慎周全。",
          noteVi: "면밀하다 (kỹ lưỡng, tỉ mỉ) nhấn mạnh sự thận trọng, chu đáo.",
        },
      ],
      [
        {
          ko: "방향 자체는",
          en: "the direction itself",
          zh: "方向本身",
          vi: "bản thân hướng đi",
          note: "Concedes the overall idea while reserving on details.",
          noteZh: "认可整体思路，但对细节保留意见。",
          noteVi: "Thừa nhận ý tưởng tổng thể nhưng vẫn bảo lưu ý kiến về chi tiết.",
        },
        {
          ko: "취지에는",
          en: "as for the intent",
          zh: "就宗旨而言",
          vi: "về mục đích thì",
          note: "취지 (intent/purpose, 趣旨) — agreeing with the aim.",
          noteZh: "취지（宗旨、意图，趣旨）——赞同其目标。",
          noteVi: "취지 (mục đích, tôn chỉ) — đồng ý với mục tiêu đề ra.",
        },
      ],
      [
        {
          ko: "검토하겠습니다",
          en: "will review it",
          zh: "会研究一下",
          vi: "sẽ xem xét",
          note: "Polite, non-committal commitment to consider.",
          noteZh: "礼貌、不作承诺地表示会考虑。",
          noteVi: "Một cam kết lịch sự nhưng không ràng buộc, chỉ hứa sẽ cân nhắc.",
        },
        {
          ko: "보고 있습니다",
          en: "am viewing it",
          zh: "正持某种看法",
          vi: "đang nhìn nhận",
          note: "긍정적으로 보다 = to view favorably.",
          noteZh: "긍정적으로 보다 = 持肯定看法。",
          noteVi: "긍정적으로 보다 = nhìn nhận một cách tích cực.",
        },
      ],
    ],
    example: {
      ko: "추가적인 검토가 필요하지만, 방향 자체는 긍정적으로 검토하겠습니다.",
      en: "It needs additional review, but I'll consider the direction itself favorably.",
      zh: "虽然还需要进一步研究，但方向本身我会积极考虑。",
      vi: "Cần xem xét thêm, nhưng bản thân hướng đi thì tôi sẽ xem xét một cách tích cực.",
    },
    alternatives: [
      {
        ko: "득실을 좀 더 따져 봐야 할 것 같습니다.",
        en: "I think we need to weigh the pros and cons a bit more.",
        zh: "我觉得还需要再权衡一下得失。",
        vi: "Tôi nghĩ chúng ta cần cân nhắc kỹ hơn về được mất.",
        note: "Buys time analytically without rejecting the idea.",
        noteZh: "以分析为由争取时间，又不否定该想法。",
        noteVi: "Tranh thủ thêm thời gian bằng lý do phân tích, mà không phủ nhận ý tưởng đó.",
      },
      {
        ko: "후속 미팅에서 구체적으로 논의하시죠.",
        en: "Let's discuss the specifics in a follow-up meeting.",
        zh: "具体细节我们在后续会议上讨论吧。",
        vi: "Chúng ta hãy bàn cụ thể trong cuộc họp tiếp theo.",
        note: "Defers detail politely to a later session.",
        noteZh: "礼貌地把细节留到之后的会议。",
        noteVi: "Lịch sự để chi tiết lại bàn vào buổi họp sau.",
      },
    ],
  },
  {
    id: "ko-dlg-c1-business-002",
    level: "C1",
    situation: "business",
    context: {
      ko: "프로젝트 차질에 대한 책임을 다루기",
      en: "Addressing accountability for a project setback",
      zh: "处理项目失误的责任问题",
      vi: "Xử lý trách nhiệm về sự cố của dự án",
    },
    prompt: {
      ko: "일정이 많이 지연됐는데, 원인이 무엇이라고 보십니까?",
      en: "The schedule has slipped a lot — what do you see as the cause?",
      zh: "进度延误了很多，您认为原因是什么？",
      vi: "Tiến độ đã bị chậm khá nhiều, anh/chị nhận định nguyên nhân là gì?",
    },
    template: "{0} 제 판단 착오였고, 결과에 대해서는 제가 {1}.",
    blanks: [
      [
        {
          ko: "솔직히 말씀드리면",
          en: "to be honest",
          zh: "坦白地说",
          vi: "nói thẳng ra thì",
          note: "Frank but professional opener for owning a mistake.",
          noteZh: "坦率却不失专业，用于主动承认错误的开场。",
          noteVi: "Mở đầu thẳng thắn nhưng vẫn chuyên nghiệp khi chủ động thừa nhận sai sót.",
        },
        {
          ko: "변명의 여지 없이",
          en: "without excuse",
          zh: "毫无借口地",
          vi: "không có gì để biện minh",
          note: "변명의 여지 없이 = leaving no room for excuses. Strong accountability.",
          noteZh: "변명의 여지 없이 = 没有辩解的余地。表示强烈的担当。",
          noteVi: "변명의 여지 없이 = không còn chỗ để biện hộ. Thể hiện tinh thần trách nhiệm mạnh mẽ.",
        },
      ],
      [
        {
          ko: "책임을 지겠습니다",
          en: "will take responsibility",
          zh: "我会承担责任",
          vi: "sẽ chịu trách nhiệm",
          note: "책임을 지다 = to bear responsibility. Valued highly in Korean work culture.",
          noteZh: "책임을 지다 = 承担责任。在韩国职场文化中备受推崇。",
          noteVi: "책임을 지다 = gánh chịu trách nhiệm. Rất được coi trọng trong văn hóa công sở Hàn Quốc.",
        },
        {
          ko: "책임을 통감합니다",
          en: "feel the responsibility keenly",
          zh: "我深感责任重大",
          vi: "cảm nhận sâu sắc trách nhiệm",
          note: "통감하다 (to feel acutely, 痛感) — formal, contrite register.",
          noteZh: "통감하다（深感、痛感，痛感）——正式而带歉意的语气。",
          noteVi: "통감하다 (cảm nhận sâu sắc, thấm thía) — văn phong trang trọng, mang ý hối lỗi.",
        },
      ],
    ],
    example: {
      ko: "솔직히 말씀드리면 제 판단 착오였고, 결과에 대해서는 제가 책임을 지겠습니다.",
      en: "To be honest, it was my misjudgment, and I will take responsibility for the outcome.",
      zh: "坦白地说，是我判断失误，对于结果我会承担责任。",
      vi: "Nói thẳng ra thì đó là sai lầm trong phán đoán của tôi, và tôi sẽ chịu trách nhiệm về kết quả này.",
    },
    alternatives: [
      {
        ko: "재발 방지책을 마련하겠습니다.",
        en: "I'll put measures in place to prevent a recurrence.",
        zh: "我会制定防止再次发生的措施。",
        vi: "Tôi sẽ chuẩn bị biện pháp phòng ngừa tái diễn.",
        note: "재발 방지 (recurrence prevention, 再發防止) — shows forward-looking ownership.",
        noteZh: "재발 방지（防止再次发生，再發防止）——体现着眼未来的担当。",
        noteVi: "재발 방지 (phòng ngừa tái diễn) — thể hiện tinh thần trách nhiệm hướng tới tương lai.",
      },
      {
        ko: "원인을 면밀히 분석해 보고드리겠습니다.",
        en: "I'll analyze the cause closely and report back.",
        zh: "我会仔细分析原因后再向您汇报。",
        vi: "Tôi sẽ phân tích kỹ nguyên nhân rồi báo cáo lại.",
        note: "Defers blame to a fact-based follow-up.",
        noteZh: "把追责引向以事实为依据的后续跟进。",
        noteVi: "Hướng việc quy trách nhiệm sang một bước theo dõi dựa trên sự thật.",
      },
    ],
  },
  {
    id: "ko-dlg-c1-society-001",
    level: "C1",
    situation: "society",
    context: {
      ko: "사회 격차 문제에 의견을 밝히기",
      en: "Stating your view on social inequality",
      zh: "就社会差距问题表明看法",
      vi: "Nêu quan điểm về vấn đề bất bình đẳng xã hội",
    },
    prompt: {
      ko: "빈부 격차 문제, 정부가 어떻게 접근해야 한다고 보세요?",
      en: "How do you think the government should approach the wealth gap?",
      zh: "对于贫富差距问题，您认为政府应该如何应对？",
      vi: "Về vấn đề khoảng cách giàu nghèo, anh/chị nghĩ chính phủ nên tiếp cận như thế nào?",
    },
    template: "단기 대책보다는 {0} 사회 안전망을 {1} 하고, 무엇보다 {2} 형성이 우선이라고 봅니다.",
    blanks: [
      [
        {
          ko: "근본적으로",
          en: "fundamentally",
          zh: "从根本上",
          vi: "về căn bản",
          note: "근본적 (fundamental, 根本的) frames a structural rather than quick fix.",
          noteZh: "근본적（根本的，根本的）强调结构性解决而非临时补救。",
          noteVi: "근본적 (căn bản, cốt lõi) nhấn mạnh giải pháp mang tính cấu trúc thay vì đối phó tạm thời.",
        },
        {
          ko: "장기적으로",
          en: "in the long term",
          zh: "从长远来看",
          vi: "về lâu dài",
          note: "장기적 (long-term, 長期的) signals sustained policy.",
          noteZh: "장기적（长期的，長期的）意味着持续性的政策。",
          noteVi: "장기적 (dài hạn) hàm ý một chính sách mang tính bền vững.",
        },
      ],
      [
        {
          ko: "강화해야",
          en: "must strengthen",
          zh: "必须强化",
          vi: "phải củng cố",
          note: "강화하다 (to reinforce, 強化) pairs with 안전망 (safety net).",
          noteZh: "강화하다（强化，強化）与 안전망（保障网）搭配。",
          noteVi: "강화하다 (củng cố, tăng cường) thường đi kèm với 안전망 (mạng lưới an sinh).",
        },
        {
          ko: "촘촘히 해야",
          en: "must make denser / tighter",
          zh: "必须织得更密",
          vi: "phải dệt cho dày, khít hơn",
          note: "촘촘히 = densely; vivid way to describe a fine-meshed safety net.",
          noteZh: "촘촘히 = 密密地；生动地形容把保障网织得更细密。",
          noteVi: "촘촘히 = một cách dày đặc, khít khao; cách diễn đạt sinh động để mô tả việc dệt mạng lưới an sinh chặt chẽ hơn.",
        },
      ],
      [
        {
          ko: "사회적 공감대",
          en: "public consensus",
          zh: "社会共识",
          vi: "sự đồng cảm chung trong xã hội",
          note: "공감대 형성 = building common ground, prerequisite for reform.",
          noteZh: "공감대 형성 = 凝聚共识，是改革的前提。",
          noteVi: "공감대 형성 = hình thành sự đồng cảm chung, điều kiện tiên quyết cho cải cách.",
        },
        {
          ko: "정책적 합의",
          en: "policy consensus",
          zh: "政策共识",
          vi: "sự đồng thuận về chính sách",
          note: "합의 (agreement, 合意) at the policy level.",
          noteZh: "합의（合意、共识，合意）在政策层面上的达成。",
          noteVi: "합의 (thỏa thuận, đồng thuận) đạt được ở cấp độ chính sách.",
        },
      ],
    ],
    example: {
      ko: "단기 대책보다는 근본적으로 사회 안전망을 강화해야 하고, 무엇보다 사회적 공감대 형성이 우선이라고 봅니다.",
      en: "Rather than short-term measures, we must fundamentally strengthen the social safety net, and above all, building public consensus comes first.",
      zh: "比起短期对策，更应从根本上强化社会保障网，而最重要的是先凝聚社会共识。",
      vi: "Thay vì các đối sách ngắn hạn, tôi cho rằng cần củng cố mạng lưới an sinh xã hội một cách căn bản, và trên hết, việc hình thành sự đồng cảm chung trong xã hội phải được ưu tiên.",
    },
    alternatives: [
      {
        ko: "취약 계층에 대한 지원을 우선해야 합니다.",
        en: "Support for vulnerable groups should come first.",
        zh: "应当优先扶持弱势群体。",
        vi: "Cần ưu tiên hỗ trợ các nhóm yếu thế.",
        note: "취약 계층 (vulnerable groups, 脆弱階層) — a common policy target.",
        noteZh: "취약 계층（弱势群体，脆弱階層）——常见的政策扶持对象。",
        noteVi: "취약 계층 (nhóm yếu thế) — đối tượng thường được nhắm tới trong chính sách hỗ trợ.",
      },
      {
        ko: "세대 간 형평성도 함께 고려해야 합니다.",
        en: "Intergenerational fairness must also be considered.",
        zh: "还须一并考虑代际之间的公平。",
        vi: "Cũng cần xem xét đồng thời sự công bằng giữa các thế hệ.",
        note: "형평성 (equity, 衡平性) broadens the framing.",
        noteZh: "형평성（公平、衡平，衡平性）拓宽了问题的视野。",
        noteVi: "형평성 (tính công bằng) mở rộng góc nhìn của vấn đề.",
      },
    ],
  },
  {
    id: "ko-dlg-c1-abstract-001",
    level: "C1",
    situation: "abstract",
    context: {
      ko: "상대 주장의 논리를 점잖게 반박하기",
      en: "Politely rebutting the logic of someone's argument",
      zh: "礼貌地反驳对方论点的逻辑",
      vi: "Nhã nhặn phản biện logic trong lập luận của đối phương",
    },
    prompt: {
      ko: "규제를 풀면 경제가 무조건 살아난다고 보는데, 동의하시죠?",
      en: "I believe deregulation will definitely revive the economy — you agree, right?",
      zh: "我认为放松管制经济就一定会复苏，您同意吧？",
      vi: "Tôi cho rằng nếu nới lỏng quản lý thì kinh tế chắc chắn sẽ hồi phục, anh/chị đồng ý chứ?",
    },
    template: "취지에는 공감하지만, 그 결론은 {0} {1} 있다고 봅니다.",
    blanks: [
      [
        {
          ko: "전제에서 결론으로 가는 과정에",
          en: "in the step from premise to conclusion",
          zh: "在从前提到结论的过程中",
          vi: "trong quá trình đi từ tiền đề đến kết luận",
          note: "Pinpoints exactly where the reasoning is weak.",
          noteZh: "精准指出推理薄弱的环节。",
          noteVi: "Chỉ ra chính xác điểm mà lập luận còn yếu.",
        },
        {
          ko: "근거가 부족해",
          en: "lacking in evidence",
          zh: "论据不足",
          vi: "thiếu căn cứ",
          note: "근거 (grounds, 根據) — challenges the evidential basis.",
          noteZh: "근거（论据、根据，根據）——质疑其证据基础。",
          noteVi: "근거 (căn cứ) — đặt nghi vấn về cơ sở chứng cứ của lập luận.",
        },
      ],
      [
        {
          ko: "다소 비약이",
          en: "somewhat of a logical leap",
          zh: "略有逻辑跳跃",
          vi: "có phần khiên cưỡng",
          note: "비약 (a leap, 飛躍) = jumping to a conclusion. 다소 (somewhat) softens it.",
          noteZh: "비약（飞跃、跳跃，飛躍）= 妄下结论。다소（略微）起到缓和作用。",
          noteVi: "비약 (bước nhảy vọt) = vội vàng đi đến kết luận. 다소 (phần nào) làm dịu bớt ý phê phán.",
        },
        {
          ko: "논란의 여지가",
          en: "room for debate",
          zh: "有争议的余地",
          vi: "chỗ để tranh cãi",
          note: "여지 (room/leeway, 餘地) — flags it as contestable.",
          noteZh: "여지（余地，餘地）——指出其尚有争议。",
          noteVi: "여지 (dư địa, khoảng trống) — chỉ ra rằng điều đó vẫn còn có thể tranh cãi.",
        },
      ],
    ],
    example: {
      ko: "취지에는 공감하지만, 그 결론은 전제에서 결론으로 가는 과정에 다소 비약이 있다고 봅니다.",
      en: "I sympathize with the intent, but I think that conclusion involves something of a logical leap from premise to conclusion.",
      zh: "我认同您的宗旨，但我认为那个结论在从前提到结论的过程中略有逻辑跳跃。",
      vi: "Tôi đồng cảm với mục đích đó, nhưng tôi cho rằng kết luận ấy có phần khiên cưỡng trong quá trình đi từ tiền đề đến kết luận.",
    },
    alternatives: [
      {
        ko: "역으로 말하면 부작용도 함께 고려해야 합니다.",
        en: "Conversely, we must also consider the side effects.",
        zh: "反过来说，也必须一并考虑副作用。",
        vi: "Nói ngược lại, cũng cần phải xem xét đồng thời cả tác dụng phụ.",
        note: "역으로 (in reverse, 逆) reframes to test the inverse.",
        noteZh: "역으로（反过来，逆）通过检验反面来重新审视。",
        noteVi: "역으로 (theo chiều ngược lại) diễn đạt lại vấn đề bằng cách kiểm chứng mặt trái của nó.",
      },
      {
        ko: "다른 관점에서 보면 해석이 달라질 수 있습니다.",
        en: "Viewed from another angle, the interpretation could differ.",
        zh: "换个角度看，解读可能会有所不同。",
        vi: "Nhìn từ góc độ khác, cách diễn giải có thể sẽ khác đi.",
        note: "관점 (viewpoint, 觀點) — invites an alternative reading.",
        noteZh: "관점（观点，觀點）——引出另一种解读。",
        noteVi: "관점 (quan điểm, góc nhìn) — mở ra một cách diễn giải khác.",
      },
    ],
  },
  {
    id: "ko-dlg-c1-media-001",
    level: "C1",
    situation: "media",
    context: {
      ko: "보도 내용을 비판적으로 평가하기",
      en: "Critically assessing a news report",
      zh: "批判性地评价报道内容",
      vi: "Đánh giá nội dung bản tin một cách phê phán",
    },
    prompt: {
      ko: "이 기사 보셨어요? 다들 사실이라고 난리던데요.",
      en: "Did you see this article? Everyone's in an uproar saying it's true.",
      zh: "你看过这篇报道吗？大家都吵着说是真的呢。",
      vi: "Anh/chị xem bài báo này chưa? Mọi người đang xôn xao bảo là chuyện thật đấy.",
    },
    template: "기사를 {0} 받아들이기보다는 {1} 먼저 {2} 할 것 같아요.",
    blanks: [
      [
        {
          ko: "곧이곧대로",
          en: "at face value",
          zh: "全盘照信",
          vi: "một cách máy móc",
          note: "곧이곧대로 = uncritically/literally. A native idiom for naive acceptance.",
          noteZh: "곧이곧대로 = 不加辨别地、原封不动地。表示轻信的固有惯用语。",
          noteVi: "곧이곧대로 = không suy xét, y nguyên như vậy. Thành ngữ thuần Hàn diễn tả sự cả tin.",
        },
        {
          ko: "그대로",
          en: "as is",
          zh: "原样",
          vi: "y nguyên như vậy",
          note: "Plainer than 곧이곧대로, still natural here.",
          noteZh: "比 곧이곧대로 更朴素，在这里同样自然。",
          noteVi: "Đơn giản hơn so với 곧이곧대로, nhưng vẫn tự nhiên trong ngữ cảnh này.",
        },
      ],
      [
        {
          ko: "사실 관계를",
          en: "the facts",
          zh: "事实真相",
          vi: "tình tiết sự việc",
          note: "사실 관계 = the factual basis journalists must verify.",
          noteZh: "사실 관계 = 记者必须核实的事实依据。",
          noteVi: "사실 관계 = cơ sở sự thật mà nhà báo bắt buộc phải kiểm chứng.",
        },
        {
          ko: "출처를",
          en: "the source",
          zh: "消息来源",
          vi: "nguồn tin",
          note: "출처 (source, 出處) — where the claim originates.",
          noteZh: "출처（出处、来源，出處）——某说法的源头。",
          noteVi: "출처 (nguồn gốc, xuất xứ) — nơi bắt nguồn của một thông tin.",
        },
      ],
      [
        {
          ko: "확인해야",
          en: "should verify",
          zh: "应当核实",
          vi: "nên xác minh",
          note: "확인하다 (to verify) pairs with 사실 관계.",
          noteZh: "확인하다（核实）与 사실 관계 搭配。",
          noteVi: "확인하다 (xác minh) thường đi cùng với 사실 관계 (tình tiết sự việc).",
        },
        {
          ko: "따져 봐야",
          en: "should scrutinize",
          zh: "应当追究",
          vi: "nên xem xét kỹ",
          note: "따지다 = to scrutinize/question critically.",
          noteZh: "따지다 = 追究、认真质疑。",
          noteVi: "따지다 = xem xét kỹ, chất vấn nghiêm túc.",
        },
      ],
    ],
    example: {
      ko: "기사를 곧이곧대로 받아들이기보다는 사실 관계를 먼저 확인해야 할 것 같아요.",
      en: "Rather than taking the article at face value, I think we should verify the facts first.",
      zh: "与其对报道全盘照信，我觉得应该先核实事实真相。",
      vi: "Thay vì tin ngay bài báo một cách máy móc, tôi nghĩ nên xác minh tình tiết sự việc trước đã.",
    },
    alternatives: [
      {
        ko: "자극적인 제목에 휘둘리면 안 됩니다.",
        en: "We shouldn't be swayed by a sensational headline.",
        zh: "不该被耸动的标题牵着走。",
        vi: "Không nên bị cuốn theo cái tiêu đề giật gân.",
        note: "자극적 (sensational, 刺戟的) — warns against clickbait framing.",
        noteZh: "자극적（耸动、刺激性的，刺戟的）——警惕标题党式的手法。",
        noteVi: "자극적 (giật gân, kích động) — cảnh báo về thủ thuật đặt tiêu đề câu view.",
      },
      {
        ko: "특정 프레임이 씌워진 건 아닌지 봐야 해요.",
        en: "We should check whether a particular frame has been imposed.",
        zh: "得看看是不是被扣上了某种框架。",
        vi: "Cần xem liệu có bị gán một khung định kiến nào đó hay không.",
        note: "프레임을 씌우다 = to impose a narrative frame.",
        noteZh: "프레임을 씌우다 = 强加某种叙事框架。",
        noteVi: "프레임을 씌우다 = áp đặt một khung tường thuật nào đó.",
      },
    ],
  },
];
