/**
 * C2 한국어 대화 응답 카드.
 * template/blanks 는 학습 언어(한국어)로 작성, en 은 뜻, note 는 영어 설명.
 *
 * C2 수준: 격식체·문어체, 학술 토론, 미묘한 어감, 관용 표현을 활용한
 * 원어민급 응답. 빈칸 3~4개로 정교한 문장을 조합한다.
 */
import type { Dialogue } from "@/types/dialogue";

export const KO_DLG_C2: Dialogue[] = [
  {
    id: "ko-dlg-c2-academic-001",
    level: "C2",
    situation: "academic",
    context: {
      ko: "학회에서 발표자에게 반론을 제기할 때",
      en: "Raising a counterargument to a presenter at a conference",
      zh: "在学术会议上向发表者提出反论时",
      vi: "Đưa ra phản biện với người thuyết trình tại hội nghị học thuật",
    },
    prompt: {
      ko: "제 연구는 이 변수가 결과를 결정한다는 점을 보여 줍니다.",
      en: "My research shows that this variable determines the outcome.",
      zh: "我的研究表明，这一变量决定了结果。",
      vi: "Nghiên cứu của tôi cho thấy biến số này quyết định kết quả.",
    },
    template: "흥미로운 발표였습니다. 다만 그 결론은 {0} {1}, 표본의 {2} 점은 어떻게 보십니까?",
    blanks: [
      [
        {
          ko: "선행 연구와",
          en: "with the prior research",
          zh: "与先行研究",
          vi: "với nghiên cứu trước đây",
          note: "Academic; frames the objection against established work.",
          noteZh: "学术用语；将异议置于既有研究的对照之下。",
          noteVi: "Học thuật; đặt sự phản biện trong tương quan với các công trình đã có.",
        },
        {
          ko: "기존 통념과",
          en: "with conventional wisdom",
          zh: "与既有的普遍看法",
          vi: "với quan niệm thông thường",
          note: "Positions the claim against the received view.",
          noteZh: "将该主张与公认的观点相对照。",
          noteVi: "Đặt lập luận đối lập với quan điểm đã được công nhận.",
        },
      ],
      [
        {
          ko: "상충하는 듯한데",
          en: "seems to be at odds, and",
          zh: "似乎相互抵触，",
          vi: "có vẻ mâu thuẫn, và",
          note: "상충하다 = to conflict; softened with -는 듯 for politeness.",
          noteZh: "상충하다＝冲突；用 -는 듯 加以委婉缓和。",
          noteVi: "상충하다 = xung đột; được làm dịu bằng -는 듯 để lịch sự hơn.",
        },
        {
          ko: "배치되는 면이 있는데",
          en: "runs counter in some respects, and",
          zh: "在某些方面有所相悖，",
          vi: "có phần trái ngược ở một số điểm, và",
          note: "배치되다 = to be contrary; measured, formal hedge.",
          noteZh: "배치되다＝相悖；分寸得当、正式的委婉说法。",
          noteVi: "배치되다 = trái ngược; cách nói thận trọng, trang trọng và có chừng mực.",
        },
      ],
      [
        {
          ko: "대표성이 부족하다는",
          en: "lacking representativeness",
          zh: "缺乏代表性这一",
          vi: "thiếu tính đại diện",
          note: "Standard methodological critique of a sample.",
          noteZh: "对样本在方法论上的标准批评。",
          noteVi: "Lời phê bình phương pháp luận tiêu chuẩn đối với mẫu nghiên cứu.",
        },
        {
          ko: "편향이 우려된다는",
          en: "raising concern of bias",
          zh: "令人担忧存在偏差这一",
          vi: "gây lo ngại về sự thiên lệch",
          note: "Points to potential sampling bias diplomatically.",
          noteZh: "委婉地指出可能存在的抽样偏差。",
          noteVi: "Khéo léo chỉ ra khả năng có sai lệch trong lấy mẫu.",
        },
      ],
    ],
    example: {
      ko: "흥미로운 발표였습니다. 다만 그 결론은 선행 연구와 상충하는 듯한데, 표본의 대표성이 부족하다는 점은 어떻게 보십니까?",
      en: "It was an interesting talk. That said, the conclusion seems at odds with prior research — how do you view the point that the sample lacks representativeness?",
      zh: "这是一场很有意思的报告。不过，那个结论似乎与先行研究相互抵触，对于样本缺乏代表性这一点，您怎么看？",
      vi: "Đây là một bài thuyết trình thú vị. Tuy nhiên, kết luận đó dường như mâu thuẫn với nghiên cứu trước đây — ngài nghĩ sao về việc mẫu nghiên cứu thiếu tính đại diện?",
    },
    alternatives: [
      {
        ko: "반론의 여지가 있어 보입니다만, 보완 설명을 부탁드려도 될까요?",
        en: "There seems to be room for counterargument; may I ask for further clarification?",
        zh: "看来还有可商榷之处，能否请您做些补充说明？",
        vi: "Có vẻ như vẫn còn chỗ để phản biện; tôi có thể xin ngài giải thích thêm được không?",
        note: "Very diplomatic academic pushback.",
        noteZh: "非常委婉的学术反驳。",
        noteVi: "Cách phản biện học thuật rất khéo léo, nhã nhặn.",
      },
      {
        ko: "인과 관계로 단정하기엔 다소 성급하지 않나 싶습니다.",
        en: "I wonder if it's a little hasty to assert a causal relationship.",
        zh: "要断定为因果关系，恐怕还稍显草率。",
        vi: "Tôi tự hỏi liệu việc khẳng định mối quan hệ nhân quả như vậy có hơi vội vàng không.",
        note: "Cautions against overclaiming causation.",
        noteZh: "提醒不要过度断言因果关系。",
        noteVi: "Cảnh báo về việc khẳng định quá mức mối quan hệ nhân quả.",
      },
    ],
  },
  {
    id: "ko-dlg-c2-formal-001",
    level: "C2",
    situation: "formal",
    context: {
      ko: "공식 행사에서 축사를 시작할 때",
      en: "Opening a congratulatory address at a formal event",
      zh: "在正式活动上开始致贺辞时",
      vi: "Khi bắt đầu bài phát biểu chúc mừng tại một sự kiện trang trọng",
    },
    prompt: {
      ko: "이어서 축사가 있겠습니다. 한 말씀 부탁드립니다.",
      en: "Next we have the congratulatory address. Please say a few words.",
      zh: "接下来是贺辞环节，有请您讲几句。",
      vi: "Tiếp theo sẽ là phần phát biểu chúc mừng. Kính mời ngài nói đôi lời.",
    },
    template: "이 자리를 빌려, 행사를 준비하신 모든 분께 {0}. 아울러 {1} 진심으로 {2}.",
    blanks: [
      [
        {
          ko: "심심한 감사를 드립니다",
          en: "I extend my heartfelt gratitude",
          zh: "致以深切的谢意",
          vi: "xin gửi lời cảm ơn sâu sắc",
          note: "심심한 = deep/profound (深甚), a formal fixed phrase.",
          noteZh: "심심한＝深切／深厚（深甚），正式的固定短语。",
          noteVi: "심심한 = sâu sắc/thâm sâu (深甚), một cụm từ cố định trang trọng.",
        },
        {
          ko: "깊은 감사의 말씀을 전합니다",
          en: "I convey my deep thanks",
          zh: "转达深深的谢意",
          vi: "xin gửi lời cảm ơn chân thành",
          note: "Slightly plainer but still ceremonial.",
          noteZh: "略为朴实，但仍显庄重。",
          noteVi: "Hơi giản dị hơn nhưng vẫn trang trọng.",
        },
      ],
      [
        {
          ko: "여러분의 무궁한 발전을",
          en: "your everlasting prosperity",
          zh: "各位的前程无量",
          vi: "sự phát triển thịnh vượng mãi mãi của quý vị",
          note: "Boilerplate well-wish for the audience.",
          noteZh: "对听众的套语式祝福。",
          noteVi: "Lời chúc mẫu dành cho khán giả.",
        },
        {
          ko: "이 자리에 함께한 인연을",
          en: "the bond of being here together",
          zh: "今日相聚于此的缘分",
          vi: "duyên phận được cùng nhau có mặt tại đây",
          note: "Warmer, more personal register.",
          noteZh: "更温暖、更具个人色彩的语体。",
          noteVi: "Văn phong ấm áp và mang tính cá nhân hơn.",
        },
      ],
      [
        {
          ko: "기원합니다",
          en: "I wish for",
          zh: "祝愿",
          vi: "xin cầu chúc",
          note: "기원하다 = to wish/pray for; elevated over 바라다.",
          noteZh: "기원하다＝祝愿／祈愿；比 바라다 更文雅。",
          noteVi: "기원하다 = cầu chúc/cầu nguyện; trang nhã hơn 바라다.",
        },
        {
          ko: "축원합니다",
          en: "I offer my blessing",
          zh: "祝福",
          vi: "xin gửi lời chúc phúc",
          note: "축원하다 = to wish blessings; ceremonial.",
          noteZh: "축원하다＝祝福；庄重用语。",
          noteVi: "축원하다 = cầu phúc; cách nói trang trọng.",
        },
      ],
    ],
    example: {
      ko: "이 자리를 빌려, 행사를 준비하신 모든 분께 심심한 감사를 드립니다. 아울러 여러분의 무궁한 발전을 진심으로 기원합니다.",
      en: "Taking this opportunity, I extend my heartfelt gratitude to all who prepared this event. I also sincerely wish you everlasting prosperity.",
      zh: "借此机会，谨向筹办本次活动的所有人士致以深切的谢意。同时，衷心祝愿各位前程无量。",
      vi: "Nhân dịp này, tôi xin gửi lời cảm ơn sâu sắc đến tất cả những người đã chuẩn bị cho sự kiện này. Đồng thời, tôi chân thành cầu chúc quý vị phát triển thịnh vượng mãi mãi.",
    },
    alternatives: [
      {
        ko: "변변치 못한 축사이오나, 너른 마음으로 들어 주시기 바랍니다.",
        en: "It is but a humble address; I ask that you receive it generously.",
        zh: "这只是一篇不成敬意的贺辞，还望各位宽宏雅纳。",
        vi: "Đây chỉ là một bài phát biểu khiêm tốn, mong quý vị rộng lòng đón nhận.",
        note: "Humble self-lowering opener common in speeches.",
        noteZh: "演讲中常见的自谦式开场白。",
        noteVi: "Lời mở đầu khiêm nhường, tự hạ thấp bản thân, thường gặp trong các bài phát biểu.",
      },
      {
        ko: "이것으로 축사를 갈음하고자 합니다.",
        en: "With this, I would like to conclude my address.",
        zh: "谨以此代替贺辞，就此作结。",
        vi: "Xin phép được khép lại bài phát biểu chúc mừng bằng những lời này.",
        note: "Set phrase to close a formal speech.",
        noteZh: "收束正式演讲的固定用语。",
        noteVi: "Cụm từ cố định để kết thúc một bài phát biểu trang trọng.",
      },
    ],
  },
  {
    id: "ko-dlg-c2-idioms-001",
    level: "C2",
    situation: "idioms",
    context: {
      ko: "어려움을 겪은 동료를 격려할 때",
      en: "Encouraging a colleague who has been through hardship",
      zh: "鼓励经历了困境的同事时",
      vi: "Khi động viên một đồng nghiệp đã trải qua khó khăn",
    },
    prompt: {
      ko: "프로젝트가 엎어져서 그동안 고생한 게 다 물거품이 됐어요.",
      en: "The project fell through, so all the effort came to nothing.",
      zh: "项目泡汤了，这段时间的辛苦全都白费了。",
      vi: "Dự án đã đổ bể nên bao công sức bỏ ra suốt thời gian qua đều tan thành mây khói.",
    },
    template: "너무 자책하지 마세요. {0} 하잖아요. 이번 일이 {1} 분명 {2} 거예요.",
    blanks: [
      [
        {
          ko: "원숭이도 나무에서 떨어진다고",
          en: "even monkeys fall from trees",
          zh: "都说猴子也会从树上掉下来",
          vi: "người ta vẫn nói khỉ cũng có lúc rơi khỏi cây",
          note: "Native proverb: anyone, even the skilled, can stumble.",
          noteZh: "本土谚语：任何人，哪怕是能手，也会失手。",
          noteVi: "Tục ngữ thuần Hàn: bất kỳ ai, kể cả người giỏi, cũng có lúc vấp ngã.",
        },
        {
          ko: "비 온 뒤에 땅이 굳는다고",
          en: "the ground hardens after the rain",
          zh: "都说雨过之后地更实",
          vi: "người ta vẫn nói sau cơn mưa đất sẽ cứng lại",
          note: "Proverb: hardship leaves you stronger.",
          noteZh: "谚语：经历磨难反而让人更坚强。",
          noteVi: "Tục ngữ: trải qua gian khổ sẽ khiến con người vững vàng hơn.",
        },
      ],
      [
        {
          ko: "전화위복이 되어",
          en: "turning into a blessing in disguise",
          zh: "因祸得福",
          vi: "biến thành cái may trong cái rủi",
          note: "전화위복 = misfortune turned to fortune.",
          noteZh: "전화위복＝转祸为福。",
          noteVi: "전화위복 = họa biến thành phúc.",
        },
        {
          ko: "좋은 약이 되어",
          en: "turning out to be a valuable lesson (lit. good medicine)",
          zh: "成为一剂良药",
          vi: "trở thành liều thuốc quý",
          note: "A bitter experience that ultimately helps you grow.",
          noteZh: "苦涩的经历最终助你成长。",
          noteVi: "Một trải nghiệm cay đắng nhưng cuối cùng lại giúp ta trưởng thành.",
        },
      ],
      [
        {
          ko: "좋은 밑거름이 될",
          en: "become good fertile soil (a foundation)",
          zh: "会成为很好的养分（根基）",
          vi: "sẽ trở thành nền tảng bồi đắp tốt",
          note: "밑거름 = nourishing base for future growth.",
          noteZh: "밑거름＝滋养未来成长的基础。",
          noteVi: "밑거름 = nền tảng nuôi dưỡng cho sự phát triển sau này.",
        },
        {
          ko: "값진 교훈으로 남을",
          en: "remain as a valuable lesson",
          zh: "会作为宝贵的教训留下",
          vi: "sẽ đọng lại như một bài học quý giá",
          note: "Reframes the setback as worthwhile experience.",
          noteZh: "把挫折重新诠释为值得的经历。",
          noteVi: "Diễn giải lại thất bại như một trải nghiệm đáng giá.",
        },
      ],
    ],
    example: {
      ko: "너무 자책하지 마세요. 원숭이도 나무에서 떨어진다고 하잖아요. 이번 일이 전화위복이 되어 분명 좋은 밑거름이 될 거예요.",
      en: "Don't blame yourself too much. Even monkeys fall from trees, you know. This setback may turn into a blessing and surely become good foundation.",
      zh: "别太自责了。都说猴子也会从树上掉下来嘛。这件事说不定因祸得福，一定会成为很好的养分的。",
      vi: "Đừng tự trách mình quá vậy. Người ta vẫn nói khỉ cũng có lúc rơi khỏi cây mà. Việc lần này biết đâu lại là cái may trong cái rủi, chắc chắn sẽ trở thành nền tảng tốt.",
    },
    alternatives: [
      {
        ko: "실패는 성공의 어머니라잖아요.",
        en: "Failure is the mother of success, as they say.",
        zh: "常言道，失败乃成功之母嘛。",
        vi: "Người ta vẫn nói thất bại là mẹ thành công mà.",
        note: "Classic consolation proverb.",
        noteZh: "经典的安慰谚语。",
        noteVi: "Câu tục ngữ an ủi kinh điển.",
      },
      {
        ko: "이 또한 지나가리라 생각하세요.",
        en: "Tell yourself that this too shall pass.",
        zh: "就这样想吧——这一切也终将过去。",
        vi: "Hãy nghĩ rằng rồi điều này cũng sẽ qua thôi.",
        note: "Reflective, somewhat literary comfort.",
        noteZh: "带有沉思意味、略显文雅的安慰。",
        noteVi: "Lời an ủi mang tính suy tư, có phần văn chương.",
      },
    ],
  },
  {
    id: "ko-dlg-c2-nuance-001",
    level: "C2",
    situation: "nuance",
    context: {
      ko: "예상과 다른 결과에 대해 의견을 말할 때",
      en: "Commenting on a result that defied expectations",
      zh: "对出乎意料的结果发表看法时",
      vi: "Khi nêu ý kiến về một kết quả trái với dự đoán",
    },
    prompt: {
      ko: "할인 행사를 했는데 매출이 오히려 줄었어요. 이해가 안 되네요.",
      en: "We ran a discount, but sales actually dropped. I can't make sense of it.",
      zh: "搞了打折促销，销售额反而下降了。真让人想不通。",
      vi: "Đã tổ chức chương trình giảm giá nhưng doanh số lại giảm. Thật không thể hiểu nổi.",
    },
    template: "{0} 가격을 낮추면 {1} 브랜드 가치가 떨어져 보일 수 있어요. {2} 정공법이 나았을지도 모르죠.",
    blanks: [
      [
        {
          ko: "역설적이게도",
          en: "paradoxically",
          zh: "看似矛盾的是",
          vi: "trớ trêu thay",
          note: "Frames the counterintuitive outcome elegantly.",
          noteZh: "优雅地引出这一反直觉的结果。",
          noteVi: "Cách dẫn dắt tinh tế cho kết quả trái với trực giác này.",
        },
        {
          ko: "오히려",
          en: "on the contrary",
          zh: "反而",
          vi: "trái lại",
          note: "Flags a result opposite to expectation.",
          noteZh: "标示出与预期相反的结果。",
          noteVi: "Đánh dấu kết quả trái ngược với dự đoán.",
        },
      ],
      [
        {
          ko: "되레",
          en: "rather / instead",
          zh: "反倒",
          vi: "trái lại / thay vào đó",
          note: "되레 = colloquial contraction of 도리어; emphatic reversal.",
          noteZh: "되레＝도리어 的口语缩略；强调反转。",
          noteVi: "되레 = dạng rút gọn khẩu ngữ của 도리어; nhấn mạnh sự đảo ngược.",
        },
        {
          ko: "자칫",
          en: "all too easily / at the slightest",
          zh: "一不小心（就）",
          vi: "chỉ cần sơ suất một chút (là)",
          note: "자칫 = warns of an easy slip into a bad outcome.",
          noteZh: "자칫＝提醒稍有不慎便会滑向坏结果。",
          noteVi: "자칫 = cảnh báo rằng chỉ cần bất cẩn một chút là sẽ dẫn đến kết quả xấu.",
        },
      ],
      [
        {
          ko: "차라리",
          en: "if anything / rather",
          zh: "倒不如",
          vi: "thà rằng",
          note: "Picks the better of imperfect options.",
          noteZh: "在都不理想的选项中挑较好的那个。",
          noteVi: "Chọn phương án tốt hơn trong số các lựa chọn không hoàn hảo.",
        },
        {
          ko: "어쩌면",
          en: "perhaps",
          zh: "或许",
          vi: "có lẽ",
          note: "Tentative; leaves room for doubt.",
          noteZh: "语气试探，留有余地。",
          noteVi: "Mang tính dò xét, để ngỏ khả năng nghi ngờ.",
        },
      ],
    ],
    example: {
      ko: "역설적이게도 가격을 낮추면 되레 브랜드 가치가 떨어져 보일 수 있어요. 차라리 정공법이 나았을지도 모르죠.",
      en: "Paradoxically, cutting the price can actually make the brand look cheaper. A straightforward approach might have been better.",
      zh: "看似矛盾的是，降价反倒可能让品牌显得掉价。倒不如用正规打法或许更好。",
      vi: "Trớ trêu thay, hạ giá có thể trái lại khiến thương hiệu trông rẻ tiền hơn. Thà rằng dùng cách làm chính đạo có khi lại tốt hơn.",
    },
    alternatives: [
      {
        ko: "겉보기와 달리 소비자 심리는 단순하지 않더라고요.",
        en: "Contrary to appearances, consumer psychology isn't simple.",
        zh: "与表面看到的不同，消费者心理其实并不简单。",
        vi: "Khác với vẻ bề ngoài, tâm lý người tiêu dùng không hề đơn giản.",
        note: "겉보기와 달리 = contrary to how it looks.",
        noteZh: "겉보기와 달리＝与表面所见相反。",
        noteVi: "겉보기와 달리 = trái với vẻ bề ngoài.",
      },
      {
        ko: "두말할 나위 없이 데이터를 더 들여다봐야겠어요.",
        en: "Needless to say, we need to dig into the data more.",
        zh: "不言而喻，我们得再深入分析一下数据。",
        vi: "Không cần phải nói, chúng ta cần xem xét kỹ hơn dữ liệu.",
        note: "두말할 나위 없이 = it goes without saying.",
        noteZh: "두말할 나위 없이＝不言而喻。",
        noteVi: "두말할 나위 없이 = không cần phải nói / hiển nhiên.",
      },
    ],
  },
  {
    id: "ko-dlg-c2-formal-002",
    level: "C2",
    situation: "formal",
    context: {
      ko: "공식 사과문을 발표할 때",
      en: "Issuing an official statement of apology",
      zh: "发表正式道歉声明时",
      vi: "Khi đưa ra tuyên bố xin lỗi chính thức",
    },
    prompt: {
      ko: "이번 사태에 대한 회사의 입장을 밝혀 주시기 바랍니다.",
      en: "Please clarify the company's position on this matter.",
      zh: "请贵公司就此次事件表明立场。",
      vi: "Kính mong quý công ty làm rõ lập trường về sự việc lần này.",
    },
    template: "먼저, 심려를 끼쳐 드린 점 {0}. 저희는 이번 일을 {1}, 재발 방지를 위해 {2}.",
    blanks: [
      [
        {
          ko: "머리 숙여 사과드립니다",
          en: "we apologize with our heads bowed",
          zh: "俯首致歉／低头谢罪",
          vi: "chúng tôi cúi đầu xin lỗi",
          note: "머리 숙여 = bowing the head; the standard contrite formula.",
          noteZh: "머리 숙여＝低头俯首；标准的谢罪套语。",
          noteVi: "머리 숙여 = cúi đầu; công thức tạ lỗi tiêu chuẩn.",
        },
        {
          ko: "깊이 사죄드립니다",
          en: "we deeply apologize",
          zh: "深深谢罪",
          vi: "chúng tôi thành thật tạ lỗi sâu sắc",
          note: "사죄 = atonement; graver than 사과.",
          noteZh: "사죄＝谢罪／赎罪；比 사과 更为郑重。",
          noteVi: "사죄 = tạ tội/chuộc lỗi; nghiêm trọng hơn 사과.",
        },
      ],
      [
        {
          ko: "엄중히 받아들이며",
          en: "taking it with the utmost seriousness, and",
          zh: "严肃对待，",
          vi: "nghiêm túc tiếp nhận, và",
          note: "엄중히 = gravely/sternly; signals accountability.",
          noteZh: "엄중히＝严正／郑重地；表明担责态度。",
          noteVi: "엄중히 = nghiêm trọng/nghiêm khắc; thể hiện thái độ chịu trách nhiệm.",
        },
        {
          ko: "뼈아프게 새기며",
          en: "engraving it painfully (as a lesson), and",
          zh: "刻骨铭心地引以为戒，",
          vi: "khắc cốt ghi tâm một cách đau đớn, và",
          note: "뼈아프게 = to the bone; vivid, contrite.",
          noteZh: "뼈아프게＝痛入骨髓；形象而深切的自省。",
          noteVi: "뼈아프게 = thấu xương; hình ảnh sinh động, thể hiện sự ăn năn sâu sắc.",
        },
      ],
      [
        {
          ko: "만전을 기하겠습니다",
          en: "we will take every possible measure",
          zh: "将采取万全之策",
          vi: "chúng tôi sẽ làm mọi biện pháp có thể",
          note: "만전을 기하다 = to leave nothing to chance; formal pledge.",
          noteZh: "만전을 기하다＝万无一失、不留隐患；正式承诺。",
          noteVi: "만전을 기하다 = không để sót bất kỳ rủi ro nào; lời cam kết trang trọng.",
        },
        {
          ko: "최선을 다하겠습니다",
          en: "we will do our utmost",
          zh: "将竭尽全力",
          vi: "chúng tôi sẽ nỗ lực hết sức",
          note: "Plainer but acceptable closing commitment.",
          noteZh: "较朴实但同样得体的收尾承诺。",
          noteVi: "Lời cam kết kết thúc giản dị nhưng vẫn phù hợp.",
        },
      ],
    ],
    example: {
      ko: "먼저, 심려를 끼쳐 드린 점 머리 숙여 사과드립니다. 저희는 이번 일을 엄중히 받아들이며, 재발 방지를 위해 만전을 기하겠습니다.",
      en: "First, we bow our heads in apology for the worry we have caused. We take this matter with the utmost seriousness and will spare no effort to prevent any recurrence.",
      zh: "首先，就给各位带来忧扰一事，我们俯首致歉。我们将严肃对待此次事件，并为防止再次发生采取万全之策。",
      vi: "Trước hết, chúng tôi xin cúi đầu xin lỗi vì đã gây ra sự lo lắng cho quý vị. Chúng tôi sẽ nghiêm túc tiếp nhận sự việc lần này và làm mọi biện pháp có thể để phòng ngừa tái diễn.",
    },
    alternatives: [
      {
        ko: "변명의 여지가 없음을 통감하고 있습니다.",
        en: "We keenly feel that there is no room for excuse.",
        zh: "我们深切地意识到此事毫无辩解余地。",
        vi: "Chúng tôi thấm thía nhận ra rằng không có chỗ để biện minh.",
        note: "통감하다 = to feel acutely; heavy, formal contrition.",
        noteZh: "통감하다＝深切体会；沉重而正式的悔过。",
        noteVi: "통감하다 = cảm nhận sâu sắc; sự hối lỗi nặng nề, trang trọng.",
      },
      {
        ko: "국민 여러분께 너른 양해를 부탁드립니다.",
        en: "We ask the public for their generous understanding.",
        zh: "恳请全体国民宽宏谅解。",
        vi: "Kính mong toàn thể quốc dân lượng thứ.",
        note: "Standard public-apology closing request.",
        noteZh: "公开道歉时收尾的标准请求用语。",
        noteVi: "Lời thỉnh cầu kết thúc tiêu chuẩn trong lời xin lỗi công khai.",
      },
    ],
  },
];
