/**
 * B2 한국어 멀티턴 시나리오.
 * template/blanks 는 학습 언어(한국어), en 은 뜻, note 는 영어 설명.
 *
 * B2: 한 주제(시사·환경·기술)로 의견을 주고받으며 근거를 덧붙이는 토론형 대화.
 */
import type { Scenario } from "@/types/scenario";

export const KO_SCN_B2: Scenario[] = [
  {
    id: "ko-scn-b2-opinion-001",
    level: "B2",
    situation: "opinion",
    title: {
      ko: "주 4일제 토론",
      en: "Debating a four-day workweek",
      zh: "四天工作制辩论",
      vi: "Tranh luận về chế độ làm việc 4 ngày/tuần",
    },
    context: {
      ko: "동료와 주 4일 근무제에 대해 의견을 나눠요",
      en: "Exchanging views with a colleague about a four-day workweek",
      zh: "和同事就四天工作制交换意见",
      vi: "Trao đổi ý kiến với đồng nghiệp về chế độ làm việc 4 ngày/tuần",
    },
    turns: [
      {
        prompt: {
          ko: "주 4일제 도입에 대해 어떻게 생각하세요?",
          en: "What do you think about introducing a four-day workweek?",
          zh: "您对引入四天工作制怎么看？",
          vi: "Bạn nghĩ sao về việc áp dụng chế độ làm việc 4 ngày một tuần?",
        },
        template: "저는 {0} 입장이에요.",
        blanks: [
          [
            {
              ko: "기본적으로 찬성하는",
              en: "basically in favor",
              zh: "基本上赞成",
              vi: "về cơ bản là ủng hộ",
              note: "기본적으로 = fundamentally/basically — hedges slightly.",
              noteZh: "기본적으로 = 基本上／根本上——略作保留。",
              noteVi: "기본적으로 = về cơ bản/về căn bản — có phần chừa đường lùi nhẹ.",
            },
            {
              ko: "조심스럽게 반대하는",
              en: "cautiously opposed",
              zh: "谨慎地反对",
              vi: "thận trọng phản đối",
              note: "조심스럽게 = cautiously, softens a 반대 stance.",
              noteZh: "조심스럽게 = 谨慎地，缓和“반대（反对）”的立场。",
              noteVi: "조심스럽게 = một cách thận trọng, làm dịu lập trường 반대 (phản đối).",
            },
          ],
        ],
        example: {
          ko: "저는 기본적으로 찬성하는 입장이에요.",
          en: "I'm basically in favor.",
          zh: "我基本上持赞成的立场。",
          vi: "Về cơ bản tôi đứng về phía ủng hộ.",
        },
      },
      {
        prompt: {
          ko: "그렇게 생각하는 이유가 뭐예요?",
          en: "What's your reason for thinking that?",
          zh: "您这么想的理由是什么？",
          vi: "Lý do bạn nghĩ như vậy là gì?",
        },
        template: "{0}, 그 이유는 {1} 때문이에요.",
        blanks: [
          [
            {
              ko: "솔직히 말하면",
              en: "to be honest",
              zh: "老实说",
              vi: "thành thật mà nói",
              note: "Signals a candid reason is coming.",
              noteZh: "预示接下来要说一个坦率的理由。",
              noteVi: "Báo hiệu sắp đưa ra một lý do thẳng thắn.",
            },
            {
              ko: "제 경험상",
              en: "in my experience",
              zh: "以我的经验",
              vi: "theo kinh nghiệm của tôi",
              note: "경험상 = 'based on experience,' grounds the claim.",
              noteZh: "경험상 = “根据经验”，为主张提供依据。",
              noteVi: "경험상 = “dựa trên kinh nghiệm”, làm căn cứ cho lập luận.",
            },
          ],
          [
            {
              ko: "쉬는 날이 늘면 오히려 효율이 높아지기",
              en: "more rest days actually raise efficiency",
              zh: "休息日增多反而会提高效率",
              vi: "vì ngày nghỉ tăng lên ngược lại sẽ làm hiệu suất tăng",
              note: "오히려 = if anything; flags a counter-intuitive point.",
              noteZh: "오히려 = 反而；引出一个出人意料的观点。",
              noteVi: "오히려 = ngược lại/trái lại; đưa ra một quan điểm trái với dự đoán thông thường.",
            },
            {
              ko: "삶의 질이 좋아지기",
              en: "quality of life improves",
              zh: "生活质量会变好",
              vi: "vì chất lượng cuộc sống được cải thiện",
              note: "삶의 질 = quality of life, a common B2 phrase.",
              noteZh: "삶의 질 = 生活质量，常用的 B2 短语。",
              noteVi: "삶의 질 = chất lượng cuộc sống, cụm từ thường dùng ở trình độ B2.",
            },
          ],
        ],
        example: {
          ko: "솔직히 말하면, 그 이유는 쉬는 날이 늘면 오히려 효율이 높아지기 때문이에요.",
          en: "To be honest, the reason is that with more rest days, efficiency actually goes up.",
          zh: "老实说，理由是休息日增多反而会提高效率。",
          vi: "Thành thật mà nói, lý do là vì ngày nghỉ tăng lên thì ngược lại hiệu suất sẽ tăng.",
        },
      },
      {
        prompt: {
          ko: "하지만 인건비 부담이 커지지 않을까요?",
          en: "But wouldn't labor costs become a bigger burden?",
          zh: "但人力成本的负担不会加重吗？",
          vi: "Nhưng gánh nặng chi phí nhân công chẳng phải sẽ tăng lên sao?",
        },
        template: "{0}, {1} 충분히 보완할 수 있다고 봐요.",
        blanks: [
          [
            {
              ko: "그 점도 일리가 있지만",
              en: "that point has merit too, but",
              zh: "那一点也有道理，但",
              vi: "điểm đó cũng có lý, nhưng",
              note: "Concedes the counterpoint diplomatically.",
              noteZh: "委婉地承认对方的反驳观点。",
              noteVi: "Thừa nhận một cách khéo léo quan điểm phản biện của đối phương.",
            },
            {
              ko: "어느 정도 동의하지만",
              en: "I agree to an extent, but",
              zh: "在一定程度上同意，但",
              vi: "tôi đồng ý một phần, nhưng",
              note: "Partial agreement before rebutting.",
              noteZh: "在反驳之前先部分表示同意。",
              noteVi: "Đồng ý một phần trước khi đưa ra phản biện.",
            },
          ],
          [
            {
              ko: "생산성이 오르면",
              en: "if productivity rises",
              zh: "如果生产率提高",
              vi: "nếu năng suất tăng lên thì",
              note: "Conditional rebuttal tied to the earlier point.",
              noteZh: "与前面观点相呼应的条件式反驳。",
              noteVi: "Phản biện có điều kiện, hô ứng với quan điểm nêu trước đó.",
            },
            {
              ko: "장기적으로 보면",
              en: "looking at it long-term",
              zh: "从长远来看",
              vi: "xét về lâu dài thì",
              note: "장기적으로 = in the long term — reframes the cost worry.",
              noteZh: "장기적으로 = 从长远看——重新审视成本方面的担忧。",
              noteVi: "장기적으로 = về lâu dài — nhìn lại mối lo về chi phí theo một góc độ khác.",
            },
          ],
        ],
        example: {
          ko: "그 점도 일리가 있지만, 생산성이 오르면 충분히 보완할 수 있다고 봐요.",
          en: "That point has merit too, but if productivity rises, I think it can be sufficiently offset.",
          zh: "那一点也有道理，但我认为如果生产率提高，是完全可以弥补的。",
          vi: "Điểm đó cũng có lý, nhưng tôi cho rằng nếu năng suất tăng lên thì có thể bù đắp đầy đủ.",
        },
      },
    ],
  },
  {
    id: "ko-scn-b2-environment-001",
    level: "B2",
    situation: "environment",
    title: {
      ko: "일회용품 규제",
      en: "Single-use plastic rules",
      zh: "一次性用品管制",
      vi: "Quy định về đồ dùng một lần",
    },
    context: {
      ko: "카페에서 일회용품 규제에 대해 이야기해요",
      en: "Chatting about single-use plastic rules at a cafe",
      zh: "在咖啡店聊一次性用品的管制",
      vi: "Trò chuyện về quy định đồ dùng một lần tại quán cà phê",
    },
    turns: [
      {
        prompt: {
          ko: "요즘 카페에서 일회용 컵을 잘 안 주더라고요.",
          en: "These days cafes don't really give out disposable cups.",
          zh: "最近咖啡店都不太给一次性杯子了。",
          vi: "Dạo này quán cà phê không hay cho cốc dùng một lần nữa.",
        },
        template: "맞아요, {0} 규제가 강화됐대요.",
        blanks: [
          [
            {
              ko: "환경 오염 때문에",
              en: "because of environmental pollution",
              zh: "因为环境污染",
              vi: "vì ô nhiễm môi trường",
              note: "환경 오염 = environmental pollution.",
              noteZh: "환경 오염 = 环境污染。",
              noteVi: "환경 오염 = ô nhiễm môi trường.",
            },
            {
              ko: "일회용품을 줄이려고",
              en: "to cut down on disposables",
              zh: "为了减少一次性用品",
              vi: "để giảm đồ dùng một lần",
              note: "일회용품 = single-use items; 줄이다 = to reduce.",
              noteZh: "일회용품 = 一次性用品；줄이다 = 减少。",
              noteVi: "일회용품 = đồ dùng một lần; 줄이다 = giảm bớt.",
            },
          ],
        ],
        example: {
          ko: "맞아요, 환경 오염 때문에 규제가 강화됐대요.",
          en: "Right, I heard the rules were tightened because of pollution.",
          zh: "对啊，听说因为环境污染，管制加强了。",
          vi: "Đúng vậy, nghe nói vì ô nhiễm môi trường nên quy định đã được siết chặt.",
        },
      },
      {
        prompt: {
          ko: "조금 불편하긴 한데, 어떻게 생각해요?",
          en: "It's a bit inconvenient, but what do you think?",
          zh: "虽然有点不方便，你怎么看？",
          vi: "Có hơi bất tiện một chút, nhưng bạn nghĩ sao?",
        },
        template: "{0}, 저는 {1} 생각해요.",
        blanks: [
          [
            {
              ko: "불편한 건 사실이지만",
              en: "it's true it's inconvenient, but",
              zh: "不方便是事实，但",
              vi: "bất tiện thì đúng là sự thật, nhưng",
              note: "Concedes before giving a positive opinion.",
              noteZh: "在给出正面看法之前先让步。",
              noteVi: "Nhượng bộ trước khi đưa ra quan điểm tích cực.",
            },
            {
              ko: "처음엔 어색했지만",
              en: "it was awkward at first, but",
              zh: "一开始不太习惯，但",
              vi: "lúc đầu thấy hơi ngượng, nhưng",
              note: "어색하다 = to feel awkward/unfamiliar.",
              noteZh: "어색하다 = 感到别扭／不习惯。",
              noteVi: "어색하다 = cảm thấy ngượng ngùng/chưa quen.",
            },
          ],
          [
            {
              ko: "꼭 필요한 변화라고",
              en: "that it's a necessary change",
              zh: "是一项必要的改变",
              vi: "là một sự thay đổi thực sự cần thiết",
              note: "꼭 필요하다 = absolutely necessary.",
              noteZh: "꼭 필요하다 = 绝对必要。",
              noteVi: "꼭 필요하다 = tuyệt đối cần thiết.",
            },
            {
              ko: "장기적으로는 옳은 방향이라고",
              en: "that it's the right direction long-term",
              zh: "从长远看是正确的方向",
              vi: "về lâu dài là một hướng đi đúng đắn",
              note: "옳은 방향 = the right direction.",
              noteZh: "옳은 방향 = 正确的方向。",
              noteVi: "옳은 방향 = hướng đi đúng đắn.",
            },
          ],
        ],
        example: {
          ko: "불편한 건 사실이지만, 저는 꼭 필요한 변화라고 생각해요.",
          en: "It's true it's inconvenient, but I think it's a necessary change.",
          zh: "不方便是事实，但我认为这是一项必要的改变。",
          vi: "Bất tiện thì đúng là sự thật, nhưng tôi nghĩ đây là một sự thay đổi thực sự cần thiết.",
        },
      },
      {
        prompt: {
          ko: "그럼 개인적으로 실천하는 것도 있어요?",
          en: "So do you personally do anything about it?",
          zh: "那你个人有没有在践行什么呢？",
          vi: "Vậy cá nhân bạn có đang thực hành điều gì không?",
        },
        template: "네, {0} 들고 다니고, {1} 신경 쓰려고 해요.",
        blanks: [
          [
            {
              ko: "텀블러를",
              en: "a tumbler",
              zh: "随行杯",
              vi: "bình giữ nhiệt cá nhân",
              note: "텀블러 = reusable tumbler — very common in Korea.",
              noteZh: "텀블러 = 可重复使用的随行杯——在韩国很常见。",
              noteVi: "텀블러 = bình/ly cá nhân dùng nhiều lần — rất phổ biến ở Hàn Quốc.",
            },
            {
              ko: "장바구니를",
              en: "a shopping bag",
              zh: "购物袋",
              vi: "túi đi chợ",
              note: "장바구니 = reusable shopping bag.",
              noteZh: "장바구니 = 可重复使用的购物袋。",
              noteVi: "장바구니 = túi đi chợ có thể dùng lại nhiều lần.",
            },
          ],
          [
            {
              ko: "분리수거에도",
              en: "to sorting recycling too",
              zh: "对垃圾分类也",
              vi: "cả việc phân loại rác nữa",
              note: "분리수거 = separating recycling.",
              noteZh: "분리수거 = 垃圾分类回收。",
              noteVi: "분리수거 = phân loại rác để tái chế.",
            },
            {
              ko: "친환경 제품에도",
              en: "to eco-friendly products too",
              zh: "对环保产品也",
              vi: "cả sản phẩm thân thiện môi trường nữa",
              note: "친환경 = eco-friendly.",
              noteZh: "친환경 = 环保。",
              noteVi: "친환경 = thân thiện với môi trường.",
            },
          ],
        ],
        example: {
          ko: "네, 텀블러를 들고 다니고, 분리수거에도 신경 쓰려고 해요.",
          en: "Yes, I carry a tumbler around and try to be careful about sorting recycling too.",
          zh: "嗯，我会随身带着随行杯，也尽量注意垃圾分类。",
          vi: "Vâng, tôi mang theo bình giữ nhiệt cá nhân, và cũng cố gắng chú ý đến việc phân loại rác.",
        },
      },
    ],
  },
  {
    id: "ko-scn-b2-technology-001",
    level: "B2",
    situation: "technology",
    title: { ko: "AI와 일자리", en: "AI and jobs", zh: "AI 与就业", vi: "AI và việc làm" },
    context: {
      ko: "친구와 인공지능이 일자리에 미치는 영향을 이야기해요",
      en: "Talking with a friend about how AI affects jobs",
      zh: "和朋友聊人工智能对就业的影响",
      vi: "Nói chuyện với bạn về ảnh hưởng của trí tuệ nhân tạo đến việc làm",
    },
    turns: [
      {
        prompt: {
          ko: "요즘 인공지능 때문에 일자리 걱정하는 사람이 많더라고요.",
          en: "A lot of people are worried about jobs because of AI these days.",
          zh: "最近因为人工智能而担心工作的人很多。",
          vi: "Dạo này có nhiều người lo lắng về việc làm vì trí tuệ nhân tạo.",
        },
        template: "그러게요, {0} 분위기예요.",
        blanks: [
          [
            {
              ko: "불안해하는",
              en: "feeling anxious",
              zh: "感到不安",
              vi: "cảm thấy bất an",
              note: "불안해하다 = to feel uneasy/anxious.",
              noteZh: "불안해하다 = 感到不安／焦虑。",
              noteVi: "불안해하다 = cảm thấy bất an/lo lắng.",
            },
            {
              ko: "변화를 실감하는",
              en: "really feeling the change",
              zh: "切实感受到变化",
              vi: "cảm nhận rõ sự thay đổi",
              note: "실감하다 = to feel something as real/tangible.",
              noteZh: "실감하다 = 真切地感受到某事。",
              noteVi: "실감하다 = cảm nhận điều gì đó một cách chân thực/rõ ràng.",
            },
          ],
        ],
        example: {
          ko: "그러게요, 불안해하는 분위기예요.",
          en: "Yeah, there's an anxious mood.",
          zh: "就是说啊，弥漫着一种不安的气氛。",
          vi: "Đúng vậy, không khí đang khá bất an.",
        },
      },
      {
        prompt: {
          ko: "정말 사람을 다 대체하게 될까요?",
          en: "Will it really end up replacing everyone?",
          zh: "真的会把人全都取代掉吗？",
          vi: "Liệu nó có thực sự thay thế hết tất cả mọi người không?",
        },
        template: "{0}, {1} 거라고 봐요.",
        blanks: [
          [
            {
              ko: "제 생각에는",
              en: "in my opinion",
              zh: "在我看来",
              vi: "theo tôi nghĩ",
              note: "Neutral opinion frame.",
              noteZh: "中性的观点表达框架。",
              noteVi: "Cách trình bày quan điểm mang tính trung lập.",
            },
            {
              ko: "엄밀히 따지면",
              en: "strictly speaking",
              zh: "严格来说",
              vi: "xét cho kỹ thì",
              note: "엄밀히 따지면 = makes a careful distinction.",
              noteZh: "엄밀히 따지면 = 做出审慎的区分。",
              noteVi: "엄밀히 따지면 = đưa ra một sự phân biệt cẩn trọng.",
            },
          ],
          [
            {
              ko: "완전히 대체하기보다는 역할이 바뀌는",
              en: "roles will change rather than be fully replaced",
              zh: "与其说是完全取代，不如说角色会转变",
              vi: "vai trò sẽ thay đổi chứ không phải bị thay thế hoàn toàn",
              note: "대체하다 = replace; reframes 'replace' as 'shift.'",
              noteZh: "대체하다 = 取代；把“取代”重新诠释为“转变”。",
              noteVi: "대체하다 = thay thế; diễn giải lại “thay thế” thành “chuyển đổi”.",
            },
            {
              ko: "오히려 새로운 일자리도 생길",
              en: "new jobs will appear, if anything",
              zh: "反而还会出现新的工作岗位",
              vi: "ngược lại sẽ còn xuất hiện việc làm mới",
              note: "오히려 = if anything — a counter-intuitive turn.",
              noteZh: "오히려 = 反而——出人意料的转折。",
              noteVi: "오히려 = ngược lại — một bước ngoặt trái với dự đoán.",
            },
          ],
        ],
        example: {
          ko: "제 생각에는, 완전히 대체하기보다는 역할이 바뀌는 거라고 봐요.",
          en: "In my opinion, roles will change rather than being fully replaced.",
          zh: "在我看来，与其说是完全取代，不如说角色会发生转变。",
          vi: "Theo tôi nghĩ, vai trò sẽ thay đổi chứ không phải bị thay thế hoàn toàn.",
        },
      },
      {
        prompt: {
          ko: "그래도 부작용은 좀 걱정되지 않아요?",
          en: "Still, aren't you a bit worried about the downsides?",
          zh: "不过副作用你就不担心一点吗？",
          vi: "Nhưng bạn không lo lắng một chút về tác dụng phụ sao?",
        },
        template: "{0}. 특히 {1} 점이 걱정돼요.",
        blanks: [
          [
            {
              ko: "그 부분은 저도 공감해요",
              en: "I share that concern",
              zh: "这一点我也有同感",
              vi: "phần đó tôi cũng đồng cảm",
              note: "공감하다 = to empathize/relate to.",
              noteZh: "공감하다 = 有同感／产生共鸣。",
              noteVi: "공감하다 = đồng cảm/thấu hiểu.",
            },
            {
              ko: "그 점은 분명히 짚어야 해요",
              en: "that point definitely needs addressing",
              zh: "那一点确实需要点明",
              vi: "điểm đó chắc chắn cần phải chỉ rõ ra",
              note: "짚다 = to point out/pinpoint an issue.",
              noteZh: "짚다 = 指出／点明问题。",
              noteVi: "짚다 = chỉ ra/nêu rõ một vấn đề.",
            },
          ],
          [
            {
              ko: "기술에 지나치게 의존하게 되는",
              en: "becoming overly reliant on technology",
              zh: "变得过度依赖技术",
              vi: "trở nên phụ thuộc quá mức vào công nghệ",
              note: "...에 의존하다 = to depend on; 지나치게 = excessively.",
              noteZh: "……에 의존하다 = 依赖；지나치게 = 过度地。",
              noteVi: "...에 의존하다 = phụ thuộc vào; 지나치게 = một cách quá mức.",
            },
            {
              ko: "정보 격차가 더 벌어지는",
              en: "the information gap widening further",
              zh: "信息鸿沟进一步拉大",
              vi: "khoảng cách thông tin ngày càng nới rộng",
              note: "정보 격차 = the digital divide; 벌어지다 = to widen.",
              noteZh: "정보 격차 = 数字鸿沟；벌어지다 = 拉大／扩大。",
              noteVi: "정보 격차 = khoảng cách số; 벌어지다 = nới rộng/mở rộng.",
            },
          ],
        ],
        example: {
          ko: "그 부분은 저도 공감해요. 특히 기술에 지나치게 의존하게 되는 점이 걱정돼요.",
          en: "I share that concern. I'm especially worried about becoming overly reliant on technology.",
          zh: "这一点我也有同感。我尤其担心变得过度依赖技术这一点。",
          vi: "Phần đó tôi cũng đồng cảm. Tôi đặc biệt lo lắng về việc trở nên phụ thuộc quá mức vào công nghệ.",
        },
      },
    ],
  },
];
