/**
 * C1 한국어 멀티턴 시나리오.
 * template/blanks 는 학습 언어(한국어), en 은 뜻, note 는 영어 설명.
 *
 * C1: 업무·전문 상황을 능숙하게 끌어가는 연속 대화. 논리적 주장, 격식 조절.
 */
import type { Scenario } from "@/types/scenario";

export const KO_SCN_C1: Scenario[] = [
  {
    id: "ko-scn-c1-business-001",
    level: "C1",
    situation: "business",
    title: { ko: "예산 협상 회의", en: "Budget negotiation meeting", zh: "预算谈判会议", vi: "Cuộc họp đàm phán ngân sách" },
    context: {
      ko: "거래처와 예산·일정을 조율하는 회의",
      en: "A meeting to align budget and schedule with a client",
      zh: "与客户协调预算和日程的会议",
      vi: "Cuộc họp điều chỉnh ngân sách và tiến độ với đối tác",
    },
    turns: [
      {
        prompt: {
          ko: "제안하신 견적이 예상보다 높습니다. 조정이 가능할까요?",
          en: "The quote you proposed is higher than expected. Is an adjustment possible?",
          zh: "您提出的报价比预期高。能否调整一下？",
          vi: "Báo giá mà quý vị đề xuất cao hơn dự kiến. Liệu có thể điều chỉnh được không?",
        },
        template: "말씀 이해합니다. {0} 일부 항목은 {1} 여지가 있습니다.",
        blanks: [
          [
            {
              ko: "범위를 조정하면",
              en: "if we adjust the scope",
              zh: "如果调整范围",
              vi: "nếu điều chỉnh phạm vi",
              note: "Trades scope for cost — a classic negotiation lever.",
              noteZh: "以范围换成本——经典的谈判筹码。",
              noteVi: "Đánh đổi phạm vi lấy chi phí — một đòn bẩy đàm phán kinh điển.",
            },
            {
              ko: "물량을 늘리면",
              en: "if you increase the volume",
              zh: "如果增加数量",
              vi: "nếu tăng số lượng",
              note: "물량 (quantity/volume, 物量) — offers a volume discount angle.",
              noteZh: "물량（数量、物量，物量）——提供以量换价的思路。",
              noteVi: "물량 (số lượng, khối lượng) — gợi ý hướng chiết khấu theo số lượng.",
            },
          ],
          [
            {
              ko: "절감할",
              en: "to cut down",
              zh: "削减",
              vi: "cắt giảm",
              note: "절감하다 (to reduce, 節減) — formal for trimming cost.",
              noteZh: "절감하다（节减，節減）——削减成本的正式说法。",
              noteVi: "절감하다 (tiết giảm) — cách nói trang trọng để chỉ việc cắt giảm chi phí.",
            },
            {
              ko: "재검토할",
              en: "to reconsider",
              zh: "重新研究",
              vi: "xem xét lại",
              note: "재검토 (re-review, 再檢討) — leaves room without committing.",
              noteZh: "재검토（重新研究，再檢討）——留有余地而不作承诺。",
              noteVi: "재검토 (xem xét lại) — để lại khoảng trống mà không cam kết chắc chắn.",
            },
          ],
        ],
        example: {
          ko: "말씀 이해합니다. 범위를 조정하면 일부 항목은 절감할 여지가 있습니다.",
          en: "I understand. If we adjust the scope, there's room to cut down some line items.",
          zh: "我理解您的意思。如果调整范围，部分项目还有削减的余地。",
          vi: "Tôi hiểu ý quý vị. Nếu điều chỉnh phạm vi thì một số hạng mục vẫn còn chỗ để cắt giảm.",
        },
      },
      {
        prompt: {
          ko: "그렇다면 일정도 함께 앞당길 수 있습니까?",
          en: "In that case, can the schedule also be moved up?",
          zh: "那样的话，日程也能一并提前吗？",
          vi: "Nếu vậy thì tiến độ cũng có thể đẩy sớm lên được không?",
        },
        template: "일정은 {0} 어렵지만, {1} 단계적으로 진행한다면 {2}.",
        blanks: [
          [
            {
              ko: "무리하게 앞당기기는",
              en: "to force it earlier",
              zh: "勉强提前",
              vi: "việc gượng ép đẩy sớm lên",
              note: "무리하게 = unreasonably/forcibly. Signals a realistic limit.",
              noteZh: "무리하게 = 勉强地、硬来地。表明现实的限度。",
              noteVi: "무리하게 = một cách gượng ép, quá sức. Cho thấy giới hạn thực tế.",
            },
            {
              ko: "전체를 단축하기는",
              en: "to shorten the whole thing",
              zh: "缩短整体",
              vi: "việc rút ngắn toàn bộ",
              note: "단축하다 (to shorten, 短縮) — addresses the timeline directly.",
              noteZh: "단축하다（缩短，短縮）——直接针对时间安排。",
              noteVi: "단축하다 (rút ngắn) — nhắm trực tiếp vào việc bố trí thời gian.",
            },
          ],
          [
            {
              ko: "핵심 기능부터",
              en: "starting with the core features",
              zh: "从核心功能开始",
              vi: "bắt đầu từ các tính năng cốt lõi",
              note: "Prioritizes high-value deliverables first.",
              noteZh: "优先交付高价值的部分。",
              noteVi: "Ưu tiên bàn giao trước những phần có giá trị cao.",
            },
            {
              ko: "우선순위를 정해",
              en: "by setting priorities",
              zh: "确定优先次序",
              vi: "bằng cách xác định thứ tự ưu tiên",
              note: "우선순위 (priority, 優先順位) — structured phasing.",
              noteZh: "우선순위（优先次序，優先順位）——有条理地分阶段推进。",
              noteVi: "우선순위 (thứ tự ưu tiên) — triển khai theo từng giai đoạn một cách có hệ thống.",
            },
          ],
          [
            {
              ko: "가능할 것 같습니다",
              en: "it should be possible",
              zh: "应该是可行的",
              vi: "chắc là có thể được",
              note: "Polite conditional offer that keeps the deal moving.",
              noteZh: "礼貌的有条件承诺，让交易得以继续推进。",
              noteVi: "Một đề nghị có điều kiện, lịch sự, giúp thương vụ tiếp tục tiến triển.",
            },
            {
              ko: "맞춰 보겠습니다",
              en: "I'll try to accommodate",
              zh: "我会尽量配合",
              vi: "tôi sẽ cố gắng thu xếp cho phù hợp",
              note: "맞추다 = to align/accommodate. Cooperative tone.",
              noteZh: "맞추다 = 配合、迁就。语气合作。",
              noteVi: "맞추다 = điều chỉnh cho khớp, thu xếp phù hợp. Giọng điệu hợp tác.",
            },
          ],
        ],
        example: {
          ko: "일정은 무리하게 앞당기기는 어렵지만, 핵심 기능부터 단계적으로 진행한다면 가능할 것 같습니다.",
          en: "Forcing the schedule earlier is difficult, but if we proceed in stages starting with the core features, it should be possible.",
          zh: "日程要勉强提前有难度，但如果从核心功能开始分阶段推进，应该是可行的。",
          vi: "Việc gượng ép đẩy sớm tiến độ thì khó, nhưng nếu triển khai theo từng giai đoạn bắt đầu từ các tính năng cốt lõi thì chắc là có thể được.",
        },
      },
      {
        prompt: {
          ko: "좋습니다. 그럼 세부 조건은 어떻게 확정하면 될까요?",
          en: "Good. Then how should we finalize the detailed terms?",
          zh: "好的。那么细节条款该如何敲定呢？",
          vi: "Tốt. Vậy các điều khoản chi tiết thì nên chốt như thế nào?",
        },
        template: "오늘 논의를 바탕으로 {0} 정리해서, {1} 다시 {2}.",
        blanks: [
          [
            {
              ko: "합의된 사항을",
              en: "the agreed points",
              zh: "已达成一致的事项",
              vi: "những nội dung đã thống nhất",
              note: "합의 (agreement, 合意) — consolidates what's settled.",
              noteZh: "합의（合意、共识，合意）——把已定下的内容归拢起来。",
              noteVi: "합의 (thỏa thuận, đồng thuận) — tổng hợp lại những gì đã được chốt.",
            },
            {
              ko: "수정 견적을",
              en: "a revised quote",
              zh: "修改后的报价",
              vi: "bản báo giá đã chỉnh sửa",
              note: "Concrete next deliverable from the negotiation.",
              noteZh: "谈判后要交付的具体成果。",
              noteVi: "Kết quả cụ thể tiếp theo cần bàn giao sau đàm phán.",
            },
          ],
          [
            {
              ko: "후속 미팅에서",
              en: "in a follow-up meeting",
              zh: "在后续会议上",
              vi: "trong cuộc họp tiếp theo",
              note: "후속 (follow-up, 後續) — schedules the next touchpoint.",
              noteZh: "후속（后续，後續）——安排下一次沟通。",
              noteVi: "후속 (tiếp theo, kế tiếp) — sắp xếp điểm liên lạc kế tiếp.",
            },
            {
              ko: "다음 주 중으로",
              en: "sometime next week",
              zh: "下周之内",
              vi: "trong khoảng tuần sau",
              note: "Gives a concrete, polite timeframe.",
              noteZh: "给出具体而礼貌的时间范围。",
              noteVi: "Đưa ra một khung thời gian cụ thể và lịch sự.",
            },
          ],
          [
            {
              ko: "확정하시죠",
              en: "let's finalize",
              zh: "就此敲定吧",
              vi: "hãy chốt lại",
              note: "확정하다 (to confirm/finalize, 確定) — decisive close.",
              noteZh: "확정하다（确定、敲定，確定）——果断收尾。",
              noteVi: "확정하다 (xác định, chốt) — kết thúc một cách dứt khoát.",
            },
            {
              ko: "검토하시죠",
              en: "let's review",
              zh: "再研究一下吧",
              vi: "hãy xem xét lại",
              note: "Slightly softer, leaves a final check.",
              noteZh: "语气略柔和，留一次最终确认。",
              noteVi: "Giọng điệu nhẹ nhàng hơn, để lại một bước kiểm tra cuối cùng.",
            },
          ],
        ],
        example: {
          ko: "오늘 논의를 바탕으로 합의된 사항을 정리해서, 후속 미팅에서 다시 확정하시죠.",
          en: "Based on today's discussion, let's organize the agreed points and finalize them in a follow-up meeting.",
          zh: "以今天的讨论为基础，把已达成一致的事项整理好，在后续会议上再敲定吧。",
          vi: "Dựa trên những gì đã thảo luận hôm nay, hãy tổng hợp lại những nội dung đã thống nhất, rồi chốt lại một lần nữa trong cuộc họp tiếp theo.",
        },
      },
    ],
  },
  {
    id: "ko-scn-c1-society-001",
    level: "C1",
    situation: "society",
    title: { ko: "사회 이슈 토론", en: "Debating a social issue", zh: "社会议题辩论", vi: "Tranh luận về vấn đề xã hội" },
    context: {
      ko: "고령화와 세대 갈등을 두고 의견을 나누는 토론",
      en: "A discussion sharing views on aging and generational conflict",
      zh: "围绕老龄化与世代矛盾交换意见的讨论",
      vi: "Cuộc thảo luận trao đổi quan điểm về già hóa dân số và xung đột thế hệ",
    },
    turns: [
      {
        prompt: {
          ko: "요즘 세대 갈등이 심하다고 하는데, 어떻게 생각하세요?",
          en: "They say generational conflict is severe these days — what do you think?",
          zh: "听说最近世代矛盾很严重，您怎么看？",
          vi: "Nghe nói dạo này xung đột thế hệ khá nghiêm trọng, anh/chị nghĩ sao?",
        },
        template: "{0} 문제지만, 갈등 자체보다 {1} 부족이 더 근본적이라고 봅니다.",
        blanks: [
          [
            {
              ko: "분명히 짚고 넘어가야 할",
              en: "definitely worth addressing",
              zh: "确实值得点明并正视的",
              vi: "chắc chắn cần phải chỉ ra",
              note: "짚고 넘어가다 = to address before moving on. Measured acknowledgment.",
              noteZh: "짚고 넘어가다 = 在继续之前先加以指出。表示有分寸的认可。",
              noteVi: "짚고 넘어가다 = nêu ra rồi mới tiếp tục. Thể hiện sự thừa nhận có chừng mực.",
            },
            {
              ko: "사회적으로 대두된",
              en: "that has emerged socially",
              zh: "在社会上凸显出来的",
              vi: "đã nổi lên trong xã hội",
              note: "대두되다 (to come to the fore, 擡頭) — frames it as a rising issue.",
              noteZh: "대두되다（抬头、凸显，擡頭）——将其定位为日益突出的问题。",
              noteVi: "대두되다 (ngóc đầu dậy, nổi lên) — định vị đây là một vấn đề đang ngày càng nổi cộm.",
            },
          ],
          [
            {
              ko: "소통의",
              en: "of communication",
              zh: "沟通的",
              vi: "về giao tiếp",
              note: "소통 (communication, 疏通) — points to the deeper cause.",
              noteZh: "소통（沟通，疏通）——指向更深层的原因。",
              noteVi: "소통 (giao tiếp, thông hiểu) — chỉ ra nguyên nhân sâu xa hơn.",
            },
            {
              ko: "상호 이해의",
              en: "of mutual understanding",
              zh: "相互理解的",
              vi: "về sự thấu hiểu lẫn nhau",
              note: "상호 (mutual, 相互) — frames it as a two-way gap.",
              noteZh: "상호（相互，相互）——将其视为双向的隔阂。",
              noteVi: "상호 (lẫn nhau, tương hỗ) — coi đây là khoảng cách mang tính hai chiều.",
            },
          ],
        ],
        example: {
          ko: "분명히 짚고 넘어가야 할 문제지만, 갈등 자체보다 소통의 부족이 더 근본적이라고 봅니다.",
          en: "It's definitely an issue worth addressing, but rather than the conflict itself, the lack of communication is more fundamental.",
          zh: "这确实是个值得正视的问题，但比起矛盾本身，沟通的缺乏才更为根本。",
          vi: "Đây chắc chắn là vấn đề cần phải chỉ ra, nhưng tôi cho rằng sự thiếu hụt trong giao tiếp mới là gốc rễ, hơn cả bản thân xung đột.",
        },
      },
      {
        prompt: {
          ko: "하지만 고령화까지 겹치면 갈등이 더 커지지 않을까요?",
          en: "But if aging is added on top, won't the conflict grow even worse?",
          zh: "但如果再加上老龄化，矛盾不会变得更大吗？",
          vi: "Nhưng nếu cộng thêm cả tình trạng già hóa dân số thì xung đột chẳng phải sẽ càng lớn hơn sao?",
        },
        template: "역으로 보면, 고령화는 {0} 세대가 {1} 계기가 될 수도 있습니다.",
        blanks: [
          [
            {
              ko: "오히려",
              en: "rather / on the contrary",
              zh: "反而",
              vi: "ngược lại",
              note: "오히려 — pivots to a counterintuitive upside.",
              noteZh: "오히려——转向一个出人意料的正面看法。",
              noteVi: "오히려 — chuyển hướng sang một góc nhìn tích cực bất ngờ.",
            },
            {
              ko: "장기적으로",
              en: "in the long term",
              zh: "从长远来看",
              vi: "về lâu dài",
              note: "장기적 (long-term, 長期的) — reframes the time horizon.",
              noteZh: "장기적（长期的，長期的）——重新设定时间视角。",
              noteVi: "장기적 (dài hạn) — thiết lập lại tầm nhìn thời gian.",
            },
          ],
          [
            {
              ko: "서로 협력하는",
              en: "to cooperate with each other",
              zh: "彼此协作",
              vi: "hợp tác với nhau",
              note: "협력 (cooperation, 協力) — turns conflict toward collaboration.",
              noteZh: "협력（协作，協力）——把矛盾引向合作。",
              noteVi: "협력 (hợp tác) — chuyển hướng xung đột sang hợp tác.",
            },
            {
              ko: "공감대를 형성하는",
              en: "to build common ground",
              zh: "凝聚共识",
              vi: "hình thành sự đồng cảm chung",
              note: "공감대 형성 = forming shared empathy across generations.",
              noteZh: "공감대 형성 = 在世代之间建立共鸣。",
              noteVi: "공감대 형성 = xây dựng sự đồng cảm chung giữa các thế hệ.",
            },
          ],
        ],
        example: {
          ko: "역으로 보면, 고령화는 오히려 세대가 서로 협력하는 계기가 될 수도 있습니다.",
          en: "Looked at the other way, aging could actually become an occasion for generations to cooperate.",
          zh: "反过来看，老龄化反而可能成为各世代彼此协作的契机。",
          vi: "Nhìn theo chiều ngược lại, tình trạng già hóa dân số ngược lại có thể trở thành cơ hội để các thế hệ hợp tác với nhau.",
        },
      },
      {
        prompt: {
          ko: "이상적이긴 한데, 현실에서 가능할까요?",
          en: "That's ideal, but is it realistic?",
          zh: "这倒是很理想，但现实中可行吗？",
          vi: "Nghe thì lý tưởng đấy, nhưng liệu có khả thi trong thực tế không?",
        },
        template: "물론 쉽지 않지만, {0} 제도가 뒷받침되고 {1} 충분히 {2}.",
        blanks: [
          [
            {
              ko: "세대 통합을 위한",
              en: "for generational integration",
              zh: "促进世代融合的",
              vi: "hướng tới sự hòa hợp giữa các thế hệ",
              note: "통합 (integration, 統合) — names a concrete policy aim.",
              noteZh: "통합（整合、融合，統合）——点出一个具体的政策目标。",
              noteVi: "통합 (hòa hợp, thống nhất) — nêu ra một mục tiêu chính sách cụ thể.",
            },
            {
              ko: "사회 안전망 같은",
              en: "such as the social safety net",
              zh: "诸如社会保障网这样的",
              vi: "như mạng lưới an sinh xã hội",
              note: "안전망 — grounds the ideal in a real mechanism.",
              noteZh: "안전망——把理想落到实实在在的机制上。",
              noteVi: "안전망 (mạng lưới an sinh) — đưa lý tưởng về với một cơ chế thực tế.",
            },
          ],
          [
            {
              ko: "인식이 제고된다면",
              en: "if awareness is raised",
              zh: "如果认识得到提高",
              vi: "nếu nhận thức được nâng cao",
              note: "제고하다 (to raise/enhance, 提高) — formal for shifting mindsets.",
              noteZh: "제고하다（提高，提高）——转变观念的正式说法。",
              noteVi: "제고하다 (nâng cao) — cách nói trang trọng để chỉ sự thay đổi nhận thức.",
            },
            {
              ko: "공감대가 자리 잡으면",
              en: "once common ground takes root",
              zh: "一旦共识扎根",
              vi: "một khi sự đồng cảm chung được định hình",
              note: "자리 잡다 = to become established as a norm.",
              noteZh: "자리 잡다 = 确立为一种常态。",
              noteVi: "자리 잡다 = được xác lập trở thành một chuẩn mực.",
            },
          ],
          [
            {
              ko: "실현 가능하다고 봅니다",
              en: "I believe it's achievable",
              zh: "我认为是可以实现的",
              vi: "tôi cho rằng điều đó khả thi",
              note: "실현 가능 (feasible, 實現可能) — confident, formal close.",
              noteZh: "실현 가능（可实现、可行，實現可能）——自信而正式的收尾。",
              noteVi: "실현 가능 (có thể thực hiện được) — lời kết tự tin và trang trọng.",
            },
            {
              ko: "해소될 수 있습니다",
              en: "it can be resolved",
              zh: "是可以化解的",
              vi: "có thể được giải tỏa",
              note: "해소되다 (to be dissolved, 解消) — pairs with 갈등.",
              noteZh: "해소되다（化解、消除，解消）——与 갈등（矛盾）搭配。",
              noteVi: "해소되다 (được giải tỏa, tan biến) — thường đi kèm với 갈등 (xung đột).",
            },
          ],
        ],
        example: {
          ko: "물론 쉽지 않지만, 세대 통합을 위한 제도가 뒷받침되고 인식이 제고된다면 충분히 실현 가능하다고 봅니다.",
          en: "Of course it's not easy, but if institutions for generational integration back it up and awareness is raised, I believe it's entirely achievable.",
          zh: "当然不容易，但只要有促进世代融合的制度作支撑，加上认识得到提高，我认为完全可以实现。",
          vi: "Tất nhiên là không dễ, nhưng nếu có thể chế hỗ trợ cho sự hòa hợp giữa các thế hệ và nhận thức được nâng cao, tôi cho rằng hoàn toàn khả thi.",
        },
      },
    ],
  },
];
