/**
 * C2 한국어 멀티턴 시나리오.
 * template/blanks 는 학습 언어(한국어), en 은 뜻, note 는 영어 설명.
 *
 * C2 수준: 학술 심사·격식 협상 등 고난도 상황에서 문어체·관용 표현을
 * 활용해 정교하게 응답한다.
 */
import type { Scenario } from "@/types/scenario";

export const KO_SCN_C2: Scenario[] = [
  {
    id: "ko-scn-c2-academic-001",
    level: "C2",
    situation: "academic",
    title: { ko: "논문 심사", en: "Thesis defense", zh: "论文答辩", vi: "Bảo vệ luận văn" },
    context: {
      ko: "심사위원의 날카로운 질문에 학술적으로 응대해요",
      en: "Responding academically to a committee member's sharp questions",
      zh: "以学术的方式应对评审委员尖锐的提问",
      vi: "Ứng đáp một cách học thuật trước những câu hỏi sắc bén của hội đồng giám khảo",
    },
    turns: [
      {
        prompt: {
          ko: "연구의 독창성을 한 문장으로 정리하면 무엇입니까?",
          en: "In one sentence, what is the originality of your research?",
          zh: "用一句话概括，您研究的独创性是什么？",
          vi: "Nếu tóm gọn trong một câu, tính độc đáo của nghiên cứu này là gì?",
        },
        template: "기존 연구가 {0} 변수를, 본 연구는 {1} 규명했다는 점입니다.",
        blanks: [
          [
            {
              ko: "간과해 온",
              en: "have overlooked",
              zh: "一直忽视的",
              vi: "đã bị bỏ qua",
              note: "간과하다 = to overlook; positions a gap in the literature.",
              noteZh: "간과하다＝忽视；指出文献中的空白。",
              noteVi: "간과하다 = bỏ qua; chỉ ra khoảng trống trong tài liệu nghiên cứu.",
            },
            {
              ko: "단편적으로만 다룬",
              en: "treated only fragmentarily",
              zh: "只作零散处理的",
              vi: "chỉ được xử lý một cách rời rạc",
              note: "단편적 = piecemeal; claims prior work was incomplete.",
              noteZh: "단편적＝零散、片面；主张既有研究不够完整。",
              noteVi: "단편적 = rời rạc, phiến diện; cho rằng nghiên cứu trước đây chưa hoàn chỉnh.",
            },
          ],
          [
            {
              ko: "통합적 관점에서",
              en: "from an integrated perspective",
              zh: "从整合的视角",
              vi: "từ góc nhìn tổng hợp",
              note: "Frames the contribution as a unifying view.",
              noteZh: "把研究贡献定位为一种整合性的视角。",
              noteVi: "Định vị đóng góp của nghiên cứu như một góc nhìn mang tính tổng hợp.",
            },
            {
              ko: "실증적으로",
              en: "empirically",
              zh: "以实证的方式",
              vi: "một cách thực chứng",
              note: "실증적 = evidence-based; stresses rigor.",
              noteZh: "실증적＝基于证据的；强调严谨性。",
              noteVi: "실증적 = dựa trên bằng chứng; nhấn mạnh tính chặt chẽ.",
            },
          ],
        ],
        example: {
          ko: "기존 연구가 간과해 온 변수를, 본 연구는 통합적 관점에서 규명했다는 점입니다.",
          en: "It is that this study clarifies, from an integrated perspective, a variable that prior research had overlooked.",
          zh: "在于本研究从整合的视角，阐明了既有研究一直忽视的变量。",
          vi: "Đó là nghiên cứu này đã làm rõ, từ góc nhìn tổng hợp, một biến số mà các nghiên cứu trước đây đã bỏ qua.",
        },
      },
      {
        prompt: {
          ko: "그렇다면 표본 수가 적다는 한계는 어떻게 보완하셨습니까?",
          en: "Then how did you address the limitation of a small sample size?",
          zh: "那么，样本数量偏少这一局限，您是如何弥补的？",
          vi: "Vậy thì ngài đã khắc phục hạn chế về cỡ mẫu nhỏ như thế nào?",
        },
        template: "타당한 지적이십니다. {0} 한계를 인정하되, {1} 보완하여 신뢰도를 {2}.",
        blanks: [
          [
            {
              ko: "표본의",
              en: "of the sample",
              zh: "样本的",
              vi: "của mẫu nghiên cứu",
              note: "Acknowledges the specific weakness head-on.",
              noteZh: "正面承认这一具体的不足。",
              noteVi: "Thẳng thắn thừa nhận điểm yếu cụ thể này.",
            },
            {
              ko: "일반화의",
              en: "of generalization",
              zh: "推广（普遍化）的",
              vi: "của việc khái quát hóa",
              note: "Names the deeper methodological concern.",
              noteZh: "点明更深层的方法论顾虑。",
              noteVi: "Chỉ rõ mối lo ngại sâu xa hơn về phương pháp luận.",
            },
          ],
          [
            {
              ko: "질적 분석을 병행해",
              en: "by also conducting qualitative analysis",
              zh: "同时进行质性分析",
              vi: "bằng cách đồng thời tiến hành phân tích định tính",
              note: "병행하다 = to carry out in parallel; a triangulation defense.",
              noteZh: "병행하다＝并行开展；以多方印证来辩护。",
              noteVi: "병행하다 = tiến hành song song; biện hộ bằng cách đối chiếu đa chiều.",
            },
            {
              ko: "반복 검증을 거쳐",
              en: "by going through repeated validation",
              zh: "经过反复验证",
              vi: "thông qua việc kiểm chứng lặp lại nhiều lần",
              note: "Replication as a robustness safeguard.",
              noteZh: "以可重复验证作为稳健性的保障。",
              noteVi: "Lấy khả năng tái kiểm chứng làm cơ sở bảo đảm tính vững chắc.",
            },
          ],
          [
            {
              ko: "확보하고자 했습니다",
              en: "sought to secure",
              zh: "力求加以确保",
              vi: "đã cố gắng đảm bảo",
              note: "-고자 하다 = formal 'sought to'; hedged, academic.",
              noteZh: "-고자 하다＝正式的“力求”；委婉、学术化。",
              noteVi: "-고자 하다 = 'cố gắng để' mang tính trang trọng; uyển chuyển, học thuật.",
            },
            {
              ko: "높이려 노력했습니다",
              en: "endeavored to raise",
              zh: "努力加以提升",
              vi: "đã nỗ lực để nâng cao",
              note: "Slightly plainer but still formal.",
              noteZh: "略为朴实，但仍属正式。",
              noteVi: "Hơi giản dị hơn nhưng vẫn thuộc văn phong trang trọng.",
            },
          ],
        ],
        example: {
          ko: "타당한 지적이십니다. 표본의 한계를 인정하되, 질적 분석을 병행해 보완하여 신뢰도를 확보하고자 했습니다.",
          en: "That is a valid point. While acknowledging the sample's limitation, I sought to secure reliability by complementing it with parallel qualitative analysis.",
          zh: "您指得很有道理。我承认样本的局限，但通过同时进行质性分析加以弥补，力求确保信度。",
          vi: "Đó là một nhận xét xác đáng. Tôi thừa nhận hạn chế của mẫu nghiên cứu, nhưng đã cố gắng đảm bảo độ tin cậy bằng cách bổ sung đồng thời phân tích định tính.",
        },
      },
      {
        prompt: {
          ko: "마지막으로, 이 연구의 후속 과제는 무엇이라고 보십니까?",
          en: "Finally, what do you see as the follow-up tasks for this research?",
          zh: "最后，您认为这项研究的后续课题是什么？",
          vi: "Cuối cùng, ngài xem đâu là những nhiệm vụ nghiên cứu tiếp theo của công trình này?",
        },
        template: "{0} 이번 결과를 다양한 맥락에 적용해 {1} 확장하는 것이 과제라고 봅니다.",
        blanks: [
          [
            {
              ko: "나아가",
              en: "by extension / furthermore",
              zh: "更进一步",
              vi: "hơn nữa",
              note: "Elevated connective to broaden scope.",
              noteZh: "文雅的衔接语，用以拓展范围。",
              noteVi: "Từ nối trang nhã dùng để mở rộng phạm vi.",
            },
            {
              ko: "장기적으로는",
              en: "in the long term",
              zh: "从长远来看",
              vi: "về lâu dài",
              note: "Sets a forward-looking research horizon.",
              noteZh: "确立前瞻性的研究视野。",
              noteVi: "Thiết lập tầm nhìn nghiên cứu hướng tới tương lai.",
            },
          ],
          [
            {
              ko: "일반화 가능성을",
              en: "the possibility of generalization",
              zh: "推广（普遍化）的可能性",
              vi: "khả năng khái quát hóa",
              note: "The natural next step after a limited study.",
              noteZh: "在有限研究之后自然的下一步。",
              noteVi: "Bước tiếp theo tự nhiên sau một nghiên cứu còn hạn chế.",
            },
            {
              ko: "이론적 함의를",
              en: "the theoretical implications",
              zh: "理论层面的意涵",
              vi: "hàm ý lý thuyết",
              note: "함의 = implication; signals scholarly ambition.",
              noteZh: "함의＝意涵；显示出学术上的抱负。",
              noteVi: "함의 = hàm ý; thể hiện tham vọng học thuật.",
            },
          ],
        ],
        example: {
          ko: "나아가 이번 결과를 다양한 맥락에 적용해 일반화 가능성을 확장하는 것이 과제라고 봅니다.",
          en: "Furthermore, I see the task as extending the generalizability by applying these results across varied contexts.",
          zh: "更进一步，我认为课题在于将本次结果应用于各种情境，从而拓展其推广的可能性。",
          vi: "Hơn nữa, tôi cho rằng nhiệm vụ là áp dụng kết quả này vào nhiều bối cảnh khác nhau để mở rộng khả năng khái quát hóa.",
        },
      },
    ],
  },
  {
    id: "ko-scn-c2-formal-001",
    level: "C2",
    situation: "formal",
    title: { ko: "고위급 협상", en: "High-level negotiation", zh: "高层谈判", vi: "Đàm phán cấp cao" },
    context: {
      ko: "격식을 갖춰 까다로운 협상을 풀어 가요",
      en: "Navigating a delicate negotiation with full formality",
      zh: "以十足的礼节化解棘手的谈判",
      vi: "Giải quyết một cuộc đàm phán hóc búa với đầy đủ nghi thức trang trọng",
    },
    turns: [
      {
        prompt: {
          ko: "솔직히 말씀드려, 제시하신 조건은 받아들이기 어렵습니다.",
          en: "Frankly speaking, the terms you've proposed are hard to accept.",
          zh: "坦率地说，您提出的条件我们很难接受。",
          vi: "Nói thẳng thắn, các điều kiện mà ngài đề xuất rất khó để chấp nhận.",
        },
        template: "충분히 이해합니다. 다만 {0} 부분은 {1}, 대안을 함께 {2}.",
        blanks: [
          [
            {
              ko: "양측의 이해가 상충하는",
              en: "where both sides' interests conflict",
              zh: "双方利益相互抵触的",
              vi: "nơi lợi ích của hai bên xung đột",
              note: "상충하다 = to clash; names the friction diplomatically.",
              noteZh: "상충하다＝冲突；委婉地点明分歧所在。",
              noteVi: "상충하다 = xung đột; khéo léo chỉ ra điểm bất đồng.",
            },
            {
              ko: "이견이 좁혀지지 않는",
              en: "where differences aren't narrowing",
              zh: "分歧难以缩小的",
              vi: "nơi những bất đồng chưa được thu hẹp",
              note: "이견 = differing views; acknowledges the impasse.",
              noteZh: "이견＝不同意见；承认陷入僵局。",
              noteVi: "이견 = quan điểm khác biệt; thừa nhận tình trạng bế tắc.",
            },
          ],
          [
            {
              ko: "지금 단정하기보다",
              en: "rather than concluding now",
              zh: "与其现在就下定论",
              vi: "thay vì kết luận ngay bây giờ",
              note: "단정하다 = to conclude definitively; urges patience.",
              noteZh: "단정하다＝断然下结论；劝人稍安勿躁。",
              noteVi: "단정하다 = khẳng định dứt khoát; khuyên nên kiên nhẫn hơn.",
            },
            {
              ko: "감정을 앞세우기보다",
              en: "rather than leading with emotion",
              zh: "与其感情用事",
              vi: "thay vì để cảm xúc lấn át",
              note: "Gently steers the tone back to reason.",
              noteZh: "温和地把语气引回理性。",
              noteVi: "Nhẹ nhàng đưa giọng điệu trở lại tính lý trí.",
            },
          ],
          [
            {
              ko: "모색해 보면 어떨까 합니다",
              en: "I wonder if we might explore",
              zh: "一起探寻一下，您看如何",
              vi: "tôi nghĩ chúng ta nên cùng tìm kiếm thử xem sao",
              note: "모색하다 = to seek out; -면 어떨까 hedges the proposal.",
              noteZh: "모색하다＝寻求；-면 어떨까 使提议更为委婉。",
              noteVi: "모색하다 = tìm kiếm; -면 어떨까 làm cho đề xuất trở nên uyển chuyển hơn.",
            },
            {
              ko: "강구해 보고자 합니다",
              en: "I would like to devise",
              zh: "想设法研拟一下",
              vi: "tôi muốn tìm cách nghiên cứu đối sách",
              note: "강구하다 = to work out a measure; formal.",
              noteZh: "강구하다＝研拟对策；正式用语。",
              noteVi: "강구하다 = tìm ra biện pháp; cách nói trang trọng.",
            },
          ],
        ],
        example: {
          ko: "충분히 이해합니다. 다만 양측의 이해가 상충하는 부분은 지금 단정하기보다, 대안을 함께 모색해 보면 어떨까 합니다.",
          en: "I fully understand. But rather than settling the points where our interests clash right now, I wonder if we might explore alternatives together.",
          zh: "我完全理解。只是双方利益相互抵触的部分，与其现在就下定论，不如一起探寻替代方案，您看如何？",
          vi: "Tôi hoàn toàn hiểu điều đó. Nhưng thay vì kết luận ngay bây giờ về những điểm mà lợi ích hai bên xung đột, tôi nghĩ chúng ta nên cùng tìm kiếm phương án thay thế thử xem sao.",
        },
      },
      {
        prompt: {
          ko: "그 말씀은 결국 양보할 뜻이 없다는 것 아닙니까?",
          en: "Doesn't that ultimately mean you have no intention of yielding?",
          zh: "您这话说到底，不就是没有让步的意思吗？",
          vi: "Nói như vậy chẳng phải cuối cùng có nghĩa là ngài không có ý định nhượng bộ sao?",
        },
        template: "오해가 있으신 듯합니다. {0} 아니라, {1} 선에서 {2} 드리겠다는 뜻입니다.",
        blanks: [
          [
            {
              ko: "양보의 여지가 없다는 것이",
              en: "that there's no room to concede",
              zh: "没有让步的余地",
              vi: "việc không có chỗ để nhượng bộ",
              note: "여지 = room/margin; directly addresses the suspicion.",
              noteZh: "여지＝余地；正面回应对方的疑虑。",
              noteVi: "여지 = dư địa/khoảng trống; trực tiếp đáp lại mối nghi ngờ của đối phương.",
            },
            {
              ko: "원칙만 고수하겠다는 것이",
              en: "that we'll cling only to principle",
              zh: "只死守原则",
              vi: "việc chỉ khăng khăng giữ nguyên tắc",
              note: "고수하다 = to adhere firmly; reframes the worry.",
              noteZh: "고수하다＝坚守；重新诠释对方的担忧。",
              noteVi: "고수하다 = kiên trì giữ vững; diễn giải lại mối lo ngại của đối phương.",
            },
          ],
          [
            {
              ko: "양측이 수용 가능한",
              en: "acceptable to both parties",
              zh: "双方都能接受的",
              vi: "mà cả hai bên đều có thể chấp nhận được",
              note: "Signals a search for common ground.",
              noteZh: "表明在寻求双方的共识。",
              noteVi: "Thể hiện việc đang tìm kiếm điểm chung giữa hai bên.",
            },
            {
              ko: "실리를 해치지 않는",
              en: "without harming substantive interests",
              zh: "不损害实际利益的",
              vi: "mà không làm tổn hại đến lợi ích thực chất",
              note: "실리 = practical benefit; protects the bottom line.",
              noteZh: "실리＝实际利益；守住底线。",
              noteVi: "실리 = lợi ích thực tế; bảo vệ giới hạn cuối cùng.",
            },
          ],
          [
            {
              ko: "최대한 조율해",
              en: "to coordinate as much as possible",
              zh: "尽最大努力加以协调",
              vi: "điều chỉnh hết mức có thể",
              note: "조율하다 = to fine-tune/harmonize; collaborative tone.",
              noteZh: "조율하다＝调和／协调；合作的语气。",
              noteVi: "조율하다 = điều hòa/phối hợp; giọng điệu mang tính hợp tác.",
            },
            {
              ko: "성의껏 검토해",
              en: "to review in good faith",
              zh: "诚意十足地加以研究",
              vi: "xem xét một cách thành tâm",
              note: "성의껏 = with sincerity; reassures the counterpart.",
              noteZh: "성의껏＝尽心诚意地；让对方安心。",
              noteVi: "성의껏 = hết lòng thành tâm; giúp đối phương yên tâm.",
            },
          ],
        ],
        example: {
          ko: "오해가 있으신 듯합니다. 양보의 여지가 없다는 것이 아니라, 양측이 수용 가능한 선에서 최대한 조율해 드리겠다는 뜻입니다.",
          en: "I think there's a misunderstanding. It's not that there's no room to concede — I mean we'll coordinate as much as possible within terms acceptable to both sides.",
          zh: "您似乎有所误会。我的意思并不是没有让步的余地，而是会在双方都能接受的范围内尽最大努力加以协调。",
          vi: "Hình như có sự hiểu lầm nào đó. Không phải là không có chỗ để nhượng bộ, mà ý tôi là chúng tôi sẽ điều chỉnh hết mức có thể trong phạm vi mà cả hai bên đều có thể chấp nhận được.",
        },
      },
      {
        prompt: {
          ko: "좋습니다. 그렇다면 다음 회의까지 수정안을 마련해 주십시오.",
          en: "All right. In that case, please prepare a revised proposal by the next meeting.",
          zh: "好。那么，请在下次会议前准备好修订方案。",
          vi: "Được rồi. Vậy thì xin hãy chuẩn bị phương án sửa đổi trước cuộc họp tiếp theo.",
        },
        template: "그렇게 하겠습니다. {0} 신뢰를 바탕으로 {1} 결실을 맺도록 {2}.",
        blanks: [
          [
            {
              ko: "오늘 쌓은",
              en: "built today",
              zh: "今天建立起的",
              vi: "được xây dựng hôm nay",
              note: "Credits the progress just made; warm close.",
              noteZh: "肯定刚刚取得的进展；温暖的收尾。",
              noteVi: "Ghi nhận tiến triển vừa đạt được; lời kết ấm áp.",
            },
            {
              ko: "그간 다져 온",
              en: "cultivated over time",
              zh: "这段时间夯实起来的",
              vi: "đã được vun đắp bấy lâu nay",
              note: "다지다 = to firm up; nods to a longer relationship.",
              noteZh: "다지다＝夯实；点到更长久的关系。",
              noteVi: "다지다 = củng cố vững chắc; ám chỉ mối quan hệ lâu dài hơn.",
            },
          ],
          [
            {
              ko: "상생의",
              en: "of mutual flourishing",
              zh: "互利共赢的",
              vi: "cùng phát triển",
              note: "상생 = win-win coexistence; aspirational framing.",
              noteZh: "상생＝共生共赢；带有愿景色彩的表述。",
              noteVi: "상생 = cùng tồn tại đôi bên cùng có lợi; cách diễn đạt mang tính tầm nhìn.",
            },
            {
              ko: "호혜적인",
              en: "reciprocal",
              zh: "互惠的",
              vi: "mang tính hỗ tương",
              note: "호혜적 = mutually beneficial; formal register.",
              noteZh: "호혜적＝互惠互利；正式语体。",
              noteVi: "호혜적 = cùng có lợi cho nhau; văn phong trang trọng.",
            },
          ],
          [
            {
              ko: "만전을 기하겠습니다",
              en: "I will leave nothing to chance",
              zh: "定当竭力做到万无一失",
              vi: "tôi sẽ không để sót bất kỳ điều gì",
              note: "만전을 기하다 = to make everything watertight; firm pledge.",
              noteZh: "만전을 기하다＝力求万无一失；坚定承诺。",
              noteVi: "만전을 기하다 = làm mọi thứ thật kín kẽ; lời cam kết chắc chắn.",
            },
            {
              ko: "최선을 다하겠습니다",
              en: "I will do my utmost",
              zh: "定当竭尽全力",
              vi: "tôi sẽ nỗ lực hết mình",
              note: "Standard but sincere commitment.",
              noteZh: "标准但真诚的承诺。",
              noteVi: "Lời cam kết tiêu chuẩn nhưng chân thành.",
            },
          ],
        ],
        example: {
          ko: "그렇게 하겠습니다. 오늘 쌓은 신뢰를 바탕으로 상생의 결실을 맺도록 만전을 기하겠습니다.",
          en: "I will do so. Building on the trust we've established today, I will leave nothing to chance so that we bear win-win fruit.",
          zh: "我会照办。我们将以今天建立起的信任为基础，竭力做到万无一失，以结出互利共赢的果实。",
          vi: "Tôi sẽ làm như vậy. Dựa trên niềm tin được xây dựng hôm nay, tôi sẽ không để sót bất kỳ điều gì nhằm gặt hái được thành quả cùng phát triển.",
        },
      },
    ],
  },
];
